---
permalink: a1k/bootmedia-replace.html 
sidebar: sidebar 
keywords: aff a1k, replace the boot media 
summary: Sie finden das ausgefallene Startmedium im Controller-Modul, indem Sie Riser 3 am Controller-Modul entfernen, bevor Sie das Boot-Medium ersetzen können. 
---
= Ersetzen Sie das Startmedium – AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das Startmedium zu ersetzen, müssen Sie das System Management-Modul von der Rückseite des Systems entfernen, das gestörte Startmedium entfernen und das Ersatz-Startmedium im System Management-Modul installieren.



== Schritt 1: Ersetzen Sie die Startmedien

Das Startmedium befindet sich im System Management-Modul und kann durch Entfernen des Moduls aus dem System aufgerufen werden.

image::../media/drw_a1k_boot_media_remove_replace_ieops-1377.svg[Startmedien ersetzen Grafik]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Legende Nummer 1]
 a| 
Nockenverriegelung des Systemmanagementmoduls



 a| 
image::../media/legend_icon_02.svg[Legende Nummer 2]
 a| 
Verriegelungstaste für Startmedien



 a| 
image::../media/legend_icon_03.svg[Legende Nummer 3]
 a| 
Boot-Medien

|===
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Ziehen Sie die Netzteilkabel von den Netzteilen vom Controller ab.
+

NOTE: Wenn Ihr Speichersystem über Gleichstromnetzteile verfügt, trennen Sie den Stromkabelblock von den Netzteilen.

+
.. Entfernen Sie alle Kabel, die am System Management-Modul angeschlossen sind. Stellen Sie sicher, dass Sie den Ort kennzeichnen, an dem die Kabel angeschlossen wurden, damit Sie sie bei der Neuinstallation des Moduls an die richtigen Anschlüsse anschließen können.
.. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Tasten an beiden Seiten an der Innenseite des Kabelführungs-Fachs ziehen und das Fach dann nach unten drehen.
.. Drücken Sie die CAM-Taste für die Systemverwaltung.
.. Drehen Sie die Nockenverriegelung so weit wie möglich nach unten.
.. Entfernen Sie das System-Management-Modul aus dem Gehäuse, indem Sie den Finger in die Öffnung des Nockenhebels stecken und das Modul aus dem Gehäuse ziehen.
.. Platzieren Sie das System-Management-Modul auf einer antistatischen Matte, damit das Startmedium zugänglich ist.


. Entfernen Sie das Startmedium aus dem Verwaltungsmodul:
+
.. Drücken Sie die blaue Verriegelungstaste.
.. Drehen Sie das Startmedium nach oben, schieben Sie es aus dem Sockel und legen Sie es beiseite.


. Installieren Sie das Ersatz-Startmedium im System Management-Modul:
+
.. Richten Sie die Kanten der Startmedien am Buchsengehäuse aus, und schieben Sie sie vorsichtig in die Buchse.
.. Drehen Sie das Startmedium nach unten in Richtung Verriegelungstaste.
.. Drücken Sie die Verriegelungstaste, drehen Sie die Manschettenmedien ganz nach unten, und lassen Sie dann die Verriegelungstaste los.


. Installieren Sie das System Management-Modul neu.
+
.. Richten Sie das Modul an den Kanten der Öffnung des Gehäusesteckplatzes aus.
.. Schieben Sie das Modul vorsichtig in den Steckplatz bis zum Gehäuse, und drehen Sie dann die Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Drehen Sie das Kabelführungs-Fach bis in die geschlossene Position.
+
.. System-Management-Modul erneut verwenden.






== Schritt 2: Übertragen Sie das ONTAP-Image auf das Boot-Medium

Das von Ihnen installierte Ersatzstartmedium ist ohne ein ONTAP-Image. Sie können das ONTAP-Image auf das Ersatz-Startmedium übertragen, indem Sie das entsprechende ONTAP-Service-Image vom https://mysupport.netapp.com/["NetApp Support Website"] auf ein USB-Flash-Laufwerk und dann auf das Ersatz-Startmedium herunterladen.

.Bevor Sie beginnen
* Sie müssen über ein leeres USB-Flash-Laufwerk verfügen, das mit FAT32 formatiert ist und mindestens 4 GB Kapazität hat.
* Sie müssen über eine Kopie derselben Image-Version von ONTAP verfügen, wie der beeinträchtigte Controller ausgeführt wurde. Sie können das entsprechende Image im Abschnitt auf der NetApp Support-Website herunterladen https://support.netapp.com/downloads["Downloads"]
+
** Wenn NVE unterstützt wird, laden Sie das Image mit NetApp Volume Encryption herunter, wie auf der Download-Schaltfläche angegeben.
** Wenn NVE nicht unterstützt wird, laden Sie das Image ohne NetApp-Volume-Verschlüsselung herunter, wie auf der Download-Schaltfläche angegeben.


* Wenn es sich bei Ihrem System um ein HA-Paar handelt, müssen Sie über eine Netzwerkverbindung zwischen den Node-Management-Ports der Controller verfügen (normalerweise die E0M Schnittstellen).


.Schritte
. Laden Sie das entsprechende Service-Image vom auf das USB-Flash-Laufwerk herunter, und kopieren https://mysupport.netapp.com/["NetApp Support Website"] Sie es.
+
.. Laden Sie das Service-Image über den Link Downloads auf der Seite auf Ihren Arbeitsbereich auf Ihrem Laptop herunter.
.. Entpacken Sie das Service-Image.
+

NOTE: Wenn Sie den Inhalt mit Windows extrahieren, verwenden Sie WinZip nicht zum Extrahieren des Netzboots-Images. Verwenden Sie ein anderes Extraktionstool, wie 7-Zip oder WinRAR.



+
Das USB-Flash-Laufwerk sollte über das entsprechende ONTAP-Image des ausgeführten Controllers verfügen.

+
.. Entfernen Sie das USB-Flash-Laufwerk von Ihrem Laptop.


. Stecken Sie das USB-Flash-Laufwerk in den USB-Steckplatz des Systemmanagementmoduls.
+
Stellen Sie sicher, dass Sie das USB-Flash-Laufwerk in den für USB-Geräte gekennzeichneten Steckplatz und nicht im USB-Konsolenport installieren.

. Schließen Sie die Netzkabel an die Netzteile an, und setzen Sie die Stromkabelhalterung wieder ein.
+
Der Controller beginnt zu starten, sobald die Stromversorgung wieder mit dem System verbunden wird.

. Unterbrechen Sie den Boot-Vorgang, indem Sie Strg-C drücken, um an der LOADER-Eingabeaufforderung zu stoppen.
+
Wenn Sie diese Meldung verpassen, drücken Sie Strg-C, wählen Sie die Option zum Booten im Wartungsmodus aus, und halten Sie dann den Controller zum Booten in LOADER an.

. Legen Sie den Verbindungstyp für das Netzwerk an der LOADER-Eingabeaufforderung fest:
+
** Wenn Sie DHCP konfigurieren: `ifconfig e0M -auto`
+

NOTE: Der von Ihnen konfigurierte Zielport ist der Zielport, über den Sie während der Wiederherstellung des var-Dateisystems mit dem beeinträchtigten Controller über den gesunden Controller kommunizieren. Sie können in diesem Befehl auch den Port E0M verwenden.

** Wenn Sie manuelle Verbindungen konfigurieren: `ifconfig e0M -addr=filer_addr -mask=netmask -gw=gateway`
+
*** Filer_addr ist die IP-Adresse des Speichersystems.
*** Netmask ist die Netzwerkmaske des Managementnetzwerks, das mit dem HA-Partner verbunden ist.
*** Das Gateway ist das Gateway für das Netzwerk.




+

NOTE: Andere Parameter können für Ihre Schnittstelle erforderlich sein. Sie können Hilfe ifconfig an der Firmware-Eingabeaufforderung für Details eingeben.


