---
permalink: a1k/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: a1k, replace the boot media 
summary: Stellen Sie vor dem Austauschen des Bootmediums in Ihrem AFF A1K -System sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen. 
---
= Voraussetzungen für die automatische Wiederherstellung von Bootmedien – AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das Bootmedium in Ihrem AFF A1K -System austauschen, stellen Sie sicher, dass die Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu gehört die Überprüfung, ob Sie das richtige Ersatz-Bootmedium haben, ob die Cluster-Ports des defekten Controllers ordnungsgemäß funktionieren und ob der Onboard Key Manager (OKM) oder der External Key Manager (EKM) aktiviert ist.

Der automatisierte Boot-Medien-Wiederherstellungsprozess wird nur in ONTAP 9.17.1 und höher unterstützt. Wenn Ihr Speichersystem eine frühere Version von ONTAP verwendet, verwenden Sie die link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] .

Überprüfen Sie die folgenden Anforderungen.

* Sie müssen das ausgefallene Boot-Medium durch ein Ersatz-Boot-Medium ersetzen, das Sie von NetApp erhalten haben.
* Die Cluster-Ports dienen der Kommunikation zwischen den beiden Controllern während der automatischen Boot-Wiederherstellung. Stellen Sie sicher, dass die Cluster-Ports auf dem beeinträchtigten Controller ordnungsgemäß funktionieren.
* Für OKM benötigen Sie die clusterweite Passphrase und auch die Sicherungsdaten.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Machen Sie sich mit der in diesem Verfahren verwendeten Controller-Terminologie vertraut:
+
** Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.




.Wie es weiter geht
Nachdem Sie die Anforderungen für die Startmedien überprüft haben, können Sie link:bootmedia-shutdown-bmr.html["Fahren Sie den Controller herunter"].
