---
permalink: a1k/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a1k, replace the chassis 
summary: Bevor das Chassis im AFF A1K System ersetzt wird, sollte geprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorhanden sind, das korrekte Ersatzchassis sowie die erforderlichen Werkzeuge bereitstehen. 
---
= Anforderungen sollten vor dem Austausch des AFF A1K Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Chassis im AFF A1K System ersetzt wird, sollte geprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorhanden sind, das korrekte Ersatzchassis sowie die erforderlichen Werkzeuge bereitstehen.

Das Gehäuse ist das physische Gehäuse, in dem alle Systemkomponenten wie Lüfter, Controller-/CPU-Einheit, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile untergebracht sind.

Überprüfen Sie die folgenden Anforderungen.

* Stellen Sie sicher, dass alle anderen Komponenten des Systems ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an, http://mysupport.netapp.com/["NetApp Support"^] um Unterstützung zu erhalten.
* Holen Sie sich lokale Administratoranmeldeinformationen für ONTAP ein, wenn diese nicht vorhanden sind.
* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.
* Sie können das Verfahren zum Austausch des Gehäuses für alle Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Bei der Beschreibung des Verfahrens zum Austausch des Gehäuses wird davon ausgegangen, dass Sie Blende, Lüfter, Controllermodul, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile in das neue Gehäuse einbauen und dass es sich bei dem Austauschgehäuse um eine neue Komponente von NetApp handelt.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie link:chassis-replace-prepare.html["Bereiten Sie den Austausch des Gehäuses vor"].
