---
permalink: a1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a1k, how to recable the system, how to reassign disks 
summary: Steuerung der Speicherressourcen wieder an den Ersatz-Controller zurückgeben, damit Ihr AFF A1K System den normalen Betrieb wieder aufnehmen kann. 
---
= Geben Sie den Controller zurück – AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Geben Sie die Kontrolle über die Speicherressourcen an den Ersatz-Controller zurück, damit Ihr AFF A1K-System den normalen Betrieb wieder aufnehmen kann. Das Rückgabeverfahren variiert je nach dem von Ihrem System verwendeten Verschlüsselungstyp: keine Verschlüsselung oder Onboard Key Manager (OKM)-Verschlüsselung.

[role="tabbed-block"]
====
.Keine Verschlüsselung oder externer Schlüsselmanager (EKM)
--
Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie seinen Speicher zurückgeben.

.Schritte
. Geben Sie in der Loader-Eingabeaufforderung `boot_ontap` .
. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die Eingabeaufforderung _Login_ angezeigt wird, fahren Sie mit dem nächsten Schritt am Ende dieses Abschnitts fort.
** Wenn „_waiting for Giveback_“ angezeigt wird, drücken Sie die Taste <enter>, melden Sie sich beim Partner-Node an und fahren Sie dann mit dem nächsten Schritt am Ende dieses Abschnitts fort.


. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`
. Wenn das automatische Giveback deaktiviert wurde, aktivieren Sie es erneut: `storage failover modify -node local -auto-giveback _true_`
. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Onboard-Verschlüsselung (OKM)
--
Die Onboard-Verschlüsselungsschlüssel für OKM wiederherstellen und neu versiegeln und den Controller wieder in den Normalbetrieb versetzen.

.Bevor Sie beginnen
Überprüfen Sie vor Beginn  https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"] oder kontaktieren Sie den NetApp Support.

.Schritte
. Starten Sie das ONTAP-Menü über die Loader-Eingabeaufforderung `boot_ontap menu`, und wählen Sie Option 10.
. Die wichtigsten Sicherungsinformationen für das Cluster werden angezeigt.
+
.. Führen Sie den folgenden Befehl aus, um die Sicherungsinformationen für die Schlüsselverwaltung des Clusters anzuzeigen:
+
`security key-manager onboard show-backup`

.. Führen Sie den folgenden Befehl aus, um die Sicherung des Onboard Key Managers zu überprüfen:
+
`security key-manager onboard verify-backup`



. Geben Sie die OKM Passphrase ein und bestätigen Sie die erfolgreiche Verifizierung.
+

NOTE: Sie werden zweimal zur Eingabe der Passphrase aufgefordert.

. Geben Sie die Daten des Sicherungsschlüssels ein, wenn Sie dazu aufgefordert werden.
. Geben Sie im Startmenü die Option für den normalen Start ein `1`.
. Drücken Sie <enter>, wenn _Waiting for Giveback_ angezeigt wird.
. Schieben Sie das Konsolenkabel zum Partner-Node und melden Sie sich als an `admin`.
. Nur die CFO-Aggregate zurückgeben (das Root-Aggregat): `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].


. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und überprüfen Sie den Failover-Status und den Giveback-Status: `storage failover show` Und `storage failover show-giveback`.
. Synchronisieren und überprüfen Sie den Status der Tasten:
+
.. Bringen Sie das Konsolenkabel wieder zum Ersatzcontroller.
.. Fehlende Schlüssel synchronisieren: `security key-manager onboard sync`
+

NOTE: Sie werden aufgefordert, die Cluster-weite Passphrase von OKM für das Cluster einzugeben.

.. Überprüfen Sie den Status der Schlüssel: `security key-manager key query -restored false`
+
Bei korrekter Synchronisierung sollte die Ausgabe keine Ergebnisse liefern.

+
Wenn in der Ausgabe Ergebnisse angezeigt werden (die Schlüssel-IDs von Schlüsseln, die nicht in der internen Schlüsseltabelle des Systems vorhanden sind), wenden Sie sich an https://support.netapp.com["NetApp Support"].



. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`
. Wenn das automatische Giveback deaktiviert wurde, aktivieren Sie es erneut: `storage failover modify -node local -auto-giveback _true_`
+

NOTE: Das Veto gegen die Rückgabe fehlender Schlüssel darf nicht außer Kraft gesetzt werden. Wenden Sie sich an NetApp Support.

. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.Was kommt als Nächstes?
Nachdem Sie die Eigentümerschaft der Storage-Ressourcen wieder an den Ersatz-Controller übergeben haben, müssen Sie link:controller-replace-restore-system-rma.html["Schließen Sie den Controller-Austausch ab"]den Vorgang durchführen.
