---
permalink: a1k/install-prepare.html 
sidebar: sidebar 
keywords: aff a1k, prepare installation 
summary: Bereiten Sie sich auf die Installation Ihrer AFF A1K-Plattform vor. 
---
= Vorbereitung der Installation - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bereiten Sie sich auf die Installation Ihrer AFF A1K-Plattform vor.

.Bevor Sie beginnen
* Verwenden Sie die https://docs.netapp.com/us-en/ontap/software_setup/index.html["Arbeitsblatt für die Cluster-Einrichtung"] , um die Werte aufzuzeichnen, die Sie beim Konfigurieren des Clusters benötigen. Wenn ein Standardwert angegeben ist, können Sie diesen Wert verwenden oder Ihren eigenen Wert eingeben.
* Vergewissern Sie sich, dass Sie über alle zusätzlichen Geräte und Tools verfügen, die Sie zum Abschluss der Hardwareinstallation benötigen.
+
** Kreuzschlitzschraubendreher #2
** Taschenlampe
** ESD-Riemen
** Eine Büroklammer oder ein Kugelschreiber mit schmaler Spitze zum Einstellen der NS224-Einschubnummern
** Laptop oder Konsole mit USB-/serieller Verbindung
** Zugriff auf einen Webbrowser zur Konfiguration des Speichersystems


* Sie sollten sich der Sicherheitsbedenken im Zusammenhang mit dem Gewicht der Plattform bewusst sein.
+
Eine voll beladene A1K-Plattform kann bis zu 28.5 kg (62.83 lbs) wiegen und erfordert zwei Personen zum Anheben oder Verwenden eines hydraulischen Hubs.

+
image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K Warnsymbol beim Anheben]

* Sie sollten sich der Sicherheitsbedenken im Zusammenhang mit dem Gewicht des Regals bewusst sein.
+
Ein voll beladenes Regal kann bis zu 30.29 kg (66.78 lbs) wiegen und erfordert zwei Personen zum Anheben oder Verwenden eines hydraulischen Hubs. Entfernen Sie keine Regalkomponenten (von der Vorder- oder Rückseite des Regals), um das Gewicht des Regals zu verringern, da das Regalgewicht unausgeglichen wird.

+
image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Vorsicht beim Anheben]

* Der Luftstrom durch das Speichersystem gelangt von der Vorderseite, an der die Blende oder die Endkappen installiert sind, und entlüftet die Rückseite, an der sich die Anschlüsse befinden.




== Schritt 1: Bereiten Sie den Standort vor

Stellen Sie sicher, dass der Standort und der Schrank oder das Rack, den Sie verwenden möchten, den Spezifikationen für Ihr Speichersystem entsprechen.

.Schritte
. Vergewissern Sie sich, dass Ihr Standort die Umwelt- und elektrischen Anforderungen für Ihre Plattform erfüllt, wie in dargestellt https://hwu.netapp.com["NetApp Hardware Universe"^].
. Stellen Sie sicher, dass ausreichend Platz im Rack vorhanden ist:
+
** 4 HE in einer HA-Konfiguration für die Plattform
** 2 HE für jedes NS224-Shelf


. Installieren Sie alle erforderlichen Netzwerk-Switches in der Nähe der Plattform.
+
Installationsanweisungen und Kompatibilitätsinformationen finden Sie im https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Switch-Dokumentation"] link:https://hwu.netapp.com["NetApp Hardware Universe"^] .





== Schritt 2: Auspacken der Boxen

Packen Sie alle Kartons aus, und vergleichen Sie den Inhalt mit den Artikeln auf dem Packzettel.

. Öffnen Sie sorgfältig alle Kartons und legen Sie den Inhalt in einer organisierten Art und Weise.
. Vergleichen Sie den Inhalt, den Sie ausgepackt haben, mit der Liste auf dem Packzettel.
+

NOTE: Sie können Ihre Packliste erhalten, indem Sie den QR-Code auf der Seite des Versandkartons scannen.

+
Die folgenden Elemente sind einige der Inhalte, die Sie in den Feldern sehen können.

+
Stellen Sie sicher, dass alle in den Kartons auf die Liste auf dem Packzettel passen. Wenn Abweichungen auftreten, notieren Sie sie für weitere Maßnahmen.

+
[cols="12,9,4"]
|===


| *Hardware* | * Kabel* |  


 a| 
** Plattform
** Shelf
** Schienensätze mit Anweisungen (optional)
** Kabelverwaltungs-Gerät
** Blende

 a| 
** Stromkabel
** Netzwerkkabel
** Management-Ethernet-Kabel (RJ-45-Kabel)
** Serielles USB-C-Anschlusskabel
** Speicherkabel (wenn zusätzlicher Speicher bestellt wird)

|  
|===




== Schritt 3: Registrieren Sie Ihre Hardware

Die Registrierung Ihrer Plattform bietet Support-Vorteile.

.Schritte
. Suchen Sie die Seriennummer des Systems für Ihre Plattform.
+
Sie finden die Nummer auf dem Packzettel, in Ihrer Bestätigungs-E-Mail oder nach dem Auspacken auf dem System Management-Modul des Controllers.

+
image::../media/drw_ssn_label.svg[Beispiel für die Seriennummer des Systems, die den Standort der Nummer anzeigt]

. Besuchen Sie die NetApp Support-Website unter http://mysupport.netapp.com/["mysupport.netapp.com"^].
. Registrieren der Hardware:
+
[role="tabbed-block"]
====
.Option 1: Bestandskunde von NetApp
--
.Schritte
.. Melden Sie sich mit Ihrem Benutzernamen und Passwort an.
.. Wählen Sie *Systeme* > *Eigene Systeme*.
.. Vergewissern Sie sich, dass die Seriennummer des neuen Systems aufgeführt ist.



NOTE: Wenn die Seriennummer des neuen Systems nicht aufgeführt ist, befolgen Sie die Anweisungen für neue NetApp Kunden.

--
.Option 2: Neuer NetApp Kunde
--
.. Klicken Sie auf *Jetzt registrieren* und erstellen Sie ein Konto.
.. Wählen Sie *Systeme* > *Systeme Registrieren*.
.. Geben Sie die Seriennummer des Produktsystems und die angeforderten Details ein.


Nach der Registrierung können Sie die erforderliche Software herunterladen. Der Genehmigungsprozess kann bis zu 24 Stunden in Anspruch nehmen.

--
====

