---
permalink: a1k/install-hardware.html 
sidebar: sidebar 
keywords: aff a1k, install hardware, telco rack 
summary: Installieren Sie Ihr Speichersystem im Schrank oder im Telco-Rack. 
---
= Installieren Sie die Hardware AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In den folgenden Anweisungen wird beschrieben, wie die Hardware in einem leeren Schrank oder Telco-Rack installiert wird. Überspringen Sie diesen Schritt, wenn Ihr Schrank bereits bestückt ist.

.Bevor Sie beginnen
* Sie sollten das Dokument durchsehen https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Sicherheitshinweise"] und die Vorsichtsmaßnahmen für das Bewegen und Installieren von Hardware verstehen.
* Die Anweisungen sollten dem Schienensatz beiliegen.
* Sie sollten sich der Sicherheitsbedenken im Zusammenhang mit dem Gewicht der Plattform und des Regals bewusst sein.


.Schritte
. Installieren Sie die Schienensätze für die Plattform und die Regale nach Bedarf gemäß den Anweisungen, die den Kits beiliegen.
. Installieren und sichern Sie Ihre Plattform im Schrank oder im Telco-Rack:
+
.. Positionieren Sie die Plattform auf den Schienen in der Mitte des Schranks oder des Telco-Racks, und stützen Sie die Plattform von unten ab, und schieben Sie sie in ihre Position.
.. Befestigen Sie die Plattform mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.


. Installieren Sie das Shelf oder die Shelfs:
+
.. Positionieren Sie die Rückseite des Regals auf den Schienen, und stützen Sie das Regal von unten ab, und schieben Sie es in den Schrank oder das Telco-Rack.
+
Wenn Sie mehrere Shelfs installieren, platzieren Sie das erste Shelf direkt über den Controllern. Platzieren Sie das zweite Shelf direkt unter den Controllern. Wiederholen Sie dieses Muster für weitere Laufwerk-Shelfs.

.. Befestigen Sie das Regal mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.


. Schließen Sie die Kabelverwaltungsgeräte an der Rückseite der Plattform an.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installieren Sie das Kabelverwaltungsgerät]

. Befestigen Sie die Blende an der Vorderseite der Plattform.

