---
permalink: a70-90/aff-a-series-affa70-overview.html 
sidebar: sidebar 
keywords: AFF A70 specifications, AFF A70 specs, NetApp AFF A70, AFF A70 hardware 
summary: Wichtige Spezifikationen des AFF A70 Speichersystems 
---
= Wichtige Spezifikationen für AFF A70
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind ausgewählte Spezifikationen für den AFF A70 aufgeführt.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der AFF A70 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für AFF A70

Plattformkonfiguration: AFF A70 Single Chassis HA Pair

Max. Rohkapazität: 6,6096 PB

Arbeitsspeicher: 256.0000 GB

Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 18

Mindestversion von ONTAP : ONTAP 9.15.1RC2



=== Scaleout-Maximalwerte

* NAS: 12 HA-Paare, 79,3 PB / 70,4 PiB Rohkapazität, 3072 GB maximaler Speicher
* SAN: 6 HA-Paare, 39,7 PB / 35,2 PiB Rohkapazität, 1536 GB maximaler Speicher
* HA-Paar: 6,6 PB / 5,9 PiB Rohkapazität, 256,0000 GB maximaler Speicher




=== IO



==== Integrierte E/A

Keine Onboard-E/A-Daten.



==== Gesamt-IO

* Ethernet 200 Gbit/s: 24 Ports
* Ethernet 100 Gbit/s: 36 Ports
* Ethernet 25 Gbit/s: 56 Ports
* Ethernet 10 Gbit/s: 56 Ports
* FC 64 Gbit/s: 56 Ports
* NVMe/FC 64 Gbit/s: 56 Ports
* SAS 12 Gbit/s: 56 Ports




==== Verwaltungsports

* Ethernet 1 Gbit/s: 2 Ports
* RS-232 115 Kbps: 4 Anschlüsse
* USB 600 Mbit/s: 2 Anschlüsse




=== Unterstützte Speichernetzwerke

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 mit NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 6938 BTU/h
* Leistung im schlimmsten Fall: 9089 BTU/h
* Gewicht: 118,0 lbbr/53,5 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 34,5 Zoll (36,6 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (br/50 °F bis br/95 °F) bei br/= 3048 mbr/= 10000 ft) Höhe; 8 % bis 80 % (br/relative Luftfeuchtigkeit, nicht kondensierend)
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß)<br/>10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 8,6;br/Schalldruck (LpAm) (in der Nähe): 71,6 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP -Management-Schnittstelle; Redundante Hot-Swap-fähige Controller; Redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Management über SAS-Verbindungen für externe Shelves; [//] 2025-10-15 ontap-systems-internal/issues/1357
