---
permalink: a70-90/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, a90, replace the boot media 
summary: Stellen Sie vor dem Austausch der Startmedien in Ihrem AFF A70- oder AFF A90-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob Sie über das richtige Ersatz-Startgerät verfügen, der Zugriff auf die System-Firmware und die ONTAP-Software sowie ein Backup der wesentlichen Konfigurationsdaten. 
---
= Voraussetzungen für den Austausch der Boot-Medien – AFF A70 und AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch der Startmedien in Ihrem AFF A70- oder AFF A90-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob Sie über das richtige Ersatz-Startgerät verfügen, der Zugriff auf die System-Firmware und die ONTAP-Software sowie ein Backup der wesentlichen Konfigurationsdaten.

Überprüfen Sie die folgenden Anforderungen.

* Sie müssen über ein USB-Flash-Laufwerk verfügen, das auf FAT32 formatiert ist, und über die entsprechende Speichermenge, um die zu speichern `image_xxx.tgz` Datei:
* Sie müssen die Datei zur späteren Verwendung in diesem Verfahren auf das USB-Flash-Laufwerk kopieren `image_xxx.tgz` .
* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Controller anwenden:
+
** Der Controller _Impared_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _Healthy_ Controller ist der HA-Partner des beeinträchtigten Controllers.




.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Boot-Mediums überprüft haben, müssen Sie link:bootmedia-encryption-preshutdown-checks.html["Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel auf dem Startmedium"].
