---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Prüfen Sie die Anforderungen, bevor Sie das Bootmedium in Ihrem AFF A70 oder AFF A90 -Speichersystem austauschen. 
---
= Voraussetzungen für die automatische Bootmedien-Wiederherstellung – AFF A70 und AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prüfen Sie die Anforderungen, bevor Sie die Bootmedien in Ihrem AFF A70 oder AFF A90 -Speichersystem austauschen, einschließlich der Cluster-Port-Funktionalität, der Key-Manager-Konfiguration und der ONTAP Versionskompatibilität.

Für den automatisierten Wiederherstellungsprozess des Bootmediums ist ONTAP 9.17.1 oder höher erforderlich.  Wenn auf Ihrem Speichersystem eine ältere Version von ONTAP ausgeführt wird, verwenden Sie dielink:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] Die

Überprüfen Sie die folgenden Anforderungen.

* Sie müssen das ausgefallene Boot-Medium durch ein Ersatz-Boot-Medium ersetzen, das Sie von NetApp erhalten haben.
* Die Cluster-Ports dienen der Kommunikation zwischen den beiden Controllern während der automatischen Boot-Wiederherstellung. Stellen Sie sicher, dass die Cluster-Ports auf dem beeinträchtigten Controller ordnungsgemäß funktionieren.
* Für OKM benötigen Sie die clusterweite Passphrase und auch die Sicherungsdaten.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Machen Sie sich mit der in diesem Verfahren verwendeten Controller-Terminologie vertraut:
+
** Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.




.Wie es weiter geht
Nachdem Sie die Anforderungen für die Startmedien überprüft haben, können Sie link:bootmedia-shutdown-bmr.html["Fahren Sie den Controller herunter"].
