---
permalink: a70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: Bevor das Chassis im AFF A70 oder AFF A90 System ersetzt wird, sollte geprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorhanden sind, das korrekte Ersatzchassis sowie die erforderlichen Werkzeuge bereitstehen. 
---
= Anforderungen sollten vor dem Austausch des AFF A70 oder AFF A90 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Chassis im AFF A70 oder AFF A90 System ersetzt wird, sollte geprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorhanden sind, das korrekte Ersatzchassis sowie die erforderlichen Werkzeuge bereitstehen.

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind

Überprüfen Sie die folgenden Anforderungen.

* Stellen Sie sicher, dass alle anderen Komponenten des Systems ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an, http://mysupport.netapp.com/["NetApp Support"^] um Unterstützung zu erhalten.
* Holen Sie sich lokale Administratoranmeldeinformationen für ONTAP ein, wenn diese nicht vorhanden sind.
* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.
* Sie können das Verfahren zum Austausch des Gehäuses für alle Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Es wird angenommen, dass Sie die Blende, die NVMe-Laufwerke und die Controller-Module auf das neue Gehäuse verschieben, und dass das Ersatzgehäuse eine neue Komponente von NetApp ist.
* Das Verfahren zum Austausch des Gehäuses führt zu Unterbrechungen. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.


.Was kommt als Nächstes?
Nach Durchsicht der Anforderungen,link:chassis-replace-prepare.html["Bereiten Sie den Austausch des Gehäuses vor"] Die
