---
permalink: a70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: Bereiten Sie den Austausch des Gehäuses für beeinträchtigte Personen in Ihrem AFF A70- oder AFF A90-System vor, indem Sie das Gehäuse für beeinträchtigte Personen ermitteln, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module beschriften. 
---
= Bereiten Sie den Austausch des Gehäuses vor – AFF A70 und AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bereiten Sie den Austausch des Gehäuses für beeinträchtigte Personen in Ihrem AFF A70- oder AFF A90-System vor, indem Sie das Gehäuse für beeinträchtigte Personen ermitteln, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module beschriften.

.Schritte
. Stellen Sie eine Verbindung zum seriellen Konsolenport mit der Schnittstelle mit her und überwachen Sie das System.
. Schalten Sie die Standort-LED des Controllers ein:
+
.. Verwenden Sie die `system controller location-led show` Befehl zur Anzeige des aktuellen Status der Standort-LED.
.. Standort-LED einschalten:
+
`system controller location-led modify -node _node1_ -state on`

+
Die Standort-LED leuchtet 30 Minuten lang.



. Prüfen Sie vor dem Öffnen der Verpackung das Verpackungsetikett und vergewissern Sie sich, dass Folgendes vorhanden ist:
+
** Bauteilnummer
** Teilebeschreibung
** Menge in der Box


. Nehmen Sie den Inhalt aus der Verpackung und bewahren Sie die Verpackung auf, um die defekte Komponente an NetApp zurückzusenden.
. Beschriften Sie alle an das Speichersystem angeschlossenen Kabel.  Dadurch wird eine ordnungsgemäße Neuverkabelung im weiteren Verlauf dieses Verfahrens sichergestellt.
. Erden Sie sich, falls Sie noch nicht geerdet sind.


.Was kommt als Nächstes?
Nachdem Sie sich darauf vorbereitet haben, Ihre AFF A70- oder AFF A90-Chassis-Hardware zu ersetzen, müssen Sie link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"].
