---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: Überprüfen Sie die erforderlichen Geräte und die Vorsichtsmaßnahmen für das Anheben der Plattform und der Regale. 
---
= Installationsvoraussetzungen - AFF A70 und AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie die erforderlichen Geräte sowie die Vorsichtsmaßnahmen beim Anheben des AFF A70 oder AFF A90 Storage-Systems und der Storage-Shelfs durch.



== Für die Installation erforderliche Ausrüstung

Zur Installation des Storage-Systems benötigen Sie die folgenden Geräte und Tools:

* Zugriff auf einen Webbrowser zur Konfiguration des Speichersystems
* Band für elektrostatische Entladung (ESD)
* Taschenlampe
* Laptop oder Konsole mit USB-/serieller Verbindung
* Büroklammer oder Kugelschreiber mit schmaler Spitze zum Einstellen der NS224-Einschubnummern
* Kreuzschlitzschraubendreher #2




== Vorsichtsmaßnahmen beim Anheben

Storage-Systeme und Shelves sind schwer. Gehen Sie beim Anheben und Bewegen dieser Gegenstände vorsichtig vor.



=== Gewicht des Storage-Systems

Treffen Sie die erforderlichen Vorsichtsmaßnahmen, wenn Sie das Speichersystem bewegen oder anheben.

Das Speichersystem kann bis zu 68.8 kg (151.68 lbs) wiegen. Zum Anheben des Lagersystems vier Personen oder einen Hydraulikhub verwenden.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== Regalgewicht

Treffen Sie die erforderlichen Vorsichtsmaßnahmen, wenn Sie Ihr Regal bewegen oder anheben.

Ein NS224-Einschub kann bis zu 30.29 kg (66.78 lbs) wiegen. Zum Anheben des Regals zwei Personen oder einen Hydraulikhub verwenden. Halten Sie alle Komponenten im Regal (vorne und hinten), um ein Ausbalancieren des Regalgewichts zu vermeiden.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 Vorsicht beim Anheben]

.Verwandte Informationen
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Sicherheitsinformationen und gesetzliche Hinweise"^]


.Was kommt als Nächstes?
Nachdem Sie die Hardwareanforderungen überprüft haben, können Sie link:install-prepare.html["Vorbereitung der Installation des AFF A70 oder AFF A90 Storage-Systems"].
