---
permalink: afx-2k/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, replace the chassis 
summary: Bevor das Gehäuse im AFX 2K Storage System ersetzt wird, sollten die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sein. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorliegen, das korrekte Ersatzgehäuse sowie die erforderlichen Werkzeuge vorhanden sind. 
---
= Anforderungen prüfen, bevor ein AFX 2K Gehäuse ausgetauscht wird
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Gehäuse im AFX 2K Storage System ersetzt wird, sollten die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sein. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, lokale Administratoranmeldedaten für ONTAP vorliegen, das korrekte Ersatzgehäuse sowie die erforderlichen Werkzeuge vorhanden sind.

Das Gehäuse ist das physische Gehäuse, in dem alle Systemkomponenten wie Lüfter, Controller-/CPU-Einheit, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile untergebracht sind.

Überprüfen Sie die folgenden Anforderungen.

* Stellen Sie sicher, dass alle anderen Komponenten des Systems ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an, http://mysupport.netapp.com/["NetApp Support"^] um Unterstützung zu erhalten.
* Holen Sie sich lokale Administratoranmeldeinformationen für ONTAP ein, wenn diese nicht vorhanden sind.
* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.
* Sie können das Verfahren zum Austausch des Gehäuses für alle Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Bei der Beschreibung des Verfahrens zum Austausch des Gehäuses wird davon ausgegangen, dass Sie Blende, Lüfter, Controllermodul, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile in das neue Gehäuse einbauen und dass es sich bei dem Austauschgehäuse um eine neue Komponente von NetApp handelt.


.Was kommt als Nächstes?
Nach Prüfung der Anforderungenlink:chassis-replace-prepare.html["Machen Sie sich bereit, das Chassis zu ersetzen"] .
