---
permalink: a900/bootmedia_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: Das Startmedium enthält einen primären und einen sekundären Satz von Systemdateien, die das System beim Start verwendet. Je nach Netzwerkkonfiguration können Sie entweder einen unterbrechungsfreien oder einen unterbrechenden Austausch durchführen. 
---
= Ersetzen Sie den Startdatenträger - AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Boot-Medium speichert einen primären und sekundären Satz von Systemdateien (Boot-Image), die das System beim Booten verwendet. Je nach Netzwerkkonfiguration können Sie entweder einen unterbrechungsfreien oder störenden Austausch durchführen.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
Sie müssen über ein USB-Flash-Laufwerk verfügen, das auf FAT32 formatiert ist, und über die entsprechende Speichermenge, um die zu speichern `image_xxx.tgz` Datei:

Außerdem müssen Sie die kopieren `image_xxx.tgz` Datei auf dem USB-Flash-Laufwerk zur späteren Verwendung in diesem Verfahren.

* Bei den unterbrechungsfreien und unterbrechungsfreien Methoden zum Austausch von Boot-Medien müssen Sie den wiederherstellen `var` Filesystem:
+
** Beim unterbrechungsfreien Austausch benötigt das HA-Paar keine Verbindung zu einem Netzwerk, um den wiederherzustellen `var` File-System. Das HA-Paar in einem einzelnen Chassis hat eine interne E0S-Verbindung, die zum Transfer verwendet wird `var` Konfigurieren zwischen ihnen.
** Für den störenden Austausch benötigen Sie keine Netzwerkverbindung, um den wiederherzustellen `var` Dateisystem, aber der Prozess erfordert zwei Neustarts.


* Sie müssen die ausgefallene Komponente durch eine FRU-Ersatzkomponente ersetzen, die Sie von NetApp erhalten haben.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Controller anwenden:
+
** Der Controller _Impared_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _Healthy_ Controller ist der HA-Partner des beeinträchtigten Controllers.



