---
permalink: a900/controller_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen. 
---
= Ersetzen Sie das Controller-Modul AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das beeinträchtigte Controller-Modul auszutauschen, müssen Sie den beeinträchtigten Controller herunterfahren, die internen Komponenten in das Ersatzcontrollermodul verschieben, das Ersatzcontrollermodul installieren und den Ersatz-Controller neu starten.

.Bevor Sie beginnen
Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen.

* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Wenn Ihr System ein FlexArray-System ist oder über eine V_StorageAttach-Lizenz verfügt, müssen Sie vor der Durchführung dieses Verfahrens die zusätzlichen erforderlichen Schritte beachten.
* Wenn sich Ihr System in einem HA-Paar befindet, muss der gesunde Controller in der Lage sein, den zu ersetzenden Controller zu übernehmen (in diesem Verfahren als „`eingeschränkter Controller`“ bezeichnet).
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie den Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"] Um zu bestimmen, ob Sie dieses Verfahren verwenden sollten.
+
Beachten Sie, dass das Verfahren zum Austausch des Controllers bei einem Controller in einer MetroCluster Konfiguration mit vier oder acht Nodes mit dem bei einem HA-Paar identisch ist. Es sind keine MetroCluster-spezifischen Schritte erforderlich, da der Ausfall auf ein HA-Paar beschränkt ist und Storage Failover-Befehle zur unterbrechungsfreien Ausführung während des Austauschs genutzt werden können.

* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Sie müssen ein Controller-Modul durch ein Controller-Modul desselben Modelltyps ersetzen. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* In diesem Verfahren wird das Startgerät vom beeinträchtigten Controller auf den Ersatzcontroller verschoben, so dass der Ersatzcontroller in derselben ONTAP-Version wie das alte Controller-Modul hochstartet.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die beeinträchtigte Steuerung ist die Steuerung, die ausgetauscht wird.
** Der Ersatz-Controller ist der neue Regler, der die beeinträchtigte Steuerung ersetzt.
** Der gesunde Controller ist der überlebende Controller.


* Sie müssen die Konsolenausgabe der Controller immer in einer Textdatei erfassen.
+
Auf diese Weise erhalten Sie eine Aufzeichnung des Verfahrens, damit Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.


