---
permalink: a900/controller_replace_system_config_restore_and_verify.html 
sidebar: sidebar 
keywords:  
summary: Nach Abschluss des Hardware-Austauschs und des Bootens im Wartungsmodus überprüfen Sie die Low-Level-Systemkonfiguration des Ersatz-Controllers, konfigurieren die Systemeinstellungen nach Bedarf neu und führen dann die Diagnose auf Systemebene aus. 
---
= Wiederherstellen und Überprüfen der Systemkonfiguration – AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach Abschluss des Hardware-Austauschs überprüfen Sie die Low-Level-Systemkonfiguration des Ersatz-Controllers, konfigurieren die Systemeinstellungen nach Bedarf neu und führen dann die Diagnose auf Systemebene aus.



== Schritt 1: Stellen Sie die Systemzeit nach dem Austausch des Controller-Moduls ein und überprüfen Sie sie

Sie sollten die Uhrzeit und das Datum auf dem Ersatzcontroller-Modul gegen das gesunde Controller-Modul in einem HA-Paar oder gegen einen zuverlässigen Zeitserver in einer eigenständigen Konfiguration überprüfen. Wenn Zeit und Datum nicht übereinstimmen, müssen Sie sie auf dem Ersatzcontroller-Modul zurücksetzen, um mögliche Ausfälle auf Clients aufgrund von Zeitunterschieden zu verhindern.

.Über diese Aufgabe
Es ist wichtig, dass Sie die Befehle in den Schritten auf den richtigen Systemen anwenden:

* Der Node _Replacement_ ist der neue Node, der den beeinträchtigten Knoten im Rahmen dieses Verfahrens ersetzt.
* Der Node _Healthy_ ist der HA-Partner des Node _Replacement_.


.Schritte
. Wenn sich der Node _Replacement_ nicht an der LOADER-Eingabeaufforderung befindet, halten Sie das System an der LOADER-Eingabeaufforderung an.
. Überprüfen Sie auf dem Node _Healthy_ die Systemzeit: `show date`
+
Datum und Uhrzeit werden in GMT angegeben.

. Prüfen Sie an der LOADER-Eingabeaufforderung Datum und Uhrzeit auf dem Node _Replacement_: `show date`
+
Datum und Uhrzeit werden in GMT angegeben.

. Legen Sie bei Bedarf das Datum in GMT auf dem Ersatzknoten fest: `set date _mm/dd/yyyy_`
. Stellen Sie bei Bedarf die Zeit in GMT auf dem Ersatzknoten ein: `set time _hh:mm:ss_`
. Bestätigen Sie an der LOADER-Eingabeaufforderung Datum und Uhrzeit am Node _Replacement_: `show date`
+
Datum und Uhrzeit werden in GMT angegeben.





== Schritt: Überprüfen Sie den HA-Status des Controller-Moduls und legen Sie ihn fest

Sie müssen die überprüfen `HA` Status des Controller-Moduls und, falls erforderlich, aktualisieren Sie den Status entsprechend Ihrer Systemkonfiguration.

. Überprüfen Sie im Wartungsmodus des Ersatz-Controller-Moduls, ob alle Komponenten gleich angezeigt werden `HA` Bundesland: `ha-config show`
+
[cols="1,2"]
|===
| Ihr System befindet sich in... | Der HA-Status für alle Komponenten sollte... 


 a| 
Ein HA-Paar
 a| 
Hochverfügbarkeit



 a| 
MetroCluster FC-Konfiguration mit vier oder mehr Nodes
 a| 
mcc



 a| 
Eine MetroCluster IP-Konfiguration
 a| 
Mccip

|===
. Wenn der angezeigte Systemzustand des Controller-Moduls nicht mit der Systemkonfiguration übereinstimmt, setzen Sie das ein `HA` Status für das Controller-Modul: `ha-config modify controller _ha-state_`
. Wenn der angezeigte Systemzustand des Gehäuses nicht mit der Systemkonfiguration übereinstimmt, legen Sie den fest `HA` Status für das Chassis: `ha-config modify chassis _ha-state_`




== Schritt 3: Führen Sie die Diagnose auf Systemebene aus

Sie sollten beim Austausch des Controllers umfassende oder gezielte Diagnosetests für bestimmte Komponenten und Subsysteme durchführen.

Alle Befehle im Diagnoseverfahren werden vom Controller ausgegeben, der die Komponente ersetzt wird.

. Wenn der zu wartenden Controller nicht an der LOADER-Eingabeaufforderung angezeigt wird, booten Sie den Controller neu: `halt`
+
Nachdem Sie den Befehl ausgegeben haben, sollten Sie warten, bis das System an der LOADER-Eingabeaufforderung angehalten wird.

. Rufen Sie an der LOADER-Eingabeaufforderung die speziellen Treiber auf, die speziell für die Diagnose auf Systemebene entwickelt wurden, um ordnungsgemäß zu funktionieren: `boot_diags`
+
Während des Startvorgangs können Sie sicher reagieren `y` Zu den Aufforderungen, bis die Eingabeaufforderung für den Wartungsmodus (*>) angezeigt wird.

. Die verfügbaren Geräte des Controller-Moduls anzeigen und notieren: `sldiag device show -dev mb`
+
Die angezeigten Controller-Module und -Ports können eine oder mehrere der folgenden sein:

+
** Bootmedia ist das Systembootgerät.
** cna ist ein konvergierter Netzwerkadapter oder eine Schnittstelle, die nicht mit einem Netzwerk oder Speichergerät verbunden ist.
** fcal ist ein Fibre Channel-Arbitrated Loop-Gerät, das nicht mit einem Fibre Channel-Netzwerk verbunden ist.
** env ist die Umgebung der Hauptplatine.
** Speicher ist Systemspeicher.
** nic ist eine Netzwerkschnittstellenkarte.
** nvram ist nicht-flüchtiger RAM.
** Nvmem ist ein Hybridmodell aus NVRAM und Systemspeicher.
** sas ist ein Serial Attached SCSI-Gerät, das nicht mit einem Festplatten-Shelf verbunden ist.


. Führen Sie die Diagnose nach Bedarf aus.
+
[cols="1,2"]
|===
| Wenn Sie Diagnosetests ausführen möchten, um... | Dann... 


 a| 
Einzelne Komponenten
 a| 
.. Löschen Sie die Statusprotokolle: `sldiag device clearstatus`
.. Anzeigen der verfügbaren Tests für die ausgewählten Geräte: `sldiag device show -dev dev_name`
+
Dev_Name kann eine beliebige der im vorherigen Schritt identifizierten Ports und Geräte sein.

.. Überprüfen Sie die Ausgabe, und wählen Sie ggf. nur die Tests aus, die Sie ausführen möchten: `sldiag device modify -dev dev_name -selection only`
+
-Selection deaktiviert nur alle anderen Tests, die Sie nicht für das Gerät ausführen möchten.

.. Die ausgewählten Tests ausführen: `sldiag device run -dev dev_name`
+
Nach Abschluss des Tests wird die folgende Meldung angezeigt:

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. Vergewissern Sie sich, dass keine Tests fehlgeschlagen sind: `sldiag device status -dev dev_name -long -state failed`
+
Die Diagnose auf Systemebene gibt die Eingabeaufforderung zurück, wenn keine Testfehler auftreten oder den vollständigen Status von Fehlern, die durch das Testen der Komponente entstehen, angezeigt wird.





 a| 
Mehrere Komponenten gleichzeitig
 a| 
.. Überprüfen Sie die aktivierten und deaktivierten Geräte in der Ausgabe des vorhergehenden Verfahrens und bestimmen Sie, welche Geräte gleichzeitig ausgeführt werden sollen.
.. Führen Sie die einzelnen Tests für das Gerät auf: `sldiag device show -dev dev_name`
.. Überprüfen Sie die Ausgabe, und wählen Sie ggf. nur die Tests aus, die Sie ausführen möchten: `sldiag device modify -dev dev_name -selection only`
+
-Selection deaktiviert nur alle anderen Tests, die Sie nicht für das Gerät ausführen möchten.

.. Überprüfen Sie, ob die Tests geändert wurden: `sldiag device show`
.. Wiederholen Sie diese Teilschritte für jedes Gerät, das gleichzeitig ausgeführt werden soll.
.. Führen Sie eine Diagnose für alle Geräte durch: `sldiag device run`
+

IMPORTANT: Fügen Sie Ihre Einträge nach dem Ausführen der Diagnose nicht hinzu oder ändern Sie sie nicht.

+
Nach Abschluss des Tests wird die folgende Meldung angezeigt:

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. Vergewissern Sie sich, dass es keine Hardware-Probleme auf dem Controller gibt: `sldiag device status -long -state failed`
+
Die Diagnose auf Systemebene gibt die Eingabeaufforderung zurück, wenn keine Testfehler auftreten oder den vollständigen Status von Fehlern, die durch das Testen der Komponente entstehen, angezeigt wird.



|===
. Fahren Sie auf der Grundlage des Ergebnisses des vorhergehenden Schritts fort:
+
[cols="1,2"]
|===
| Wenn die Diagnose auf Systemebene testet... | Dann... 


 a| 
Wurden ohne Fehler abgeschlossen
 a| 
.. Löschen Sie die Statusprotokolle: `sldiag device clearstatus`
.. Überprüfen Sie, ob das Protokoll gelöscht wurde: `sldiag device status`
+
Die folgende Standardantwort wird angezeigt:

+
SLDIAG: Es sind keine Protokollnachrichten vorhanden.

.. Beenden des Wartungsmodus: `halt`
+
Der Controller zeigt die LOADER-Eingabeaufforderung an.

.. Booten des Controllers über die LOADER-Eingabeaufforderung: `bye`
.. Zurückkehren des Controllers in den normalen Betrieb:


|===


[cols="1,2"]
|===
| Wenn Ihr Controller in... | Dann... 


 a| 
Ein HA-Paar
 a| 
Geben Sie zurück: `storage failover giveback -ofnode replacement_node_name` *Hinweis:* Wenn Sie das automatische Giveback deaktiviert haben, aktivieren Sie es mit dem Befehl Storage Failover modify erneut.



 a| 
Es kam zu einigen Testfehlern
 a| 
Bestimmen Sie die Ursache des Problems:

. Beenden des Wartungsmodus: `halt`
+
Nachdem Sie den Befehl ausgegeben haben, warten Sie, bis das System an der LOADER-Eingabeaufforderung angehalten wird.

. Schalten Sie die Netzteile aus oder wieder ein, abhängig von der Anzahl der Controller-Module im Chassis. + Lassen Sie die Netzteile eingeschaltet, um das andere Controller-Modul mit Strom zu versorgen.
. Überprüfen Sie, ob Sie alle Aspekte, die bei der Ausführung von Diagnose auf Systemebene zu beachten sind, dass die Kabel sicher angeschlossen sind und die Hardwarekomponenten ordnungsgemäß im Storage-System installiert wurden.
. Booten Sie das zu betreuende Controller-Modul, und unterbrechen Sie den Boot, indem Sie auf drücken `Ctrl-C` Wenn Sie dazu aufgefordert werden, zum Startmenü zu gelangen. + das Controller-Modul wird bei vollem Sitz hochgestartet.
. Wählen Sie aus dem Menü die Option Start in den Wartungsmodus.
. Beenden Sie den Wartungsmodus, indem Sie den folgenden Befehl eingeben: `halt`
+
Nachdem Sie den Befehl ausgegeben haben, warten Sie, bis das System an der LOADER-Eingabeaufforderung angehalten wird.

. Führen Sie den Diagnosetest auf Systemebene erneut aus.


|===