---
permalink: a900/overview.html 
sidebar: sidebar 
keywords: AFF A900 specifications, AFF A900 specs, NetApp AFF A900, AFF A900 hardware 
summary: Wichtige Spezifikationen für die A900-Plattformgruppe 
---
= Wichtige Spezifikationen für AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das AFF A900 Speichersystem in einem einzelnen Hochverfügbarkeitspaar. Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== Wichtige Spezifikationen für AFF A900

* Plattformkonfiguration: AFF A900 Single Chassis HA Pair
* Max. Rohkapazität: 14,6880 PB
* Arbeitsspeicher: 2048.0000 GB
* Formfaktor: 8U-Gehäuse mit 2 HA-Controllern
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 20
* Mindestversion von ONTAP : ONTAP 9.10.1RC2




== Skalierungsmaxima

* Typ: NAS; HA-Paare: 12; Rohkapazität: 176,3 PB / 156,5 PiB; Max. Speicher: 24576 GB
* Typ: SAN; HA-Paare: 6; Rohkapazität: 88,1 PB / 78,3 PiB; Max. Speicher: 12288 GB
* Typ: HA-Paar; Rohkapazität: 14,7 PB / 13,0 PiB; Max. Speicher: 2048.0000




== E/A



=== Integrierte E/A

Keine Onboard-E/A-Daten.



=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 32
* Protokoll: Ethernet 25 Gbit/s; Ports: 64
* Protokoll: Ethernet 10 Gbit/s; Ports: 64
* Protokoll: FC 32 Gbit/s; Ports: 64
* Protokoll: NVMe/FC 32 Gbit/s; Ports: 64
* Anschlüsse: 0
* Protokoll: SAS 12 Gbit/s; Ports: 64




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 2
* Protokoll: RS-232 115 Kbps; Ports: 6
* Protokoll: USB 12 Mbit/s; Anschlüsse: 2




== Speichernetzwerke werden unterstützt

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 mit NAS
* KMU 2.0
* SMB 2.1
* SMB 2.x
* KMU 3.0
* KMU 3.1
* SMB 3.1.1




== Systemumgebungsspezifikationen

* Typische Leistung: 8004 BTU/h
* Leistung im schlimmsten Fall: 9937 BTU/h
* Gewicht: 220.5 lb 100.0 kg
* Höhe: 8U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,7 Zoll, 45,0 cm)
* Tiefe: 28,8 Zoll (36,8 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bis zu einer Höhe von 3048 m (10000 ft); 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Lagertemperatur/Luftfeuchtigkeit: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12192 m (40000 ft), 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 7,4 Schalldruck (LpAm) (in der Nähe): 65,0 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile
* SAS-In-Band-Verwaltung über SAS-Verbindungen

