---
permalink: asa800/overview.html 
sidebar: sidebar 
keywords: ASA A800 specifications, ASA A800 specs, NetApp ASA A800, ASA A800 hardware 
summary: Wichtige Spezifikationen für das ASA A800 -Speichersystem 
---
= Wichtige Spezifikationen für ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für den ASA A800.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der ASA A800 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für ASA A800

Plattformkonfiguration: ASA A800 Single Chassis HA-Paar

Max. Rohkapazität: 6,6096 PB

Arbeitsspeicher: 1280.0000 GB

Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 10

Mindestens erforderliche ONTAP -Version: ONTAP 9.13.1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS |  |  |  


| SAN | 6 | 39,7 PB / 35,2 PiB | 7680 GB 


| HA-Paar |  | 6,6 PB / 5,9 PiB | 1280,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 4 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 20 


| Ethernet 25 Gbit/s | 16 


| Ethernet 10 Gbit/s | 32 


| FC 32 Gbit/s | 32 


| NVMe/FC 32 Gbit/s | 32 


|  | 0 


|  | 0 


| SAS 12 Gbit/s | 32 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 4 
|===


=== Unterstützte Speichernetzwerke

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== Spezifikationen der Systemumgebung

Keine Umgebungsdaten verfügbar.



=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle; redundante Hot-Swap-fähige Controller; redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Verwaltung über SAS-Verbindungen für externe Shelves;
