---
permalink: a200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, replace the chassis 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Anforderungen sollten vor dem Austausch des AFF A200 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Gehäuses in Ihrem AFF A200 System sollten die Anforderungen für einen erfolgreichen Austausch geprüft werden. Das Verfahren zum Austausch des Gehäuses umfasst das Umsetzen aller Netzteile, Laufwerke und Controller-Module vom defekten Gehäuse in das Ersatzgehäuse und ist mit einer Unterbrechung verbunden.

.Bevor Sie beginnen
Alle anderen Komponenten im System müssen ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an den technischen Support.

.Über diese Aufgabe
* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie alle Laufwerke und Controller-Module bzw. -Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

