---
permalink: a200/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a200, verify and set HA state,  complete the replacement process 
summary: Sie müssen den HA-Status des Gehäuses überprüfen und das fehlerhafte Teil an NetApp zurücksenden, wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben. 
---
= Wiederherstellen und Verifizieren der Konfiguration – AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

[role="lead"]
Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

.Schritte
. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest: `ha-config modify chassis _HA-state_`
+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
*** `ha`
*** `non-ha`


.. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`


. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.




== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
