---
permalink: a200/maintain-overview.html 
sidebar: sidebar 
keywords: aff A220 maintenance, maintenance, repairing a200, repairing aff a200, replace aff a200 components, replace aff a200 components 
summary: Wartung der AFF A200 Hardware 
---
= Informationen zur Wartung Ihres AFF A200 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für das AFF A200 Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



[[boot-media]]
== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



[[caching-module]]
== Caching-Modul

Sie müssen das Caching-Modul des Controllers ersetzen, wenn Ihr System eine einzelne AutoSupport-Meldung (ASUP) registriert, dass das Modul offline gegangen ist.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[drive]]
== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



[[nvem-battery]]
== NVEM-Batterie

Ein Akku ist im Lieferumfang eines Controllers enthalten und behält zwischengespeicherte Daten bei Ausfall des Netzstroms bei.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Echtzeituhr-Akku

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
