---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP Hardwaresysteme – Dok
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was gibt es Neues bei ONTAP Hardwaresystemen
      url: "/whats-new.html"
    - title: ONTAP Hardware- und Softwarekompatibilität
      url: "/supported-platforms.html"
    - title: Einstellung des Supports
      url: "/eoa-hardware.html"
  - title: Schnellstart
    url: "/get-up-and-run.html"
  - title: AFF Systeme
    url: "/aff-landing/index.html"
    entries:
    - title: A-Series Systemen verfügbar
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: C-Series Systeme
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
      - section: c800
  - title: ASA Systeme
    url: "/allsan-landing/index.html"
    entries:
    - title: A-Series Systemen verfügbar
      url: "/allsan-a-series/index.html"
      entries:
      - section: asa150
      - section: asa250
      - section: asa400
      - section: asa800
      - section: asa900
    - title: C-Series Systeme
      url: "/allsan-c-series/index.html"
      entries:
      - section: asa-c250
      - section: asa-c400
      - section: asa-c800
  - title: ASA r2-Systeme
    url: "/asa-r2/index.html"
    entries:
    - title: Installation und Einrichtung
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: Wartung
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: FAS Systeme
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Auslaufen der Verfügbarkeit
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: Andere Modelle
      url: "/other/other-models.html"
  - title: Festplatten-Shelfs
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: sas3
  - title: Rack und Schienensatz
    entries:
    - title: SuperRail Kit
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700/FAS9000 zweiposanter Schienensatz
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42-HE-1280-mm-Systemschrank
      entries:
      - title: Vorbereiten der Installation des Schranks
        entries:
        - title: Schaltschrankfunktionen
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Erforderliche Werkzeuge/Ausrüstung
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Platzbedarf und Abmessungen der Schränke
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Unterstützte PDU-Typen und Spezifikationen
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Systemschrank auspacken
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Schrank einbauen
        entries:
        - title: Überblick
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Einbau des Schaltschrankkoppelsatzes
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Den Schraubensatz einbauen
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Installieren Sie die Stützschienen
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Installation der Geräte
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Schalten Sie den Schrank ein
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Tauschen Sie PDUs aus
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Vordere Klappe des Rückwärtsschranks
        entries:
        - title: Was Sie brauchen
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Beleuchtetes Abzeichen entfernen
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Die Schranktür ausbauen
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Stromversorgung und Verkabelung der Abzeichen verschieben
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Scharnier und Verriegelung der Rückwärtsgangklappe
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Die Tür und das beleuchtete Abzeichen wieder einbauen
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Austauschverfahren nach Komponente
    url: "/fru-reference/index.html"
    entries:
    - title: Boot-Medien
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: Caching-Modul
      url: "/fru-reference/caching-module-fru-links.html"
    - title: Chassis
      url: "/fru-reference/chassis-fru-links.html"
    - title: Controller
      url: "/fru-reference/controller-fru-links.html"
    - title: DCPM-Leistungsmodul
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: Laufwerk
      url: "/fru-reference/drive-fru-links.html"
    - title: Ventilator
      url: "/fru-reference/fan-fru-links.html"
    - title: I/O-Modul
      url: "/fru-reference/io-module-fru-links.html"
    - title: LED-Modul
      url: "/fru-reference/led-module-fru-links.html"
    - title: Mezzanin
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: NVMEM/ NVRAM -Batterie
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: NVRAM-Modul
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: PCI-Karten und Riser
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: Stromversorgung
      url: "/fru-reference/power-supply-fru-links.html"
    - title: RTC-Akku
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: Systemmanagement-Modul
      url: "/fru-reference/system-management-fru-links.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
