---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP Hardwaresysteme – Dok
    url: "/index.html"
  - title: Versionshinweise
    url: "/rel-notes.html"
  - title: Los geht's
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Starten Sie jetzt
      url: "/get-up-and-run.html"
  - title: Systeme der AFF A-Series
    url: "/aff-aseries/index.html"
    entries:
    - section: a150
    - section: a250
    - section: a400
    - section: a800
    - section: a900
  - title: Systeme der AFF C-Serie
    url: "/aff-cseries/index.html"
    entries:
    - section: c250
    - section: c400
    - section: c800
  - title: Systeme der ASA A-Series
    url: "/allsan-a-series/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Systeme der ASA C-Serie
    url: "/allsan-c-series/index.html"
    entries:
    - section: asa-c250
    - section: asa-c-400
    - section: asa-c800
  - title: FAS Systeme
    url: "/fas/index.html"
    entries:
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Auslaufen der Verfügbarkeit
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - section: other
  - title: Festplatten-Shelfs
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: sas3
  - title: Rack und Schienensatz
    entries:
    - title: SuperRail Kit
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700/FAS9000 zweiposanter Schienensatz
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42-HE-1280-mm-Systemschrank
      entries:
      - title: Vorbereiten der Installation des Schranks
        entries:
        - title: Schaltschrankfunktionen
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Erforderliche Werkzeuge/Ausrüstung
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Platzbedarf und Abmessungen der Schränke
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Unterstützte PDU-Typen und Spezifikationen
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Systemschrank auspacken
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Schrank einbauen
        entries:
        - title: Überblick
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Einbau des Schaltschrankkoppelsatzes
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Den Schraubensatz einbauen
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Installieren Sie die Stützschienen
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Installation der Geräte
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Schalten Sie den Schrank ein
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Tauschen Sie PDUs aus
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Vordere Klappe des Rückwärtsschranks
        entries:
        - title: Was Sie brauchen
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Beleuchtetes Abzeichen entfernen
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Die Schranktür ausbauen
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Stromversorgung und Verkabelung der Abzeichen verschieben
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Scharnier und Verriegelung der Rückwärtsgangklappe
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Die Tür und das beleuchtete Abzeichen wieder einbauen
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
