---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Erfahren Sie mehr über die neuen Plattformen für ONTAP Hardware-Systeme. 
---
= Neuerungen bei ONTAP Hardwaresystemen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei ONTAP Hardwaresystemen.



== Dezember 2024



=== AFF A20, AFF A30 und AFF A50

Die neuen Hardwaresysteme AFF A20, A30 und A50 bieten noch mehr Kunden und Workloads leistungsstarke, intelligente und umfassende Datenmanagementfunktionen.

Die Systeme bieten ML-basierte Ransomware-Erkennung in Echtzeit, nahtlose Cloud-Integration und beispiellose Performance für geschäftskritische Workloads wie KI, VMware, Datenbanken und Analysen und unterstützen Block-, File- und Objekt-Storage.

link:https://www.netapp.com/data-storage/aff-a-series/["Weitere Informationen zu den Systemen der AFF A-Serie"].



=== AFF C30, AFF C60 und AFF C80

Mit den neuen Hardwaresystemen AFF C30, AFF C60 und AFF C80 ist die Performance und Effizienz von Flash für Unternehmen einfacher zugänglich, da sie in Implementierungen mit zwei Racks eine Storage-Kapazität von 1,5 PB bieten.

Die Lösung bietet eine außergewöhnliche Dichte mit 60-TB-Laufwerken, höhere Performance und verbesserte I/O-Flexibilität.

link:https://www.netapp.com/data-storage/aff-c-series/["Erfahren Sie mehr über die Systeme der AFF C-Serie"].



== September 2024



=== ASA r2-Systeme

Die neuen ASA r2 Hardwaresysteme (ASA A1K, ASA A70 und ASA A90) bieten eine einheitliche Hardware- und Softwarelösung, mit der speziell auf die Anforderungen von reinen SAN-Kunden eine vereinfachte Benutzererfahrung erzielt wird.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].



=== FAS70 und FAS90

Die neuen Hardwaresysteme FAS70 und FAS90 bieten kostengünstigen und gleichzeitig hochperformanten Backup-Storage und ermöglichen damit eine sichere Cyber-Vault zur Recovery nach Ransomware-Angriffen.

link:https://www.netapp.com/data-storage/fas/["Erfahren Sie mehr über FAS Systeme"].
