---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features,aff, asa,  fas, legacy, end-of-support 
summary: Erfahren Sie mehr über die neuen Funktionen der Systeme AFF, ASA und FAS sowie über die alte Hardware, die nicht mehr unterstützt wird. 
---
= Neuerungen bei AFF, ASA und FAS Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die neuen Funktionen für AFF-, ASA- und FAS-Systeme.

Details zu bekannten Problemen, Einschränkungen und Upgrade-Warnhinweisen in ONTAP 9 Versionen finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP 9"]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.



== Unterstützung für neue Plattformen

[cols="2*"]
|===
| Plattformen (mit Links zu Datenblättern) | Verfügbar ab 


 a| 
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A1K"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A70"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A90"]

 a| 
ONTAP 9.15.1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9.13.P11



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA und neuere ONTAP Versionen

[NOTE]
====
Diese Plattformen werden mit ONTAP 9.13.1 RC1 nicht unterstützt.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
Versuchen Sie nicht, Ihr AFF A150-Speichersystem mit einer nicht unterstützten ONTAP-Version zu installieren oder zu booten. Wenn Sie versuchen, Ihr System mit einer nicht unterstützten Version von ONTAP zu installieren oder zu starten, lässt ONTAP dies zu (ONTAP blockiert den Versuch nicht). Die Folge ist, dass Ihr AFF A150 Storage-System als FAS2750 Storage-System eingesetzt wird.

==== a| 
ONTAP 9.13.1 und höhere ONTAP-Versionen

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7623-ds-3989.pdf["AFF C 190"^]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===


== Unterstützung für neue Switches

[cols="20,65,15"]
|===
| Schalter | Beschreibung | Verfügbar ab 


 a| 
https://hwu.netapp.com/Switch/Index["NVIDIA IP SN2100-SWITCH"]
 a| 
Der NVIDIA IP SN2100-Storage-Switch wird in MetroCluster IP-Konfigurationen unterstützt, die die Plattformen A900/FAS9500 verwenden.
 a| 
ONTAP 9.12.1



 a| 
https://hwu.netapp.com/Switch/Index["NVIDIA IP SN2100-SWITCH (X190006)"]
 a| 
Der NVIDIA IP SN2100-Storage-Switch wird in MetroCluster IP-Konfigurationen unterstützt, die die folgenden Plattformen verwenden:

* FAS500f/AFF A250
* FAS8300/AFF A400
* FAS8700
* FAS9000/AFF A700
* AFF A800

 a| 
ONTAP 9.10.1P3



 a| 
https://hwu.netapp.com/Switch/Index["100 GbE Cisco Switch mit 36 Ports (X190200)"]
 a| 
Unterstützung einer Shared IT-Infrastruktur (Cluster, HA und Switch-Attached Storage) auf demselben Paar Cisco Nexus 9336C-FX2 Switches, einschließlich Unterstützung für MetroCluster IP-Konfigurationen.
 a| 
ONTAP 9.9.1



 a| 
https://hwu.netapp.com/Switch/Index["100-GbE-Cisco-Switch mit 36 Ports (X190200 und X190210)"]
 a| 
Cisco Nexus 9336C-FX2 Cluster-Interconnect-Switch und Storage-Switch-Unterstützung für All Flash FAS/FAS Controller sowie für Front-End-Konnektivität für Daten
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BES-53248 Switch (X190005 und X190005R)"]
 a| 
Unterstützung von Broadcom BES-53248 Cluster-Interconnect-Switches für All Flash FAS/FAS Controller mit 40/100-GbE-Ports
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["100 GbE Cisco Switch mit 36 Ports (X190200)"] https://hwu.netapp.com/Switch/Index["100 GbE Cisco Switch mit 32 Ports (X190100 und X190100R)"]
 a| 
Cisco Nexus 100 GbE Switch kann als dedizierter Storage-Switch verwendet werden, um NS224 NVMe Laufwerk-Shelfs mit folgenden Plattformen zu verbinden:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BES-53248 Switch (X190005 und X190005R)"]
 a| 
Unterstützung von Broadcom BES-53248 Cluster-Interconnect-Switches für All Flash FAS/FAS Controller mit 10/25-GbE-Ports
 a| 
ONTAP 9.5P8

|===


== Unterstützung für neue Adapter

[cols="4*"]
|===
| Teilenummer des Adapters | Beschreibung | Kategorie | Verfügbar ab 


 a| 
https://hwu.netapp.com/adapter/index["X91148A"]
 a| 
2-Port 100 GbE RoCE QSFP28
 a| 
* Storage
* Netzwerkbetrieb
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
2-Port 25 GbE RoCE QSFP28
 a| 
* Netzwerkbetrieb
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
NVMe-SSD-Modul (1 TB)
 a| 
Core Dump-Gerät
 a| 
ONTAP 9.8

|===


== Neue Shelf-Unterstützung

[cols="2*"]
|===
| Shelfs | Verfügbar ab 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== Neue Hardware-Updates

[cols="25h,~,~"]
|===
| Funktionalität | Beschreibung und wo man mehr erfahren kann | Verfügbar ab 


 a| 
Multi-Cluster Interconnect-Switch
 a| 
Multi-Cluster-Konfigurationen ermöglichen es mehreren Clustern, denselben Cluster-Switch zu nutzen, bereitgestellt durch zwei neue Referenzkonfigurationsdateien für 4x4- und 2x8-Node-Konfigurationen.
 a| 
ONTAP 9.14.1



 a| 
Erweiterte Plattformunterstützung für NS224 Festplatten-Shelfs
 a| 
Die folgenden Plattformen unterstützen NS224 Laufwerk-Shelfs:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9.8



 a| 
Hot-zusätzliche 12-GB-SAS-Shelfs zu 6-GB-SAS-Storage-Stacks
 a| 
Ein einziger Wechsel von 6 GB zu 12 GB in einem SAS-Storage-Stack wird jetzt unterstützt. Somit können bestehende 6-GB-Stacks mit 12-GB-Shelfs erweitert werden.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Hot-Adding-Shelfs mit IOM12-Modulen werden in einem Shelf-Stack mit IOM6-Modulen ausgeführt"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===