---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Erfahren Sie mehr über die neuen Plattformen für ONTAP Hardware-Systeme. 
---
= Neuerungen bei ONTAP Hardwaresystemen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei ONTAP Hardwaresystemen.



== Mai 2025



=== ASA C30

Das neue ASA C30-System erweitert leistungsstarke, intelligente und umfassende Datenverwaltungsfunktionen auf mehr Kunden und Workloads.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].



== April 2025



=== FAS50

Das FAS50-System bietet die niedrigsten Kosten pro Gigabyte für sekundären Speicher link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html["Sichere Cyber-Vault"]sowie eine höhere Performance für sekundäre Workloads durch schnellere Backups, höhere IOPS und eine niedrige Latenz von 5 bis 10 ms.

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Erfahren Sie mehr über FAS Systeme"].



== Februar 2025



=== ASA A20, ASA A30 und ASA A50

Die Entry-Level Systeme ASA A20 und Midrange ASA A30 und A50 machen Block Storage für Unternehmen jeder Größe für geschäftskritische Applikationen wie Datenbanken und Virtual Machines verfügbar.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].



== Dezember 2024



=== AFF A20, AFF A30 und AFF A50

Die neuen Hardwaresysteme AFF A20, A30 und A50 bieten noch mehr Kunden und Workloads umfassende Funktionen für hochperformantes, intelligentes und umfassendes Datenmanagement.

Die Systeme bieten ML-basierte Ransomware-Erkennung in Echtzeit, nahtlose Cloud-Integration und beispiellose Performance für geschäftskritische Workloads wie KI, VMware, Datenbanken und Analysen und unterstützen Block-, File- und Objekt-Storage.

link:https://www.netapp.com/data-storage/aff-a-series/["Weitere Informationen zu den Systemen der AFF A-Serie"].



=== AFF C30, AFF C60 und AFF C80

Mit den neuen Hardwaresystemen AFF C30, AFF C60 und AFF C80 ist die Performance und Effizienz von Flash für Unternehmen einfacher zugänglich, da sie in Implementierungen mit zwei Racks eine Storage-Kapazität von 1,5 PB bieten.

Die Lösung bietet eine außergewöhnliche Dichte mit 60-TB-Laufwerken, höhere Performance und verbesserte I/O-Flexibilität.

link:https://www.netapp.com/data-storage/aff-c-series/["Erfahren Sie mehr über die Systeme der AFF C-Serie"].



=== NS224 Festplatten-Shelf mit NSM100B Shelf-Modulen

Erweitern Sie Ihre Datacenter-Funktionen mit der NS224 und dem neuen NVMe-Storage-Erweiterungsmodul NSM100B. Das neue Shelf-Modul NSM100B wurde als direkter Ersatz für das NSM100-Modul entwickelt und lässt sich nahtlos in Ihr bestehendes Setup integrieren. Es unterstützt sowohl Direct-Attached- als auch Switch-Attached-Konfigurationen von NS224-Shelfs und bietet eine außergewöhnliche Flexibilität zur Optimierung der Effizienz und Skalierbarkeit Ihres Storage-Systems.



== September 2024



=== ASA r2-Systeme

Die neuen ASA r2 Hardwaresysteme (ASA A1K, ASA A70 und ASA A90) bieten eine einheitliche Hardware- und Softwarelösung, mit der speziell auf die Anforderungen reiner SAN-Kunden eine vereinfachte Benutzererfahrung erzielt wird.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].



=== FAS70 und FAS90

Die neuen Hardwaresysteme FAS70 und FAS90 bieten kostengünstigen und gleichzeitig hochperformanten Backup-Storage und ermöglichen damit eine sichere Cyber-Vault zur Recovery nach Ransomware-Angriffen.

link:https://www.netapp.com/data-storage/fas/["Erfahren Sie mehr über FAS Systeme"].
