---
permalink: asa400/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, boot, media, store, primary, secondary, set, system, boot, image, file, replace, replace the boot media 
summary: 'Das Boot-Medium speichert einen primären und sekundären Satz von System \(Boot Image\)-Dateien, die das System beim Booten verwendet.' 
---
= Überblick über den Austausch von Boot-Medien - ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Boot-Medium speichert einen primären und sekundären Satz von Systemdateien (Boot-Image), die das System beim Booten verwendet. Je nach Netzwerkkonfiguration können Sie entweder einen unterbrechungsfreien oder störenden Austausch durchführen.

Sie müssen über ein USB-Flash-Laufwerk verfügen, das auf FAT32 formatiert ist, und über die entsprechende Speichermenge, um die zu speichern `image_xxx.tgz` Datei:

Außerdem müssen Sie die kopieren `image_xxx.tgz` Datei auf dem USB-Flash-Laufwerk zur späteren Verwendung in diesem Verfahren.

* Bei den unterbrechungsfreien und unterbrechungsfreien Methoden zum Austausch von Boot-Medien müssen Sie den wiederherstellen `var` Filesystem:
+
** Beim unterbrechungsfreien Austausch muss das HA-Paar mit einem Netzwerk verbunden sein, um den wiederherzustellen `var` File-System.
** Für den störenden Austausch benötigen Sie keine Netzwerkverbindung, um den wiederherzustellen `var` Dateisystem, aber der Prozess erfordert zwei Neustarts.


* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Node anwenden:
+
** Der Node _Impared_ ist der Knoten, auf dem Sie Wartungsarbeiten durchführen.
** Der _Healthy Node_ ist der HA-Partner des beeinträchtigten Knotens.



