---
permalink: asa400/install-setup.html 
sidebar: sidebar 
keywords: asa a400, install, setup, initial configuration 
summary: Installieren und richten Sie Ihr System ein. 
---
= Wählen Sie, wie Ihr ASA A400-Speichersystem installiert werden soll.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wählen Sie Ihr bevorzugtes Format für die Installation Ihres ASA A400 Storage Systems: detaillierte Schritt-für-Schritt-Anleitung, grafische Kurzanleitung oder Videoanleitung.

* link:../asa400/install-quick-guide.html["Schnelle Schritte"]
+
Eine druckbare PDF-Datei mit Schritt-für-Schritt-Anweisungen mit Live-Links zu zusätzlichen Inhalten.

* link:../asa400/install-videos.html["Videoschritte"]
+
Video Schritt-für-Schritt-Anleitungen.

* link:../asa400/install-detailed-guide.html["Detaillierte Schritte"]
+
Schritt-für-Schritt-Anleitungen mit Live-Links zu weiteren Inhalten



Informationen zu MetroCluster-Konfigurationen finden Sie unter:

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP-Konfiguration installieren"]
* https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["MetroCluster Fabric-Attached-Konfiguration installieren"]

