---
permalink: asa400/overview.html 
sidebar: sidebar 
keywords: ASA A400 specifications, ASA A400 specs, NetApp ASA A400, ASA A400 hardware 
summary: Wichtige Spezifikationen für das ASA A400 -Speichersystem 
---
= Wichtige Spezifikationen für ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für den ASA A400.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der ASA A400 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für ASA A400

Plattformkonfiguration: ASA A400 Single Chassis HA-Paar, Ethernet-Bundle

Max. Rohkapazität: 14,6880 PB

Arbeitsspeicher: 256.0000 GB

Formfaktor: 4U-Gehäuse mit 2 HA-Controllern

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 10

Mindestens erforderliche ONTAP -Version: ONTAP 9.13.1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS |  |  |  


| SAN | 6 | 88,1 PB / 78,3 PiB | 1536 GB 


| HA-Paar |  | 14,7 PB / 13,0 PiB | 256,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 4 


| Ethernet 25 Gbit/s | 12 


| SAS 12 Gbit/s | 8 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 20 


| Ethernet 25 Gbit/s | 24 


| Ethernet 10 Gbit/s | 32 


| FC 32 Gbit/s | 24 


| NVMe/FC 32 Gbit/s | 24 


|  | 0 


| SAS 12 Gbit/s | 32 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 4 
|===


=== Unterstützte Speichernetzwerke

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 4209 BTU/h
* Leistung im schlimmsten Fall: 5212 BTU/h
* Gewicht: 110.0 lb 49.9 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 32,6 Zoll (34,7 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bis zu einer Höhe von 3048 m (10000 ft); 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Lagertemperatur/Luftfeuchtigkeit: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12192 m (40000 ft), 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustische Geräusche: Angegebene Schallleistung (LwAd): 8,5; Schalldruck (LpAm) (Positionen von Umstehenden): 67,2 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle; redundante Hot-Swap-fähige Controller; redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Verwaltung über SAS-Verbindungen;
