---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: Stellen Sie vor dem Austausch der Startmedien in Ihrem AFF C80-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört, dass Sie ein USB-Flash-Laufwerk mit der entsprechenden Speichermenge haben und überprüfen, ob Sie das richtige Ersatz-Boot-Gerät haben. 
---
= Anforderungen für die manuelle Wiederherstellung von Bootmedien in Ihrem AFF C80 Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch der Startmedien in Ihrem AFF C80-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört, dass Sie ein USB-Flash-Laufwerk mit der entsprechenden Speichermenge haben und überprüfen, ob Sie das richtige Ersatz-Boot-Gerät haben.

Wenn Ihr System unter ONTAP 9.17.1 oder höher läuft, verwenden Sie die link:bootmedia-replace-workflow-bmr.html["automatische Boot-Wiederherstellung"] .

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
.USB-Speicherstick
* Stellen Sie sicher, dass Sie einen USB-Stick haben, der auf FAT32 formatiert ist.
* Der USB-Stick muss über ausreichend Speicherkapazität verfügen, um die  `image_xxx.tgz` Datei.


.Dateivorbereitung
Kopieren Sie die  `image_xxx.tgz` Datei auf den USB-Stick. Diese Datei wird verwendet, wenn Sie das ONTAP Image mit dem USB-Stick übertragen.

Kopieren Sie aus dem extrahierten ONTAP-Image den  `EFI` Ordner in das Stammverzeichnis des USB-Flash-Laufwerks.

.Komponentenaustausch
Ersetzen Sie die ausgefallene Komponente durch die von NetApp bereitgestellte Ersatzkomponente.

.Controller-Identifikation
Es ist wichtig, die Befehle auf den richtigen Controller anzuwenden, wenn Sie das beschädigte Startmedium ersetzen:

* Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
* Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Boot-Mediums überprüft haben, müssen Sie link:bootmedia-encryption-preshutdown-checks.html["Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel auf dem Startmedium"].
