---
permalink: c80/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: c80, verify and set HA state, complete the replacement process 
summary: Starten Sie die Controller neu, überprüfen Sie den Systemzustand und senden Sie das fehlerhafte Teil an NetApp zurück, um den letzten Schritt beim AFF C80-Gehäuse-Austausch abzuschließen. 
---
= Vollständiger Chassisaustausch – AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Starten Sie die Controller neu, überprüfen Sie den Systemzustand und senden Sie das fehlerhafte Teil an NetApp zurück, um den letzten Schritt beim AFF C80-Gehäuse-Austausch abzuschließen.



== Schritt 1: Controller starten und Giveback durchführen

Starten Sie ONTAP auf den Controllern und führen Sie eine Controller-Rückgabe durch, um die Speicherhoheit zurückzuerlangen.

.Schritte
. Überprüfen Sie die Konsolenausgabe:
+
.. Wenn der Controller bis zur Loader-Eingabeaufforderung gebootet wird, booten Sie den Controller mit dem Befehl neu `boot_ontap`.
.. Wenn die Konsole nach dem Neubooten angezeigt wird `waiting for giveback`, loggen Sie sich beim Partner-Controller ein und überprüfen Sie, ob der ausgetauschte Controller mit dem Befehl bereit ist, die Rückgabe durchzuführen `storage failover show`.


. Giveback durchführen:
+
.. Schließen Sie das Konsolenkabel an den Partner Controller an.
.. Geben Sie mit dem Befehl den Controller zurück `storage failover giveback -fromnode local`.






== Schritt 2: Überprüfen Sie den Zustand des Storage-Systems

Nachdem die Controller-Rückgabe abgeschlossen ist, überprüfen Sie den Systemzustand mit https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] Die  Beheben Sie alle festgestellten Probleme.



== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
