---
permalink: c80/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: c80, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: Überprüfen Sie, ob die logischen Schnittstellen an ihren Home Port berichten, führen Sie eine Cluster-Integritätsprüfung durch und senden Sie das fehlerhafte Teil an NetApp zurück, um den letzten Schritt im AFF C80-Controller-Austausch-Workflow abzuschließen. 
---
= Kompletter Controller-Austausch - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie, ob die logischen Schnittstellen an ihren Home Port berichten, führen Sie eine Cluster-Integritätsprüfung durch und senden Sie das fehlerhafte Teil an NetApp zurück, um den letzten Schritt im AFF C80-Controller-Austausch-Workflow abzuschließen.



== Schritt 1: Verifizieren von LIFs und Überprüfen des Clusterzustands

Bevor Sie den Ersatz-Node an einen Service zurücksenden, überprüfen Sie, ob sich die logischen Schnittstellen auf ihren Home Ports befinden, überprüfen Sie den Cluster-Zustand und setzen Sie das automatische Giveback zurück.

.Schritte
. Vergewissern Sie sich, dass die logischen Schnittstellen ihrem Home-Server und ihren Ports Berichterstellung: `network interface show -is-home false`
+
Wenn logische Schnittstellen als falsch aufgeführt sind, setzen Sie sie auf ihre Home-Ports zurück: `network interface revert -vserver * -lif *`

. Überprüfen Sie den Zustand Ihres Clusters. Weitere Informationen finden Sie im https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["So führen Sie eine Cluster-Integritätsprüfung mit einem Skript in ONTAP durch"^] KB-Artikel.
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`




== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
