---
permalink: c80/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a1k, prerequisite, replace the controller module 
summary: Stellen Sie vor dem Austausch des Gehäuses in Ihrem AFF C80-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört das richtige Ersatzgehäuse, ein Backup Ihrer Systemkonfiguration sowie der Zugriff auf alle erforderlichen Tools und Firmware. 
---
= Anforderungen an den Controller-Austausch – AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Gehäuses in Ihrem AFF C80-System sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört das richtige Ersatzgehäuse, ein Backup Ihrer Systemkonfiguration sowie der Zugriff auf alle erforderlichen Tools und Firmware.

Überprüfen Sie die Anforderungen für den Austausch des Controller-Moduls.

* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Verwenden Sie dieses Verfahren nicht für Controller-Upgrades. Eine Anleitung finden Sie im https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Wählen Sie das Upgrade Ihrer Controller-Hardware aus"].
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie prüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"], ob Sie dieses Verfahren verwenden sollten.
* Sie müssen die ausgefallene Komponente durch die Field-Replaceable Unit (FRU) ersetzen, die Sie von NetApp erhalten haben.
* Ein Controller-Modul muss durch ein Controller-Modul desselben Modelltyps ersetzt werden. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* Da sich das Startgerät auf dem Systemverwaltungsmodul befindet, das auf der Rückseite des Systems installiert ist, müssen Sie das Startgerät beim Austausch eines Controller-Moduls nicht verschieben.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.


* Sie müssen immer die Konsolenausgabe des Controllers in einer Textprotokolldatei erfassen.
+
Auf diese Weise erhalten Sie eine Aufzeichnung des Verfahrens, damit Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.


