---
permalink: c80/io-module-overview.html 
sidebar: sidebar 
keywords: AFF C80, replace io module 
summary: Sie können ein defektes E/A-Modul in Ihrem AFF C80-Speichersystem durch ein E/A-Modul desselben Typs oder durch ein Modul eines anderen Typs ersetzen. Sie können auch ein E/A-Modul in ein System mit freien Steckplätzen einfügen. 
---
= Überblick über Hinzufügen und Ersetzen eines E/A-Moduls – AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das AFF C80-System bietet Flexibilität beim erweitern oder Ersetzen von E/A-Modulen, um die Netzwerkkonnektivität und -Leistung zu verbessern. Das Hinzufügen oder Austauschen eines E/A-Moduls ist wichtig, wenn die Netzwerkfunktionen aktualisiert oder ein fehlerhaftes Modul behandelt werden soll.

Sie können ein ausgefallenes I/O-Modul in Ihrem AFF C80-Speichersystem durch dasselbe I/O-Modul oder durch ein anderes I/O-Modul ersetzen. Sie können auch ein I/O-Modul zu einem System mit leeren Steckplätzen hinzufügen.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das System auch bei einem Ausfall eines Moduls betriebsbereit bleibt.

* link:io-module-hotswap.html["Hot-Swap eines E/A-Moduls"]
+
Das Hot-Swap eines E/A-Moduls ermöglicht es Ihnen, ein ausgefallenes Modul zu ersetzen, ohne das System herunterzufahren, wodurch Ausfallzeiten minimiert und die Systemverfügbarkeit aufrechterhalten werden.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften E/A-Moduls kann das System in den optimalen Betriebszustand zurückversetzt werden.



.Nummerierung des E/A-Steckplatzes
Die I/O-Steckplätze der AFF C80-Controller sind wie in der folgenden Abbildung dargestellt mit 1 bis 11 nummeriert.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Steckplatznummerierung auf einem AFF C80-Controller]
