---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: Wichtige Spezifikationen des AFF C80-Speichersystems 
---
= Wichtige Spezifikationen für AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind ausgewählte Spezifikationen für den AFF C80 aufgeführt.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der AFF C80-Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für AFF C80

Plattformkonfiguration: AFF C80 Single Chassis HA-Paar

Max. Rohkapazität: 14,7360 PB

Arbeitsspeicher: 512.0000 GB

Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 18

Mindestversion von ONTAP : ONTAP 9.16.1RC1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS | 12 | 176,8 PB / 157,0 PiB | 6144 GB 


| SAN | 6 | 88,4 PB / 78,5 PiB | 3072 GB 


| HA-Paar |  | 14,7 PB / 13,1 PiB | 512,0000 
|===


=== IO



==== Integrierte E/A

Keine Onboard-E/A-Daten.



==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 200 Gbit/s | 24 


| Ethernet 100 Gbit/s | 36 


| Ethernet 25 Gbit/s | 56 


| Ethernet 10 Gbit/s | 56 


| FC 64 Gbit/s | 56 


| NVMe/FC 64 Gbit/s | 56 


|  | 0 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbit/s | 2 
|===


=== Unterstützte Speichernetzwerke

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 mit NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spezifikationen der Systemumgebung

Keine Umgebungsdaten verfügbar.



=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Management-Schnittstelle; Redundante Hot-Swap-fähige Controller; Redundante Hot-Swap-fähige Netzteile; [//] 2025-10-15 ontap-systems-internal/issues/1357
