---
permalink: fas2700/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas2700, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Vor dem Austausch des Gehäuses in Ihrem FAS2700 System sollten die Anforderungen für einen erfolgreichen Austausch geprüft werden. Das Verfahren zum Austausch des Gehäuses umfasst das Umsetzen aller Netzteile, Laufwerke und Controller-Module vom defekten Gehäuse in das Ersatzgehäuse und ist mit einer Unterbrechung verbunden. 
---
= Anforderungen vor dem Austausch des FAS2700 Chassis prüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Gehäuses in Ihrem FAS2700 System sollten die Anforderungen für einen erfolgreichen Austausch geprüft werden. Das Verfahren zum Austausch des Gehäuses umfasst das Umsetzen aller Netzteile, Laufwerke und Controller-Module vom defekten Gehäuse in das Ersatzgehäuse und ist mit einer Unterbrechung verbunden.

Um das Gehäuse zu ersetzen, müssen Sie die Netzteile, Festplatten und Controller-Module oder Module vom beeinträchtigten Gehäuse in das neue Gehäuse verlegen und das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse auswechseln.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie alle Laufwerke und Controller-Module bzw. -Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Controllern kommt es zu einem vollständigen Service-Ausfall und zu einem teilweisen Ausfall in einem Cluster mit mehreren Nodes.

