---
sidebar: sidebar 
permalink: fru-reference/io-module-fru-links.html 
keywords: I/O module, field replaceable units, FRU, I/O module replacement 
summary: Hier finden Sie Verfahren zum Austausch von E/A-Modulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austauschen von E/A-Modulen für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können. 
---
= Verfahren zum Austausch von E/A-Modulen nach Plattformfamilie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Verfahren zum Austausch von E/A-Modulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austauschen von E/A-Modulen für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können.

[role="tabbed-block"]
====
.AFF Systeme
--
* link:../a1k/io-module-replace.html["AFF A1K"]
* link:../a20-30-50/io-module-replace.html["AFF A20/30/50"]
* link:../a70-90/io-module-replace.html["AFF A70/90"]
* link:../c30-60/io-module-replace.html["AFF C30/60"]
* link:../c80/io-module-replace.html["AFF C80"]


--
.ASA Systeme
--
* link:../asa-r2-a1k/io-module-replace.html["ASA A1K"]
* link:../asa-r2-a20-30-50/io-module-replace.html["ASA A20/30/50"]
* link:../asa-r2-70-90/io-module-replace.html["ASA 70/90"]
* link:../asa-r2-c30/io-module-replace.html["ASA C30"]


--
.FAS Systeme
--
* link:../fas50/io-module-replace.html["FAS50"]
* link:../fas-70-90/io-module-replace.html["FAS70/90"]


--
====