---
sidebar: sidebar 
permalink: fru-reference/nvdimm-fru-links.html 
keywords: NVDIMM, field replaceable units, FRU, NVDIMM replacement 
summary: Suchen Sie nach NVDIMM-Austauschverfahren für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Diese Referenz bietet direkte Links zu schrittweisen NVDIMM-Austausch-Workflows für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können. 
---
= NVDIMM-Austauschverfahren nach Plattformfamilie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suchen Sie nach NVDIMM-Austauschverfahren für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Diese Referenz bietet direkte Links zu schrittweisen NVDIMM-Austausch-Workflows für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können.

[role="tabbed-block"]
====
.AFF Systeme
--
* link:../a320/nvdimm-replace.html["AFF A320"]
* link:../a400/nvdimm-replace.html["AFF A400"]
* link:../a800/nvdimm-replace.html["AFF A800"]
* link:../c400/nvdimm-replace.html["AFF C400"]
* link:../c800/nvdimm-replace.html["AFF C800"]


--
.AFX-Systeme
--
* link:../afx-1k/nvdimm-battery-replace.html["AFX A1K"]


--
.ASA Systeme
--
* link:../asa400/nvdimm-replace.html["ASA A400"]
* link:../asa800/nvdimm-replace.html["ASA A800"]
* link:../asa-c400/nvdimm-replace.html["ASA C400"]
* link:../asa-c800/nvdimm-replace.html["ASA C800"]


--
.FAS Systeme
--
* link:../fas8300/nvdimm-replace.html["FAS8300"]


--
====