---
sidebar: sidebar 
permalink: fru-reference/nvram-module-fru-links.html 
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement 
summary: Suchen Sie nach Verfahren zum Austausch von NVRAM -Modulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austauschen von NVRAM -Modulen für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können. 
---
= Verfahren zum Austausch von NVRAM -Modulen nach Plattformfamilie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suchen Sie nach Verfahren zum Austausch von NVRAM -Modulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austauschen von NVRAM -Modulen für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können.

[role="tabbed-block"]
====
.AFF Systeme
--
* link:../a1k/nvram-replace.html["AFF A1K"]
* link:../a70-90/nvram-replace.html["AFF A70/90"]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html["AFF A700"]
* link:../a700s/nvram-or-nvram-dimm-replacement.html["AFF A700s"]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html["AFF A900"]
* link:../c80/nvram-replace.html["AFF C80"]


--
.AFX-Systeme
--
* link:../afx-1k/nvram-replace.html["AFX A1K"]


--
.ASA Systeme
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html["ASA A900"]
* link:../asa-r2-a1k/nvram-replace.html["ASA A1K"]
* link:../asa-r2-70-90/nvram-replace.html["ASA 70/90"]


--
.FAS Systeme
--
* link:../fas-70-90/nvram-replace.html["FAS70/90"]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html["FAS9000"]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html["FAS9500"]


--
====