---
sidebar: sidebar 
permalink: fru-reference/pci-cards-fru-links.html 
keywords: PCI cards, risers, field replaceable units, FRU, PCI replacement 
summary: Hier finden Sie Verfahren zum Austausch von PCI-Karten und Risern für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austausch von PCI-Karten und Risern für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können. 
---
= Verfahren zum Austausch von PCI-Karten und Risern nach Plattformfamilie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Verfahren zum Austausch von PCI-Karten und Risern für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austausch von PCI-Karten und Risern für AFF, ASA und FAS Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können.

[role="tabbed-block"]
====
.AFF Systeme
--
* link:../a300/pci-cards-and-risers-replace.html["AFF A300"]
* link:../a320/pci-cards-and-risers-replace.html["AFF A320"]
* link:../a400/pci-cards-and-risers-replace.html["AFF A400"]
* link:../a700/pci-cards-and-risers-replace.html["AFF A700"]
* link:../a700s/pci-cards-and-risers-replace.html["AFF A700s"]
* link:../a800/pci-cards-and-risers-replace.html["AFF A800"]
* link:../c400/pci-cards-and-risers-replace.html["AFF C400"]
* link:../c800/pci-cards-and-risers-replace.html["AFF C800"]


--
.ASA Systeme
--
* link:../asa400/pci-cards-and-risers-replace.html["ASA A400"]
* link:../asa800/pci-cards-and-risers-replace.html["ASA A800"]
* link:../asa-c400/pci-cards-and-risers-replace.html["ASA C400"]
* link:../asa-c800/pci-cards-and-risers-replace.html["ASA C800"]


--
.FAS Systeme
--
* link:../fas2800/pci-cards-and-risers-replace.html["FAS2800"]
* link:../fas8200/pci-cards-and-risers-replace.html["FAS8200"]
* link:../fas8300/pci-cards-and-risers-replace.html["FAS8300"]
* link:../fas9000/pci-cards-and-risers-replace.html["FAS9000"]


--
====