---
sidebar: sidebar 
permalink: fru-reference/system-management-fru-links.html 
keywords: system management module, field replaceable units, FRU, system management replacement 
summary: Hier finden Sie Verfahren zum Austausch von Systemverwaltungsmodulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austausch von Systemverwaltungsmodulen für AFF, ASA und FAS -Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können. 
---
= Verfahren zum Austausch des Systemverwaltungsmoduls nach Plattformfamilie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Verfahren zum Austausch von Systemverwaltungsmodulen für Ihr NetApp -Speichersystem, sortiert nach Plattformfamilie.  Dieses Nachschlagewerk bietet direkte Links zu schrittweisen Arbeitsabläufen zum Austausch von Systemverwaltungsmodulen für AFF, ASA und FAS -Systeme, damit Sie schnell das richtige Verfahren für Ihr spezifisches Modell finden können.

[role="tabbed-block"]
====
.AFF Systeme
--
* link:../a1k/system-management-replace.html["AFF A1K"]
* link:../a70-90/system-management-replace.html["AFF A70/90"]
* link:../c80/system-management-replace.html["AFF C80"]


--
.AFX-Systeme
--
* link:../afx-1k/system-management-replace.html["AFX A1K"]


--
.ASA Systeme
--
* link:../asa-r2-a1k/system-management-replace.html["ASA A1K"]
* link:../asa-r2-70-90/system-management-replace.html["ASA 70/90"]


--
.FAS Systeme
--
* link:../fas-70-90/system-management-replace.html["FAS70/90"]


--
====