---
permalink: platform-supplemental/42u-1280mm-remove-door.html 
sidebar: sidebar 
keywords: remove, system, cabinet, door, side, panel, illuminate, badge, component, reverse, door, remove the system cabinet door 
summary: Sie müssen die Tür und die Seitenwände des Systemschranks entfernen, um das beleuchtete Abzeichen und die Komponenten zu bewegen und die Tür umzukehren. 
---
= Entfernen Sie die Tür des Systemschranks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Tür und die Seitenwände des Systemschranks entfernen, um das beleuchtete Abzeichen und die Komponenten zu bewegen und die Tür umzukehren.

. Öffnen Sie die Tür des Systemschranks, wenn sie nicht bereits geöffnet ist.
. Führen Sie die entsprechenden Maßnahmen durch, je nachdem, ob Ihre Schränke mit dem Interconnect-Kit verbunden sind.
+
[cols="1,2"]
|===
| Wenn Ihr Systemschrank... | Dann... 


 a| 
Nicht mit einem anderen Systemschrank verbunden
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Anschluss an einen anderen Systemschrank mit einem Interconnect-Kit
 a| 
Entfernen Sie alle vier Halterungen des Verbindungssatzes, und setzen Sie die Halterungen und Schrauben an einer sicheren Stelle ein.

|===
. Entriegeln Sie beide Seitenwände, trennen Sie die Erdungskabel von den Seitenverkleidungen, entfernen Sie sie, und legen Sie sie beiseite.
. Trennen Sie das Erdungskabel von der Schussade oben an der Tür.
. Lösen Sie die Erdungsöse und die Drahtbaugruppe aus dem Rahmen des Systemschranks und legen Sie sie beiseite.
. Lösen Sie die Erdungsöse von der Systemschranktür und legen Sie sie beiseite.
. Heben Sie den oberen Scharnierstift an, bis er die Unterseite des Scharniers entfernt.
. Schieben Sie die Oberseite der Tür vorsichtig vom Rahmen des Systemschranks weg, und lösen Sie dann den Scharnierstift.
. Heben Sie die Tür vom unteren Scharnier ab, und stellen Sie die Tür beiseite.

