---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: Sie müssen die Systemkomponenten an die PDUs anschließen, die PDU-Kabel an die Wechselstromquellen leiten, sie an die Stromquellen anschließen und das System einschalten. 
---
= Schalten Sie den Systemschrank ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Systemkomponenten an die PDUs anschließen, die PDU-Kabel an die Wechselstromquellen leiten, sie an die Stromquellen anschließen und das System einschalten.


IMPORTANT: Um einen Systemausfall bei Ausfall einer PDU zu verhindern, schließen Sie nicht beide Netzkabel einer beliebigen Komponente an eine PDU an. Verteilen Sie die Last über die PDS, die an verschiedene Stromkreise angeschlossen sind, wie in der Abbildung dargestellt.

Für jede PDU in Ihrem Systemschrank müssen separate Stromkreise verfügbar sein.

. Verbinden Sie Ihre Geräte mit den PDUs:
+
.. Schließen Sie die Controller-Netzteile an verschiedene PDUs an, die an verschiedene Stromquellen angeschlossen sind.
.. Schließen Sie die Festplatten-Shelf-Netzteile an verschiedene PDUs an, die an verschiedene Stromquellen angeschlossen sind.
.. Schließen Sie alle Switch-Netzteile an verschiedene PDUs an, die an verschiedene Stromquellen angeschlossen sind.
+
image::../media/cabinet_power_cabling_IEOPS-1320.svg[Schaltschrankstromverkabelung IEOPS 1320]

+
Führen Sie die PDU-Stromkabel durch eine der folgenden Öffnungen im Systemschrank:

+
*** Die Oberseite des Systemschranks
*** Zwischen der hinteren Tür unten und dem Rahmen des Systemschranks
*** Durch die Bodenöffnung und unter dem Systemschrank




. Schalten Sie die Netzschalter oder Leistungsschalter an den PDUs aus.
. Schließen Sie jedes PDU-Netzkabel an einzelne Wechselstromquellen an, die sich auf separaten Wechselstromkreisen befinden.
. Schalten Sie die Netzschalter oder Leistungsschalter an die PDUs ein.
. Schalten Sie die Komponenten ein, und starten Sie das System.
. Schließen und verriegeln Sie die Türen des Systemschranks.

