---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: Sie müssen die Systemkomponenten an die PDUs anschließen, die PDU-Kabel an die Wechselstromquellen leiten, sie an die Stromquellen anschließen und das System einschalten. 
---
= Schalten Sie den Systemschrank ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Systemkomponenten an die PDUs anschließen, die PDU-Kabel an die Wechselstromquellen leiten, sie an die Stromquellen anschließen und das System einschalten.

Für jede PDU in Ihrem Systemschrank müssen separate Stromkreise verfügbar sein.

. Schließen Sie Ihr Gerät an die PDUs an. Stellen Sie sicher, dass Sie die Netzteile jeder Komponente an eine PDU auf gegenüberliegenden Seiten des Systemschranks anschließen.
. Führen Sie die PDU-Stromkabel durch eine Öffnung im Systemschrank.
+
Nutzen Sie eine der folgenden Öffnungen:

+
** Die Oberseite des Systemschranks
** Zwischen der hinteren Tür unten und dem Rahmen des Systemschranks
** Durch die Bodenöffnung und unter dem Systemschrank


. Schalten Sie die Netzschalter oder Leistungsschalter an den PDUs aus.
. Schließen Sie jedes PDU-Netzkabel an einzelne Wechselstromquellen an, die sich auf separaten Wechselstromkreisen befinden.
. Schalten Sie die Netzschalter oder Leistungsschalter an die PDUs ein.
. Schalten Sie die Komponenten ein, und starten Sie das System.
. Schließen und verriegeln Sie die Türen des Systemschranks.

