---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: Der Systemschrank besteht aus Seitenverkleidungen, Vorder- und Hintertüren, einem optionalen Abrisskit, einem optionalen Verbindungskit, PDUs für Ihre Geräte und einem integrierten Kabelmanagementsystem. 
---
= Systemschrankfunktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Systemschrank besteht aus Seitenverkleidungen, Vorder- und Hintertüren, einem optionalen Abrisskit, einem optionalen Verbindungskit, PDUs für Ihre Geräte und einem integrierten Kabelmanagementsystem.

[cols="1,2"]
|===
| Merkmal | Beschreibung 


 a| 
Seiteneinsätze
 a| 
Systemschränke sind mit abschließbaren, abnehmbaren und austauschbaren Seitenverkleidungen ausgestattet.



 a| 
Perforierte Vorder- und Hintertüren
 a| 
Systemschränke verfügen über abnehmbare Vorder- und Hintertüren mit Schnellverschluss. Die Vordertür ist reversibel und die hinteren Türen sind gespalten. Beide Türen sind zur Kühlung perforiert.



 a| 
Gemeinsamer Schlüssel
 a| 
Mit dieser Taste werden die vorderen Türen, die hinteren Türen und die Seitenwände entriegelt.



 a| 
Ersatzteilesatz
 a| 
Dieses Kit befindet sich im Systemschrank, der an der Schranktür befestigt ist. Er enthält die folgenden Komponenten:

* Vier 10-32 x 0.75 Zoll Kreuzschlitzschrauben
* Vier 10-32 Käfigmuttern
* Ein Werkzeug zur Einfügung von Käfigmutter
* Zwei Master-Schlüsselkopien




 a| 
Kabelzugang
 a| 
Die Kabeldurchführungen sind oben und unten im Schrank sowie zwischen der Unterseite der hinteren Tür und dem Rahmen eingebaut.



 a| 
Kabelführung
 a| 
Kabelführungshaken und Schlaufenband werden in gleichen Abständen am Rahmen des Systemschranks befestigt.



 a| 
Stützschienen
 a| 
Die Anzahl der eingelensten Support-Schienen hängt von Ihrer Konfiguration ab. Im leeren Systemschrank sind keine Stützschienen installiert.

* Für konfigurierte Systemschränke wird ein fester Schienensatz mit den Systemschränken geliefert, die die Halterungen für die Heckklammern 80xx, FAS8200 und DS4486 unterstützen.
* Die Schaltschränke für die Schnellzustellsysteme enthalten nicht den zusätzlichen festen Schienensatz.




 a| 
Abdeckbleche
 a| 
Die Anzahl und Größe der Blindplatten, die Sie erhalten, hängt von Ihrer Konfiguration ab. Der leere Systemschrank wird ohne Blindplatten geliefert.



 a| 
Abschraubkit
 a| 
Mit diesem optionalen Kit können Sie den Systemschrank im Rechenzentrum sichern. Das Kit ist nicht für seismische Stabilität vorgesehen.

* Vier Schraubhalterungen
* Vier Distanzhalterungen
* Sechs M8x20 mm Sechskantschrauben und Unterlegscheiben




 a| 
Verbindungskit
 a| 
Mit diesem optionalen Kit können Sie mehrere Systemschränke miteinander verbinden.

* Verbindungshalterungen
+
** Ein Satz von vier Verbindungstasten für den Anschluss der Systemschränke mit Seitenverkleidungen an
** Ein Satz von vier Verbindungshalterungen zum Anschluss der Systemschränke an die Seitenabdeckungen aus


* Vier M12x20 Torx-30-Schrauben, die im Systemschrank mit Seitenverkleidungen verwendet werden.
* Acht M6x10-Senkschraubenschrauben Torx-30, die im Systemschrank mit Seitenverkleidungen verwendet werden.




 a| 
Für den Support Rail Kit
 a| 
Wenn Sie zusätzliche Stützschienen für Ihren Systemschrank bestellt haben, enthält jedes Kit eine linke und eine rechte Stützschiene.


NOTE: Die Haltegriffe und -Kit wurden so konzipiert, dass sie nur in einen NetApp 42U 1280-mm-Systemschrank passen. Verwenden Sie die Schienen oder den Schienensatz nicht von anderen Systemschränken, da diese nicht für den Einsatz im 42-HE-1280-mm-Systemschrank ausgelegt sind.

* Eine linke und rechte Stützschiene
* Zwei Schrauben pro Schiene zum Befestigen der Schiene am Systemschrankrahmen




 a| 
Halbmond-Schraubenschlüssel
 a| 
Mit dem Schraubenschlüssel werden die Haltewinkel auf der Verpackungspalette entfernt, die Standfüße des Systemschranks eingestellt und die Halterungen des Abrisssatzes, falls bestellt, montiert.

|===