---
permalink: platform-supplemental/drive-hotswap-drive.html 
sidebar: sidebar 
keywords: drive, fail, platform, log, warning, message, system, console, drive, addition, fault, led, operator, display, panel, fault, led, illuminate, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: Wenn ein Laufwerk ausfällt, meldet die Plattform eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Fehler-LED auf der Bedieneranzeige und die Fehler-LED am ausgefallenen Laufwerk. Sie können ein ausgefallenes Laufwerk unterbrechungsfrei ersetzen, während I/O gerade läuft. 
---
= Hot-Swap-fähige Laufwerke
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Laufwerk ausfällt, meldet die Plattform eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Fehler-LED auf der Bedieneranzeige und die Fehler-LED am ausgefallenen Laufwerk. Sie können ein ausgefallenes Laufwerk unterbrechungsfrei ersetzen, während I/O gerade läuft.

* Das Ersatzlaufwerk muss von Ihrer Plattform unterstützt werden.
+
https://["NetApp Hardware Universe"]

* Wenn die SED-Authentifizierung aktiviert ist, müssen Sie die SED-Ersatzanweisungen in der ONTAP-Dokumentation verwenden.
+
Anweisungen in der ONTAP-Dokumentation beschreiben zusätzliche Schritte, die vor und nach dem Austausch einer SED ausgeführt werden müssen.

+
https://["ONTAP 9 – NetApp Verschlüsselungsleitfadens"]

* Alle anderen Komponenten im System müssen ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an den technischen Support.
* Überprüfen Sie, ob das Laufwerk, das Sie entfernen, fehlgeschlagen ist, indem Sie das ausführen `storage disk show -broken` Befehl. Das ausgefallene Laufwerk wird in der Liste der ausgefallenen Laufwerke angezeigt. Falls nicht, sollten Sie warten und dann den Befehl erneut ausführen.
+

NOTE: Abhängig vom Laufwerkstyp und der Kapazität kann es bis zu mehrere Stunden dauern, bis das Laufwerk in der Liste der ausgefallenen Laufwerke angezeigt wird.

* *Best Practice:* die beste Vorgehensweise ist, die aktuelle Version des Disk Qualification Package (DQP) vor dem Hot-Swap eines Laufwerks installiert zu haben.
* Die Festplatten-Firmware wird bei neuen Laufwerken, die nicht über aktuelle Firmware-Versionen verfügen, automatisch (unterbrechungsfrei) aktualisiert.
* Wenn Sie das Ersatzlaufwerk auspacken, speichern Sie alle Verpackungsmaterialien für die Verwendung, wenn Sie das ausgefallene Laufwerk zurücksenden.
+
.. Wenn Sie dem Ersatzlaufwerk den Besitz eines Laufwerks manuell zuweisen möchten, müssen Sie das Ersatzlaufwerk für die automatische Laufwerkszuweisung deaktivieren, sofern dieses aktiviert ist
+

NOTE: Sie weisen den Antriebseigentum manuell zu und aktivieren dann die automatische Laufwerkszuweisung später in diesem Verfahren.

+
... Überprüfen Sie, ob die automatische Laufwerkszuweisung aktiviert ist: `storage disk option show`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Wenn die automatische Laufwerkszuweisung aktiviert ist, wird die Ausgabe angezeigt `on` In der Spalte „`Auto Assign`“ (für jedes Controller-Modul).

... Wenn die automatische Laufwerkszuweisung aktiviert ist, deaktivieren Sie sie: `storage disk option modify -node node_name -autoassign off`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen deaktivieren.



.. Richtig gemahlen.
.. Identifizieren Sie das ausgefallene Laufwerk physisch.
+
Wenn ein Laufwerk ausfällt, protokolliert das System eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Warnungs-LED (gelb) auf der Anzeige des Festplatten-Shelf-Bedieners und des ausgefallenen Laufwerks.

+

NOTE: Die Aktivitäts-LED (grün) auf einem ausgefallenen Laufwerk kann leuchten (leuchtet dauerhaft), was darauf hinweist, dass das Laufwerk zwar mit Strom versorgt wird, aber nicht blinken sollte, was auf I/O-Aktivität hinweist. Ein ausgefallenes Laufwerk hat keine I/O-Aktivität.

.. Entfernen Sie das ausgefallene Laufwerk:
+
... Drücken Sie die Entriegelungstaste an der Antriebsfläche, um den Nockengriff zu öffnen.
... Schieben Sie den Antrieb mithilfe des Nockengriffs aus dem Regal und halten Sie den Antrieb mit der anderen Hand.


.. Warten Sie mindestens 70 Sekunden, bevor Sie das Ersatzlaufwerk einsetzen.
+
Dadurch erkennt das System, dass ein Laufwerk entfernt wurde.

.. Setzen Sie das Ersatzlaufwerk ein:
+
... Wenn sich der Nockengriff in der geöffneten Position befindet, setzen Sie den Ersatzantrieb mit beiden Händen ein.
... Drücken Sie, bis das Laufwerk stoppt.
... Schließen Sie den Nockengriff, so dass der Antrieb fest in der Mittelebene sitzt und der Griff einrastet.
+
Schließen Sie den Nockengriff langsam, damit er korrekt an der Antriebsfläche ausgerichtet ist.



.. Vergewissern Sie sich, dass die Aktivitäts-LED (grün) des Laufwerks leuchtet.
+
Wenn die Aktivitäts-LED des Laufwerks leuchtet, bedeutet dies, dass das Laufwerk mit Strom versorgt wird. Wenn die Aktivitäts-LED des Laufwerks blinkt, bedeutet dies, dass das Laufwerk gerade mit Strom versorgt wird und der I/O-Vorgang ausgeführt wird. Wenn die Laufwerk-Firmware automatisch aktualisiert wird, blinkt die LED.

.. Wenn Sie ein anderes Laufwerk ersetzen, wiederholen Sie die Schritte 3 bis 7.
.. Wenn Sie die automatisierte Laufwerkszuweisung in Schritt 1 deaktiviert haben, weisen Sie die Laufwerkseigentümer manuell zu und aktivieren Sie bei Bedarf die automatische Laufwerkszuweisung erneut.
+
... Alle Laufwerke ohne Besitzer anzeigen: `storage disk show -container-type unassigned`
+
Sie können den Befehl an einem der Controller-Module eingeben.

... Weisen Sie jedes Laufwerk zu: `storage disk assign -disk disk_name -owner owner_name`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Mit dem Platzhalterzeichen können Sie mehr als ein Laufwerk gleichzeitig zuweisen.

... Bei Bedarf die automatische Laufwerkszuweisung erneut aktivieren: `storage disk option modify -node node_name -autoassign on`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen erneut aktivieren.



.. Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.
+
Wenden Sie sich an den technischen Support unter https://["NetApp Support"], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik) wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen.




