---
permalink: platform-supplemental/sldiag-system-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, initial, system, installation, identify, version, system-level, diagnostic, support, device, storage, system, successful, hardware, function, properly, run system installation diagnostic 
summary: Sie führen nach der ersten Systeminstallation eine Diagnose aus, um die Version der Diagnose auf Systemebene und die unterstützten Geräte auf Ihrem Speichersystem zu identifizieren und um zu überprüfen, ob die Installation erfolgreich ist und die gesamte Hardware ordnungsgemäß funktioniert. 
---
= Führen Sie die Systeminstallationsdiagnose aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie führen nach der ersten Systeminstallation eine Diagnose aus, um die Version der Diagnose auf Systemebene und die unterstützten Geräte auf Ihrem Speichersystem zu identifizieren und um zu überprüfen, ob die Installation erfolgreich ist und die gesamte Hardware ordnungsgemäß funktioniert.

Ihr Storage-System muss bereits Data ONTAP ausführen.

. Wechseln Sie an der Eingabeaufforderung des Storage-Systems zur LOADER-Eingabeaufforderung: `halt`
. Geben Sie an der LOADER-Eingabeaufforderung den folgenden Befehl ein: `boot_diags`
+

NOTE: Sie müssen diesen Befehl von der LOADER-Eingabeaufforderung ausführen, damit die Diagnose auf Systemebene ordnungsgemäß funktioniert. Der Befehl Boot_diags startet spezielle Treiber, die speziell für die Diagnose auf Systemebene entwickelt wurden.

. Zeigen Sie die Version der Diagnose auf Systemebene auf Ihrem Storage-System an, indem Sie den folgenden Befehl eingeben: `sldiag version show`
+
Die Version wird im Format Systemebene DiagnosticsX.nn.nn angezeigt. Das X ist eine Alpha-Referenz und nn.nn sind wichtige und kleine numerische Referenzen.

. Identifizieren Sie die Gerätetypen in Ihrer neuen Systeminstallation, damit Sie wissen, welche Komponenten Sie überprüfen müssen, indem Sie den folgenden Befehl eingeben: `sldiag device types`
+
Ihr Speichersystem zeigt einige oder alle der folgenden Geräte an:

+
** `ata` Ist ein Advanced Technology Attachment-Gerät.
** `bootmedia` Ist das Systembootgerät.
** `cna` Ist ein konvergierter Netzwerkadapter, der nicht mit einem Netzwerk oder einem Speichergerät verbunden ist.
** `env` Ist die Umgebung der Hauptplatine.
** `fcache` Ist der Flash Cache Adapter, auch bekannt als Performance Acceleration Module 2.
** `fcal` Ist ein Fibre Channel-Arbitrated Loop-Gerät, das nicht mit einem Storage-Gerät oder einem Fibre Channel-Netzwerk verbunden ist.
** `fcvi` Ist die virtuelle Fibre Channel-Schnittstelle, die nicht mit einem Fibre Channel-Netzwerk verbunden ist.
** `interconnect` Oder `nvram-ib` Ist die Hochverfügbarkeitsschnittstelle.
** Speicher ist Systemspeicher.
** `nic` Ist eine Netzwerkschnittstellenkarte, die nicht mit einem Netzwerk verbunden ist.
** `nvram` Ist nicht-flüchtiger RAM.
** `nvmem` Ist ein Hybride von NVRAM und Systemspeicher.
** `sas` Ist ein Serial Attached SCSI-Gerät, das nicht mit einem Festplatten-Shelf verbunden ist.
** `serviceproc` Ist der Service Processor.
** `storage` Ist eine ATA-, FC-AL- oder SAS-Schnittstelle mit einem angeschlossenen Platten-Shelf.
** `toe` Ist eine TCP Offload Engine, ein NIC-Typ.


. Führen Sie alle standardmäßig ausgewählten Diagnosetests auf Ihrem Speichersystem aus, indem Sie den folgenden Befehl eingeben: `sldiag device run`
. Zeigen Sie den Status des Tests an, indem Sie den folgenden Befehl eingeben: `sldiag device status`
+
Ihr Storage-System liefert während der Tests den folgenden Output:

+
[listing]
----
There are still test(s) being processed.
----
+
Nach Abschluss aller Tests wird standardmäßig die folgende Antwort angezeigt:

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. Überprüfen Sie, ob Ihr neues Storage-System keine Hardware-Probleme hat, indem Sie den folgenden Befehl eingeben: `sldiag device status -long -state failed`
+
Das folgende Beispiel zeigt, wie der volle Status der Fehler in einem Testlauf ohne die entsprechende Hardware angezeigt wird:

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| Wenn die Diagnose auf Systemebene testet... | Dann... 


 a| 
Wurden ohne Fehler abgeschlossen
 a| 
Es sind keine Hardware-Probleme aufgetreten, und Ihr Storage-System kehrt zur Eingabeaufforderung zurück.

.. Geben Sie folgenden Befehl ein, um die Status-Protokolle zu löschen: `sldiag device clearstatus`
.. Überprüfen Sie, ob das Protokoll gelöscht wird, indem Sie den folgenden Befehl eingeben: `sldiag device status`
+
Die folgende Standardantwort wird angezeigt:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Beenden Sie den Wartungsmodus, indem Sie den folgenden Befehl eingeben: `halt`
.. Geben Sie an der Loader-Eingabeaufforderung den folgenden Befehl ein, um das Storage-System zu booten: `boot_ontap`Sie haben die Diagnose auf Systemebene abgeschlossen.




 a| 
Es kam zu einigen Testfehlern
 a| 
Bestimmen Sie die Ursache des Problems.

.. Beenden Sie den Wartungsmodus, indem Sie den folgenden Befehl eingeben: `halt`
.. Führen Sie eine saubere Abschaltung durch und trennen Sie die Netzteile.
.. Überprüfen Sie, ob Sie alle Aspekte, die bei der Ausführung von Diagnose auf Systemebene zu beachten sind, dass die Kabel sicher angeschlossen sind und die Hardwarekomponenten ordnungsgemäß im Storage-System installiert wurden.
.. Schließen Sie die Netzteile wieder an, und schalten Sie das Speichersystem wieder ein.
.. Wiederholen Sie die Schritte 1 bis 7 von _Diagnose der Systeminstallation_.


|===

