---
permalink: platform-supplemental/sldiag-slow-system-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, help, identify, slow, system, response, time, run slow system response diagnostic 
summary: Eine Diagnose kann Ihnen dabei helfen, die Ursachen für langsame Systemreaktionszeiten zu identifizieren. 
---
= Führen Sie die Diagnose für langsame Systemantwort aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Diagnose kann Ihnen dabei helfen, die Ursachen für langsame Systemreaktionszeiten zu identifizieren.

. Wechseln Sie an der Eingabeaufforderung des Storage-Systems zur LOADER-Eingabeaufforderung: `halt`
. Geben Sie an der LOADER-Eingabeaufforderung den folgenden Befehl ein: `boot_diags`
+

NOTE: Sie müssen diesen Befehl von der LOADER-Eingabeaufforderung ausführen, damit die Diagnose auf Systemebene ordnungsgemäß funktioniert. Der Befehl Boot_diags startet spezielle Treiber, die speziell für die Diagnose auf Systemebene entwickelt wurden.

. Führen Sie die Diagnose auf allen Geräten durch, indem Sie den folgenden Befehl eingeben: `sldiag device run`
. Zeigen Sie den Status des Tests an, indem Sie den folgenden Befehl eingeben: `sldiag device status`
+
Ihr Storage-System liefert während der Tests den folgenden Output:

+
[listing]
----
There are still test(s) being processed.
----
+
Nach Abschluss aller Tests wird standardmäßig die folgende Antwort angezeigt:

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. Ermitteln Sie die Ursache der Systemabfälligkeit durch Eingabe des folgenden Befehls: `sldiag device status -long -state failed`
+
Das folgende Beispiel zeigt, wie der volle Status der Fehler in einem Testlauf ohne die entsprechende Hardware angezeigt wird:

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| Wenn die Diagnose auf Systemebene testet... | Dann... 


 a| 
Wurden ohne Fehler abgeschlossen
 a| 
Es sind keine Hardware-Probleme aufgetreten, und Ihr Storage-System kehrt zur Eingabeaufforderung zurück.

.. Geben Sie folgenden Befehl ein, um die Status-Protokolle zu löschen: `sldiag device clearstatus`
.. Überprüfen Sie, ob das Protokoll gelöscht wird, indem Sie den folgenden Befehl eingeben: `sldiag device status`
+
Die folgende Standardantwort wird angezeigt:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Beenden Sie den Wartungsmodus, indem Sie den folgenden Befehl eingeben: `halt`
.. Geben Sie an der Loader-Eingabeaufforderung den folgenden Befehl ein, um das Storage-System zu booten: `boot_ontap`Sie haben die Diagnose auf Systemebene abgeschlossen.




 a| 
Es kam zu einigen Testfehlern
 a| 
Bestimmen Sie die Ursache des Problems.

.. Beenden Sie den Wartungsmodus, indem Sie den folgenden Befehl eingeben: `halt`
.. Führen Sie eine saubere Abschaltung durch und trennen Sie die Netzteile.
.. Stellen Sie sicher, dass Sie alle Anforderungen für die Ausführung von Diagnose auf Systemebene eingehalten, dass die Kabel sicher angeschlossen sind und dass Hardwarekomponenten ordnungsgemäß im Storage-System installiert wurden.
.. Schließen Sie die Netzteile wieder an, und schalten Sie das Speichersystem wieder ein.
.. Wiederholen Sie die Schritte 1 bis 5 von _Diagnose für langsame Systemantwort ausführen_.




 a| 
Es ergaben sich dieselben Testfehler
 a| 
Der technische Support empfiehlt möglicherweise, bei einigen Tests die Standardeinstellungen zu ändern, um das Problem zu identifizieren.

.. Ändern Sie den Auswahlstatus eines bestimmten Geräts oder Gerätetyps auf Ihrem Speichersystem, indem Sie den folgenden Befehl eingeben: `sldiag device modify [-dev _devtype_|mb|slot_slotnum_] [-name device] [-selection _enable|disable|default|only_]`
+
-`selection _enable|disable|default|only_` Ermöglicht die Aktivierung, Deaktivierung, Annahme der Standardauswahl eines bestimmten Gerätetyps oder eines benannten Geräts oder das benannte Gerät oder die Aktivierung des angegebenen Geräts oder benanntem Gerät, indem alle anderen zuerst deaktiviert werden.

.. Überprüfen Sie, ob die Tests geändert wurden, indem Sie den folgenden Befehl eingeben: `sldiag option show`
.. Wiederholen Sie die Schritte 3 bis 5 von _Diagnose für langsame Systemantwort ausführen_.
.. Nachdem Sie das Problem erkannt und behoben haben, setzen Sie die Tests auf ihren Standardstatus zurück, indem Sie die Teilschritte 1 und 2 wiederholen.
.. Wiederholen Sie die Schritte 1 bis 5 von _Diagnose für langsame Systemantwort ausführen_.


|===


Wenn die Fehler nach der Wiederholung der Schritte weiter bestehen, müssen Sie die Hardware austauschen.
