---
permalink: a320/bootmedia-recovery-image-boot-non-2n-mcc.html 
sidebar: sidebar 
keywords: aff a320, aff, a320, procedure, boot, impair, node, recovery, image, system, two-node, metrocluster, configuration, boot the recovery image, manual, manual boot recovery 
summary: Sie müssen das ONTAP Image vom USB-Laufwerk starten, das Dateisystem wiederherstellen und die Umgebungsvariablen überprüfen. Das AFF A320 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt. 
---
= Starten Sie das Recovery-Image – AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das ONTAP Image vom USB-Laufwerk starten, das Dateisystem wiederherstellen und die Umgebungsvariablen überprüfen. Das AFF A320 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt.

. Starten Sie von der LOADER-Eingabeaufforderung das Recovery-Image vom USB-Flash-Laufwerk: `boot_recovery`
+
Das Bild wird vom USB-Flash-Laufwerk heruntergeladen.

. Wenn Sie dazu aufgefordert werden, geben Sie entweder den Namen des Bilds ein oder akzeptieren Sie das Standardbild, das in den Klammern auf dem Bildschirm angezeigt wird.
. Stellen Sie das var-Dateisystem wieder her:
+
[cols="1,2"]
|===
| Wenn Ihr System... | Dann... 


 a| 
Eine Netzwerkverbindung
 a| 
.. Drücken Sie `y` Wenn Sie aufgefordert werden, die Backup-Konfiguration wiederherzustellen.
.. Legen Sie den gesunden Node auf die erweiterte Berechtigungsebene fest: `set -privilege advanced`
.. Führen Sie den Befehl Restore Backup aus: `system node restore-backup -node local -target-address impaired_node_IP_address`
.. Gibt den Node wieder auf Administratorebene: `set -privilege admin`
.. Drücken Sie `y` Wenn Sie aufgefordert werden, die wiederhergestellte Konfiguration zu verwenden.
.. Drücken Sie `y` Wenn Sie zum Neubooten des Node aufgefordert werden.




 a| 
Keine Netzwerkverbindung
 a| 
.. Drücken Sie `n` Wenn Sie aufgefordert werden, die Backup-Konfiguration wiederherzustellen.
.. Starten Sie das System neu, wenn Sie dazu aufgefordert werden.
.. Wählen Sie im angezeigten Menü die Option *Flash aktualisieren aus Backup config* (Flash synchronisieren) aus.
+
Wenn Sie aufgefordert werden, mit der Aktualisierung fortzufahren, drücken Sie `*y*`.





 a| 
Keine Netzwerkverbindung und befindet sich in einer MetroCluster IP-Konfiguration
 a| 
.. Drücken Sie `n` Wenn Sie aufgefordert werden, die Backup-Konfiguration wiederherzustellen.
.. Starten Sie das System neu, wenn Sie dazu aufgefordert werden.
.. Warten Sie, bis die iSCSI-Speicherverbindungen verbunden sind.
+
Sie können fortfahren, nachdem Sie die folgenden Meldungen angezeigt haben:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Wählen Sie im angezeigten Menü die Option *Flash aktualisieren aus Backup config* (Flash synchronisieren) aus.
+
Wenn Sie aufgefordert werden, mit der Aktualisierung fortzufahren, drücken Sie `*y*`.



|===
. Stellen Sie sicher, dass die Umgebungsvariablen wie erwartet festgelegt sind:
+
.. Nehmen Sie den Node zur LOADER-Eingabeaufforderung.
.. Überprüfen Sie die Einstellungen der Umgebungsvariable mit dem `printenv` Befehl.
.. Wenn eine Umgebungsvariable nicht wie erwartet festgelegt ist, ändern Sie sie mit dem `setenv _environment_variable_name_ _changed_value_` Befehl.
.. Speichern Sie Ihre Änderungen mit dem `savenv` Befehl.


. Das nächste hängt von Ihrer Systemkonfiguration ab:
+
** Wenn keymanager, NSE oder NVE in Ihrem System integriert sind, finden Sie unter xref:bootmedia-encryption-restore.adoc[Schritte zum Austausch von Medien nach dem Booten für OKM, NSE und NVE]
** Wenn keymanager, NSE oder NVE auf Ihrem System nicht konfiguriert sind, führen Sie die Schritte in diesem Abschnitt aus.


. Geben Sie an der LOADER-Eingabeaufforderung das ein `boot_ontap` Befehl.
+
[cols="1,2"]
|===
| Wenn Sie sehen... | Dann... 


 a| 
Die Eingabeaufforderung für die Anmeldung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
.. Melden Sie sich beim Partner-Node an.
.. Vergewissern Sie sich, dass der Ziel-Node zur Rückgabe mit dem bereit ist `storage failover show` Befehl.


|===
. Schließen Sie das Konsolenkabel an den Partner-Node an.
. Geben Sie den Node mithilfe des zurück `storage failover giveback -fromnode local` Befehl
. Überprüfen Sie an der Cluster-Eingabeaufforderung die logischen Schnittstellen mit dem `net int -is-home false` Befehl.
+
Wenn Schnittstellen als „falsch“ aufgeführt sind, stellen Sie diese Schnittstellen mithilfe der zurück auf ihren Home Port `net int revert` Befehl.

. Bewegen Sie das Konsolenkabel auf den reparierten Node und führen Sie den aus `version -v` Befehl zum Prüfen der ONTAP-Versionen.
. Stellen Sie die automatische Rückgabe wieder her, wenn Sie die Funktion mithilfe von deaktivieren `storage failover modify -node local -auto-giveback true` Befehl.

