---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process 
summary: Verschieben Sie die Lüfter, Festplatten und Controller-Module oder Module vom beeinträchtigten Gehäuse in das neue Gehäuse und tauschen Sie das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank aus, indem Sie das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse verwenden. 
---
= Hardware austauschen – AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verschieben Sie die Lüfter, Festplatten und Controller-Module oder Module vom beeinträchtigten Gehäuse in das neue Gehäuse und tauschen Sie das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank aus, indem Sie das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse verwenden.



== Schritt 1: Entfernen Sie die Controller-Module

Um das Chassis auszutauschen, müssen Sie die Controller-Module aus dem alten Chassis entfernen.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Lösen Sie die Netzkabelhalter, und ziehen Sie anschließend die Kabel von den Netzteilen ab.
. Lösen Sie den Haken- und Schlaufenriemen, mit dem die Kabel am Kabelführungsgerät befestigt sind, und ziehen Sie dann die Systemkabel und SFPs (falls erforderlich) vom Controller-Modul ab, um zu verfolgen, wo die Kabel angeschlossen waren.
+
Lassen Sie die Kabel im Kabelverwaltungs-Gerät so, dass bei der Neuinstallation des Kabelverwaltungsgeräts die Kabel organisiert sind.

. Entfernen Sie die Kabelführungsgeräte von der linken und rechten Seite des Controller-Moduls und stellen Sie sie zur Seite.
. Entfernen Sie das Controller-Modul aus dem Chassis:
+
.. Setzen Sie den Zeigefinger in den Verriegelungsmechanismus auf beiden Seiten des Controller-Moduls ein.
.. Drücken Sie auf die orangefarbene Lasche oben am Verriegelungsmechanismus nach unten, bis der Rastbolzen am Gehäuse entfernt wird.
+
Der Haken des Verriegelungsmechanismus sollte fast senkrecht sein und sich vom Chassispindel frei sein.

.. Ziehen Sie das Controller-Modul vorsichtig einige Zentimeter zu Ihnen, damit Sie die Seiten des Controller-Moduls erfassen können.
.. Ziehen Sie das Controller-Modul vorsichtig mit beiden Händen aus dem Gehäuse und legen Sie es auf eine flache, stabile Oberfläche.


. Wiederholen Sie diese Schritte für das andere Controller-Modul im Chassis.




== Schritt 2: Bewegen Sie die Lüfter

Um die Lüftermodule beim Austausch des Gehäuses in das Ersatzgehäuse zu verschieben, müssen Sie eine bestimmte Sequenz von Aufgaben durchführen.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Entfernen Sie die Blende (falls erforderlich) mit zwei Händen, indem Sie die Öffnungen auf beiden Seiten der Blende fassen und dann zu Ihnen ziehen, bis sich die Blende von den Kugelknöpfen am Rahmen des Chassis löst.
. Drücken Sie die Freigabehebel am Nockengriff des Lüftermoduls nach unten, und drehen Sie dann den Nockengriff nach unten.
+
Das Lüftermodul bewegt sich ein wenig vom Gehäuse entfernt.

. Ziehen Sie das Lüftermodul gerade aus dem Gehäuse heraus. Stellen Sie sicher, dass Sie es mit der freien Hand unterstützen, damit es nicht aus dem Gehäuse herausschwingt.
+

CAUTION: Die Lüftermodule sind kurz. Unterstützen Sie das Lüftermodul immer mit Ihrer freien Hand, damit es nicht plötzlich vom Gehäuse abfällt und Sie verletzt.

. Setzen Sie das Lüftermodul beiseite.
. Wiederholen Sie die vorherigen Schritte für alle verbleibenden Lüftermodule.
. Setzen Sie das Lüftermodul in das Ersatzgehäuse ein, indem Sie es an der Öffnung ausrichten und dann in das Gehäuse schieben.
. Drücken Sie den Nockengriff des Lüftermoduls fest, damit er ganz in das Gehäuse eingesetzt wird.
+
Der Nockengriff hebt sich leicht, wenn das Lüftermodul vollständig sitzt.

. Schwenken Sie den Nockengriff in die geschlossene Position, und stellen Sie sicher, dass der Freigabehebel des Nockengriffs in die verriegelte Position einrastet.
+
Die Lüfter-LED sollte grün leuchten, nachdem der Lüfter eingesetzt wurde und sich auf die Betriebsgeschwindigkeit verdreht hat.

. Wiederholen Sie diese Schritte für die übrigen Lüftermodule.




== Schritt 3: Ersetzen Sie ein Chassis aus dem Rack oder Systemschrank der Ausrüstung

Sie müssen das vorhandene Chassis aus dem Rack oder dem Systemschrank entfernen, bevor Sie das Ersatzgehäuse installieren können.

. Entfernen Sie die Schrauben von den Montagepunkten des Gehäuses.
. Schieben Sie das alte Chassis bei zwei Personen von den Rack-Schienen in einem Systemschrank oder Ausrüstungs-Rack und legen Sie es dann beiseite.
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Installieren Sie das Ersatzgehäuse mithilfe von zwei Personen in das Rack oder den Systemschrank. Führen Sie das Chassis durch die Rack-Schienen in einem System-Schrank oder Ausrüstungs-Rack.
. Schieben Sie das Chassis vollständig in das Rack oder den Systemschrank der Ausrüstung.
. Befestigen Sie die Vorderseite des Chassis mit den Schrauben, die Sie vom alten Chassis entfernt haben, am Rack oder am Systemschrank des Geräts.
. Falls noch nicht geschehen, befestigen Sie die Blende.




== Schritt 4: Installieren Sie die Controller-Module

Nachdem Sie die Controller-Module im neuen Gehäuse installiert haben, müssen Sie das System booten.

Bei HA-Paaren mit zwei Controller-Modulen im selben Chassis ist die Sequenz, in der Sie das Controller-Modul installieren, besonders wichtig, da sie versucht, neu zu booten, sobald Sie es vollständig im Chassis einsetzen.

. Richten Sie das Ende des Controller-Moduls an der Öffnung im Gehäuse aus, und drücken Sie dann vorsichtig das Controller-Modul zur Hälfte in das System.
+

NOTE: Setzen Sie das Controller-Modul erst dann vollständig in das Chassis ein, wenn Sie dazu aufgefordert werden.

. Führen Sie die Konsole wieder mit dem Controller-Modul aus, und schließen Sie den Management-Port wieder an.
. Schließen Sie die Stromkabel an die Netzteile an, und setzen Sie die Netzkabelhalter wieder ein.
. Führen Sie die Neuinstallation des Controller-Moduls durch:
+
.. Stellen Sie sicher, dass die Verriegelungsarme in der ausgestreckten Position verriegelt sind.
.. Drücken Sie das Controller-Modul mithilfe der Entriegelungshebel in den Chassis-Schacht, bis der Anschlag einrastet.
.. Drücken Sie die orangefarbenen Laschen oben am Verriegelungsmechanismus nach unten und halten Sie sie gedrückt.
.. Schieben Sie das Controller-Modul vorsichtig in den Gehäuseschacht, bis es bündig an den Kanten des Chassis liegt.
+

NOTE: Die Arms des Verriegelungsmechanismus lassen sich in das Gehäuse schieben.

+
Das Controller-Modul beginnt zu booten, sobald es vollständig im Gehäuse sitzt.

.. Lösen Sie die Verriegelungen, um das Controller-Modul einrasten zu lassen.
.. Stromversorgung wieder einschalten.
.. Wenn Sie dies noch nicht getan haben, installieren Sie das Kabelverwaltungsgerät neu.
.. Unterbrechen Sie den normalen Bootvorgang, indem Sie auf drücken `Ctrl-C`.


. Wiederholen Sie die vorherigen Schritte, um den zweiten Controller im neuen Chassis zu installieren.

