---
permalink: fas500f/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: fas500f, replace the chassis 
summary: Bereiten Sie den Austausch des defekten Chassis in Ihrem FAS500f System vor, indem Sie das defekte Chassis identifizieren, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module kennzeichnen. 
---
= Vorbereitung auf den Austausch des FAS500f Chassis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bereiten Sie den Austausch des defekten Chassis in Ihrem FAS500f System vor, indem Sie das defekte Chassis identifizieren, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module kennzeichnen.

.Schritte
. Stellen Sie eine Verbindung zum seriellen Konsolenport mit der Schnittstelle mit her und überwachen Sie das System.
. Schalten Sie die Standort-LED des Controllers ein:
+
.. Verwenden Sie die `system controller location-led show` Befehl zur Anzeige des aktuellen Status der Standort-LED.
.. Standort-LED einschalten:
+
`system controller location-led modify -node _node1_ -state on`

+
Die Standort-LED leuchtet 30 Minuten lang.



. Prüfen Sie vor dem Öffnen der Verpackung das Verpackungsetikett und vergewissern Sie sich, dass Folgendes vorhanden ist:
+
** Bauteilnummer
** Teilebeschreibung
** Menge in der Box


. Nehmen Sie den Inhalt aus der Verpackung und bewahren Sie die Verpackung auf, um die defekte Komponente an NetApp zurückzusenden.
. Beschriften Sie alle an das Speichersystem angeschlossenen Kabel.  Dadurch wird eine ordnungsgemäße Neuverkabelung im weiteren Verlauf dieses Verfahrens sichergestellt.
. Erden Sie sich, falls Sie noch nicht geerdet sind.


.Was kommt als Nächstes?
Nachdem Sie die Vorbereitung für den Austausch Ihrer FAS500f-Chassis-Hardware abgeschlossen haben, müssen Sie link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"].
