---
permalink: fas500f/maintain-overview.html 
sidebar: sidebar 
keywords: fas500f maintenance, maintenance, repairing, repairing fas500f, replace fas500f components, replace fas500f components 
summary: Wartung der ASA C800 Hardware 
---
= Instandhaltung der FAS500f Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für das FAS500f Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



== Ventilator

Der Lüfter kühlt den Controller.



== Mezzanine-Karte

Eine Mezzanine-Karte ist eine Leiterplatte, die direkt in eine andere Steckkarte eingesteckt wird.



== NVMEM-Akku

Im Lieferumfang des Controllers ist eine Batterie enthalten, die zwischengespeicherte Daten bewahrt, wenn der Netzstrom ausfällt.



== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



== Akku in Echtzeit

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
