---
permalink: c400/install-videos.html 
sidebar: sidebar 
keywords: aff c400, aff, c400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.' 
---
= Videos – AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.

Wenn Sie über eine MetroCluster-Konfiguration verfügen, verwenden Sie den MetroCluster-Installationsinhalt.

https://["MetroCluster-Dokumentation"^]



== Video eines von zwei: Hardware-Installation und -Verkabelung

Das folgende Video zeigt, wie Sie Ihr neues System installieren und verkabeln.

.Animation - AFF C400 Installations- und Setup-Anweisungen
video::8e392453-beac-4db7-8088-aff1005e1f90[panopto]


== Video zwei von zwei: Führen Sie End-to-End-Software-Konfiguration

Das folgende Video zeigt die End-to-End-Softwarekonfiguration für Systeme mit ONTAP 9.2 und höher.

video::WAE0afWhj1c?[youtube]