---
permalink: a800/overview.html 
sidebar: sidebar 
keywords: AFF A800 specifications, AFF A800 specs, NetApp AFF A800, AFF A800 hardware 
summary: Wichtige Spezifikationen für die A800-Plattformgruppe 
---
= Wichtige Spezifikationen für AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das AFF A800 Speichersystem in einem einzelnen Hochverfügbarkeitspaar. Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== Wichtige Spezifikationen für AFF A800

* Plattformkonfiguration: AFF A800 Single Chassis HA Pair
* Max. Rohkapazität: 6,6096 PB
* Arbeitsspeicher: 1280.0000 GB
* Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 10
* Mindestversion von ONTAP : ONTAP 9.4RC1




== Skalierungsmaxima

* Typ: NAS; HA-Paare: 12; Rohkapazität: 79,3 PB / 70,4 PiB; Max. Speicher: 15360 GB
* Typ: SAN; HA-Paare: 6; Rohkapazität: 39,7 PB / 35,2 PiB; Max. Speicher: 7680 GB
* Typ: HA-Paar; Rohkapazität: 6,6 PB / 5,9 PiB; Max. Speicher: 1280.0000




== E/A



=== Integrierte E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 4




=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 20
* Protokoll: Ethernet 25 Gbit/s; Ports: 16
* Protokoll: Ethernet 10 Gbit/s; Ports: 32
* Protokoll: FC 32 Gbit/s; Ports: 32
* Protokoll: NVMe/FC 32 Gbit/s; Ports: 32
* Anschlüsse: 0
* Anschlüsse: 0
* Protokoll: SAS 12 Gbit/s; Ports: 32




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 4
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 12 Mbit/s; Anschlüsse: 4




== Speichernetzwerke werden unterstützt

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NFSv3/RDMA
* NFSv4/RDMA
* NVMe/FC
* NVMe/TCP
* S3
* S3 mit NAS
* KMU 2.0
* SMB 2.1
* SMB 2.x
* KMU 3.0
* KMU 3.1
* SMB 3.1.1




== Systemumgebungsspezifikationen

* Typische Leistung: 6626 BTU/h
* Leistung im schlimmsten Fall: 8417 BTU/h
* Gewicht: 132.5 lb 60.1 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 34,5 Zoll (36,6 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 5 °C bis 40 °C (41 °F bis 104 °F) bis zu einer Höhe von 3048 m (10000 ft); 8 % bis 90 % relative Luftfeuchtigkeit, nicht kondensierend
* Lagertemperatur/Luftfeuchtigkeit: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12192 m (40000 ft), 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 8,0 Schalldruck (LpAm) (in der Nähe): 62,8 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile
* SAS-In-Band-Management über SAS-Verbindungen für externe Regale

