---
permalink: asa-c800/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: asa c800, post boot media replacement steps for okm, nse, and nve 
summary: 'Sobald Umgebungsvariablen geprüft werden, müssen Sie spezifische Schritte für Systeme mit Onboard Key Manager \(OKM\), NetApp Storage Encryption \(NSE\) oder NetApp Volume Encryption \(NVE\) durchführen.' 
---
= Wiederherstellung der Verschlüsselung – ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie die Verschlüsselung auf dem Ersatz-Startmedium wieder her.

Wenn Ihr Speichersystem ONTAP 9.17.1 oder höher ausführt, verwenden Sie dielink:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"]

Führen Sie die entsprechenden Schritte zur Wiederherstellung der Verschlüsselung auf Ihrem System durch, abhängig von Ihrem Schlüsselverwaltungstyp.  Wenn Sie sich nicht sicher sind, welchen Key-Manager Ihr System verwendet, überprüfen Sie die Einstellungen, die Sie zu Beginn des Vorgangs zum Austausch des Startmediums erfasst haben.

[role="tabbed-block"]
====
.Onboard Key Manager (OKM)
--
Stellen Sie die OKM-Konfiguration (Onboard Key Manager) über das ONTAP-Startmenü wieder her.

.Bevor Sie beginnen
Stellen Sie sicher, dass Ihnen folgende Informationen zur Verfügung stehen:

* Clusterweite Passphrase eingegeben während https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["Aktivierung der Onboard-Schlüsselverwaltung"]
* https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Backup-Informationen für den Onboard Key Manager"]
* Überprüfen Sie mithilfe der https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Verifizierung von Onboard-Verschlüsselungsmanagement-Backup und Cluster-weiter Passphrase"] Verfahren


.Schritte
*Zum beeinträchtigten Regler:*

. Schließen Sie das Konsolenkabel an den defekten Controller an.
. Wählen Sie im ONTAP Bootmenü die entsprechende Option aus:
+
[cols="1a,2a"]
|===
| ONTAP-Version | Wählen Sie diese Option aus 


 a| 
ONTAP 9.8 oder höher
 a| 
Wählen Sie Option 10.

.Beispiel für ein Startmenü anzeigen
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
=====


 a| 
ONTAP 9.7 und frühere Versionen
 a| 
Wählen Sie die ausgeblendete Option aus `recover_onboard_keymanager`

.Beispiel für ein Startmenü anzeigen
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
=====
|===
. Bestätigen Sie auf Aufforderung, dass Sie den Wiederherstellungsprozess fortsetzen möchten:
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

=====
. Geben Sie die Cluster-weite Passphrase zweimal ein.
+
Während der Eingabe der Passphrase wird in der Konsole keine Eingabe angezeigt.

+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

=====
. Geben Sie die Sicherungsinformationen ein:
+
.. Fügen Sie den gesamten Inhalt von der Zeile BEGIN BACKUP bis zur Zeile END BACKUP einschließlich der Bindestriche ein.
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
=====
.. Drücken Sie am Ende der Eingabe zweimal die Eingabetaste.
+
Der Wiederherstellungsprozess ist abgeschlossen und die folgende Meldung wird angezeigt:

+
`Successfully recovered keymanager secrets.`

+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
=====
+

WARNING: Fahren Sie nicht fort, wenn die angezeigte Ausgabe etwas anderes ist als `Successfully recovered keymanager secrets` Die  Führen Sie eine Fehlerbehebung durch, um den Fehler zu beheben.



. Option auswählen `1` vom Bootmenü zum Fortfahren des Bootvorgangs in ONTAP.
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. Vergewissern Sie sich, dass auf der Konsole des Controllers die folgende Meldung angezeigt wird:
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

+
*Auf dem Partner-Controller:*

. Geben Sie den beeinträchtigten Controller zurück:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`

+
*Zum beeinträchtigten Regler:*

. Nach dem Booten nur mit dem CFO-Aggregat synchronisieren Sie den Schlüsselmanager:
+
`security key-manager onboard sync`

. Geben Sie bei Aufforderung die clusterweite Passphrase für den Onboard Key Manager ein.
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
=====
+

NOTE: Wenn die Synchronisierung erfolgreich ist, wird die Cluster-Eingabeaufforderung ohne weitere Meldungen zurückgegeben.  Wenn die Synchronisierung fehlschlägt, wird eine Fehlermeldung angezeigt, bevor zur Cluster-Eingabeaufforderung zurückgekehrt wird.  Fahren Sie erst fort, wenn der Fehler behoben ist und die Synchronisierung erfolgreich abgeschlossen wurde.

. Überprüfen Sie, ob alle Schlüssel synchronisiert sind:
+
`security key-manager key query -restored false`

+
Der Befehl sollte keine Ergebnisse liefern.  Falls Ergebnisse angezeigt werden, wiederholen Sie den Synchronisierungsbefehl, bis keine Ergebnisse mehr zurückgegeben werden.

+
*Auf dem Partner-Controller:*

. Geben Sie den beeinträchtigten Controller zurück:
+
`storage failover giveback -fromnode local`

. Automatisches Giveback wiederherstellen, wenn Sie es deaktiviert haben:
+
`storage failover modify -node local -auto-giveback true`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.Externer Schlüsselmanager (EKM)
--
Stellen Sie die Konfiguration des externen Schlüsselmanagers über das ONTAP-Startmenü wieder her.

.Bevor Sie beginnen
Sammeln Sie die folgenden Dateien von einem anderen Clusterknoten oder aus Ihrer Sicherung:

* `/cfcard/kmip/servers.cfg`Datei oder die KMIP-Serveradresse und Port
* `/cfcard/kmip/certs/client.crt`Datei (Clientzertifikat)
* `/cfcard/kmip/certs/client.key`Datei (Client-Schlüssel)
* `/cfcard/kmip/certs/CA.pem`Datei (KMIP-Server-CA-Zertifikate)


.Schritte
*Zum beeinträchtigten Regler:*

. Schließen Sie das Konsolenkabel an den defekten Controller an.
. Option auswählen `11` aus dem ONTAP Bootmenü.
+
.Beispiel für ein Startmenü anzeigen
[%collapsible]
=====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
=====
. Bestätigen Sie auf Aufforderung, dass Sie die erforderlichen Informationen gesammelt haben:
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
=====
. Geben Sie die Client- und Serverinformationen ein, wenn Sie dazu aufgefordert werden:
+
.. Geben Sie den Inhalt der Clientzertifikatsdatei (client.crt) einschließlich der BEGIN- und END-Zeilen ein.
.. Geben Sie den Inhalt der Client-Schlüsseldatei (client.key) einschließlich der BEGIN- und END-Zeilen ein.
.. Geben Sie den Inhalt der KMIP-Server-CA(s)-Datei (CA.pem) ein, einschließlich der BEGIN- und END-Zeilen.
.. Geben Sie die IP-Adresse des KMIP-Servers ein.
.. Geben Sie den KMIP-Server-Port ein (drücken Sie Enter, um den Standardport 5696 zu verwenden).
+
.Beispiel anzeigen
[%collapsible]
=====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
=====
+
Der Wiederherstellungsprozess ist abgeschlossen und die folgende Meldung wird angezeigt:

+
`Successfully recovered keymanager secrets.`

+
.Beispiel anzeigen
[%collapsible]
=====
....
System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.
....
=====


. Option auswählen `1` vom Bootmenü zum Fortfahren des Bootvorgangs in ONTAP.
+
.Beispiel-Eingabeaufforderung anzeigen
[%collapsible]
=====
....

***************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***************************************************************************

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. Automatisches Giveback wiederherstellen, wenn Sie es deaktiviert haben:
+
`storage failover modify -node local -auto-giveback true`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====