---
permalink: asa-c800/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: asa c800, boot the recovery image 
summary: Sie müssen das ONTAP-Image vom USB-Laufwerk starten, das Dateisystem wiederherstellen und die Umgebungsvariablen überprüfen. 
---
= Manuelle Wiederherstellung eines Bootmediums von einem USB-Laufwerk – ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Installation des neuen Startmediengeräts im System können Sie das Wiederherstellungsabbild von einem USB-Laufwerk starten und die Konfiguration vom Partnerknoten wiederherstellen.

Wenn Ihr Speichersystem ONTAP 9.17.1 oder höher ausführt, verwenden Sie dielink:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"]

.Bevor Sie beginnen
* Stellen Sie sicher, dass Ihre Konsole mit dem defekten Controller verbunden ist.
* Vergewissern Sie sich, dass Sie einen USB-Stick mit dem Wiederherstellungsabbild besitzen.
* Prüfen Sie, ob Ihr System Verschlüsselung verwendet.  Je nachdem, ob die Verschlüsselung aktiviert ist, müssen Sie in Schritt 3 die entsprechende Option auswählen.


.Schritte
. Starten Sie vom LOADER-Eingabeaufforderung des betroffenen Controllers aus das Wiederherstellungsabbild vom USB-Stick:
+
`boot_recovery`

+
Das Wiederherstellungsabbild wird vom USB-Stick heruntergeladen.

. Geben Sie bei Aufforderung den Namen des Bildes ein oder drücken Sie die *Eingabetaste*, um das in Klammern angezeigte Standardbild zu übernehmen.
. Stellen Sie das var-Dateisystem gemäß der für Ihre ONTAP Version geltenden Vorgehensweise wieder her:
+
[role="tabbed-block"]
====
.ONTAP 9.16.0 oder früher
--
Führen Sie die folgenden Schritte sowohl für den beeinträchtigten Steuermann als auch für den Partnersteuermann durch:

.. *Auf dem beeinträchtigten Controller:* Drücken Sie `Y` wenn du siehst `Do you want to restore the backup configuration now?`
.. *Auf dem beeinträchtigten Controller:* Drücken Sie bei Aufforderung die Taste `Y` um _/etc/ssh/ssh_host_ecdsa_key_ zu überschreiben.
.. *Auf dem Partnercontroller:* Legen Sie für den beeinträchtigten Controller die erweiterte Berechtigungsstufe fest:
+
`set -privilege advanced`

.. *Auf dem Partner-Controller:* Führen Sie den Befehl zum Wiederherstellen der Sicherung aus:
+
`system node restore-backup -node local -target-address _impaired_node_IP_address_`

+

NOTE: Sollten Sie eine andere Meldung als eine erfolgreiche Wiederherstellung erhalten, wenden Sie sich bitte an den NetApp Support.

.. *Auf dem Partner-Controller:* Zurück zur Administratorebene:
+
`set -privilege admin`

.. *Auf dem beeinträchtigten Controller:* Drücken Sie `Y` wenn du siehst `Was the restore backup procedure successful?`
.. *Auf dem beeinträchtigten Controller:* Drücken Sie `Y` wenn du siehst `...would you like to use this restored copy now?`
.. *Auf dem beeinträchtigten Controller:* Drücken Sie `Y` Wenn Sie zum Neustart aufgefordert werden, drücken Sie `Ctrl-C` wenn das Bootmenü erscheint.
.. *Bei beeinträchtigter Steuerung:* Führen Sie einen der folgenden Schritte aus:
+
*** Wenn das System keine Verschlüsselung verwendet, wählen Sie im Bootmenü _Option 1 Normal Boot_ aus.
*** Wenn das System Verschlüsselung verwendet, gehen Sie zulink:bootmedia-encryption-restore.html["Wiederherstellung der Verschlüsselung"] Die




--
.ONTAP 9.16.1 oder höher
--
Führen Sie die folgenden Schritte auf dem beeinträchtigten Steuergerät durch:

.. Drücken Sie auf `Y`, wenn Sie dazu aufgefordert werden, die Sicherungskonfiguration wiederherzustellen.
+
Nach erfolgreichem Wiederherstellungsvorgang wird folgende Meldung angezeigt: `syncflash_partner: Restore from partner complete`

.. Drücken `Y` wenn man dazu aufgefordert wird, zu bestätigen, dass die Wiederherstellung des Backups erfolgreich war.
.. Drücken `Y` wenn Sie aufgefordert werden, die wiederhergestellte Konfiguration zu verwenden.
.. Drücken `Y` wenn zum Neustart des Knotens aufgefordert wird.
.. Drücken `Y` Wenn Sie zum erneuten Neustart aufgefordert werden, drücken Sie `Ctrl-C` wenn das Bootmenü erscheint.
.. Führen Sie einen der folgenden Schritte aus:
+
*** Wenn das System keine Verschlüsselung verwendet, wählen Sie im Bootmenü _Option 1 Normal Boot_ aus.
*** Wenn das System Verschlüsselung verwendet, gehen Sie zulink:bootmedia-encryption-restore.html["Wiederherstellung der Verschlüsselung"] Die




--
====
. Schließen Sie das Konsolenkabel an den Partner Controller an.
. Wiederherstellung des normalen Betriebs des Controllers durch Zurückgeben des Speichers:
+
`storage failover giveback -fromnode local`

. Falls Sie die automatische Rückvergütung deaktiviert haben, aktivieren Sie sie bitte wieder:
+
`storage failover modify -node local -auto-giveback true`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


