---
permalink: asa-c800/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa c800, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Um den vollen Betrieb des Systems wiederherzustellen, müssen Sie die NetApp Storage Encryption-Konfiguration (falls erforderlich) wiederherstellen und Lizenzen für den neuen Controller installieren und das ausgefallene Teil an NetApp zurückgeben, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben. Wenden Sie sich an den technischen Support unter https://mysupport.netapp.com/site/global/dashboard["NetApp Support"], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik) wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen.' 
---
= Vollständige Systemwiederherstellung - ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den vollen Betrieb des Systems wiederherzustellen, müssen Sie die NetApp Storage Encryption-Konfiguration (falls erforderlich) wiederherstellen und Lizenzen für den neuen Controller installieren und das ausgefallene Teil an NetApp zurückgeben, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben.



== Schritt 1: Installieren Sie Lizenzen für den Ersatz-Controller in ONTAP

Sie müssen neue Lizenzen für den Node _Replacement_ installieren, wenn der beeinträchtigte Knoten ONTAP-Funktionen verwendete, die eine Standard-Lizenz (Node-locked) erfordern. Bei Standardlizenzen sollte jeder Node im Cluster über seinen eigenen Schlüssel für die Funktion verfügen.

.Über diese Aufgabe
Bis Sie Lizenzschlüssel installieren, sind Funktionen, für die Standardlizenzen erforderlich sind, weiterhin für den Node _Replacement_ verfügbar. Wenn der beeinträchtigte Knoten jedoch der einzige Node im Cluster war, der eine Lizenz für die Funktion besitzt, sind keine Konfigurationsänderungen an der Funktion zulässig. Durch die Verwendung nicht lizenzierter Funktionen auf dem Knoten können Sie möglicherweise nicht mit Ihrer Lizenzvereinbarung einverstanden sein. Sie sollten daher den Ersatzlizenzschlüssel oder die Schlüssel so schnell wie möglich auf dem Node _Replacement_ installieren.

.Bevor Sie beginnen
Die Lizenzschlüssel müssen im 28-stelligen Format vorliegen.

Sie haben eine 90-Tage-Nachfrist zur Installation der Lizenzschlüssel. Nach Ablauf der Frist werden alle alten Lizenzen ungültig. Nachdem ein gültiger Lizenzschlüssel installiert wurde, haben Sie 24 Stunden Zeit, um alle Schlüssel zu installieren, bevor die Kulanzzeit endet.

.Schritte
. Wenn Sie neue Lizenzschlüssel benötigen, holen Sie sich die Ersatzlizenz auf dem https://mysupport.netapp.com/site/global/dashboard["NetApp Support Website"] Im Abschnitt „My Support“ unter „Software-Lizenzen“.
+

NOTE: Die neuen Lizenzschlüssel, die Sie benötigen, werden automatisch generiert und an die E-Mail-Adresse in der Datei gesendet. Wenn Sie die E-Mail mit den Lizenzschlüssel nicht innerhalb von 30 Tagen erhalten, sollten Sie sich an den technischen Support wenden.

. Installieren Sie jeden Lizenzschlüssel: `+system license add -license-code license-key, license-key...+`
. Entfernen Sie ggf. die alten Lizenzen:
+
.. Suchen Sie nach nicht verwendeten Lizenzen: `license clean-up -unused -simulate`
.. Wenn die Liste korrekt aussieht, entfernen Sie die nicht verwendeten Lizenzen: `license clean-up -unused`






== Schritt: LIFs überprüfen und Seriennummer registrieren

Bevor Sie den Node _Replacement_ zum Service zurücksenden, sollten Sie überprüfen, ob sich die LIFs auf ihren Home-Ports befinden, und bei aktiviertem AutoSupport die Seriennummer des Node _Replacement_ registrieren.

.Schritte
. Vergewissern Sie sich, dass die logischen Schnittstellen ihrem Home-Server und ihren Ports Berichterstellung: `network interface show -is-home false`
+
Wenn eine der LIFs als falsch aufgeführt ist, stellen Sie sie auf ihre Home-Ports zurück: `network interface revert -vserver * -lif *`

. Registrieren Sie die Seriennummer des Systems beim NetApp Support.
+
** Wenn AutoSupport aktiviert ist, senden Sie eine AutoSupport Nachricht, um die Seriennummer zu registrieren.
** Wenn AutoSupport nicht aktiviert ist, rufen Sie an https://mysupport.netapp.com["NetApp Support"] Um die Seriennummer zu registrieren.


. Wenn ein AutoSupport-Wartungsfenster ausgelöst wurde, beenden Sie das Fenster mit. Verwenden Sie dazu die `system node autosupport invoke -node * -type all -message MAINT=END` Befehl.
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`




== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
