---
permalink: asa-c800/install-setup.html 
sidebar: sidebar 
keywords: asa c800, initial configuration options 
summary: Wählen Sie die Installationsmethode, die am besten zu Ihren Anforderungen für die Einrichtung eines ASA C800 Systems passt, mithilfe von schnellen grafischen Anleitungen, Video-Walkthroughs oder detaillierter Schritt-für-Schritt-Anleitung. 
---
= ASA C800 Installations- und Konfigurations-Workflow
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wählen Sie die Installationsmethode, die am besten zu Ihren Anforderungen für die Einrichtung eines ASA C800 Systems passt, mithilfe von schnellen grafischen Anleitungen, Video-Walkthroughs oder detaillierter Schritt-für-Schritt-Anleitung.

* link:../asa-c800/install-quick-guide.html["Schnelle Schritte"]
+
Eine druckbare PDF-Datei mit Schritt-für-Schritt-Anweisungen mit Live-Links zu zusätzlichen Inhalten.

* link:../asa-c800/install-videos.html["Videoschritte"]
+
Video Schritt-für-Schritt-Anleitungen.

* link:../asa-c800/install-detailed-guide.html["Detaillierte Schritte"]
+
Schritt-für-Schritt-Anleitungen mit Live-Links zu weiteren Inhalten



Wenn sich das System in einer MetroCluster-IP-Konfiguration befindet, lesen Sie den https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster-IP-Konfiguration installieren"^] Anweisungen.
