---
permalink: asa-c800/overview.html 
sidebar: sidebar 
keywords: ASA C800 specifications, ASA C800 specs, NetApp ASA C800, ASA C800 hardware 
summary: Wichtige Spezifikationen für die ASA-C800-Plattformgruppe 
---
= Wichtige Spezifikationen für ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das ASA C800 Speichersystem in einem einzelnen Hochverfügbarkeitspaar.  Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== Wichtige Spezifikationen für ASA C800

* Plattformkonfiguration: ASA C800 Single Chassis HA-Paar
* Max. Rohkapazität: 7,3680 PB
* Arbeitsspeicher: 1280.0000 GB
* Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 10
* Mindest ONTAP -Version: ONTAP 9.13.1P1 == Scaleout-Maxima
* Typ: NAS
* Typ: SAN; HA-Paare: 6; Rohkapazität: 44,2 PB / 39,3 PiB; Max. Speicher: 7680 GB
* Typ: HA-Paar; Rohkapazität: 7,4 PB / 6,5 PiB; Max. Speicher: 1280.0000




== E/A



=== Integrierte E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 4




=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 20
* Protokoll: Ethernet 25 Gbit/s; Ports: 16
* Protokoll: Ethernet 10 Gbit/s; Ports: 32
* Protokoll: FC 32 Gbit/s; Ports: 32
* Protokoll: NVMe/FC 32 Gbit/s; Ports: 32
* Anschlüsse: 0
* Anschlüsse: 0




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 4
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 12 Mbit/s; Anschlüsse: 4




== Speichernetzwerke werden unterstützt

* FC
* iSCSI
* NVMe/FC == Systemumgebungsspezifikationen
* Typische Leistung: 6626 BTU/h
* Leistung im schlimmsten Fall: 8417 BTU/h
* Gewicht: 132.5 lb 60.1 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 34,5 Zoll (36,6 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 5 °C bis 40 °C (41 °F bis 104 °F) bei 3048 m (10000 Fuß) Höhe; 8 % bis 90 % relative Luftfeuchtigkeit, nicht kondensierend
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß) 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 8,0 Schalldruck (LpAm) (in der Nähe): 62,8 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile [//] 2025-10-15 ontap-systems-internal/issues/1357

