---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: Bevor Sie das Bootmedium in Ihrem ASA C30-Speichersystem austauschen, stellen Sie sicher, dass Sie alle notwendigen Voraussetzungen und Überlegungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob Sie das richtige Ersatz-Bootmedium haben, die Bestätigung, dass der e0M-Wrench-Port am betroffenen Controller ordnungsgemäß funktioniert, und die Feststellung, ob Onboard Key Manager oder External Key Manager aktiviert ist. 
---
= Voraussetzungen für den Austausch des Startmediums - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Startmediums in Ihrem ASA C30-Speichersystem sicher, dass Sie die erforderlichen Anforderungen und Überlegungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört die Überprüfung, ob Sie über das richtige Ersatz-Bootmedium verfügen, die Bestätigung, dass der e0M-Port (Schraubenschlüssel) am beschädigten Controller ordnungsgemäß funktioniert, und die Feststellung, ob Onboard Key Manager (OKM) oder External Key Manager (EKM) aktiviert ist.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Sie müssen die ausgefallene Komponente durch eine FRU-Ersatz-Komponente ersetzen, die dieselbe Kapazität hat wie Sie von NetApp erhalten.
* Prüfen Sie, ob die e0S-Schnittstelle (e0M wrench port) am betroffenen Controller nicht defekt ist.
+
Der e0M-Port wird während des automatisierten Boot-Wiederherstellungsprozesses zur Kommunikation zwischen den beiden Controllern verwendet.

* Für OKM benötigen Sie die clusterweite Passphrase und auch die Sicherungsdaten.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** Datei /cfcard/kmip/servers.cfg.
** Datei /cfcard/kmip/certs/Client.crt.
** Datei /cfcard/kmip/certs/client.key.
** Datei /cfcard/kmip/certs/CA.pem.


* Es ist wichtig, die Befehle auf den richtigen Controller anzuwenden, wenn Sie das beschädigte Startmedium ersetzen:
+
** Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.




.Wie es weiter geht
Nachdem Sie die Anforderungen für die Startmedien überprüft haben, können Sie link:bootmedia-shutdown-bmr.html["Fahren Sie den Controller herunter"].
