---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module 
summary: Das ASA C30-Speichersystem bietet Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen oder Austauschen eines E/A-Moduls ist wichtig, wenn die Netzwerkfunktionen aktualisiert oder ein fehlerhaftes Modul behandelt werden soll. 
---
= Überblick über Hinzufügen und Ersetzen eines E/A-Moduls – ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das ASA C30-Speichersystem bietet Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen oder Austauschen eines E/A-Moduls ist wichtig, wenn die Netzwerkfunktionen aktualisiert oder ein fehlerhaftes Modul behandelt werden soll.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher I/O-Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das Speichersystem auch bei Ausfall eines I/O-Moduls betriebsbereit bleibt.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften I/O-Moduls kann das Speichersystem wieder in den optimalen Betriebszustand versetzt werden.


