---
permalink: asa-r2-c30/maintain-overview.html 
sidebar: sidebar 
keywords: asa c30, maintenance, maintenance 
summary: Warten Sie die Hardware Ihres ASA C30 Storage-Systems, um eine langfristige Zuverlässigkeit und optimale Leistung zu gewährleisten. Führen Sie regelmäßige Wartungsaufgaben durch, wie zum Beispiel den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden. 
---
= Übersicht über die Hardwarewartung - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Warten Sie die Hardware Ihres ASA C30 Storage-Systems, um eine langfristige Zuverlässigkeit und optimale Leistung zu gewährleisten. Führen Sie regelmäßige Wartungsaufgaben durch, wie zum Beispiel den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden.

Bei den Verfahren in diesem Abschnitt wird davon ausgegangen, dass das ASA C30-Speichersystem bereits als Speicherknoten in der ONTAP-Umgebung bereitgestellt wurde.



== Systemkomponenten

Für das ASA C30-Speichersystem können Sie Wartungsarbeiten an den folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem zum Booten verwendet.  Während der automatischen Wiederherstellung ruft das System das Boot-Image vom Partnerknoten ab und führt automatisch die entsprechende Boot-Menüoption aus, um das Image auf Ihrem Ersatz-Boot-Medium zu installieren.

Der automatisierte Boot-Medien-Wiederherstellungsprozess wird nur in ONTAP 9.17.1 und höher unterstützt. Wenn Ihr Speichersystem eine frühere Version von ONTAP verwendet, verwenden Sie die link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] .



 a| 
link:bootmedia-replace-workflow.html["Bootmedium – manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem verwendet, um das Image von einem USB-Laufwerk zu booten und die Konfiguration vom Partnerknoten wiederherzustellen



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und führt die ONTAP-Betriebssystemsoftware aus.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Ein duales Inline-Speichermodul (DIMM) ist eine Art von Computerspeicher. Sie sind installiert, um einem Controller-Motherboard Systemspeicher hinzuzufügen.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den für Daten erforderlichen physischen Storage bereitstellt.



 a| 
link:fan-replace.html["Ventilator"]
 a| 
Ein Lüfter kühlt den Controller und die Laufwerke.



 a| 
link:io-module-overview.html["I/O-Modul"]
 a| 
Das E/A-Modul (Eingangs-/Ausgangsmodul) ist eine Hardwarekomponente, die als Vermittler zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.



 a| 
link:nvdimm-battery-replace.html["NV-Batterie"]
 a| 
Die nichtflüchtige Speicherbatterie (NV) sorgt dafür, dass die NVMEM-Komponenten mit Strom versorgt werden, während die aktiven Daten nach einem Stromausfall in den Flash-Speicher ausgelagert werden.



 a| 
link:power-supply-replace.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromquelle in einem Controller bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Bei ausgeschaltetem Gerät bleiben Datum und Uhrzeit über eine Echtzeitbatterie erhalten.

|===