---
permalink: a250/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff a250, check onboard encryption keys as needed 
summary: Bevor Sie den beeinträchtigten Controller herunterfahren und den Status der integrierten Verschlüsselungsschlüssel prüfen, müssen Sie den Status des beeinträchtigten Controllers überprüfen, die automatische Rückgabe deaktivieren und überprüfen, welche Version von ONTAP das System ausführt. 
---
= Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie vor dem Herunterfahren des beeinträchtigten Controllers, ob Ihre Version von ONTAP NetApp Volume Encryption (NVE) unterstützt und ob Ihr Verschlüsselungsmanagement-System ordnungsgemäß konfiguriert ist.



== Schritt 1: Überprüfen Sie, ob Ihre Version von ONTAP Verschlüsselung unterstützt

Prüfen Sie, ob Ihre ONTAP Version NetApp Volume Encryption (NVE) unterstützt. Diese Informationen sind entscheidend, um das richtige ONTAP-Image herunterzuladen.

. Stellen Sie fest, ob Ihre ONTAP-Version Verschlüsselung unterstützt, indem Sie den folgenden Befehl ausführen:
+
`version -v`

+
Wenn die Ausgabe enthält `1Ono-DARE`, wird NVE auf Ihrer Cluster-Version nicht unterstützt.

. Je nachdem, ob NVE auf Ihrem System unterstützt wird, führen Sie eine der folgenden Aktionen durch:
+
** Falls NVE unterstützt wird, laden Sie das ONTAP Image mit NetApp Volume Encryption herunter.
** Falls NVE nicht unterstützt wird, laden Sie das ONTAP Image *ohne* NetApp-Volume-Verschlüsselung herunter.






== Schritt 2: Stellen Sie fest, ob es sicher ist, den Controller herunterzufahren

Um einen Controller sicher herunterzufahren, müssen Sie zuerst ermitteln, ob der Onboard Key Manager (OKM) oder der External Key Manager (EKM) aktiv ist. Überprüfen Sie anschließend den verwendeten Schlüsselmanager, zeigen Sie die entsprechenden Schlüsselinformationen an und ergreifen Sie Maßnahmen, die auf dem Status der Authentifizierungsschlüssel basieren.

. Bestimmen Sie, welcher Schlüsselmanager auf Ihrem System aktiviert ist:
+
[cols="1a,2a"]
|===
| Typ des Schlüsselmanagers | Führen Sie die folgenden Schritte aus... 


 a| 
Externer Schlüsselmanager (EKM)
 a| 
Stellen Sie fest, ob EKM auf Ihrem System aktiviert ist, indem Sie den folgenden Befehl ausführen:

`security key-manager show key store`

Wenn EKM aktiviert ist, `external` wird in der Ausgabe aufgeführt.



 a| 
Onboard Key Manager (OKM)
 a| 
Stellen Sie fest, ob OKM auf Ihrem System aktiviert ist, indem Sie basierend auf der Version von ONTAP, auf der der Node ausgeführt wird, einen der folgenden Befehle ausführen.

** Geben Sie für ONTAP 9.14.1 oder höher den folgenden Befehl ein:
+
`security key-manager keystore show`

+
Wenn OKM aktiviert ist, `OKM` wird in der Befehlsausgabe aufgelistet.

** Geben Sie für ONTAP 9.13.1 oder früher den folgenden Befehl ein:
+
`security key-manager show-key-store`

+
Wenn OKM aktiviert ist, `onboard` wird in der Befehlsausgabe aufgelistet.



|===
. Geben Sie den folgenden Abfragebefehl ein, um den Status der Authentifizierungsschlüssel in Ihrem Schlüsselmanager anzuzeigen:
+
`security key-manager key query`

. Überprüfen Sie die Ausgabe für den Wert in der `Restored` Spalte für Ihren Schlüsselmanager.
+
Diese Spalte gibt an, ob die Authentifizierungsschlüssel für Ihren Schlüsselmanager (entweder EKM oder OKM) erfolgreich wiederhergestellt wurden.

+
** Wenn der Wert in der Spalte „Restored“ wahr ist, werden die Schlüssel korrekt wiederhergestellt, und es ist sicher, mit dem Herunterfahren des Controllers fortzufahren.
** Wenn der Wert nicht wahr ist, wurden die Schlüssel nicht wiederhergestellt, und Sie müssen weitere Schritte (Wiederherstellen oder Synchronisieren von Schlüsseln) durchführen, je nachdem, ob Sie EKM oder OKM verwenden.


. Je nachdem, ob Sie EKM oder OKM verwenden, wählen Sie eine der folgenden Optionen aus und befolgen Sie die entsprechenden Schritte, je nach dem in der Spalte angezeigten Ausgabewert `Restored`.
+
[role="tabbed-block"]
====
.EKM
--
Befolgen Sie je nach dem in der Spalte angezeigten Ausgangswert `Restored` die entsprechenden Schritte.

[cols="1a,2a"]
|===
| Ausgabewert in `Restored` Spalte | Führen Sie die folgenden Schritte aus... 


 a| 
`true`
 a| 
Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].



 a| 
Alles andere als `true`
 a| 
.. Stellen Sie die externen Authentifizierungsschlüssel für das Verschlüsselungsmanagement auf allen Nodes im Cluster mit dem folgenden Befehl wieder her:
+
`security key-manager external restore`

+
Wenn der Befehl fehlschlägt, wenden Sie sich an http://mysupport.netapp.com/["NetApp Support"^].

.. Überprüfen Sie, ob in der `Restored` Spalte für alle Authentifizierungsschlüssel die angezeigt werden `true`, indem Sie den  Befehl eingeben `_security key-manager key query_`.
+
Wenn alle Authentifizierungsschlüssel vorhanden sind `true`, können Sie den beeinträchtigten Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].



|===
--
.OKM
--
Befolgen Sie je nach dem in der Spalte angezeigten Ausgangswert `Restored` die entsprechenden Schritte.

[cols="1a,2a"]
|===
| Ausgabewert in `Restored` Spalte | Führen Sie die folgenden Schritte aus... 


 a| 
`true`
 a| 
Sichern Sie die OKM-Informationen manuell.

.. Wechseln Sie in den erweiterten Modus, indem `set -priv advanced` Sie aufrufen und dann bei Aufforderung eingeben `Y`.
.. Geben Sie den folgenden Befehl ein, um die Informationen zum Verschlüsselungsmanagement anzuzeigen:
+
`security key-manager onboard show-backup`

.. Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei.
+
Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.

.. Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].




 a| 
Alles andere als `true`
 a| 
.. Geben Sie den integrierten Sicherheitsschlüssel-Manager Sync-Befehl ein:
+
`security key-manager onboard sync`

.. Geben Sie bei Aufforderung die 32-stellige alphanumerische Passphrase für das Onboard-Verschlüsselungsmanagement ein.
+
Wenn die Passphrase nicht angegeben werden kann, wenden Sie sich an http://mysupport.netapp.com/["NetApp Support"^].

.. Überprüfen Sie, ob die `Restored` Spalte für alle Authentifizierungsschlüssel angezeigt wird `true`:
+
`security key-manager key query`

.. Überprüfen Sie, ob der `Key Manager` Typ , anzeigt `onboard`und sichern Sie die OKM-Informationen manuell.
.. Geben Sie den Befehl ein, um die Backup-Informationen für das Verschlüsselungsmanagement anzuzeigen:
+
`security key-manager onboard show-backup`

.. Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei.
+
Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.

.. Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].


|===
--
====

