---
permalink: a250/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a250, shutdown the controllers 
summary: Zum Austausch des Chassis müssen Sie die Controller herunterfahren. 
---
= Schalten Sie die Controller aus - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieses Verfahren gilt nur für Konfigurationen ohne MetroCluster mit 2 Nodes. Wenn Sie ein System mit mehr als zwei Nodes haben, finden Sie weitere Informationen unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["So schalten Sie ein HA-Paar in einem Cluster mit 4 Nodes ein und fahren ein paar ordnungsgemäß hoch"^].

.Bevor Sie beginnen
Sie benötigen:

* Lokale Administratoranmeldeinformationen für ONTAP.
* NetApp Onboard-Verschlüsselungsmanagement (OKM) Cluster-weite Passphrase bei Verwendung von Storage-Verschlüsselung.
* SP/BMC-Zugriff für jeden Controller.
* Stoppen Sie den Zugriff aller Clients/Hosts auf Daten auf dem NetApp System.
* Externe Sicherungsaufträge werden angehalten.
* Notwendige Werkzeuge und Ausrüstung für den Austausch.



NOTE: Wenn es sich bei dem System um ein NetApp StorageGRID oder ONTAP S3 handelt, das als FabricPool Cloud Tier verwendet wird, finden Sie im https://kb.netapp.com/onprem/ontap/hardware/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage#["Anleitung zur Problemlösung des Speichersystems wird ordnungsgemäß heruntergefahren und gestartet"] Nach Durchführung dieses Verfahrens.


NOTE: Wenn Sie FlexArray-Array-LUNs verwenden, befolgen Sie die Dokumentation zum Speicher-Array des jeweiligen Anbieters, um das Herunterfahren für diese Systeme durchzuführen, nachdem Sie dieses Verfahren durchgeführt haben.


NOTE: Wenn Sie SSDs verwenden, finden Sie weitere Informationen unter https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU490["SU490: (Auswirkung: Kritisch) SSD Best Practices: Vermeiden Sie das Risiko von Laufwerksausfällen und Datenverlust, wenn Sie sich für mehr als zwei Monate ausgeschaltet haben"]

Als Best Practice vor dem Herunterfahren sollten Sie:

* Zusätzliche Durchführung https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Zustandsberichte zu Systemen"].
* Führen Sie ein Upgrade von ONTAP auf eine empfohlene Version für das System durch.
* Lösen Sie alle https://activeiq.netapp.com/["Active IQ Wellness-Alarme und Risiken"]. Notieren Sie sich alle derzeit auftretenden Fehler im System, z. B. LEDs an den Systemkomponenten.


.Schritte
. Melden Sie sich über SSH beim Cluster an oder von einem beliebigen Node im Cluster mit einem lokalen Konsolenkabel und einem Laptop/einer Konsole an.
. Schalten Sie AutoSupport aus, und geben Sie an, wie lange das System voraussichtlich offline ist:
+
`system node autosupport invoke -node * -type all -messages "MAINT=8h Power Maintenance"`

. Ermitteln Sie die SP/BMC-Adresse aller Nodes:
+
`system service-processor show -node * -fields address`

. Beenden Sie die Cluster-Shell: `exit`
. Melden Sie sich über SSH beim SP/BMC an. Verwenden Sie dabei die IP-Adresse eines der in der Ausgabe des vorherigen Schritts aufgeführten Nodes.
+
Wenn Sie eine Konsole oder einen Laptop verwenden, melden Sie sich mit den gleichen Cluster-Administratorberechtigungen beim Controller an.

+

NOTE: Öffnen Sie eine SSH-Sitzung für jede SP/BMC-Verbindung, damit Sie den Fortschritt überwachen können.

. Alle Nodes im Cluster anhalten:
+
`system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`.

+

NOTE: Bei Clustern mit SnapMirror Synchronous-Betrieb im StructSync-Modus: `system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Geben Sie *y* für jeden Controller im Cluster ein, wenn angezeigt wird `_Warning: Are you sure you want to halt node "cluster name-controller number"?
{y|n}:_`
. Warten Sie, bis die einzelnen Controller angehalten sind, und zeigen Sie die LOADER-Eingabeaufforderung an.
. Schalten Sie jedes Netzteil aus, oder ziehen Sie den Netzstecker, wenn kein Netzteilschalter vorhanden ist.
. Ziehen Sie das Netzkabel von den einzelnen Netzteilen ab.
. Vergewissern Sie sich, dass alle Controller im Gehäuse für beeinträchtigte Verbindung heruntergefahren sind.

