---
permalink: a250/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a250, replace the chassis 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Übersicht über den Chassisaustausch - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das Gehäuse zu ersetzen, müssen Sie die Blende, die Controller-Module und die NVMe-Laufwerke vom beeinträchtigten Gehäuse in das Ersatzgehäuse verschieben und dann das beeinträchtigte Chassis aus dem Rack oder dem Systemschrank entfernen und das Ersatzgehäuse an seiner Stelle installieren.

.Über diese Aufgabe
* Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.
* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie die Blende, NVMe-Laufwerke und Controller-Module in das neue Chassis verschieben und dass es sich bei dem Ersatzgehäuse um eine neue Komponente von NetApp handelt.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

