---
permalink: a250/maintain-overview.html 
sidebar: sidebar 
keywords: aff A250 maintenance, maintenance, repairing A250, repairing aff A250, replace aff A250 components, replace aff A250 components 
summary: Warten Sie die AFF A250 Hardware 
---
= Informationen zur Wartung Ihres AFF A250 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Hardware Ihres AFF A250 Storage-Systems wird gepflegt, um langfristige Zuverlässigkeit und optimale Leistung zu unterstützen. Regelmäßige Wartungsaufgaben wie der Austausch fehlerhafter Komponenten tragen dazu bei, Ausfallzeiten und Datenverlust zu vermeiden.

Die Wartungsverfahren setzen voraus, dass das AFF A250 Speichersystem bereits als Speicherknoten in der ONTAP Umgebung eingesetzt wurde.



[[system-components]]
== Systemkomponenten

Für das AFF A250-Speichersystem können Sie Wartungsverfahren für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP-Image-Dateien, die das Speichersystem zum Booten verwendet. Während der automatisierten Wiederherstellung ruft das System das Boot-Image vom Partnerknoten ab und führt automatisch die entsprechende Bootmenüoption aus, um das Image auf Ihrem Ersatz-Bootmedium zu installieren. Der automatisierte Wiederherstellungsprozess für das Bootmedium wird nur in ONTAP 9.18.1 und höher unterstützt. Wenn auf Ihrem Speichersystem eine frühere Version von ONTAP ausgeführt wird, verwenden Sie das link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"].



 a| 
link:bootmedia-replace-workflow.html["Bootmedium - manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP-Image-Dateien, die das Speichersystem zum Booten verwendet. Während der manuellen Wiederherstellung booten Sie das Speichersystem von einem USB-Laufwerk und stellen das Dateisystem-Image und die Konfiguration manuell wieder her. Wenn auf Ihrem Speichersystem ONTAP 9.18.1 oder höher ausgeführt wird, verwenden Sie die link:bootmedia-replace-workflow-bmr.html["automatisiertes Boot-Wiederherstellungsverfahren"].



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



 a| 
link:fan-replace.html["Ventilator"]
 a| 
Der Lüfter kühlt den Controller.



 a| 
link:mezzanine-replace.html["Mezzanine-Karte"]
 a| 
Die Mezzanine-Karte ist eine Leiterplatte, die direkt in eine andere Steckkarte gesteckt wird.



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM-Akku"]
 a| 
Die NVMEM-Batterie ist dafür zuständig, zwischengespeicherte Daten zu erhalten, falls die Netzstromversorgung ausfällt.



 a| 
link:power-supply-replace.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.

|===