---
permalink: a250/overview.html 
sidebar: sidebar 
keywords: AFF A250 specifications, AFF A250 specs, NetApp AFF A250, AFF A250 hardware 
summary: Wichtige Spezifikationen des AFF A250 Speichersystems 
---
= Wichtige Spezifikationen für AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind ausgewählte Spezifikationen für den AFF A250 aufgeführt.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der AFF A250 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für AFF A250

Plattformkonfiguration: AFF A250 Single Chassis HA Pair

Max. Rohkapazität: 1,1016 PB

Arbeitsspeicher: 128.0000 GB

Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 4

Mindestens erforderliche ONTAP -Version: ONTAP 9.8RC1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS | 12 | 13,2 PB / 11,7 PiB | 1536 GB 


| SAN | 6 | 6,6 PB / 5,9 PiB | 768 GB 


| HA-Paar |  | 1,1 PB / 1,0 PiB | 128,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 25 Gbit/s | 4 


| Ethernet 10 Gbit/s | 4 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 4 


| Ethernet 25 Gbit/s | 20 


| Ethernet 10 Gbit/s | 4 


| FC 32 Gbit/s | 16 


| NVMe/FC 32 Gbit/s | 16 


|  | 0 


| SAS 12 Gbit/s | 8 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 4 
|===


=== Unterstützte Speichernetzwerke

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 mit NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 2642 BTU/h
* Leistung im schlimmsten Fall: 3476 BTU/h
* Gewicht: 54.3 lb 24.6 kg
* Höhe: 2U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe:
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bis zu einer Höhe von 3048 m (10000 ft); 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Lagertemperatur/Luftfeuchtigkeit: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12192 m (40000 ft), 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustische Geräusche: Angegebene Schallleistung (LwAd): 7,2; Schalldruck (LpAm) (Positionen von Umstehenden): 69,1 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle; redundante Hot-Swap-fähige Controller; redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Verwaltung über SAS-Verbindungen für externe Shelves;
