---
permalink: fas8200/bootmedia-2n-mcc-switchback.html 
sidebar: sidebar 
keywords: fas8200, switch back aggregate in a two-node metrocluster configuration, manual, manual boot recovery 
summary: Führen Sie den MetroCluster -Switchback-Vorgang auf einem FAS8200 System durch, nachdem der Austausch des Bootmediums in einer Zwei-Knoten MetroCluster Konfiguration abgeschlossen ist. Das FAS8200 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt. 
---
= Wechseln Sie Aggregate in einer MetroCluster Konfiguration mit zwei Nodes – FAS8200 – zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie den MetroCluster -Switchback-Vorgang auf einem FAS8200 System durch, nachdem der Austausch des Bootmediums in einer Zwei-Knoten MetroCluster Konfiguration abgeschlossen ist. Dieses Verfahren beinhaltet die Überprüfung der Zustände von Knoten und Storage Virtual Machines (SVM), die Ausführung des Switchback-Befehls und die Bestätigung, dass die Konfiguration in den normalen Betriebszustand zurückkehrt, wobei Sync-Source-SVMs Daten aus lokalen Festplattenpools bereitstellen.

Das FAS8200 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt.

Dieser Task gilt nur für MetroCluster-Konfigurationen mit zwei Nodes.

.Schritte
. Vergewissern Sie sich, dass sich alle Nodes im befinden `enabled` Bundesland: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Überprüfen Sie, ob die Neusynchronisierung auf allen SVMs abgeschlossen ist: `metrocluster vserver show`
. Überprüfen Sie, ob die automatischen LIF-Migrationen durch die heilenden Vorgänge erfolgreich abgeschlossen wurden: `metrocluster check lif show`
. Führen Sie den Wechsel zurück mit dem aus `metrocluster switchback` Befehl von einem beliebigen Node im verbleibenden Cluster
. Stellen Sie sicher, dass der Umkehrvorgang abgeschlossen ist: `metrocluster show`
+
Der Vorgang zum zurückwechseln wird weiterhin ausgeführt, wenn sich ein Cluster im befindet `waiting-for-switchback` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Der Vorgang zum zurückwechseln ist abgeschlossen, wenn sich die Cluster im befinden `normal` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Wenn ein Wechsel eine lange Zeit in Anspruch nimmt, können Sie den Status der in-progress-Basispläne über die überprüfen `metrocluster config-replication resync-status show` Befehl.

. Wiederherstellung beliebiger SnapMirror oder SnapVault Konfigurationen

