---
permalink: fas8200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the chassis 
summary: Vor dem Austausch des Chassis in einem FAS8200-System ist zu prüfen, ob alle anderen Komponenten ordnungsgemäß funktionieren und ob das Ersatzchassis eine neue Komponente von NetApp desselben Modells ist. Das Verfahren erfordert das Umsetzen der Netzteile, Lüfter und Controller-Module in das neue Chassis und ist mit Unterbrechungen verbunden, wobei es in einem Cluster mit zwei Controllern zu einem vollständigen Dienstausfall und in einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall kommt. 
---
= Anforderungen sollten vor dem Austausch des Chassis in einem FAS8200 System geprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Chassis in einem FAS8200-System ist zu prüfen, ob alle anderen Komponenten ordnungsgemäß funktionieren und ob das Ersatzchassis eine neue Komponente von NetApp desselben Modells ist. Das Verfahren erfordert das Umsetzen der Netzteile, Lüfter und Controller-Module in das neue Chassis und ist mit Unterbrechungen verbunden, wobei es in einem Cluster mit zwei Controllern zu einem vollständigen Dienstausfall und in einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall kommt.

Alle anderen Systemkomponenten müssen einwandfrei funktionieren. Falls dies nicht der Fall ist, sollte der technische Support kontaktiert werden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie das Controller-Modul oder die Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieses Verfahren ist mit Störungen verbunden. Bei einem Cluster mit zwei Controllern kommt es zu einem vollständigen Dienstausfall und bei einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall.

