---
permalink: fas8200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the chassis 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Anforderungen sollten vor dem Austausch des FAS8200 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das Gehäuse zu ersetzen, müssen Sie die Netzteile, Lüfter und Controller-Module vom beeinträchtigten Gehäuse in das neue Gehäuse verschieben und das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse auswechseln.

Alle anderen Systemkomponenten müssen einwandfrei funktionieren. Falls dies nicht der Fall ist, sollte der technische Support kontaktiert werden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie das Controller-Modul oder die Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieses Verfahren ist mit Störungen verbunden. Bei einem Cluster mit zwei Controllern kommt es zu einem vollständigen Dienstausfall und bei einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall.

