---
permalink: fas8200/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas8200, verify and set HA state, run diagnostics, complete the replacement process 
summary: Sie müssen den HA-Status des Chassis überprüfen und die System-Level-Diagnose ausführen, Aggregate wechseln und das ausgefallene Teil an NetApp zurückgeben. Dies gilt auch in den mit dem Kit gelieferten RMA-Anweisungen. 
---
= Konfiguration wiederherstellen und überprüfen – FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen den HA-Status des Chassis überprüfen und die System-Level-Diagnose ausführen, Aggregate wechseln und das ausgefallene Teil an NetApp zurückgeben. Dies gilt auch in den mit dem Kit gelieferten RMA-Anweisungen.



== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest: `ha-config modify chassis _HA-state_`
+
Der Wert für HA-Zustand kann einer der folgenden sein: *** `ha`*** `mcc`*** `mcc-2n`*** `mccip`*** `non-ha`

.. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`


. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.
. Der nächste Schritt hängt von Ihrer Systemkonfiguration ab.
+
[cols="1,2"]
|===
| Ihr System befindet sich in... | Dann... 


 a| 
Eine eigenständige Konfiguration
 a| 
.. Beenden des Wartungsmodus: `halt`
.. Gehen Sie zu link:chassis-replace-move-hardware.html["Abschluss des Austauschvorgangs"].




 a| 
Ein HA-Paar mit einem zweiten Controller-Modul
 a| 
Beenden des Wartungsmodus: `halt` Die LOADER-Eingabeaufforderung wird angezeigt.

|===




== Schritt 2: Führen Sie die Diagnose auf Systemebene aus

Nach der Installation eines neuen Gehäuses sollten Sie die Interconnect-Diagnose ausführen.

Ihr System muss die LOADER-Eingabeaufforderung aufweisen, um die Diagnose auf Systemebene zu starten.

Alle Befehle im Diagnoseverfahren werden vom Controller ausgegeben, der die Komponente ersetzt wird.

. Wenn der zu wartenden Controller nicht an der LOADER-Eingabeaufforderung angezeigt wird, führen Sie die folgenden Schritte aus:
+
.. Wählen Sie im angezeigten Menü die Option Wartungsmodus.
.. Nachdem der Controller in den Wartungsmodus gebootet wurde, beenden Sie den Controller: `halt`
+
Nachdem Sie den Befehl ausgegeben haben, sollten Sie warten, bis das System an der LOADER-Eingabeaufforderung angehalten wird.

+

NOTE: Während des Startvorgangs können Sie sicher reagieren `y` So werden Sie aufgefordert:



. Wiederholen Sie den vorherigen Schritt auf dem zweiten Controller, wenn Sie sich in einer HA-Konfiguration befinden.
+

NOTE: Zum Ausführen des Interconnect-Tests müssen sich beide Controller im Wartungsmodus befinden.

. Rufen Sie an der LOADER-Eingabeaufforderung die speziellen Treiber auf, die speziell für die Diagnose auf Systemebene entwickelt wurden, um ordnungsgemäß zu funktionieren: `boot_diags`
+
Während des Startvorgangs können Sie sicher reagieren `y` Zu den Aufforderungen, bis die Eingabeaufforderung für den Wartungsmodus (*>) angezeigt wird.

. Aktivieren Sie die Verbindungstests über die Eingabeaufforderung für den Wartungsmodus: `sldiag device modify -dev interconnect -sel enable`
+
Die Verbindungstests sind standardmäßig deaktiviert und müssen aktiviert sein, damit sie separat ausgeführt werden können.

. Führen Sie den Verbindungstest über die Eingabeaufforderung für den Wartungsmodus aus: `sldiag device run -dev interconnect`
+
Sie müssen den Interconnect-Test nur von einem Controller aus ausführen.

. Vergewissern Sie sich, dass keine Hardwareprobleme aufgrund des Austauschs des Chassis aufgetreten sind: `sldiag device status -dev interconnect -long -state failed`
+
Die Diagnose auf Systemebene gibt die Eingabeaufforderung zurück, wenn keine Testfehler auftreten oder den vollständigen Status von Fehlern, die durch das Testen der Komponente entstehen, angezeigt wird.

. Fahren Sie auf der Grundlage des Ergebnisses des vorhergehenden Schritts fort.
+
[cols="1,2"]
|===
| Wenn die Diagnose auf Systemebene testet... | Dann... 


 a| 
Wurden ohne Fehler abgeschlossen
 a| 
.. Löschen Sie die Statusprotokolle: `sldiag device clearstatus`
.. Überprüfen Sie, ob das Protokoll gelöscht wurde: `sldiag device status`
+
Die folgende Standardantwort wird angezeigt:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Beenden Sie den Wartungsmodus bei beiden Controllern: `halt`
+
Vom System wird die LOADER-Eingabeaufforderung angezeigt.

+

NOTE: Sie müssen den Wartungsmodus auf beiden Controllern beenden, bevor Sie fortfahren.

.. Geben Sie an der LOADER-Eingabeaufforderung den folgenden Befehl für beide Controller ein: `bye`
.. Zurückkehren des Controllers in den normalen Betrieb:


|===
+
[cols="1,2"]
|===
| Wenn Ihr System ONTAP ausführt... | Dann... 


 a| 
Mit zwei Nodes im Cluster
 a| 
Geben Sie folgende Befehle ein: `node::> cluster ha modify -configured true``node::> storage failover modify -node node0 -enabled true`



 a| 
Mit mehr als zwei Nodes im Cluster
 a| 
Geben Sie diesen Befehl ein:``node::> storage failover modify -node node0 -enabled true``



 a| 
In einer MetroCluster Konfiguration mit zwei Nodes
 a| 
Fahren Sie mit dem nächsten Schritt fort. Das Verfahren zum Wechsel von MetroCluster erfolgt bei der nächsten Aufgabe des Ersatzprozesses.



 a| 
In einer eigenständigen Konfiguration
 a| 
Sie haben keine weiteren Schritte in dieser speziellen Aufgabe. Sie haben die Diagnose auf Systemebene abgeschlossen.



 a| 
Es kam zu einigen Testfehlern
 a| 
Bestimmen Sie die Ursache des Problems.

.. Beenden des Wartungsmodus: `halt`
.. Führen Sie eine saubere Abschaltung durch, und trennen Sie dann die Netzteile.
.. Überprüfen Sie, ob Sie alle Aspekte, die bei der Ausführung von Diagnose auf Systemebene zu beachten sind, dass die Kabel sicher angeschlossen sind und die Hardwarekomponenten ordnungsgemäß im Storage-System installiert wurden.
.. Schließen Sie die Netzteile wieder an, und schalten Sie das Speichersystem dann ein.
.. Führen Sie den Diagnosetest auf Systemebene erneut aus.


|===




== Schritt 3: Aggregate in einer MetroCluster Konfiguration mit zwei Nodes zurückwechseln

Nachdem Sie in einer MetroCluster Konfiguration mit zwei Nodes den FRU-Austausch abgeschlossen haben, können Sie den MetroCluster SwitchBack-Vorgang durchführen. Damit wird die Konfiguration in ihren normalen Betriebszustand zurückversetzt, wobei die Synchronisations-Storage Virtual Machines (SVMs) auf dem ehemals beeinträchtigten Standort jetzt aktiv sind und Daten aus den lokalen Festplattenpools bereitstellen.

Dieser Task gilt nur für MetroCluster-Konfigurationen mit zwei Nodes.

.Schritte
. Vergewissern Sie sich, dass sich alle Nodes im befinden `enabled` Bundesland: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Überprüfen Sie, ob die Neusynchronisierung auf allen SVMs abgeschlossen ist: `metrocluster vserver show`
. Überprüfen Sie, ob die automatischen LIF-Migrationen durch die heilenden Vorgänge erfolgreich abgeschlossen wurden: `metrocluster check lif show`
. Führen Sie den Wechsel zurück mit dem aus `metrocluster switchback` Befehl von einem beliebigen Node im verbleibenden Cluster
. Stellen Sie sicher, dass der Umkehrvorgang abgeschlossen ist: `metrocluster show`
+
Der Vorgang zum zurückwechseln wird weiterhin ausgeführt, wenn sich ein Cluster im befindet `waiting-for-switchback` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Der Vorgang zum zurückwechseln ist abgeschlossen, wenn sich die Cluster im befinden `normal` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Wenn ein Wechsel eine lange Zeit in Anspruch nimmt, können Sie den Status der in-progress-Basispläne über die überprüfen `metrocluster config-replication resync-status show` Befehl.

. Wiederherstellung beliebiger SnapMirror oder SnapVault Konfigurationen




== Schritt 4: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://["Teilerückgabe  Austausch"] Seite für weitere Informationen.
