---
permalink: fas8200/maintain-overview.html 
sidebar: sidebar 
keywords: fas8200 maintenance, maintenance, repairing fas8200, replace fas8200 components 
summary: Wartungsarbeiten an Komponenten des FAS8200 Speichersystems, einschließlich Bootmedien, Chassis, Controller, DIMMs und Netzteil, sind möglich. 
---
= Informationen zur Wartung eines FAS8200 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wartungsarbeiten an Komponenten des FAS8200 Speichersystems, einschließlich Bootmedien, Chassis, Controller, DIMMs und Netzteil, sind möglich.



[[boot-media]]
== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



[[caching-module]]
== Caching-Modul

Sie müssen das Caching-Modul des Controllers ersetzen, wenn Ihr System eine einzelne AutoSupport-Meldung (ASUP) registriert, dass das Modul offline gegangen ist.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[drive]]
== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



[[nvmem-battery]]
== NVMEM-Akku

Ein Akku ist im Lieferumfang eines Controllers enthalten und behält zwischengespeicherte Daten bei Ausfall des Netzstroms bei.



[[pcie-card]]
== PCIe-Karte

Eine PCIe-Karte (Peripheral Component Interconnect Express) ist eine Erweiterungskarte, die in den PCIe-Steckplatz auf der Hauptplatine eingesteckt wird.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Echtzeituhr-Akku

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
