---
permalink: afx-1k/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shut down the controller 
summary: Fahren Sie den beeinträchtigten Controller in Ihrem AFX 1K-Speichersystem herunter, um Datenverlust zu verhindern und die Systemstabilität beim Austausch des Startmediums sicherzustellen. 
---
= Fahren Sie den Controller herunter, um das Bootmedium zu ersetzen – AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fahren Sie den beeinträchtigten Controller in Ihrem AFX 1K-Speichersystem herunter, um Datenverlust zu verhindern und die Systemstabilität beim Austausch des Startmediums sicherzustellen.

Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers ermitteln und gegebenenfalls eine Speicher-Failover-Übernahme des Controllers durchführen, damit der fehlerfreie Controller weiterhin Daten aus dem beeinträchtigten Controller-Speicher bereitstellt.

.Über diese Aufgabe
* Wenn Sie einen Cluster mit mehr als vier Knoten haben, muss dieser im Quorum sein.  Um Clusterinformationen zu Ihren Knoten anzuzeigen, verwenden Sie die `cluster show` Befehl.  Weitere Informationen zum `cluster show` Befehl, siehelink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Anzeigen von Details auf Knotenebene in einem ONTAP Cluster"^] .
* Wenn der Cluster nicht im Quorum ist oder wenn der Zustand oder die Berechtigung eines Controllers (mit Ausnahme des beeinträchtigten Controllers) als falsch angezeigt wird, müssen Sie das Problem beheben, bevor Sie den beeinträchtigten Controller herunterfahren. Sehen link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^] .


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie die automatische Rückgabe von der Konsole des beeinträchtigten Controllers:
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Wenn Sie _Möchten Sie die automatische Rückgabe deaktivieren?_ sehen, geben Sie ein `y` .

+
.. Wenn Sie ONTAP Version 9.17.1 ausführen und der beeinträchtigte Controller nicht hochgefahren werden kann oder bereits übernommen wurde, müssen Sie die HA-Verbindung vom fehlerfreien Controller trennen, bevor Sie den beeinträchtigten Controller hochfahren.  Dadurch wird verhindert, dass der beeinträchtigte Controller eine automatische Rückgabe durchführt.
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`

+

NOTE: Wenn Sie nicht ONTAP Version 9.17.1 ausführen, überspringen Sie den obigen Schritt und fahren Sie mit Schritt 3 fort.



. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Eingabeaufforderung für das System oder Passwort
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Controller vom fehlerfreien Controller:
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Der Parameter _-halt true_ bringt den beeinträchtigten Knoten zur LOADER-Eingabeaufforderung.

|===


.Was kommt als Nächstes?
Nach dem Herunterfahren des Controllerslink:bootmedia-replace.html["Ändern Sie das Bootmedium"] .
