---
permalink: afx-1k/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: afx 1k, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Überprüfen Sie, ob die HA-Konfiguration des Controllers in Ihrem AFX 1K-Speichersystem aktiv ist und ordnungsgemäß funktioniert, und bestätigen Sie, dass die Adapter des Systems alle Pfade zu den Festplatten auflisten. 
---
= Wiederherstellen und Überprüfen der Systemkonfiguration – AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie, ob die HA-Konfiguration des Controllers in Ihrem AFX 1K-Speichersystem aktiv ist und ordnungsgemäß funktioniert, und bestätigen Sie, dass die Adapter des Systems alle Pfade zu den Festplatten auflisten.



== Schritt: Überprüfen Sie HA-Konfigurationseinstellungen

Sie müssen die überprüfen `HA` Status des Controller-Moduls und, falls erforderlich, aktualisieren Sie den Status entsprechend Ihrer Systemkonfiguration.

. Booten im Wartungsmodus: `boot_ontap maint`
+
.. Geben Sie ein `y`, wenn _Continue with Boot?_ angezeigt wird.
+
Wenn die Warnmeldung _System ID Mismatch_ angezeigt wird, geben Sie ein `y`.



. Geben Sie den Inhalt der Anzeige ein `sysconfig -v` und erfassen Sie diesen.
+

NOTE: Wenn Sie _PERSONALITY MISMATCH_ sehen, wenden Sie sich an den Kundendienst.

. Vergleichen Sie in der `sysconfig -v` Ausgabe die Adapterkarteninformationen mit den Karten und Positionen im Ersatzcontroller.




== Schritt 2: Überprüfen Sie die Datenträgerliste

. Überprüfen Sie, ob der Adapter die Pfade zu allen Festplatten auflistet:
+
`storage show disk -p`

+
Wenn Sie Probleme sehen, überprüfen Sie die Verkabelung, und setzen Sie die Kabel wieder ein.

. Beenden des Wartungsmodus:
+
`halt`



.Was kommt als Nächstes?
Nach der Wiederherstellung und Überprüfung der AFX 1K-Speichersystemkonfigurationlink:controller-replace-recable-reassign-disks.html["Geben Sie den Controller zurück"] .
