---
permalink: afx-1k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: afx 1k, prerequisite, replace the controller module 
summary: Stellen Sie vor dem Austausch des Controllers in Ihrem AFX 1K-Speichersystem sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört, dass Sie über den richtigen Ersatzcontroller, eine Sicherungskopie Ihrer Systemkonfiguration und Zugriff auf alle erforderlichen Tools und Firmware verfügen. 
---
= Anforderungen vor dem Austausch des Controllers in einem AFX 1K-System prüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Controllers in Ihrem AFX 1K-Speichersystem sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, die Überprüfung, ob Sie den richtigen Ersatzcontroller haben, und das Speichern der Konsolenausgabe des Controllers in einer Textprotokolldatei.

Überprüfen Sie die Anforderungen für den Austausch des Controllers.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.


* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Sie müssen die ausgefallene Komponente durch die Field-Replaceable Unit (FRU) ersetzen, die Sie von NetApp erhalten haben.
* Ein Controller-Modul muss durch ein Controller-Modul desselben Modelltyps ersetzt werden. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.


.Was kommt als Nächstes?
Nachdem Sie die Voraussetzungen für den Austausch Ihres AFX 1K-Controllers überprüft haben,link:controller-replace-shutdown.html["schalte die Controller aus"] .
