---
permalink: afx-1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: afx 1k, how to recable the system, how to reassign disks 
summary: Geben Sie die Kontrolle über die Speicherressourcen an den Ersatzcontroller zurück, damit Ihr AFX 1K-Speichersystem den Normalbetrieb wieder aufnehmen kann. 
---
= Gib den Controller zurück – AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Geben Sie die Kontrolle über die Speicherressourcen an den Ersatzcontroller zurück, damit Ihr AFX 1K-Speichersystem den Normalbetrieb wieder aufnehmen kann.  Das Rückgabeverfahren variiert je nach dem von Ihrem System verwendeten Verschlüsselungstyp: keine Verschlüsselung oder Onboard Key Manager (OKM)-Verschlüsselung.

[role="tabbed-block"]
====
.Keine Verschlüsselung
--
Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie seinen Speicher zurückgeben.

.Schritte
. Geben Sie in der LOADER-Eingabeaufforderung Folgendes ein:
+
`boot_ontap`

. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die Eingabeaufforderung _Login_ angezeigt wird, fahren Sie mit dem nächsten Schritt am Ende dieses Abschnitts fort.
** Wenn keine Anmeldeaufforderung angezeigt wird, drücken Sie die <Eingabe>-Taste. Wenn immer noch keine Anmeldeaufforderung angezeigt wird, melden Sie sich beim Partnerknoten an.


. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.  Weitere Informationen zu Berechtigungsstufen finden Sie unterlink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Verstehen Sie die Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und überprüfen Sie dann den Failover- und Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

. Wenn die HA-Interconnect-Links deaktiviert wurden, stellen Sie sie wieder her:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`

. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local -auto-giveback-of true`

. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.OKM-Verschlüsselung
--
Setzt die integrierte Verschlüsselung zurück und setzt den Controller in den normalen Betrieb zurück.

.Schritte
. Geben Sie an der LOADER-Eingabeaufforderung Folgendes ein:
+
`boot_ontap maint`

. Starten Sie das ONTAP-Menü über die Loader-Eingabeaufforderung `boot_ontap menu`, und wählen Sie Option 10.
. Geben Sie die OKM-Passphrase ein. Sie können diese Passphrase vom Kunden erhalten, oder wenden Sie sich an https://support.netapp.com["NetApp Support"].
+

NOTE: Sie werden zweimal zur Eingabe der Passphrase aufgefordert.

. Geben Sie die Daten des Sicherungsschlüssels ein, wenn Sie dazu aufgefordert werden.
. Geben Sie im Startmenü die Option für den normalen Start ein `1`.
. Verlegen Sie das Konsolenkabel zum Partnerknoten und geben Sie die folgenden Anmeldedaten ein:
+
`admin`

. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage  failover giveback -ofnode impaired-node -only-root true -override-destination-checks true`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.  Weitere Informationen zu Berechtigungsstufen finden Sie unterlink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Verstehen Sie die Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und überprüfen Sie dann den Failover- und Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

. Verlegen Sie das Konsolenkabel zum Ersatzknoten und geben Sie Folgendes ein:
+
`security key-manager onboard sync`

+

NOTE: Sie werden aufgefordert, die Cluster-weite Passphrase von OKM für den Cluster einzugeben.

. Überprüfen Sie den Status der Tasten mit folgendem Befehl:
+
`security key-manager key query -key-type svm-KEK`

+
Wenn in der Spalte _restored_ alles außer _true_ angezeigt wird, kontaktieren Sie https://support.netapp.com["NetApp Support"].

. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
.. Wenn die HA-Verbindungslinks getrennt wurden, aktivieren Sie sie erneut, um die automatische Rückgabe fortzusetzen:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local -auto-giveback-of true`

. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====
.Was kommt als Nächstes?
Nachdem Sie den Besitz der Speicherressourcen auf den Ersatzcontroller übertragen haben,link:controller-replace-restore-system-rma.html["Schließen Sie den Austausch des Controllers ab"] .
