---
permalink: afx-1k/io-module-overview.html 
sidebar: sidebar 
keywords: afx 1k, replace io module 
summary: Das AFX 1K-Speichersystem bietet Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen, um die Netzwerkkonnektivität und -leistung zu verbessern.  Das Hinzufügen oder Ersetzen eines E/A-Moduls ist unerlässlich, wenn Sie die Netzwerkfunktionen aktualisieren oder ein ausgefallenes Modul reparieren möchten. 
---
= Übersicht zum Hinzufügen und Ersetzen von E/A-Modulen – AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das AFX 1K-Speichersystem bietet Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen, um die Netzwerkkonnektivität und -leistung zu verbessern.  Das Hinzufügen oder Ersetzen eines E/A-Moduls ist unerlässlich, wenn Sie die Netzwerkfunktionen aktualisieren oder ein ausgefallenes Modul reparieren möchten.

Sie können ein ausgefallenes E/A-Modul in Ihrem AFX 1K-Speichersystem durch den gleichen E/A-Modultyp oder durch einen anderen E/A-Modultyp ersetzen.  Sie können einem System mit leeren Steckplätzen auch ein E/A-Modul hinzufügen.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das System auch bei einem Ausfall eines Moduls betriebsbereit bleibt.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften E/A-Moduls kann das System in den optimalen Betriebszustand zurückversetzt werden.



.Nummerierung des E/A-Steckplatzes
Die E/A-Steckplätze des AFX 1K-Controllers sind von 1 bis 11 nummeriert, wie in der folgenden Abbildung gezeigt.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Steckplatznummerierung auf einem AFX 1K-Controller]
