---
permalink: afx-1k/io-module-add.html 
sidebar: sidebar 
keywords: afx 1k, add I/O module 
summary: Fügen Sie Ihrem AFX 1K-Speichersystem ein E/A-Modul hinzu, um die Netzwerkkonnektivität zu verbessern und die Fähigkeit Ihres Systems zur Verarbeitung des Datenverkehrs zu erweitern. 
---
= E/A-Modul hinzufügen – AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fügen Sie Ihrem AFX 1K-Speichersystem ein E/A-Modul hinzu, um die Netzwerkkonnektivität zu verbessern und die Fähigkeit Ihres Systems zur Verarbeitung des Datenverkehrs zu erweitern.

Sie können Ihrem AFX 1K-Speichersystem ein E/A-Modul hinzufügen, wenn leere Steckplätze verfügbar sind oder alle Steckplätze vollständig belegt sind.



== Schritt 1: Schalten Sie das Controller-Modul für die gestörte Steuerung aus

Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Bevor Sie beginnen
Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].

.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Fallerstellung, indem Sie einen AutoSupport -Nachrichtenbefehl aufrufen:
+
`system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`

+
Der folgende AutoSupport -Befehl unterdrückt die automatische Fallerstellung für zwei Stunden:

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie die automatische Rückgabe über die Konsole des fehlerfreien Controllers:
+
`storage failover modify –node local -auto-giveback false`

. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
`Waiting for giveback...`
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung:

`storage failover takeover -ofnode impaired_node_name -halt true`

Der `-halt true` Der Parameter bringt Sie zur LOADER-Eingabeaufforderung.

|===




== Schritt 2: Fügen Sie das neue E/A-Modul hinzu

Wenn das Speichersystem über freie Steckplätze verfügt, installieren Sie das neue I/O-Modul in einem der verfügbaren Steckplätze. Wenn alle Steckplätze belegt sind, entfernen Sie ein vorhandenes E/A-Modul, um Platz zu schaffen, und installieren Sie dann das neue.

.Bevor Sie beginnen
* Überprüfen Sie die https://hwu.netapp.com/["NetApp Hardware Universe"^] um sicherzustellen, dass das neue E/A-Modul mit Ihrem Speichersystem und ONTAP -Version kompatibel ist.
* Wenn mehrere Steckplätze verfügbar sind, überprüfen Sie die Steckplatzprioritäten in https://hwu.netapp.com/["NetApp Hardware Universe"^] Und verwenden Sie die beste für Ihr I/O-Modul verfügbare Lösung.
* Stellen Sie sicher, dass alle anderen Komponenten ordnungsgemäß funktionieren.
* Stellen Sie sicher, dass Sie über die Ersatzkomponente verfügen, die Sie von NetApp erhalten haben.


[role="tabbed-block"]
====
.Fügen Sie ein E/A-Modul zu einem verfügbaren Steckplatz hinzu
--
Sie können ein neues I/O-Modul zu einem Speichersystem mit verfügbaren Steckplätzen hinzufügen.

.Schritte
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Tasten an der Innenseite des Kabelführungs-Fachs herausziehen und nach unten drehen.
. Entfernen Sie das Ausblendmodul des Zielsteckplatzes vom Träger:
+
.. Drücken Sie die Nockenverriegelung am Blindmodul im Zielsteckplatz.
.. Drehen Sie die Nockenverriegelung so weit wie möglich vom Modul weg.
.. Entfernen Sie das Modul aus dem Gehäuse, indem Sie den Finger in die Öffnung des Nockenhebels stecken und das Modul aus dem Gehäuse ziehen.


. Installieren Sie das E/A-Modul:
+
.. Richten Sie das E/A-Modul an den Kanten der Öffnung des Gehäusesteckplatzes aus.
.. Schieben Sie das Modul vorsichtig in den Steckplatz bis zum Gehäuse, und drehen Sie dann die Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Verkabeln Sie das E/A-Modul mit dem vorgesehenen Gerät.
+

NOTE: Stellen Sie sicher, dass alle nicht verwendeten I/O-Steckplätze leer sind, um mögliche thermische Probleme zu vermeiden.

. Drehen Sie das Kabelführungs-Fach bis in die geschlossene Position.
. Booten Sie an der LOADER-Eingabeaufforderung den Node neu:
+
`bye`

+

NOTE: Dadurch werden das I/O-Modul und andere Komponenten neu initialisiert und der Node neu gestartet.

. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die _Anmeldeaufforderung_ angezeigt wird, fahren Sie mit dem nächsten Schritt fort.
** Wenn die Anmeldeaufforderung nicht angezeigt wird, melden Sie sich beim Partnerknoten an.


. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.  Weitere Informationen zu Berechtigungsstufen finden Sie unterlink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Verstehen Sie die Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und prüfen Sie den Failover-Status und den Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

. Wenn die HA-Interconnect-Links deaktiviert wurden, stellen Sie sie wieder her:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`

. Wiederholen Sie diese Schritte für Controller B.
. Stellen Sie im funktionstüchtigen Knoten das automatische Giveback wieder her, wenn Sie es deaktiviert haben:
+
`storage failover modify -node local -auto-giveback-of _true_`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.Hinzufügen eines E/A-Moduls zu einem vollständig bestückten System
--
Sie können ein E/A-Modul zu einem vollständig bestückten System hinzufügen, indem Sie ein vorhandenes E/A-Modul entfernen und ein neues an dessen Stelle installieren.

.Über diese Aufgabe
Stellen Sie sicher, dass Sie die folgenden Szenarien kennen, um ein neues I/O-Modul zu einem vollständig bestückten System hinzuzufügen:

[cols="1,2"]
|===
| Szenario | Handeln erforderlich 


 a| 
NIC zu NIC (gleiche Anzahl von Ports)
 a| 
Die LIFs werden automatisch migriert, wenn das Controller-Modul heruntergefahren wird.



 a| 
NIC zu NIC (unterschiedliche Anzahl von Ports)
 a| 
Weisen Sie die ausgewählten LIFs dauerhaft einem anderen Home Port zu. Weitere Informationen finden Sie unter https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["Migrieren eines LIF"^] .



 a| 
NIC zu Speicher-I/O-Modul
 a| 
Verwenden Sie System Manager, um die LIFs dauerhaft zu verschiedenen Home Ports zu migrieren, wie in beschrieben https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["Migrieren eines LIF"^].

|===
.Schritte
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Trennen Sie alle Kabel vom Ziel-E/A-Modul.
. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Tasten an der Innenseite des Kabelführungs-Fachs herausziehen und nach unten drehen.
. Entfernen Sie das Ziel-I/O-Modul aus dem Gehäuse:
+
.. Drücken Sie die Taste für die Nockenverriegelung.
.. Drehen Sie die Nockenverriegelung so weit wie möglich vom Modul weg.
.. Entfernen Sie das Modul aus dem Gehäuse, indem Sie den Finger in die Öffnung des Nockenhebels stecken und das Modul aus dem Gehäuse ziehen.
+
Stellen Sie sicher, dass Sie den Steckplatz verfolgen, in dem sich das I/O-Modul befand.



. Installieren Sie das E/A-Modul im Zielsteckplatz im Gehäuse:
+
.. Richten Sie das Modul an den Kanten der Öffnung des Gehäusesteckplatzes aus.
.. Schieben Sie das Modul vorsichtig in den Steckplatz bis zum Gehäuse, und drehen Sie dann die Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Verkabeln Sie das E/A-Modul mit dem vorgesehenen Gerät.
. Wiederholen Sie die Schritte zum Entfernen und Installieren, um zusätzliche Module für den Controller zu ersetzen.
. Drehen Sie das Kabelführungs-Fach bis in die geschlossene Position.
. Booten Sie den Controller über die LOADER-Eingabeaufforderung:_bye_ neu
+
Dadurch werden die PCIe-Karten und andere Komponenten neu initialisiert und der Node wird neu gebootet.

. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die _Anmeldeaufforderung_ angezeigt wird, fahren Sie mit dem nächsten Schritt fort.
** Wenn die Anmeldeaufforderung nicht angezeigt wird, melden Sie sich beim Partnerknoten an.


. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.  Weitere Informationen zu Berechtigungsstufen finden Sie unterlink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Verstehen Sie die Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und prüfen Sie den Failover-Status und den Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

. Wenn die HA-Interconnect-Links deaktiviert wurden, stellen Sie sie wieder her:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode impaired_node_name`

. Automatisches Giveback aktivieren, falls deaktiviert:
+
`storage failover modify -node local -auto-giveback-of true`

. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie ein Speicher-E/A-Modul entfernt und ein neues NIC-E/A-Modul installiert haben, verwenden Sie für jeden Port den folgenden Netzwerkbefehl:
+
`storage port modify -node <node name>__ -port <port name>__ -mode network`

** Wenn Sie ein NIC-E/A-Modul entfernt und ein Speicher-E/A-Modul installiert haben, installieren und verkabeln Sie Ihre NX224-Shelves, wie inlink:../nx224/hot-add-shelf.html["Hot-Add NX224-Regal"] .


. Wiederholen Sie diese Schritte für Controller B.


--
====