---
permalink: asa150/install-quick-guide.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, quick, guide, graphic, instructions, install, rack, cable 
summary: Diese Kurzanleitung bietet grafische Anweisungen für die Installation Ihres ASA A150 Systems, vom Einbau in das Rack und der Verkabelung bis zur ersten Inbetriebnahme des Systems. 
---
= Ihr ASA A150 Speichersystem lässt sich in wenigen Schritten installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*Warnung:* Wenn Ihr System mit ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 oder ONTAP 9.15.1 - 9.15.1P2 installiert wird und Ihr System 10 oder mehr interne Solid-State-Laufwerke enthält, müssen Sie zusätzliche Schritte zur Vorbereitung des Systems auf die Installation durchführen. Siehe Ausgabe  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173 - ADP hinterlässt keine freie Root-Partition auf einer AFF A150 mit 10 oder mehr internen Laufwerken"^].

Die Installations- und Setup-Anweisungen enthalten grafische Anweisungen für eine typische Installation Ihres Systems, von Rack und Verkabelung bis zur ersten Inbetriebnahme des Systems. Wenn Sie mit der Installation von NetApp Systemen vertraut sind, lesen Sie diesen Leitfaden.

Verwenden Sie den Link: link:../media/PDF/Jan_2024_Rev2_AFFA150_ISI_IEOPS-1480.pdf["Installations- und Setup-Anweisungen für das AFF A150-System"^]


NOTE: Der ASA A150 verwendet dasselbe Installationsverfahren wie das AFF A150-System.
