---
permalink: asa150/install-videos.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, asa a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.' 
---
= Videoschritte - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In den folgenden Videos erfahren Sie, wie Sie Ihr System in Racks einarbeiten und verkabeln und wie Sie die Erstkonfiguration des Systems durchführen.

Wenn Sie über eine MetroCluster-Konfiguration verfügen, verwenden Sie die https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"^].

*Warnung:* Wenn Ihr System mit ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 oder ONTAP 9.15.1 - 9.15.1P2 installiert wird und Ihr System 10 oder mehr interne Solid-State-Laufwerke enthält, müssen Sie zusätzliche Schritte zur Vorbereitung des Systems auf die Installation durchführen. Siehe Ausgabe  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173 - ADP hinterlässt keine freie Root-Partition auf einer AFF A150 mit 10 oder mehr internen Laufwerken"^].

Hardwareinstallation und -Verkabelung:: Das folgende Video zeigt, wie Sie Ihr System installieren und verkabeln.


.Animation - Installation und Einrichtung eines AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]

NOTE: Der ASA A150 verwendet dasselbe Installationsverfahren wie das AFF A150-System.
