---
permalink: asa150/overview.html 
sidebar: sidebar 
keywords: ASA A150 specifications, ASA A150 specs, NetApp ASA A150, ASA A150 hardware 
summary: Wichtige Spezifikationen für das ASA A150 -Speichersystem 
---
= Wichtige Spezifikationen für ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für den ASA A150.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der ASA A150 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für ASA A150

Plattformkonfiguration: ASA A150 UTA2 Einzelgehäuse HA-Paar

Max. Rohkapazität: 0,5472 PB

Arbeitsspeicher: 64.0000 GB

Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze:

Mindestens erforderliche ONTAP -Version: ONTAP 9.13.1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS |  |  |  


| SAN | 6 | 3,3 PB / 2,9 PiB | 384 GB 


| HA-Paar |  | 0,5 PB / 0,5 PiB | 64,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 10 Gbit/s | 12 


| FC 16 Gbit/s | 8 


| SAS 12 Gbit/s | 4 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 2 
|===


=== Unterstützte Speichernetzwerke

FC; iSCSI; NVMe/TCP;



=== Spezifikationen der Systemumgebung

Keine Umgebungsdaten verfügbar.



=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP -Management-Schnittstelle; Redundante Hot-Swap-fähige Controller; Redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Management über SAS-Verbindungen; [//] 2025-10-15 ontap-systems-internal/issues/1357
