---
permalink: fas50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, replace the chassis 
summary: Stellen Sie vor dem Austausch des Gehäuses Ihres FAS50-Systems sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, ob das richtige Ersatzgehäuse vorhanden ist und welche Tools erforderlich sind. 
---
= Anforderungen für den Austausch des Gehäuses – FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Gehäuses Ihres FAS50-Systems sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, ob das richtige Ersatzgehäuse vorhanden ist und welche Tools erforderlich sind.

Lesen Sie die folgenden Anforderungen und Überlegungen durch.



== Anforderungen

* Das Ersatzgehäuse muss das gleiche Modell aufweisen wie das Gehäuse für beeinträchtigte Störungen. Dieses Verfahren gilt für einen ähnlichen Austausch, nicht für ein Upgrade.
* Alle anderen Komponenten des Speichersystems müssen ordnungsgemäß funktionieren. Falls nicht, wenden Sie sich an https://mysupport.netapp.com/site/global/dashboard["NetApp Support"], bevor Sie mit diesem Verfahren fortfahren.




== Überlegungen

* *Das Chassis-Austauschverfahren ist störend.* Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.
* Sie können das Verfahren zum Gehäuseaustausch bei allen Versionen von ONTAP verwenden, die von Ihrem Speichersystem unterstützt werden.
* Beim Austausch des Gehäuses wird angenommen, dass Sie den Blende, die Laufwerke, etwaige Laufwerkplatzhalter und die Controller auf das neue Gehäuse verschieben.
* Bei Bedarf können Sie die LEDs des Speichersystems (blau) einschalten, um das betroffene Speichersystem physisch zu lokalisieren. Melden Sie sich über SSH bei der BMC an und geben Sie den Befehl ein `system location-led _on_`.
+
Ein Speichersystem verfügt über drei Standort-LEDs: Eine auf dem Bedienfeld und eine auf jedem Controller. Die Standort-LEDs leuchten 30 Minuten lang.

+
Sie können sie deaktivieren, indem Sie den Befehl eingeben `system location-led _off_`. Wenn Sie sich nicht sicher sind, ob die LEDs leuchten oder nicht, können Sie ihren Status überprüfen, indem Sie den Befehl eingeben `system location-led show`.



.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"].
