---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen. 
---
= Anforderungen an den Austausch von Controllern – FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie die Anforderungen und Überlegungen beim Austausch des Controllers.



== Anforderungen

* Alle Regale müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie den Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"] Um zu bestimmen, ob Sie dieses Verfahren verwenden sollten.
* Sie müssen einen Controller durch einen Controller desselben Modelltyps ersetzen. Sie können Ihr System nicht aktualisieren, indem Sie einfach den Controller austauschen.
* Im Rahmen dieses Verfahrens können keine Laufwerke oder Shelfs geändert werden.
* Sie müssen immer die Konsolenausgabe des Controllers in einer Textprotokolldatei erfassen.
+
Die Konsolenausgabe enthält eine Aufzeichnung des Verfahrens, mit dem Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.





== Überlegungen

* Es ist wichtig, dass Sie die Befehle in diesem Verfahren auf den richtigen Controller anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.


* Bei Bedarf können Sie die LEDs des Speichersystems (blau) einschalten, um das betroffene Speichersystem physisch zu lokalisieren. Melden Sie sich über SSH bei der BMC an und geben Sie den Befehl ein `system location-led _on_`.
+
Ein Speichersystem verfügt über drei Standort-LEDs: Eine auf dem Bedienfeld und eine auf jedem Controller. Die Standort-LEDs leuchten 30 Minuten lang.

+
Sie können sie deaktivieren, indem Sie den Befehl eingeben `system location-led _off_`. Wenn Sie sich nicht sicher sind, ob die LEDs leuchten oder nicht, können Sie ihren Status überprüfen, indem Sie den Befehl eingeben `system location-led show`.


