---
sidebar: sidebar 
permalink: fas50/install-requirements.html 
keywords: fas50, install, setup, cautions 
summary: Überprüfen Sie die erforderlichen Geräte und die Vorsichtsmaßnahmen für das Anheben der Plattform und der Regale. 
---
= Installationsvoraussetzungen - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie die Anforderungen für Ihr FAS50 Storage-System.



== Für die Installation erforderliche Ausrüstung

Zur Installation des Storage-Systems benötigen Sie die folgenden Geräte und Tools:

* Zugriff auf einen Webbrowser zur Konfiguration des Speichersystems
* Band für elektrostatische Entladung (ESD)
* Taschenlampe
* Laptop oder Konsole mit USB-/serieller Verbindung
* Kreuzschlitzschraubendreher #2




== Vorsichtsmaßnahmen beim Anheben

Storage-Systeme und Shelves sind schwer. Gehen Sie beim Anheben und Bewegen dieser Gegenstände vorsichtig vor.



=== Gewicht des Storage-Systems

Treffen Sie die erforderlichen Vorsichtsmaßnahmen, wenn Sie das Speichersystem bewegen oder anheben.

Das Speichersystem kann bis zu 24.4 kg (53.8 lbs) wiegen. Zum Anheben des Lagersystems zwei Personen oder einen Hydraulikhub verwenden.

image::../media/drw_g_lifting_weight_ieops-1831.svg[FAS50 Symbol für Gewichtwarnung]



=== Regalgewicht

Treffen Sie die erforderlichen Vorsichtsmaßnahmen, wenn Sie Ihr Regal bewegen oder anheben.

Ein DS460C Shelf kann bis zu 181.1 kg (260.4 lbs) wiegen. Zum Anheben des Regals benötigen Sie möglicherweise bis zu fünf Personen oder einen hydraulischen Aufzug. Halten Sie alle Komponenten im Regal (vorne und hinten), um ein Ausbalancieren des Regalgewichts zu vermeiden.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C Vorsicht beim Anheben]

.Verwandte Informationen
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Sicherheitsinformationen und gesetzliche Hinweise"^]


.Was kommt als Nächstes?
Nachdem Sie die Installationsanforderungen und Überlegungen für Ihr Speichersystem überprüft haben, müssen Sie die link:install-prepare.html["Vorbereiten der Installation"].
