---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: fas50, replace io module 
summary: Die FAS50-Speichersysteme bieten Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen, um die Netzwerkkonnektivität und -leistung zu verbessern. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn die Netzwerkkapazität erweitert oder ein ausgefallenes Modul repariert werden soll. 
---
= Informationen zum Hinzufügen und Austauschen von E/A-Modulen in Ihrem FAS50 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die FAS50-Speichersysteme bieten Flexibilität beim Erweitern oder Ersetzen von E/A-Modulen, um die Netzwerkkonnektivität und -leistung zu verbessern. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn die Netzwerkkapazität erweitert oder ein ausgefallenes Modul repariert werden soll.

Sie können ein ausgefallenes E/A-Modul in Ihrem Speichersystem durch ein E/A-Modul desselben Typs oder durch ein anderes ersetzen. Sie können Cluster- und HA-E/A-Module im laufenden Betrieb austauschen, wenn Ihr Speichersystem bestimmte Anforderungen erfüllt. Sie können einem Speichersystem mit freien Steckplätzen auch ein E/A-Modul hinzufügen.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher I/O-Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das Speichersystem auch bei Ausfall eines I/O-Moduls betriebsbereit bleibt.

* link:io-module-hotswap.html["Hot-Swap eines I/O-Moduls"]
+
Sie können bestimmte E/A-Module im Hot-Swap-Verfahren gegen ein gleichwertiges E/A-Modul austauschen, um das Speichersystem wieder in seinen optimalen Betriebszustand zu versetzen. Hot-Swap erfolgt, ohne dass eine manuelle Übernahme durchgeführt werden muss.

+
Um dieses Verfahren zu verwenden, muss auf Ihrem Speichersystem ONTAP 9.17.1 oder höher ausgeführt werden und bestimmte Systemanforderungen erfüllen.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften I/O-Moduls kann das Speichersystem wieder in den optimalen Betriebszustand versetzt werden.


