---
permalink: fas9500/add_io_module.html 
sidebar:  
keywords:  
summary: Sie können Ihrem System ein I/O-Modul hinzufügen, indem Sie ein vorhandenes I/O-Modul durch ein neues I/O-Modul in einem vollständig bestückten System ersetzen oder ein neues I/O-Modul in einen leeren Steckplatz im Gehäuse hinzufügen. 
---
= Fügen Sie ein I/O-Modul hinzu: FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihrem System ein I/O-Modul hinzufügen, indem Sie entweder einen NIC oder einen Speicheradapter durch einen neuen in einem vollständig bestückten System ersetzen oder einen neuen NIC- oder Speicheradapter in einen leeren Gehäusesteckplatz Ihres Systems hinzufügen.

.Bevor Sie beginnen
* Prüfen Sie die https://["NetApp Hardware Universe"] Vergewissern Sie sich, dass das neue I/O-Modul mit Ihrem System und Ihrer Version von ONTAP kompatibel ist.
* Wenn mehrere Steckplätze verfügbar sind, überprüfen Sie die Steckplatzprioritäten in https://["NetApp Hardware Universe"] Und verwenden Sie die beste für Ihr I/O-Modul verfügbare Lösung.
* Damit ein I/O-Modul unterbrechungsfrei hinzugefügt werden kann, müssen Sie den Zielcontroller übernehmen, die Abdeckung für die Steckplatzabdeckung im Zielsteckplatz entfernen oder ein vorhandenes I/O-Modul entfernen, das neue oder das neue I/O-Modul hinzufügen und dann den Zielcontroller zurückgeben.
* Stellen Sie sicher, dass alle anderen Komponenten ordnungsgemäß funktionieren.




== Option 1: Fügen Sie das I/O-Modul zu einem System mit offenen Steckplätzen hinzu

Sie können ein I/O-Modul zu einem leeren Modulsteckplatz in Ihrem System hinzufügen.



== Schritt 1: Fahren Sie den Knoten mit beeinträchtigten Knoten herunter

Fahren Sie den Regler herunter oder übernehmen Sie ihn mit einer der folgenden Optionen.

[role="tabbed-block"]
====
.Option 1: Die meisten Systeme
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Über diese Aufgabe
Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].

.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
`Waiting for giveback...`
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
.Option 2: Controller befindet sich in einem MetroCluster
--

NOTE: Verwenden Sie dieses Verfahren nicht, wenn sich Ihr System in einer MetroCluster-Konfiguration mit zwei Knoten befindet.

Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].
* Wenn Sie über eine MetroCluster-Konfiguration verfügen, müssen Sie bestätigt haben, dass der MetroCluster-Konfigurationsstatus konfiguriert ist und dass die Nodes in einem aktivierten und normalen Zustand vorliegen (`metrocluster node show`).


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
====


== Schritt 2: E/A-Module hinzufügen

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Entfernen Sie die Abdeckung des Zielsteckplatzes:
+
.. Drücken Sie den mit Buchstaben versehenen und nummerierten Nockenriegel.
.. Drehen Sie die Nockenverriegelung nach unten, bis sie sich in der geöffneten Position befindet.
.. Entfernen Sie die Abdeckung.


. Installieren Sie das E/A-Modul:
+
.. Richten Sie das E/A-Modul an den Kanten des Schlitzes aus.
.. Schieben Sie das E/A-Modul in den Steckplatz, bis die vorletzte und nummerierte E/A-Nockenverriegelung mit dem E/A-Nockenstift einrastet.
.. Drücken Sie die E/A-Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Wenn es sich bei dem Ersatz-E/A-Modul um eine NIC handelt, verkabeln Sie das Modul mit den Datenschaltern.
+

NOTE: Stellen Sie sicher, dass alle nicht verwendeten I/O-Steckplätze leer sind, um mögliche thermische Probleme zu vermeiden.

. Starten Sie den Controller von der LOADER-Eingabeaufforderung neu: _Bye_
+

NOTE: Dadurch werden die PCIe-Karten und andere Komponenten neu initialisiert und der Node wird neu gebootet.

. Geben Sie den Node vom Partner-Node zurück. `storage failover giveback -ofnode target_node_name`
. Automatisches Giveback aktivieren, falls deaktiviert: `storage failover modify -node local -auto-giveback true`
. Wenn Sie die Steckplätze 3 und/oder 7 für Netzwerke verwenden, verwenden Sie den `storage port modify -node __<node name>__ -port __<port name>__ -mode network` Befehl zum Konvertieren des Steckplatzes für die Netzwerkverwendung.
. Wiederholen Sie diese Schritte für Controller B.
. Wenn Sie ein Storage-I/O-Modul installiert haben, installieren und verkabeln Sie Ihre SAS-Shelfs, wie unter beschrieben https://["Hot-Adding eines SAS-Shelfs"^].




== Option 2: Fügen Sie ein I/O-Modul in ein System ohne offene Steckplätze hinzu

Wenn Ihr System vollständig bestückt ist, können Sie ein I/O-Modul in einem I/O-Steckplatz ändern, indem Sie ein vorhandenes I/O-Modul entfernen und es durch ein anderes I/O-Modul ersetzen.

. Wenn Sie sind:
+
[cols="1,2"]
|===
| Ersetzen einer... | Dann... 


 a| 
NIC-I/O-Modul mit der gleichen Anzahl an Ports
 a| 
Die LIFs werden automatisch migriert, wenn das Controller-Modul heruntergefahren wird.



 a| 
NIC-I/O-Modul mit weniger Ports
 a| 
Die betroffenen LIFs werden permanent einem anderen Home-Port zugewiesen. Siehe https://["Migrieren eines LIF"^] Weitere Informationen über die Verwendung von System Manager zum permanenten Verschieben der LIFs



 a| 
NIC-I/O-Modul mit Speicher-I/O-Modul
 a| 
Verwenden Sie System Manager, um die LIFs dauerhaft zu verschiedenen Home Ports zu migrieren, wie in beschrieben https://["Migrieren eines LIF"^].

|===




== Schritt 1: Fahren Sie den Knoten mit beeinträchtigten Knoten herunter

Fahren Sie den Regler herunter oder übernehmen Sie ihn mit einer der folgenden Optionen.

[role="tabbed-block"]
====
.Option 1: Die meisten Systeme
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Über diese Aufgabe
Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].

.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
`Waiting for giveback...`
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
.Option 2: Controller befindet sich in einem MetroCluster
--

NOTE: Verwenden Sie dieses Verfahren nicht, wenn sich Ihr System in einer MetroCluster-Konfiguration mit zwei Knoten befindet.

Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].
* Wenn Sie über eine MetroCluster-Konfiguration verfügen, müssen Sie bestätigt haben, dass der MetroCluster-Konfigurationsstatus konfiguriert ist und dass die Nodes in einem aktivierten und normalen Zustand vorliegen (`metrocluster node show`).


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
====


== Schritt 2: E/A-Module ersetzen

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Trennen Sie alle Kabel vom Ziel-E/A-Modul.
. Entfernen Sie das Ziel-I/O-Modul aus dem Gehäuse:
+
.. Drücken Sie den mit Buchstaben versehenen und nummerierten Nockenriegel.
+
Die Nockenverriegelung bewegt sich vom Gehäuse weg.

.. Drehen Sie die Nockenverriegelung nach unten, bis sie sich in horizontaler Position befindet.
+
Das I/O-Modul wird aus dem Gehäuse entfernt und bewegt sich ca. 1/2 Zoll aus dem I/O-Steckplatz.

.. Entfernen Sie das E/A-Modul aus dem Gehäuse, indem Sie an den Zuglaschen an den Seiten der Modulfläche ziehen.
+
Stellen Sie sicher, dass Sie den Steckplatz verfolgen, in dem sich das I/O-Modul befand.

+
.Animation - Ersetzen eines E/A-Moduls
video::0903b1f9-187b-4bb8-9548-ae9b0012bb21[panopto]
+
image::../media/drw_9500_remove_PCIe_module.svg[drw 9500 entfernen das PCIe-Modul]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[Legende Symbol 01]
 a| 
Gerettete und nummerierte E/A-Nockenverriegelung



 a| 
image::../media/legend_icon_02.svg[Legende Symbol 02]
 a| 
E/A-Nockenverriegelung vollständig entriegelt

|===


. Installieren Sie das I/O-Modul in den Zielsteckplatz:
+
.. Richten Sie das E/A-Modul an den Kanten des Schlitzes aus.
.. Schieben Sie das E/A-Modul in den Steckplatz, bis die vorletzte und nummerierte E/A-Nockenverriegelung mit dem E/A-Nockenstift einrastet.
.. Drücken Sie die E/A-Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Wiederholen Sie die Schritte zum Entfernen und Installieren, um zusätzliche Module für Controller A auszutauschen
. Wenn es sich bei dem Ersatz-E/A-Modul um eine NIC handelt, verkabeln Sie das Modul oder die Module mit den Datenschaltern.
+

NOTE: Dadurch werden die PCIe-Karten und andere Komponenten neu initialisiert und der Node wird neu gebootet.

. Booten Sie den Controller über die LOADER-Eingabeaufforderung neu:
+
.. Überprüfen Sie die BMC-Version auf dem Controller: `system service-processor show`
.. Aktualisieren Sie ggf. die BMC-Firmware: `system service-processor image update`
.. Booten Sie den Node neu: `bye`
+

NOTE: Dadurch werden die PCIe-Karten und andere Komponenten neu initialisiert und der Node wird neu gebootet.

+

NOTE: Wenn beim Neustart ein Problem auftritt, lesen Sie https://["BURT 1494308 – das Herunterfahren der Umgebung kann während des Austauschs des I/O-Moduls ausgelöst werden"]



. Geben Sie den Node vom Partner-Node zurück. `storage failover giveback -ofnode target_node_name`
. Automatisches Giveback aktivieren, falls deaktiviert: `storage failover modify -node local -auto-giveback true`
. Wenn Sie hinzugefügt haben:
+
[cols="1,2"]
|===
| Wenn I/O-Modul ist ein... | Dann... 


 a| 
NIC-Modul in den Steckplätzen 3 oder 7,
 a| 
Verwenden Sie die `storage port modify -node *_<node name>__ -port *_<port name>__ -mode network` Befehl für jeden Port.



 a| 
Speichermodul
 a| 
Installieren und verkabeln Sie Ihre SAS-Shelfs, wie unter beschriebenhttps://["Hot-Adding eines SAS-Shelfs"^].

|===
. Wiederholen Sie diese Schritte für Controller B.

