---
permalink: fas9500/bootmedia_encryption_restore.html 
sidebar: sidebar 
keywords:  
summary: 'Sobald Umgebungsvariablen geprüft werden, müssen Sie spezifische Schritte für Systeme mit Onboard Key Manager \(OKM\), NetApp Storage Encryption \(NSE\) oder NetApp Volume Encryption \(NVE\) durchführen.' 
---
= Schritte zum Austausch von Medien nach dem Booten für OKM, NSE und NVE – FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sobald Umgebungsvariablen aktiviert sind, müssen Sie bestimmte Schritte zur Wiederherstellung von Onboard Key Manager (OKM), NetApp Storage Encryption (NSE) und NetApp Volume Encryption (NVE) ausführen.

. Bestimmen Sie den Abschnitt, den Sie zum Wiederherstellen Ihrer OKM-, NSE- oder NVE-Konfigurationen verwenden sollten: Wenn NSE oder NVE zusammen mit Onboard Key Manager aktiviert sind, müssen Sie die zu Beginn dieses Verfahrens erfassten Einstellungen wiederherstellen.
+
** Wenn NSE oder NVE aktiviert sind und der Onboard Key Manager aktiviert ist, wechseln Sie zu <<Stellen Sie NVE oder NSE wieder her, wenn Onboard Key Manager aktiviert ist>>.
** Wenn NSE oder NVE für ONTAP 9.6 aktiviert sind, finden Sie unter <<Stellen Sie NSE/NVE auf Systemen mit ONTAP 9.6 und höher wieder her>>.






== Stellen Sie NVE oder NSE wieder her, wenn Onboard Key Manager aktiviert ist

. Verbinden Sie das Konsolenkabel mit dem Ziel-Node.
. Verwenden Sie die `boot_ontap` Befehl an der LOADER-Eingabeaufforderung zum Booten des Node.
. Überprüfen Sie die Konsolenausgabe:
+
[cols="1,2"]
|===
| Wenn die Konsole angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Starten Sie den Knoten im Startmenü: `boot_ontap menu`



 a| 
Warten auf Zurückgeben
 a| 
.. Eingabe `Ctrl-C` An der Eingabeaufforderung
.. Bei der Meldung: Möchten Sie diesen Knoten anhalten, anstatt [y/n] zu warten? , Geben Sie ein: `y`
.. Geben Sie an der LOADER-Eingabeaufforderung den ein `boot_ontap menu` Befehl.


|===
. Geben Sie im Startmenü den verborgenen Befehl ein. `recover_onboard_keymanager`, Und antworten `y` An der Eingabeaufforderung.
. Geben Sie die Passphrase für das Onboard-Schlüsselmanagement ein, das Sie zu Beginn dieses Verfahrens vom Kunden erhalten haben.
. Wenn Sie zur Eingabe der Backup-Daten aufgefordert werden, fügen Sie die zu Beginn dieses Abschnitts erfassten Backup-Daten bei der Aufforderung ein. Fügen Sie die Ausgabe von ein `security key-manager backup show` ODER `security key-manager onboard show-backup` Befehl.
+

NOTE: Die Daten werden von beiden ausgegeben `security key-manager backup show` Oder Security key-Manager Onboard show-Backup` Befehl.

+
Beispiel für Backup-Daten:

+
Backup-Daten eingeben:

+
[]
====
------------------------------- BACKUP-------------------------------------- TmV0QXBwIETERTABCbGaiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA . . . H4nPQM0nrDRYRa9SCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

--------------------------------- END-BACKUP--------------------------------------------------

====
. Wählen Sie im Startmenü die Option Normal Boot aus.
+
Das System startet zum Warten auf Giveback... Eingabeaufforderung.

. Verschieben Sie das Konsolenkabel zum Partner-Node und melden Sie sich als Administrator an.
. Vergewissern Sie sich, dass der Ziel-Node zur Rückgabe mit dem bereit ist `storage failover show` Befehl.
. Geben Sie nur die CFO-Aggregate mit dem zurück `storage failover giveback -fromnode local -only-cfo-aggregates true` Befehl.
+
** Wenn der Befehl aufgrund eines ausgefallenen Laufwerks ausfällt, setzen Sie die ausgefallene Festplatte physisch aus, lassen Sie sie aber in den Steckplatz, bis ein Austausch erfolgt.
** Wenn der Befehl aufgrund einer offenen CIFS-Sitzung nicht erfolgreich ausgeführt wird, informieren Sie sich beim Kunden, wie CIFS-Sitzungen abgeschlossen werden können.
+

NOTE: Die Beendigung von CIFS kann zu Datenverlust führen.

** Wenn der Befehl fehlschlägt, weil der Partner „nicht bereit“ ist, warten Sie 5 Minuten, bis die NVRAMs synchronisiert wurden.
** Wenn der Befehl aufgrund eines NDMP-, SnapMirror- oder SnapVault-Prozesses ausfällt, deaktivieren Sie den Prozess. Weitere Informationen finden Sie in den entsprechenden Inhalten.


. Sobald die Rückgabe abgeschlossen ist, überprüfen Sie den Failover- und Giveback-Status mit `storage failover show` Und Befehle zur Anzeige von Storage Failover.
+
Es werden nur die CFO-Aggregate (Root-Aggregate und Daten-Aggregate im CFO-Stil) angezeigt.

. Wenn Sie ONTAP 9.6 oder höher verwenden, führen Sie die integrierte Synchronisierung des Security Key-Managers aus:
+
.. Führen Sie die aus `security key-manager onboard sync` Geben Sie bei der entsprechenden Aufforderung die Passphrase ein.
.. Geben Sie das ein `security key-manager key-query` Befehl zum Anzeigen einer detaillierten Ansicht aller im Onboard-Schlüsselmanager gespeicherten Schlüssel und zur Überprüfung des s `Restored` Spalte = `yes/true` Für alle Authentifizierungsschlüssel.
+

NOTE: Wenn der `Restored` Spalte = nichts anderes als `yes/true`, Wenden Sie sich an den Kundendienst.

.. Warten Sie 10 Minuten, bis der Schlüssel über das Cluster synchronisiert wird.


. Verschieben Sie das Konsolenkabel auf den Partner-Node.
. Geben Sie den Ziel-Node mithilfe des zurück `storage failover giveback -fromnode local` Befehl.
. Überprüfen Sie den Giveback-Status, drei Minuten nachdem Berichte abgeschlossen wurden, mithilfe des `storage failover show` Befehl.
+
Falls das Giveback nach 20 Minuten nicht abgeschlossen ist, wenden Sie sich an den Kundendienst.

. Geben Sie an der Clustershell-Eingabeaufforderung den ein `net int show -is-home false` Befehl zum Auflisten der logischen Schnittstellen, die sich nicht auf ihrem Home-Node und Port befinden.
+
Wenn Schnittstellen als aufgeführt werden `false`, Zurücksetzen dieser Schnittstellen zurück zu ihrem Home-Port mit dem `net int revert` Befehl.

. Bewegen Sie das Konsolenkabel auf den Zielknoten, und führen Sie den aus `version -v` Befehl zum Prüfen der ONTAP-Versionen.
. Stellen Sie die automatische Rückgabe wieder her, wenn Sie die Funktion mithilfe von deaktivieren `storage failover modify -node local -auto-giveback true` Befehl.




== Stellen Sie NSE/NVE auf Systemen mit ONTAP 9.6 und höher wieder her

. Verbinden Sie das Konsolenkabel mit dem Ziel-Node.
. Verwenden Sie die `boot_ontap` Befehl an der LOADER-Eingabeaufforderung zum Booten des Node.
. Überprüfen Sie die Konsolenausgabe:
+
[cols="1,2"]
|===
| Wenn die Konsole angezeigt wird... | Dann... 


 a| 
Die Eingabeaufforderung für die Anmeldung
 a| 
Fahren Sie mit Schritt 7 fort.



 a| 
Warten auf Giveback...
 a| 
.. Melden Sie sich beim Partner-Node an.
.. Vergewissern Sie sich, dass der Ziel-Node zur Rückgabe mit dem bereit ist `storage failover show` Befehl.


|===
. Verschieben Sie das Konsolenkabel auf den Partner-Node und geben Sie den Ziel-Node-Storage mithilfe des zurück `storage failover giveback -fromnode local -only-cfo-aggregates true local` Befehl.
+
** Wenn der Befehl aufgrund eines ausgefallenen Laufwerks ausfällt, setzen Sie die ausgefallene Festplatte physisch aus, lassen Sie sie aber in den Steckplatz, bis ein Austausch erfolgt.
** Wenn der Befehl aufgrund von offenen CIFS-Sitzungen ausfällt, wenden Sie sich an den Kunden, wie CIFS-Sitzungen abgeschlossen werden können.
+

NOTE: Die Beendigung von CIFS kann zu Datenverlust führen.

** Wenn der Befehl fehlschlägt, weil der Partner "nicht bereit" ist, warten Sie 5 Minuten, bis die NVMEMs synchronisieren.
** Wenn der Befehl aufgrund eines NDMP-, SnapMirror- oder SnapVault-Prozesses ausfällt, deaktivieren Sie den Prozess. Weitere Informationen finden Sie in den entsprechenden Inhalten.


. Warten Sie 3 Minuten, und überprüfen Sie den Failover-Status mit `storage failover show` Befehl.
. Geben Sie an der Clustershell-Eingabeaufforderung den ein `net int show -is-home false` Befehl zum Auflisten der logischen Schnittstellen, die sich nicht auf ihrem Home-Node und Port befinden.
+
Wenn Schnittstellen als aufgeführt werden `false`, Zurücksetzen dieser Schnittstellen zurück zu ihrem Home-Port mit dem `net int revert` Befehl.

. Bewegen Sie das Konsolenkabel auf den Zielknoten, und führen Sie den aus `version -v` Befehl zum Prüfen der ONTAP-Versionen.
. Stellen Sie die automatische Rückgabe wieder her, wenn Sie die Funktion mithilfe von deaktivieren `storage failover modify -node local -auto-giveback true` Befehl.
. Verwenden Sie die `storage encryption disk show` An der clustershell-Eingabeaufforderung zur Überprüfung der Ausgabe.
. Verwenden Sie die `security key-manager key-query` Befehl zum Anzeigen der Verschlüsselung und Authentifizierungsschlüssel, die auf den Verschlüsselungsmanagement-Servern gespeichert sind.
+
** Wenn der `Restored` Spalte = `yes/true`, Sie sind fertig und können den Austauschprozess abschließen.
** Wenn der `Key Manager type` = `external` Und das `Restored` Spalte = nichts anderes als `yes/true`, Verwenden Sie die `security key-manager external restore` Befehl zum Wiederherstellen der Schlüssel-IDs der Authentifizierungsschlüssel.
+

NOTE: Falls der Befehl fehlschlägt, wenden Sie sich an den Kundendienst.

** Wenn der `Key Manager type` = `onboard` Und das `Restored` Spalte = nichts anderes als `yes/true`, Verwenden Sie die `security key-manager onboard sync` Befehl zum erneuten Synchronisieren des Key Manager-Typs.
+
Verwenden Sie die `security key-manager key-query` Befehl zum Überprüfen des `Restored` Spalte = `yes/true` Für alle Authentifizierungsschlüssel.



. Schließen Sie das Konsolenkabel an den Partner-Node an.
. Geben Sie den Node mithilfe des zurück `storage failover giveback -fromnode local` Befehl.
. Stellen Sie die automatische Rückgabe wieder her, wenn Sie die Funktion mithilfe von deaktivieren `storage failover modify -node local -auto-giveback true` Befehl.

