---
permalink: fas9500/chassis_replace_complete_system_restore_rma.html 
sidebar: sidebar 
keywords: aff fas9500, verify and set HA state, complete the replacement process 
summary: Sie müssen den HA-Status des Gehäuses überprüfen und das fehlerhafte Teil an NetApp zurücksenden, wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben. 
---
= Den Chassis-Austausch für ein FAS9500 System abschließen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Chassis-Austausch in Ihrem FAS9500-System abzuschließen, müssen der HA-Status des Chassis überprüft und eingestellt, das System wieder in Betrieb genommen und das defekte Chassis an NetApp zurückgesendet werden, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben.



[[step-1-verify-and-set-the-ha-state-of-the-chassis]]
== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest: `ha-config modify chassis _ha-state_`
+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
*** Hochverfügbarkeit
*** Ohne Hochverfügbarkeit




. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`
. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.




[[step-2-bring-up-the-system]]
== Schritt 2: Das System hochfahren

. Wenn Sie dies nicht getan haben, schließen Sie die Netzkabel wieder an die Netzteile an.
. Die Netzteile werden eingeschaltet, indem der Kippschalter auf *EIN* gestellt wird, anschließend ist abzuwarten, bis die Controller vollständig hochgefahren sind.
. Überprüfen Sie nach dem Einschalten die Vorder- und Rückseite des Chassis und der Controller auf Fehler-LEDs.
. Stellen Sie über SSH eine Verbindung zur SP- oder BMC-IP-Adresse der Knoten her. Dies ist dieselbe Adresse, die zum Herunterfahren der Knoten verwendet wird.
. Führen Sie zusätzliche Zustandsprüfungen durch, wie in beschrieben https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Wie_ein_Cluster_Health_Check_with_a_script_in_ONTAP_durchführen"^]
. Schalten Sie AutoSupport wieder ein (beenden Sie die Meldung zum Wartungsfenster):
`system node autosupport invoke -node * -type all -message MAINT=end`


[]
====

NOTE: Als Best Practice sollten Sie Folgendes tun:

* Lösen Sie alle https://activeiq.netapp.com/["Active IQ Wellness-Alarme und Risiken"^] (Active IQ nimmt Zeit in Anspruch, um Autosupports nach dem Einschalten zu verarbeiten - erwarten Sie eine Verzögerung der Ergebnisse)
* Laufen https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* Überprüfen Sie den Systemzustand mit https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Wie_ein_Cluster_Health_Check_with_a_script_in_ONTAP_durchführen"^]


====


[[step-3-return-the-failed-part-to-netapp]]
== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
