---
permalink: fas9500/chassis_replace_overview.html 
sidebar: sidebar 
keywords: fas9500, replace the chassis 
summary: Zum Austausch des Gehäuses müssen Sie die Netzteile, Lüfter, Controller-Module, E/A-Module, DCPM-Module und das USB-LED-Modul aus dem defekten Gehäuse ausbauen und in das Ersatzgehäuse einbauen. 
---
= Anforderungen sollten vor dem Austausch des Chassis in einem FAS9500 System geprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Austauschen des Gehäuses müssen Sie die Netzteile, Lüfter, Controller-Module, I/O-Module, DCPM-Module entfernen. Und USB-LED-Modul aus dem beeinträchtigten Gehäuse, entfernen Sie das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank, installieren Sie das Ersatzgehäuse an seiner Stelle und installieren Sie dann die Komponenten im Ersatzgehäuse.

.Bevor Sie beginnen
Alle anderen Systemkomponenten müssen ordnungsgemäß funktionieren; falls dies nicht der Fall ist, sollte der technische Support kontaktiert werden.

.Über diese Aufgabe
* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Dieses Verfahren ist mit Störungen verbunden. Bei einem Zwei-Node-Cluster kommt es zu einem vollständigen Dienstausfall und bei einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall.

