---
permalink: fas9500/controller_replace_overview.html 
sidebar: sidebar 
keywords: FAS9500 
summary: Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen. 
---
= Anforderungen sollten vor dem Austausch des Controllers in einem FAS9500 System geprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um das beeinträchtigte Controller-Modul auszutauschen, müssen Sie den beeinträchtigten Controller herunterfahren, die internen Komponenten in das Ersatzcontrollermodul verschieben, das Ersatzcontrollermodul installieren und den Ersatz-Controller neu starten.

.Bevor Sie beginnen
Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Wenn Ihr System über eine V_StorageAttach-Lizenz verfügt, müssen Sie vor dem Ausführen dieses Verfahrens die zusätzlich erforderlichen Schritte beachten.
* Wenn sich Ihr System in einem HA-Paar befindet, muss der gesunde Knoten den Knoten übernehmen können, der ersetzt wird (in diesem Verfahren wird „`beeinträchtigter Knoten`“ genannt).
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie den Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"^] Um zu bestimmen, ob Sie dieses Verfahren verwenden sollten.
+
Beachten Sie, dass das Verfahren zum Austausch des Controllers bei einem Node in einer MetroCluster Konfiguration mit vier oder acht Nodes mit dem bei einem HA-Paar identisch ist. Es sind keine MetroCluster-spezifischen Schritte erforderlich, da der Ausfall auf ein HA-Paar beschränkt ist und Storage Failover-Befehle zur unterbrechungsfreien Ausführung während des Austauschs genutzt werden können.

* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Sie müssen ein Controller-Modul durch ein Controller-Modul desselben Modelltyps ersetzen. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* Bei diesem Verfahren wird das Boot-Gerät vom defekten Node auf den Ersatz-Node verschoben, sodass der Ersatz-Node in derselben Version von ONTAP wie das alte Controller-Modul startet.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Der Knoten „beeinträchtigt“ ist der Knoten, der ersetzt wird.
** Der Ersatzknoten ist der neue Knoten, der den beeinträchtigten Knoten ersetzt.
** Der intakten Node ist der noch intakten Node.



