---
permalink: fas9500/controller_replace_complete_system_restoration_rma.html 
sidebar: sidebar 
keywords: fas9500, complete the replacement process 
summary: 'Um den Ersatzvorgang abzuschließen und den Betrieb des Systems wiederherzustellen, müssen Sie den Storage erneut herstellen, die NetApp Storage Encryption Konfiguration (falls erforderlich) wiederherstellen und die Lizenzen für den neuen Controller installieren.' 
---
= Vollständige Systemwiederherstellung - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Ersatzvorgang abzuschließen und den Betrieb des Systems wiederherzustellen, müssen Sie den Storage erneut herstellen, die NetApp Storage Encryption Konfiguration (falls erforderlich) wiederherstellen und die Lizenzen für den neuen Controller installieren. Vor der Wiederherstellung des Systembetriebs müssen Sie eine Reihe von Aufgaben ausführen.



[[step-1-install-licenses-for-the-replacement-node-in-ontap]]
== Schritt: Lizenzen für den Ersatz-Node in ONTAP installieren

Sie müssen neue Lizenzen für den Node _Replacement_ installieren, wenn der beeinträchtigte Knoten ONTAP-Funktionen verwendete, die eine Standard-Lizenz (Node-locked) erfordern. Bei Standardlizenzen sollte jeder Node im Cluster über seinen eigenen Schlüssel für die Funktion verfügen.

.Bevor Sie beginnen
Wenn auf Ihrem System zunächst ONTAP 9.10.1 oder höher ausgeführt wurde, gehen Sie wie in beschrieben  https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system#Internal_Notes^["Post-Motherboard-Austauschprozess zur Aktualisierung der Lizenzierung auf ONTAP-Plattformen"]vor. Wenn Sie sich nicht sicher sind, wie die erste ONTAP-Version für Ihr System ist, finden Sie weitere Informationen unterlink:https://hwu.netapp.com["NetApp Hardware Universe"^].

.Über diese Aufgabe
* Bis Sie Lizenzschlüssel installieren, sind Funktionen, für die Standardlizenzen erforderlich sind, weiterhin für den Node _Replacement_ verfügbar. Wenn der beeinträchtigte Knoten jedoch der einzige Node im Cluster war, der eine Lizenz für die Funktion besitzt, sind keine Konfigurationsänderungen an der Funktion zulässig.
+
Durch die Verwendung nicht lizenzierter Funktionen auf dem Knoten können Sie möglicherweise nicht mit Ihrer Lizenzvereinbarung einverstanden sein. Sie sollten daher den Ersatzlizenzschlüssel oder die Schlüssel so schnell wie möglich auf dem Node _Replacement_ installieren.

* Die Lizenzschlüssel müssen im 28-stelligen Format vorliegen.
* Sie haben eine 90-Tage-Nachfrist zur Installation der Lizenzschlüssel. Nach Ablauf der Frist werden alle alten Lizenzen ungültig. Nachdem ein gültiger Lizenzschlüssel installiert wurde, haben Sie 24 Stunden Zeit, um alle Schlüssel zu installieren, bevor die Kulanzzeit endet.
* Wenn sich der Node in einer MetroCluster-Konfiguration befindet und alle Nodes an einem Standort ersetzt wurden, müssen vor dem Wechsel die Lizenzschlüssel auf dem Node _Replacement_ oder den Nodes installiert werden.


.Schritte
. Wenn Sie neue Lizenzschlüssel benötigen, holen Sie sich die Ersatzlizenz auf dem https://mysupport.netapp.com/site/global/dashboard["NetApp Support Website"] Im Abschnitt „My Support“ unter „Software-Lizenzen“.
+

NOTE: Die neuen Lizenzschlüssel, die Sie benötigen, werden automatisch generiert und an die E-Mail-Adresse in der Datei gesendet. Wenn Sie die E-Mail mit den Lizenzschlüssel nicht innerhalb von 30 Tagen erhalten, sollten Sie sich an den technischen Support wenden.

. Installieren Sie jeden Lizenzschlüssel: `+system license add -license-code license-key, license-key...+`
. Entfernen Sie ggf. die alten Lizenzen:
+
.. Suchen Sie nach nicht verwendeten Lizenzen: `license clean-up -unused -simulate`
.. Wenn die Liste korrekt aussieht, entfernen Sie die nicht verwendeten Lizenzen: `license clean-up -unused`






[[step-2-verify-lifs-and-registering-the-serial-number]]
== Schritt: LIFs überprüfen und Seriennummer registrieren

Bevor Sie den _Ersatzknoten_ wieder in Betrieb nehmen, sollten Sie überprüfen, ob sich die LIFs an ihren Home-Ports befinden, und die Seriennummer des _Ersatzknotens_ registrieren, falls AutoSupport aktiviert ist, den Zustand Ihres Clusters überprüfen, alle Wartungsfenster schließen und die automatische Rückgabe zurücksetzen.

.Schritte
. Vergewissern Sie sich, dass die logischen Schnittstellen ihrem Home-Server und ihren Ports Berichterstellung: `network interface show -is-home false`
+
Wenn eine der LIFs als falsch aufgeführt ist, stellen Sie sie auf ihre Home-Ports zurück: `network interface revert -vserver * -lif *`

. Registrieren Sie die Seriennummer des Systems beim NetApp Support.
+
** Wenn AutoSupport aktiviert ist, senden Sie eine AutoSupport Nachricht, um die Seriennummer zu registrieren.
** Wenn AutoSupport nicht aktiviert ist, rufen Sie an https://mysupport.netapp.com["NetApp Support"] Um die Seriennummer zu registrieren.


. Überprüfen Sie den Zustand Ihres Clusters. Weitere Informationen finden Sie im https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["So führen Sie eine Cluster-Integritätsprüfung mit einem Skript in ONTAP durch"^] KB-Artikel.
. Wenn ein AutoSupport-Wartungsfenster ausgelöst wurde, beenden Sie das Fenster mit. Verwenden Sie dazu die `system node autosupport invoke -node * -type all -message MAINT=END` Befehl.
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`




[[step-3-return-the-failed-part-to-netapp]]
== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
