---
permalink: fas9500/controller_replace_recable_reassign_disks.html 
sidebar: sidebar 
keywords: fas9500, recable the system, reassign disks 
summary: Verkabeln Sie das System neu und ordnen Sie die Festplatten neu zu. 
---
= Der Controller in Ihrem FAS9500 System wird zurückgegeben, damit der normale Betrieb fortgesetzt werden kann.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Kontrolle über die Speicherressourcen wird an den Ersatzcontroller zurückgegeben, sodass Ihr FAS9500 System den normalen Betrieb wieder aufnehmen kann.



[[step-1-recable-the-system]]
== Schritt 1: Das System erneut einsetzen

Sie müssen die Speicher- und Netzwerkverbindungen des Controller-Moduls neu aufbauen.

.Schritte
. Das System neu aufführen.
. Überprüfen Sie anhand von, ob die Verkabelung korrekt ist https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
.. Laden Sie Config Advisor herunter und installieren Sie es.
.. Geben Sie die Informationen für das Zielsystem ein und wählen Sie dann „Daten sammeln“ aus.
.. Wählen Sie die Registerkarte „Verkabelung“ aus und prüfen Sie die Ausgabe. Es sollte sichergestellt sein, dass alle Festplattengehäuse angezeigt werden und alle Festplatten in der Ausgabe erscheinen, wobei etwaige festgestellte Verkabelungsprobleme zu korrigieren sind.
.. Die übrige Verkabelung lässt sich über die entsprechende Registerkarte und die anschließende Prüfung der Ausgabe von Config Advisor überprüfen.





NOTE: Die System-ID und die Informationen zur Festplattenzuordnung befinden sich im NVRAM Modul, das sich in einem Modul getrennt vom Controller Modul befindet und von einem Austausch des Controller Moduls nicht betroffen ist.



[[step-2-reassign-disks]]
== Schritt 2: Festplatten neu zuweisen

Befindet sich das Speichersystem in einem HA-Paar, wird die System-ID des neuen Controller-Moduls den Festplatten automatisch zugewiesen, sobald die Rückgabe am Ende des Vorgangs erfolgt. Die Änderung der System-ID muss beim Booten des _replacement_ Node bestätigt und anschließend überprüft werden, ob die Änderung korrekt ist.

Diese Vorgehensweise gilt nur für Systeme, auf denen ONTAP in einem HA-Paar ausgeführt wird.

. Wenn sich der Node _Replacement_ im Wartungsmodus befindet (zeigt das an `*>` Eingabeaufforderung), beenden Sie den Wartungsmodus und gehen Sie zur LOADER-Eingabeaufforderung: `halt`
. Vom LOADER-Prompt auf dem _Ersatzknoten_ den Knoten starten und  `y` eingeben, falls Sie aufgrund einer System-ID-Diskrepanz zur Überschreibung der System-ID aufgefordert werden: `boot_ontap`
. Warten Sie, bis der `Waiting for giveback...` Die Meldung wird auf der Konsole „_Replacement_“ angezeigt. Überprüfen Sie dann vom gesunden Node, ob die neue Partner-System-ID automatisch zugewiesen wurde: Storage Failover show
+
In der Befehlsausgabe sollte eine Meldung angezeigt werden, dass sich die System-ID auf dem Knoten „beeinträchtigt“ geändert hat und die korrekten alten und neuen IDs angezeigt werden. Im folgenden Beispiel wurde node2 ersetzt und hat eine neue System-ID von 151759706.

+
[listing]
----
node1> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Vergewissern Sie sich am gesunden Knoten, dass alle Corestapy gespeichert sind:
+
.. Ändern Sie die erweiterte Berechtigungsebene: `set -privilege advanced`
+
Sie können antworten `Y` Wenn Sie aufgefordert werden, den erweiterten Modus fortzusetzen. Die Eingabeaufforderung für den erweiterten Modus wird angezeigt (*>).

.. Speichern von CoreDumps: `system node run -node _local-node-name_ partner savecore`
.. Warten Sie, bis der Befehl savecore abgeschlossen ist, bevor Sie das Giveback ausgeben.
+
Sie können den folgenden Befehl eingeben, um den Fortschritt des Befehls savecore zu überwachen: `system node run -node _local-node-name_ partner savecore -s`

.. Zurück zur Administratorberechtigungsebene: `set -privilege admin`


. Wenn Ihr Storage- oder Volume Encryption-System konfiguriert ist, müssen Sie die Funktionen für Storage oder Volume Encryption mithilfe eines der folgenden Verfahren wiederherstellen: Je nachdem, ob Sie integriertes oder externes Verschlüsselungsmanagement verwenden:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Wiederherstellung der integrierten Verschlüsselungsschlüssel für das Verschlüsselungsmanagement"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Wiederherstellung der externen Verschlüsselungsschlüssel für das Verschlüsselungsmanagement"^]


. Geben Sie den Knoten zurück:
+
.. Geben Sie vom ordnungsgemäßen Node den Speicher des ersetzten Node wieder: `storage failover giveback -ofnode _replacement_node_name_`
+
Der Node _Replacement_ nimmt seinen Storage wieder ein und schließt den Booten ab.

+
Wenn Sie aufgrund einer nicht übereinstimmenden System-ID aufgefordert werden, die System-ID außer Kraft zu setzen, sollten Sie eingeben `y`.

+

NOTE: Wenn das Rückübertragung ein Vetorecht ist, können Sie erwägen, das Vetos außer Kraft zu setzen.

+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted["Manuelle Giveback-Befehle"^] Thema, um das Veto zu überschreiben.

.. Nach Abschluss des Giveback bestätigen, dass das HA-Paar sich stabil befindet und ein Takeover möglich ist: Storage Failover Show
+
Die Ausgabe von der `storage failover show` Befehl sollte nicht die in der Partnernachricht geänderte System-ID enthalten.



. Überprüfen Sie, ob die Festplatten ordnungsgemäß zugewiesen wurden: `storage disk show -ownership`
+
Die Festplatten, die zum Node _Replacement_ gehören, sollten die neue System-ID anzeigen. Im folgenden Beispiel zeigen die Festplatten von node1 jetzt die neue System-ID, 1873775277:

+
[listing]
----
node1> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Wenn sich das System in einer MetroCluster-Konfiguration befindet, überwachen Sie den Status des Node: `metrocluster node show`
+
Die MetroCluster-Konfiguration dauert einige Minuten nach dem Austausch und kehrt in den normalen Zustand zurück. Zu diesem Zeitpunkt zeigt jeder Node einen konfigurierten Status mit aktivierter DR-Spiegelung und einem normalen Modus. Der `metrocluster node show -fields node-systemid` In der Befehlsausgabe wird die alte System-ID angezeigt, bis die MetroCluster-Konfiguration den normalen Status aufweist.

. Wenn sich der Node abhängig vom MetroCluster-Status in einer MetroCluster-Konfiguration befindet, vergewissern Sie sich, dass im Feld für die DR-Home-ID der ursprüngliche Eigentümer der Festplatte angezeigt wird, wenn der ursprüngliche Eigentümer ein Node am Disaster-Standort ist.
+
Dies ist erforderlich, wenn beide der folgenden Werte erfüllt sind:

+
** Die MetroCluster Konfiguration befindet sich in einem Switchover-Zustand.
** Der Node _Replacement_ ist der aktuelle Besitzer der Festplatten am Disaster-Site.
+
Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Änderungen am Festplattenbesitz während HA Takeover und MetroCluster Switchover in einer MetroCluster Konfiguration mit vier Nodes"^] Thema:



. Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, vergewissern Sie sich, dass jeder Node konfiguriert ist: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Vergewissern Sie sich, dass die erwarteten Volumes für jeden Node vorhanden sind: `vol show -node node-name`
. Wenn Sie die automatische Übernahme beim Neustart deaktiviert haben, aktivieren Sie sie vom gesunden Knoten: `storage failover modify -node replacement-node-name -onreboot true`

