---
permalink: fas9500/maintain-overview.html 
sidebar: sidebar 
keywords: FAS9500 maintenance, maintenance, repairing FAS9500, repairing aff FAS9500, replace FAS9500 components, replace FAS9500 components 
summary: Wartung der FAS9500 Hardware 
---
= Wartung der FAS9500 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Warten Sie die Hardware Ihres FAS9500 Speichersystems, um langfristige Zuverlässigkeit und optimale Leistung sicherzustellen. Führen Sie regelmäßige Wartungsarbeiten durch, z. B. den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden.

Bei den Wartungsverfahren wird davon ausgegangen, dass das FAS9500 Speichersystem bereits als Speicherknoten in der ONTAP Umgebung bereitgestellt wurde.



== Systemkomponenten

Für das FAS9500-Speichersystem können Sie Wartungsverfahren für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem zum Booten verwendet.  Während der automatischen Wiederherstellung ruft das System das Boot-Image vom Partnerknoten ab und führt automatisch die entsprechende Boot-Menüoption aus, um das Image auf Ihrem Ersatz-Boot-Medium zu installieren. Die automatische Wiederherstellung des Bootmediums wird nur in ONTAP 9.17.1 und höher unterstützt. Wenn Ihr Speichersystem eine frühere Version von ONTAP verwendet, verwenden Sie die link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] .



 a| 
link:bootmedia-replace-workflow.html["Bootmedium - manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem zum Booten verwendet. Bei der manuellen Wiederherstellung starten Sie das Speichersystem von einem USB-Laufwerk und stellen das Dateisystem-Image und die Konfiguration manuell wieder her.  Wenn Ihr Speichersystem ONTAP 9.17.1 oder höher ausführt, verwenden Sie dielink:bootmedia-replace-workflow-bmr.html["automatisiertes Boot-Wiederherstellungsverfahren"] .



 a| 
link:caching_module_hot_swap.html["Caching-Modul"]
 a| 
Sie müssen das Caching-Modul des Controllers ersetzen, wenn Ihr System eine einzelne AutoSupport-Meldung (ASUP) registriert, dass das Modul offline gegangen ist.



 a| 
link:chassis_replace_overview.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller_replace_overview.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



 a| 
link:dimm_replace.html["DIMM"]
 a| 
Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



 a| 
link:dcpm-nvram11-battery-replace.html["DFPM"]
 a| 
Die DCPM (Controller-Stromversorgungsmodul der Auslagerung) enthält die NVRAM11-Batterie.



 a| 
link:fan_swap_out.html["Ventilator"]
 a| 
Der Lüfter kühlt den Controller.



 a| 
link:pci_cards_and_risers_replace.html["I/O-Modul"]
 a| 
Das E/A-Modul (Eingangs-/Ausgangsmodul) ist eine Hardwarekomponente, die als Vermittler zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.



 a| 
link:led_module_replace.html["LED USB"]
 a| 
Das USB-LED-Modul stellt Verbindungen zu Konsolenports und Systemstatus bereit.



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
Das NVRAM Modul (Non-Volatile Random Access Memory) ermöglicht es dem Controller, Daten über Stromzyklen oder Systemneustarts hinweg beizubehalten, während das NVRAM DIMM die NVRAM Einstellungen beibehält.



 a| 
link:power_supply_swap_out.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromquelle in einem Controller bereit.



 a| 
link:rtc_battery_replace.html["Akku in Echtzeit"]
 a| 
Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.

|===