---
permalink: fas9500/rtc_battery_replace.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Ersetzen Sie den Echtzeitakku FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie ersetzen den Echtzeituhr-Akku (RTC) im Controller-Modul, sodass die Dienste und Anwendungen Ihres Systems, die von der genauen Zeitsynchronisierung abhängen, weiterhin funktionieren.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden
* Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.




== Schritt 1: Fahren Sie den Knoten mit beeinträchtigten Knoten herunter

Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Über diese Aufgabe
* Wenn Sie NetApp Storage Encryption verwenden, müssen Sie die MSID mithilfe der Anweisungen im zurückgesetzt haben link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["SEDs werden in den ungeschützten Modus versetzt"].
* Wenn Sie über ein SAN-System verfügen, müssen Sie Ereignismeldungen geprüft haben  `cluster kernel-service show`) Für beeinträchtigte Controller SCSI-Blade. Der `cluster kernel-service show` Der Befehl zeigt den Node-Namen, den Quorum-Status dieses Node, den Verfügbarkeitsstatus dieses Node und den Betriebsstatus dieses Node an.
+
Jeder Prozess des SCSI-Blades sollte sich im Quorum mit den anderen Nodes im Cluster befinden. Probleme müssen behoben werden, bevor Sie mit dem Austausch fortfahren.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
+

NOTE: Wenn Sie sehen _Möchten Sie Auto-Giveback deaktivieren?_, geben Sie ein `y`.

. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung für das System oder Passwort
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===




== Schritt 2: Entfernen Sie die Steuerung

Um auf Komponenten innerhalb des Controllers zuzugreifen, müssen Sie zuerst das Controller-Modul aus dem System entfernen und dann die Abdeckung am Controller-Modul entfernen.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Ziehen Sie die Kabel vom beeinträchtigten Controller-Modul ab, und verfolgen Sie, wo die Kabel angeschlossen waren.
. Schieben Sie die Terrakotta-Taste am Nockengriff nach unten, bis sie entsperrt wird.
+
.Animation - Controller-Modul entfernen
video::5e029a19-8acc-4fa1-be5d-ae78004b365a[panopto]
+
image::../media/drw_9500_remove_PCM.svg[drw 9500 PCM entfernen]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[Legende Symbol 01]
 a| 
Freigabetaste für den CAM-Griff



 a| 
image::../media/legend_icon_02.svg[Legende Symbol 02]
 a| 
CAM-Griff

|===
. Drehen Sie den Nockengriff so, dass er das Controller-Modul vollständig aus dem Gehäuse herausrückt, und schieben Sie dann das Controller-Modul aus dem Gehäuse.
+
Stellen Sie sicher, dass Sie die Unterseite des Controller-Moduls unterstützen, während Sie es aus dem Gehäuse schieben.

. Setzen Sie die Abdeckung des Controller-Moduls auf eine stabile, flache Oberfläche, drücken Sie die blaue Taste auf der Abdeckung, schieben Sie die Abdeckung auf die Rückseite des Controller-Moduls, und schwenken Sie sie dann nach oben und heben Sie sie vom Controller-Modul ab.


image::../media/drw_9500_PCM_open.svg[drw 9500 PCM offen]

[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[Legende Symbol 01]
 a| 
Verriegelungstaste für die Controllermodulabdeckung

|===


== Schritt 3: Ersetzen Sie die RTC-Batterie

Zum Austauschen der RTC-Batterie müssen Sie den defekten Akku im Controller-Modul suchen, ihn aus dem Halter entfernen und dann den Ersatzakku in den Halter einsetzen.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Suchen Sie den RTC-Akku.
+
.Animation - Ersetzen des RTC-Akkus
video::3b977f96-3ebb-4b11-9703-ae78004b4add[panopto]
+
image::../media/drw_9500_remove_RTC_battery.svg[drw 9500 die RTC-Batterie ausbauen]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[Legende Symbol 01]
 a| 
Batterie nach oben drehen



 a| 
image::../media/legend_icon_02.svg[Legende Symbol 02]
 a| 
Schieben Sie die Batterie aus dem Gehäuse heraus

|===
. Schieben Sie den Akku vorsichtig von der Halterung weg, drehen Sie ihn vom Halter weg, und heben Sie ihn dann aus der Halterung.
+

NOTE: Beachten Sie die Polarität der Batterie, während Sie sie aus dem Halter entfernen. Der Akku ist mit einem Pluszeichen gekennzeichnet und muss korrekt in der Halterung positioniert werden. Ein Pluszeichen in der Nähe des Halters zeigt an, wie der Akku positioniert werden soll.

. Entfernen Sie den Ersatzakku aus dem antistatischen Versandbeutel.
. Suchen Sie den leeren Batteriehalter im Controller-Modul.
. Notieren Sie die Polarität der RTC-Batterie, und setzen Sie sie anschließend in den Halter ein, indem Sie die Batterie schräg kippen und nach unten drücken.
. Überprüfen Sie die Batterie visuell, um sicherzustellen, dass sie vollständig in den Halter eingebaut ist und die Polarität korrekt ist.
. Bringen Sie die Abdeckung des Controller-Moduls wieder an.




== Schritt 4: Installieren Sie das Controller-Modul neu und stellen Sie Uhrzeit/Datum ein

Nachdem Sie den RTC-Akku ersetzt haben, müssen Sie das Controller-Modul neu installieren. Wenn der RTC-Akku länger als 10 Minuten aus dem Controller-Modul entfernt wurde, müssen Sie die Uhrzeit und das Datum möglicherweise zurücksetzen.

. Wenn Sie dies noch nicht getan haben, schließen Sie den Luftkanal oder die Abdeckung des Controller-Moduls.
. Richten Sie das Ende des Controller-Moduls an der Öffnung im Gehäuse aus, und drücken Sie dann vorsichtig das Controller-Modul zur Hälfte in das System.
+
Setzen Sie das Controller-Modul erst dann vollständig in das Chassis ein, wenn Sie dazu aufgefordert werden.

. Das System nach Bedarf neu einsetzen.
+
Wenn Sie die Medienkonverter (QSFPs oder SFPs) entfernt haben, sollten Sie diese erneut installieren, wenn Sie Glasfaserkabel verwenden.

. Wenn die Netzteile nicht angeschlossen waren, schließen Sie sie wieder an, und setzen Sie die Netzkabelhalter wieder ein.
. Führen Sie die Neuinstallation des Controller-Moduls durch:
+
.. Schieben Sie das Steuermodul fest in die offene Position, bis es auf die Mittelebene trifft und vollständig sitzt, und schließen Sie dann den Nockengriff in die verriegelte Position.
+

IMPORTANT: Beim Einschieben des Controller-Moduls in das Gehäuse keine übermäßige Kraft verwenden, um Schäden an den Anschlüssen zu vermeiden.

.. Wenn Sie dies noch nicht getan haben, installieren Sie das Kabelverwaltungsgerät neu.
.. Verbinden Sie die Kabel mit dem Haken- und Schlaufenband mit dem Kabelmanagement-Gerät.
.. Schließen Sie die Stromkabel wieder an die Netzteile und an die Stromquellen an, und schalten Sie dann den Netzstrom ein, um den Bootvorgang zu starten.
.. Halten Sie den Controller an der LOADER-Eingabeaufforderung an.





NOTE: Wenn das System im Boot-Menü stoppt, wählen Sie die Option für „Node neu booten“ und antworten bei Aufforderung y. Starten Sie dann zum LOADER, indem Sie auf drücken `Ctrl-C`.

. Uhrzeit und Datum auf dem Controller zurücksetzen:
+
.. Überprüfen Sie Datum und Uhrzeit auf dem gesunden Knoten mit dem `show date` Befehl.
.. Überprüfen Sie an der LOADER-Eingabeaufforderung auf dem Ziel-Node die Uhrzeit und das Datum.
.. Ändern Sie bei Bedarf das Datum mit dem `set date mm/dd/yyyy` Befehl.
.. Stellen Sie bei Bedarf die Uhrzeit in GMT mithilfe des ein `set time hh:mm:ss` Befehl.
.. Bestätigen Sie Datum und Uhrzeit auf dem Ziel-Node.


. Geben Sie an der LOADER-Eingabeaufforderung ein `bye` Um die PCIe-Karten und andere Komponenten neu zu initialisieren und den Node neu zu booten.
. Wiederherstellung des normalen Betriebs des Node durch Zurückgeben des zugehörigen Speichers: `storage failover giveback -ofnode impaired_node_name`
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`




== Schritt 5: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://mysupport.netapp.com/site/info/rma["Teilerückgabe  Austausch"] Seite für weitere Informationen.
