---
permalink: fas2800/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas2820, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Um das Chassis in Ihrem FAS2820 System auszutauschen, müssen die Netzteile, Festplatten und das oder die Controller-Module vom defekten Chassis in das neue Chassis desselben Modells umgebaut werden. 
---
= Die Anforderungen für den Austausch eines Chassis in einem FAS2820 System werden dargestellt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Austausch des Gehäuses in Ihrem FAS2820 System werden die Netzteile, Festplatten und Controller-Module vom defekten Gehäuse in das neue Gehäuse umgesetzt. Anschließend wird das defekte Gehäuse aus dem Geräteschrank oder Systemschrank entfernt und das neue Gehäuse desselben Modells an dessen Stelle installiert.

Alle anderen Systemkomponenten müssen einwandfrei funktionieren. Falls dies nicht der Fall ist, sollte der technische Support kontaktiert werden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie alle Laufwerke und Controller-Module bzw. -Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieses Verfahren ist unterbrechend. Bei einem Cluster mit zwei Controllern verursacht dieses Verfahren einen vollständigen Dienstausfall, in einem Cluster mit mehreren Knoten einen teilweisen Ausfall.

