---
permalink: fas2800/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Verschieben Sie die Netzteile, Festplatten und Controller-Module oder -Module vom Gehäuse für beeinträchtigte Störungen in das Ersatzgehäuse, und ersetzen Sie das Gehäuse für beeinträchtigte Störungen aus dem Geräte-Rack oder Systemschrank durch das Ersatzgehäuse desselben Modells wie das Gehäuse für beeinträchtigte Störungen. 
---
= Verschieben und ersetzen Sie Hardware – FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verschieben Sie die Netzteile, Festplatten und Controller-Module oder -Module vom Gehäuse für beeinträchtigte Störungen in das Ersatzgehäuse, und ersetzen Sie das Gehäuse für beeinträchtigte Störungen aus dem Geräte-Rack oder Systemschrank durch das Ersatzgehäuse desselben Modells wie das Gehäuse für beeinträchtigte Störungen.



== Schritt 1: Ein Netzteil bewegen

Wenn Sie ein Netzteil entfernen, wenn Sie ein Gehäuse ersetzen, müssen Sie das Netzteil ausschalten, trennen und aus dem Gehäuse entfernen sowie es am Ersatzgehäuse installieren und anschließen.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Schalten Sie das Netzteil aus und trennen Sie die Netzkabel:
+
.. Schalten Sie den Netzschalter am Netzteil aus.
.. Öffnen Sie die Netzkabelhalterung, und ziehen Sie dann das Netzkabel vom Netzteil ab.
.. Ziehen Sie das Netzkabel von der Stromversorgung ab.


. Drücken Sie die Verriegelung am Handgriff der Stromversorgungs-Nockenwelle, und öffnen Sie dann den Nockengriff, um das Netzteil vollständig von der Mittelebene zu lösen.
. Schieben Sie die Stromversorgung mit dem Nockengriff aus dem System heraus.
+

CAUTION: Wenn Sie ein Netzteil entfernen, verwenden Sie immer zwei Hände, um sein Gewicht zu stützen.

. Wiederholen Sie die vorherigen Schritte für alle weiteren Netzteile.
. Halten und richten Sie die Kanten des Netzteils mit beiden Händen an der Öffnung im Systemgehäuse aus, und drücken Sie dann vorsichtig das Netzteil mithilfe des Nockengriffs in das Gehäuse.
+
Die Netzteile sind codiert und können nur auf eine Weise installiert werden.

+

NOTE: Beim Einschieben des Netzteils in das System keine übermäßige Kraft verwenden. Sie können den Anschluss beschädigen.

. Schließen Sie den Nockengriff, so dass die Verriegelung in die verriegelte Position einrastet und das Netzteil vollständig eingesetzt ist.
. Schließen Sie das Netzkabel wieder an, und befestigen Sie es mithilfe des Verriegelungsmechanismus für Netzkabel am Netzteil.
+

NOTE: Schließen Sie das Netzkabel nur an das Netzteil an. Schließen Sie das Netzkabel derzeit nicht an eine Stromquelle an.





== Schritt 2: Entfernen Sie das Controller-Modul

Entfernen Sie das oder die Controller-Module aus dem Gehäuse für beeinträchtigte Störungen.

. Lösen Sie den Haken- und Schlaufenriemen, mit dem die Kabel am Kabelführungsgerät befestigt sind, und ziehen Sie dann die Systemkabel und SFPs (falls erforderlich) vom Controller-Modul ab, um zu verfolgen, wo die Kabel angeschlossen waren.
+
Lassen Sie die Kabel im Kabelverwaltungs-Gerät so, dass bei der Neuinstallation des Kabelverwaltungsgeräts die Kabel organisiert sind.

. Entfernen Sie die Kabelführungsgeräte von der linken und rechten Seite des Controller-Moduls und stellen Sie sie zur Seite.
. Drücken Sie die Verriegelung am Nockengriff, bis sie loslässt, öffnen Sie den Nockengriff vollständig, um das Controller-Modul aus der Mittelplatine zu lösen, und ziehen Sie das Controller-Modul anschließend mit zwei Händen aus dem Gehäuse heraus.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[Entfernen Sie den Controller]

. Stellen Sie das Controller-Modul an einem sicheren Ort beiseite.
. Wiederholen Sie diese Schritte für das zweite Controller-Modul im Chassis.




== Schritt 3: Verschieben Sie Laufwerke in das Ersatzgehäuse

Verschieben Sie die Laufwerke aus den einzelnen Laufwerkschachtöffnungen im Gehäuse für beeinträchtigte Laufwerke in dieselbe Schachtöffnung im Ersatzgehäuse.

. Entfernen Sie vorsichtig die Blende von der Vorderseite des Systems.
. Entfernen Sie die Laufwerke:
+
.. Drücken Sie die Entriegelungstaste auf der gegenüberliegenden Seite der LEDs.
.. Ziehen Sie den Nockengriff in die vollständig geöffnete Position, um den Antrieb von der Mittelplatine zu lösen, und schieben Sie ihn dann vorsichtig aus dem Chassis heraus.
+
Das Laufwerk sollte aus dem Gehäuse heraus einrücken und so das Gehäuse frei schieben.

+

NOTE: Wenn Sie ein Laufwerk entfernen, verwenden Sie immer zwei Hände, um sein Gewicht zu stützen.

+

NOTE: Laufwerke sind zerbrechlich. Behandeln Sie sie so wenig wie möglich, um Schäden an ihnen zu vermeiden.



. Richten Sie das Laufwerk aus dem Gehäuse für beeinträchtigte Verbindung mit der gleichen Schachtöffnung im Ersatzgehäuse aus.
. Schieben Sie das Laufwerk vorsichtig so weit wie möglich in das Gehäuse.
+
Der Nockengriff rastet ein und beginnt sich in die geschlossene Position zu drehen.

. Schieben Sie den Antrieb ganz fest in das Gehäuse, und verriegeln Sie dann den Nockengriff, indem Sie ihn gegen den Antriebshalter drücken.
+
Schließen Sie den Nockengriff langsam, damit er korrekt an der Vorderseite des Laufwerkträgers ausgerichtet ist. Klicken Sie auf, wenn es sicher ist.

. Wiederholen Sie den Vorgang für die übrigen Laufwerke im System.




== Schritt 4: Ersetzen Sie ein Chassis aus dem Rack oder Systemschrank der Ausrüstung

Entfernen Sie das vorhandene Chassis aus dem Geräte-Rack oder Systemschrank und installieren Sie das Ersatzgehäuse im Geräte-Rack oder Systemschrank.

. Entfernen Sie die Schrauben von den Montagepunkten des Gehäuses.
. Schieben Sie mit Hilfe von zwei oder drei Personen das Gehäuse für beeinträchtigte Personen von den Rack-Schienen in einem Systemschrank oder _L_ Halterungen in einem Geräterahmen und legen Sie es dann beiseite.
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Installieren Sie das Ersatzgehäuse mithilfe von zwei oder drei Personen in das Rack oder den Systemschrank des Geräts, indem Sie das Chassis an die Rack-Schienen in einem Systemschrank oder _L_ -Halterungen in einem Rack führen.
. Schieben Sie das Chassis vollständig in das Rack oder den Systemschrank der Ausrüstung.
. Befestigen Sie die Vorderseite des Gehäuses mit den Schrauben, die Sie aus dem Gehäuse für beeinträchtigte Geräte entfernt haben, am Geräte-Rack oder Systemschrank.
. Falls noch nicht geschehen, befestigen Sie die Blende.




== Schritt 5: Installieren Sie den Controller

Installieren Sie das Controller-Modul und alle anderen Komponenten in das Ersatzgehäuse, und booten Sie es im Wartungsmodus.

Bei HA-Paaren mit zwei Controller-Modulen im selben Chassis ist die Sequenz, in der Sie das Controller-Modul installieren, besonders wichtig, da sie versucht, neu zu booten, sobald Sie es vollständig im Chassis einsetzen.

. Richten Sie das Ende des Controller-Moduls an der Öffnung im Gehäuse aus, und drücken Sie dann vorsichtig das Controller-Modul zur Hälfte in das System.
+

NOTE: Setzen Sie das Controller-Modul erst dann vollständig in das Chassis ein, wenn Sie dazu aufgefordert werden.

. Führen Sie die Konsole wieder mit dem Controller-Modul aus, und schließen Sie den Management-Port wieder an.
. Wiederholen Sie die vorherigen Schritte für den zweiten Controller im Ersatzgehäuse.
. Schließen Sie die Installation des Controller-Moduls ab:
+
.. Schieben Sie das Steuermodul fest in die offene Position, bis es auf die Mittelebene trifft und vollständig sitzt, und schließen Sie dann den Nockengriff in die verriegelte Position.
+

NOTE: Beim Einschieben des Controller-Moduls in das Gehäuse keine übermäßige Kraft verwenden, um Schäden an den Anschlüssen zu vermeiden.

.. Wenn Sie dies noch nicht getan haben, installieren Sie das Kabelverwaltungsgerät neu.
.. Verbinden Sie die Kabel mit dem Haken- und Schlaufenband mit dem Kabelmanagement-Gerät.
.. Wiederholen Sie die vorherigen Schritte für das zweite Controller-Modul im Ersatzgehäuse.


. Schließen Sie die Netzteile an verschiedene Stromquellen an, und schalten Sie sie dann ein.
. Booten jedes Controllers in den Wartungsmodus:
+
.. Drücken Sie, wenn der Boot-Vorgang von jedem Controller gestartet wird `Ctrl-C` Um den Bootvorgang zu unterbrechen, wenn die Meldung angezeigt wird `Press Ctrl-C for Boot Menu`.
+

NOTE: Wenn die Eingabeaufforderung nicht angezeigt wird und die Controller-Module beim ONTAP booten, geben Sie ein `halt`, Und geben Sie an der LOADER-Eingabeaufforderung ein `boot_ontap`, Drücken Sie `Ctrl-C` Wenn Sie dazu aufgefordert werden, und wiederholen Sie diesen Schritt.

.. Wählen Sie im Startmenü die Option Wartungsmodus aus.



