---
permalink: fas2800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas2820, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Der HA-Status des Chassis muss überprüft, Aggregate müssen zurückgeschaltet und das defekte Teil an NetApp zurückgesendet werden, um den Chassis-Austausch für Ihr FAS2820-System gemäß den in dem Kit enthaltenen RMA-Anweisungen abzuschließen. 
---
= Den Chassis-Austausch für Ihr FAS2820 System abschließen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Den HA-Status des Chassis überprüfen, die Aggregate zurückschalten und das defekte Teil an NetApp zurücksenden, um den Chassis-Austausch für das FAS2820-System gemäß den in dem Kit enthaltenen RMA-Anweisungen abzuschließen.



[[step-1-verify-and-set-the-ha-state-of-the-chassis]]
== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie den HA-Status für das Chassis basierend auf der vorhandenen Konfiguration des Systems fest: `ha-config modify chassis _ha-state_`
+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
*** `ha`
*** `non-ha`


.. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`


. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.
. Beenden des Wartungsmodus: `halt`.    Die LOADER-Eingabeaufforderung wird angezeigt.
. Starten Sie die Controller-Module.




[[step-2-bring-up-the-system]]
== Schritt 2: Das System hochfahren

. Wenn Sie dies nicht getan haben, schließen Sie die Netzkabel wieder an die Netzteile an.
. Die Netzteile werden eingeschaltet, indem der Kippschalter auf *EIN* gestellt wird, anschließend ist abzuwarten, bis die Controller vollständig hochgefahren sind.
. Überprüfen Sie nach dem Einschalten die Vorder- und Rückseite des Chassis und der Controller auf Fehler-LEDs.
. Stellen Sie über SSH eine Verbindung zur SP- oder BMC-IP-Adresse der Knoten her. Dies ist dieselbe Adresse, die zum Herunterfahren der Knoten verwendet wird.
. Führen Sie zusätzliche Zustandsprüfungen durch, wie in beschrieben https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Wie_ein_Cluster_Health_Check_with_a_script_in_ONTAP_durchführen"^]
. Wenn ein AutoSupport-Wartungsfenster ausgelöst wurde, beenden Sie das Fenster mit. Verwenden Sie dazu die `system node autosupport invoke -node * -type all -message MAINT=END` Befehl.


[]
====

NOTE: Als Best Practice sollten Sie Folgendes tun:

* Lösen Sie alle https://activeiq.netapp.com/["Active IQ Wellness-Alarme und Risiken"^] (Active IQ nimmt Zeit in Anspruch, um Autosupports nach dem Einschalten zu verarbeiten - erwarten Sie eine Verzögerung der Ergebnisse)
* Laufen https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* Überprüfen Sie den Systemzustand mit https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Wie_ein_Cluster_Health_Check_with_a_script_in_ONTAP_durchführen"^]


====


[[step-3-return-the-failed-part-to-netapp]]
== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
