---
permalink: fas2800/maintain-overview.html 
sidebar: sidebar 
keywords: fas2820 maintenance, maintenance, repairing, repairing fas2820, replace fas2820 components, replace fas2820 components 
summary: Warten Sie die Hardware Ihres FAS2820-Speichersystems, um langfristige Zuverlässigkeit und optimale Leistung sicherzustellen. 
---
= Informationen zur Wartung Ihres FAS2820 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Warten Sie die Hardware Ihres FAS2820 Speichersystems, um langfristige Zuverlässigkeit und optimale Leistung zu gewährleisten. Führen Sie regelmäßige Wartungsarbeiten durch, z. B. den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden.

Bei den Wartungsverfahren wird davon ausgegangen, dass das FAS2820 Speichersystem bereits als Speicherknoten in der ONTAP Umgebung bereitgestellt wurde.



[[system-components]]
== Systemkomponenten

An diesen Komponenten Ihres FAS2820-Speichersystems lassen sich Wartungsarbeiten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem zum Booten verwendet.  Während der automatischen Wiederherstellung ruft das System das Boot-Image vom Partnerknoten ab und führt automatisch die entsprechende Boot-Menüoption aus, um das Image auf Ihrem Ersatz-Boot-Medium zu installieren. Die automatische Wiederherstellung des Bootmediums wird nur in ONTAP 9.17.1 und höher unterstützt. Wenn Ihr Speichersystem eine frühere Version von ONTAP verwendet, verwenden Sie die link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] .



 a| 
link:bootmedia-replace-workflow.html["Bootmedium - manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem zum Booten verwendet. Bei der manuellen Wiederherstellung starten Sie das Speichersystem von einem USB-Laufwerk und stellen das Dateisystem-Image und die Konfiguration manuell wieder her.  Wenn Ihr Speichersystem ONTAP 9.17.1 oder höher ausführt, verwenden Sie dielink:bootmedia-replace-workflow-bmr.html["automatisiertes Boot-Wiederherstellungsverfahren"] .



 a| 
link:caching-module-replace.html["Caching-Modul"]
 a| 
Sie müssen das Caching-Modul des Controllers ersetzen, wenn Ihr System eine einzelne AutoSupport-Meldung (ASUP) registriert, dass das Modul offline gegangen ist.



 a| 
link:chassis-replace-overview.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-overview.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM-Akku"]
 a| 
Im Lieferumfang des Controllers ist eine Batterie enthalten, die zwischengespeicherte Daten bewahrt, wenn der Netzstrom ausfällt.



 a| 
link:pci-cards-and-risers-replace.html["Mezzanine-Karte"]
 a| 
Eine Mezzanine Karte ist eine Erweiterungskarte, die in einen speziellen Steckplatz auf dem Motherboard eingesetzt wird und die Karten-I/O-Karten aufnimmt.



 a| 
link:power-supply-swap-out.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromquelle in einem Controller bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Bei ausgeschaltetem Gerät bleiben Datum und Uhrzeit über eine Echtzeitbatterie erhalten.

|===