---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2820, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: Der Hot-Swap eines Netzteils in Ihrem FAS2820 System umfasst das Ausschalten, Trennen und Entfernen des defekten Netzteils sowie das Installieren, Anschließen und Einschalten des Ersatznetzteils. 
---
= Netzteil im laufenden Betrieb in Ihrem FAS2820 System austauschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Netzteil in Ihrem FAS2820 System kann im laufenden Betrieb im Hot-Swap-Verfahren ausgetauscht werden, falls es ausfällt oder an Leistung verliert, ohne den Systembetrieb zu unterbrechen. Dieses Verfahren umfasst das Ausschalten und Entfernen des defekten Netzteils sowie das Installieren und Einschalten des Ersatzteils.

Falls andere Systemkomponenten nicht ordnungsgemäß funktionieren, sollte der technische Support kontaktiert werden.

* Die Netzteile sind redundant und Hot-Swap-fähig.
* Dieses Verfahren ist für den Austausch eines Netzteils nach dem anderen beschrieben.
+

NOTE: Das Netzteil sollte innerhalb von zwei Minuten nach dem Ausbau aus dem Gehäuse ersetzt werden. Das System bleibt weiterhin funktionsfähig, jedoch sendet ONTAP Meldungen über die beeinträchtigte Stromversorgung an die Konsole, bis das Netzteil ersetzt wurde.

* Die Netzteile haben einen automatischen Bereich.


.Animation: Ersetzen Sie das Netzteil
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.Schritte
. Identifizieren Sie das zu ersetzenden Netzteil anhand von Konsolenfehlern oder über die LEDs an den Netzteilen.
. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Schalten Sie das Netzteil aus und trennen Sie die Netzkabel:
+
.. Schalten Sie den Netzschalter am Netzteil aus.
.. Öffnen Sie die Netzkabelhalterung, und ziehen Sie dann das Netzkabel vom Netzteil ab.
.. Ziehen Sie das Netzkabel von der Stromversorgung ab.


. Drücken Sie die Verriegelung am Handgriff der Stromversorgungs-Nockenwelle, und öffnen Sie dann den Nockengriff, um das Netzteil vollständig von der Mittelebene zu lösen.
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[Ersetzen Sie ein Netzteil]

. Schieben Sie die Stromversorgung mit dem Nockengriff aus dem System heraus.
+

CAUTION: Wenn Sie ein Netzteil entfernen, verwenden Sie immer zwei Hände, um sein Gewicht zu stützen.

. Stellen Sie sicher, dass sich der ein-/Ausschalter des neuen Netzteils in der Stellung aus befindet.
. Die Kanten des Netzteils mit beiden Händen an der Öffnung im Systemgehäuse abstützen und ausrichten, anschließend das Netzteil vorsichtig mit dem Nockengriff in das Gehäuse schieben.
+
Die Netzteile sind codiert und können nur auf eine Weise installiert werden.

+

NOTE: Beim Einschieben des Netzteils in das System keine übermäßige Kraft verwenden. Sie können den Anschluss beschädigen.

. Schließen Sie den Nockengriff, so dass die Verriegelung in die verriegelte Position einrastet und das Netzteil vollständig eingesetzt ist.
. Schließen Sie die Verkabelung des Netzteils wieder an:
+
.. Schließen Sie das Netzkabel wieder an das Netzteil und die Stromversorgung an.
.. Befestigen Sie das Netzkabel mithilfe der Netzkabelhalterung am Netzteil.


+
Nach Wiederherstellung der Stromversorgung sollte die Status-LED grün leuchten.

. Schalten Sie das neue Netzteil ein, und überprüfen Sie dann den Betrieb der Aktivitäts-LEDs für das Netzteil.
+
Die Netzteil-LEDs leuchten, wenn das Netzteil online geschaltet wird.

. Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"^]Weitere Informationen finden Sie auf der Seite.

