---
permalink: asa250/maintain-overview.html 
sidebar: sidebar 
keywords: asa A250 maintenance, maintenance, repairing A250, repairing asa A250, replace asa A250 components, replace asa A250 components 
summary: Wartung der ASA A250 Hardware 
---
= Wartung der ASA A250 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Warten Sie die Hardware Ihres ASA A250 Storage-Systems, um langfristige Zuverlässigkeit und optimale Leistung sicherzustellen. Führen Sie regelmäßige Wartungsaufgaben wie den Austausch fehlerhafter Komponenten durch, da dies dazu beiträgt, Ausfallzeiten und Datenverlust zu verhindern.

Die Wartungsverfahren setzen voraus, dass das ASA A250 Storage-System bereits als Speicherknoten in der ONTAP-Umgebung eingesetzt wurde.



[[system-components]]
== Systemkomponenten

Für das ASA A250-Speichersystem können Sie Wartungsverfahren für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP-Image-Dateien, die das Speichersystem zum Booten verwendet. Während der automatisierten Wiederherstellung ruft das System das Boot-Image vom Partnerknoten ab und führt automatisch die entsprechende Bootmenüoption aus, um das Image auf Ihrem Ersatz-Bootmedium zu installieren. Der automatisierte Wiederherstellungsprozess für das Bootmedium wird nur in ONTAP 9.18.1 und höher unterstützt. Wenn auf Ihrem Speichersystem eine frühere Version von ONTAP ausgeführt wird, verwenden Sie das link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"].



 a| 
link:bootmedia-replace-workflow.html["Bootmedium - manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP-Image-Dateien, die das Speichersystem zum Booten verwendet. Während der manuellen Wiederherstellung booten Sie das Speichersystem von einem USB-Laufwerk und stellen das Dateisystem-Image und die Konfiguration manuell wieder her. Wenn auf Ihrem Speichersystem ONTAP 9.18.1 oder höher ausgeführt wird, verwenden Sie die link:bootmedia-replace-workflow-bmr.html["automatisiertes Boot-Wiederherstellungsverfahren"].



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



 a| 
link:fan-replace.html["Ventilator"]
 a| 
Der Lüfter kühlt den Controller.



 a| 
link:mezzanine-replace.html["Mezzanine-Karte"]
 a| 
Die Mezzanine-Karte ist eine Leiterplatte, die direkt in eine andere Steckkarte gesteckt wird.



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM-Akku"]
 a| 
Die NVMEM-Batterie ist dafür zuständig, zwischengespeicherte Daten zu erhalten, falls die Netzstromversorgung ausfällt.



 a| 
link:power-supply-replace.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.

|===