---
permalink: c30-60/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, replace the boot media 
summary: Bevor Sie das Bootmedium in Ihrem AFF C30- oder AFF C60-Speichersystem austauschen, stellen Sie sicher, dass die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Stellen Sie dazu sicher, dass Sie einen USB-Stick mit ausreichend Speicherplatz verwenden und dass Sie das richtige Ersatz-Bootmedium verwenden. 
---
= Voraussetzungen für die manuelle Boot-Medienwiederherstellung – AFF C30 und AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das Bootmedium in Ihrem AFF C30- oder AFF C60-Speichersystem austauschen, stellen Sie sicher, dass die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Stellen Sie dazu sicher, dass Sie einen USB-Stick mit ausreichend Speicherplatz verwenden und dass Sie das richtige Ersatz-Bootmedium verwenden.

.USB-Speicherstick
* Stellen Sie sicher, dass Sie einen USB-Stick haben, der auf FAT32 formatiert ist.
* Der USB-Stick muss über ausreichend Speicherkapazität verfügen, um die  `image_xxx.tgz` Datei.


.Dateivorbereitung
Kopieren Sie die  `image_xxx.tgz` Datei auf den USB-Stick. Diese Datei wird verwendet, wenn Sie das ONTAP Image mit dem USB-Stick übertragen.

.Komponentenaustausch
Ersetzen Sie die ausgefallene Komponente durch die von NetApp bereitgestellte Ersatzkomponente.

.Controller-Identifikation
Es ist wichtig, die Befehle auf den richtigen Controller anzuwenden, wenn Sie das beschädigte Startmedium ersetzen:

* Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
* Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Boot-Mediums überprüft haben, müssen Sie link:bootmedia-encryption-preshutdown-checks.html["Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel auf dem Startmedium"].
