---
permalink: c30-60/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, replace the chassis 
summary: Bevor das Gehäuse Ihres AFF C30 oder AFF C60 Storage-Systems ersetzt wird, sollten die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sein. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren und dass das richtige Ersatzgehäuse sowie die erforderlichen Werkzeuge vorhanden sind. 
---
= Die Anforderungen für den Austausch eines Chassis in einem AFF C30 oder AFF C60 System werden hier aufgeführt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Gehäuse Ihres AFF C30 oder AFF C60 Storage-Systems ersetzt wird, sollten die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sein. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren und dass das richtige Ersatzgehäuse sowie die erforderlichen Werkzeuge vorhanden sind.

Lesen Sie die folgenden Anforderungen und Überlegungen durch.



[[requirements]]
== Anforderungen

* Das Ersatzgehäuse muss das gleiche Modell aufweisen wie das Gehäuse für beeinträchtigte Störungen. Dieses Verfahren gilt für einen ähnlichen Austausch, nicht für ein Upgrade.
* Alle anderen Komponenten des Speichersystems müssen ordnungsgemäß funktionieren. Falls nicht, wenden Sie sich an https://mysupport.netapp.com/site/global/dashboard["NetApp Support"], bevor Sie mit diesem Verfahren fortfahren.




[[considerations]]
== Überlegungen

* Das Verfahren zum Austausch des Gehäuses führt zu Unterbrechungen. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.
* Sie können das Verfahren zum Gehäuseaustausch bei allen Versionen von ONTAP verwenden, die von Ihrem Speichersystem unterstützt werden.
* Beim Austausch des Gehäuses wird angenommen, dass Sie den Blende, die Laufwerke, etwaige Laufwerkplatzhalter und die Controller auf das neue Gehäuse verschieben.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie dies tun link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"]
