---
permalink: c30-60/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, prerequisite, replace the controller module 
summary: Bevor der Controller in Ihrem AFF C30 oder AFF C60 Storage-System ersetzt wird, sollte bestätigt werden, dass alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass der richtige Ersatzcontroller vorhanden ist und dass die Konsolenausgabe des Controllers in einer Textprotokolldatei gespeichert wird. 
---
= Anforderungen sollten vor dem Austausch des Controllers in einem AFF C30 oder AFF C60 System überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor der Controller in Ihrem AFF C30 oder AFF C60 Storage-System ersetzt wird, sollte bestätigt werden, dass alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass der richtige Ersatzcontroller vorhanden ist und dass die Konsolenausgabe des Controllers in einer Textprotokolldatei gespeichert wird.

Überprüfen Sie die Anforderungen und Überlegungen beim Austausch des Controllers.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====


[[requirements]]
== Anforderungen

* Alle Regale müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie den Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"] Um zu bestimmen, ob Sie dieses Verfahren verwenden sollten.
* Sie müssen einen Controller durch einen Controller desselben Modelltyps ersetzen. Sie können Ihr System nicht aktualisieren, indem Sie einfach den Controller austauschen.
* Im Rahmen dieses Verfahrens können keine Laufwerke oder Shelfs geändert werden.




[[considerations]]
== Überlegungen

Es ist wichtig, dass Sie die Befehle in diesem Verfahren auf den richtigen Controller anwenden:

* Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
* Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
* Der _Healthy_ Controller ist der überlebende Controller.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen überprüft haben, um den beeinträchtigten Controller zu ersetzen, müssen Sie link:controller-replace-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].
