---
permalink: c30-60/install-hardware.html 
sidebar: sidebar 
keywords: aff c30, aff c60, install hardware, telco rack 
summary: Installieren Sie Ihr Speichersystem im Schrank oder im Telco-Rack. 
---
= Installieren Sie die Hardware AFF C30 und AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installieren Sie nach der Vorbereitung auf die Installation des AFF C30- oder AFF C60-Speichersystems die Hardware für das Speichersystem. Installieren Sie zunächst die Schienensätze. Installieren und sichern Sie dann Ihr Speichersystem in einem Schrank oder einem Telco-Rack.

Überspringen Sie diesen Schritt, wenn Ihr Speichersystem in einem Schrank geliefert wurde.

.Bevor Sie beginnen
* Stellen Sie sicher, dass die Anweisungen im Schienensatz enthalten sind.
* Beachten Sie die Sicherheitsbedenken im Zusammenhang mit dem Gewicht des Lagersystems und des Regals.
* Stellen Sie fest, dass der Luftstrom durch das Speichersystem von der Vorderseite, an der die Blende oder die Endkappen installiert sind, einströmt und an der Rückseite, an der sich die Anschlüsse befinden, absaugt.


.Schritte
. Installieren Sie die Schienen-Kits für Ihr Speichersystem und die Regale nach Bedarf gemäß den Anweisungen, die in den Kits enthalten sind.
. Installieren und sichern Sie Ihr Speichersystem im Schrank oder im Telco-Rack:
+
.. Positionieren Sie das Speichersystem auf den Schienen in der Mitte des Schranks oder des Telco-Racks, und stützen Sie das Speichersystem von unten ab, und schieben Sie es hinein.
.. Stellen Sie sicher, dass die Führungsstifte des Gehäuses oder des Telco-Racks sicher in den Schlitzen der Gehäuseführung sind.
.. Befestigen Sie das Speichersystem mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.


. Befestigen Sie die Blende an der Vorderseite des Speichersystems.
. Installieren Sie das Shelf und befestigen Sie es bei Bedarf.
+
.. Positionieren Sie die Rückseite des Regals auf den Schienen, und stützen Sie das Regal von unten ab, und schieben Sie es in den Schrank oder das Telco-Rack.
+
Wenn Sie mehrere Shelfs installieren, platzieren Sie das erste Shelf direkt über den Controllern. Platzieren Sie das zweite Shelf direkt unter den Controllern. Wiederholen Sie dieses Muster für alle zusätzlichen Regale.

.. Befestigen Sie das Regal mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.
+
.Was kommt als Nächstes?
Nachdem Sie die Hardware für Ihr Storage-System installiert haben, Sie link:install-cable.html["Verkabeln Sie die Hardware"].




