---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module 
summary: Die Speichersysteme AFF C30 und AFF C60 bieten Flexibilität bei der Erweiterung oder dem Austausch von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn Sie die Netzwerkkapazität erweitern oder ein ausgefallenes Modul reparieren möchten. 
---
= Informationen zum Hinzufügen und Austauschen von E/A-Modulen in einem AFF C30 oder AFF C60 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Speichersysteme AFF C30 und AFF C60 bieten Flexibilität bei der Erweiterung oder dem Austausch von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn Sie die Netzwerkkapazität erweitern oder ein ausgefallenes Modul reparieren möchten.

Sie können ein defektes E/A-Modul in Ihrem Speichersystem durch ein E/A-Modul desselben Typs oder eines anderen Typs ersetzen. Ein Cluster- und HA-E/A-Modul kann im laufenden Betrieb ausgetauscht werden, wenn Ihr Speichersystem bestimmte Anforderungen erfüllt. Ein E/A-Modul kann auch zu einem Speichersystem mit verfügbaren Steckplätzen hinzugefügt werden.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher I/O-Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das Speichersystem auch bei Ausfall eines I/O-Moduls betriebsbereit bleibt.

* link:io-module-hotswap.html["Hot-Swap eines I/O-Moduls"]
+
Durch den Austausch bestimmter E/A-Module im laufenden Betrieb gegen ein gleichwertiges Modul kann das Speichersystem wieder in seinen optimalen Betriebszustand versetzt werden. Der Austausch erfolgt, ohne dass eine manuelle Übernahme erforderlich ist.

+
Um dieses Verfahren zu verwenden, muss auf Ihrem Speichersystem ONTAP 9.17.1 oder höher ausgeführt werden und bestimmte Systemanforderungen erfüllen.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften I/O-Moduls kann das Speichersystem wieder in den optimalen Betriebszustand versetzt werden.


