---
permalink: c30-60/maintain-overview.html 
sidebar: sidebar 
keywords: aff c30, aff c60, maintenance, maintenance, repairing a20 aff a30 aff a50, replace a20 aff a30 aff a50 components 
summary: Warten Sie die Hardware Ihrer AFF C30- oder AFF C60-Speichersysteme, um eine langfristige Zuverlässigkeit und optimale Leistung zu gewährleisten. Führen Sie regelmäßige Wartungsaufgaben durch, wie zum Beispiel den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden. 
---
= Überblick über die Hardwarewartung - AFF C30 und AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Warten Sie die Hardware Ihres AFF C30- oder AFF C60-Speichersystems, um langfristige Zuverlässigkeit und optimale Leistung zu gewährleisten. Führen Sie regelmäßige Wartungsarbeiten durch, z. B. den Austausch defekter Komponenten, um Ausfallzeiten und Datenverlust zu vermeiden.

Bei den Verfahren in diesem Abschnitt wird davon ausgegangen, dass das Speichersystem AFF C30 oder AFF C60 bereits als Speicherknoten in der ONTAP Umgebung bereitgestellt wurde.



== Systemkomponenten

Für die Speichersysteme AFF C30 und AFF C60 können Sie Wartungsverfahren für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Bootmedium – automatisierte Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP -Imagedateien, die das Speichersystem verwendet, um das Image vom Partnerknoten zu booten und automatisch die entsprechende Bootmenüoption auszuführen, um das Boot-Image auf Ihrem Ersatz-Bootmedium zu installieren. Die automatische Wiederherstellung des Bootmediums wird nur in ONTAP 9.17.1 und höher unterstützt. Wenn Ihr Speichersystem eine frühere Version von ONTAP verwendet, verwenden Sie die link:bootmedia-replace-workflow.html["manuelle Boot-Wiederherstellung"] .



 a| 
link:bootmedia-replace-workflow.html["Bootmedium – manuelle Wiederherstellung"]
 a| 
Das Bootmedium speichert einen primären und einen sekundären Satz von ONTAP Imagedateien, die das Speichersystem verwendet, um das Image von einem USB-Laufwerk zu booten und die Konfiguration vom Partnerknoten wiederherzustellen.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und führt die ONTAP-Betriebssystemsoftware aus.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Ein duales Inline-Speichermodul (DIMM) ist eine Art von Computerspeicher. Sie sind installiert, um einem Controller-Motherboard Systemspeicher hinzuzufügen.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den für Daten erforderlichen physischen Storage bereitstellt.



 a| 
link:fan-replace.html["Ventilator"]
 a| 
Ein Lüfter kühlt den Controller und die Laufwerke.



 a| 
link:io-module-overview.html["I/O-Modul"]
 a| 
Das E/A-Modul (Eingangs-/Ausgangsmodul) ist eine Hardwarekomponente, die als Vermittler zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.



 a| 
link:nvdimm-battery-replace.html["NV-Batterie"]
 a| 
Die nichtflüchtige Speicherbatterie (NV) sorgt dafür, dass die NVMEM-Komponenten mit Strom versorgt werden, während die aktiven Daten nach einem Stromausfall in den Flash-Speicher ausgelagert werden.



 a| 
link:power-supply-replace.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromquelle in einem Controller bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Bei ausgeschaltetem Gerät bleiben Datum und Uhrzeit über eine Echtzeitbatterie erhalten.

|===