---
permalink: a20-30-50/a50-key-specifications.html 
sidebar: sidebar 
keywords: AFF A50 specifications, AFF A50 specs, AFF A50 capacity, AFF A50 memory, AFF A50 I/O, AFF A50 compliance 
summary: Wichtige Spezifikationen für AFF A50 
---
= Wichtige Spezifikationen für AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das AFF A50-Speichersystem in einem einzelnen Hochverfügbarkeitspaar.  Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== AFF A50 Spezifikationen im Überblick

* Plattformkonfiguration: AFF A50 Single Chassis HA Pair
* Max. Rohkapazität: 4,0392 PB
* Arbeitsspeicher: 256.0000 GB
* Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 8
* Mindestversion von ONTAP : ONTAP 9.16.1RC1




== Skalierungsmaxima

* Typ: NAS; HA-Paare: 12; Rohkapazität: 48,5 PB / 43,0 PiB; Max. Speicher: 3072 GB
* Typ: SAN; HA-Paare: 6; Rohkapazität: 24,2 PB / 21,5 PiB; Max. Speicher: 1536 GB
* Typ: HA-Paar; Rohkapazität: 4,0 PB / 3,6 PiB; Max. Speicher: 256.0000




== E/A



=== Integrierte E/A

Keine Onboard-E/A-Daten.



=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 16
* Protokoll: Ethernet 25 Gbit/s; Ports: 24
* Protokoll: Ethernet 10 Gbit/s; Ports: 24
* Protokoll: FC 64 Gbit/s; Ports: 24
* Protokoll: NVMe/FC 64 Gbit/s; Ports: 24
* Anschlüsse: 0
* Protokoll: SAS 12 Gbit/s; Ports: 16




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 2
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 600 Mbit/s; Anschlüsse: 2




== Speichernetzwerke werden unterstützt

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 mit NAS
* KMU 2.0
* SMB 2.1
* SMB 2.x
* KMU 3.0
* KMU 3.1
* SMB 3.1.1




== Systemumgebungsspezifikationen

* Typische Leistung: 3076 BTU/h
* Leistung im schlimmsten Fall: 4860 BTU/h
* Gewicht: 60,7 lb, 27,5 kg
* Höhe: 2U
* Breite: 19" IEC-Rack-kompatibel (17,6" 44,7 cm)
* Tiefe:
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bis zu einer Höhe von 3048 m (10000 ft); 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Lagertemperatur/Luftfeuchtigkeit: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12192 m (40000 ft); 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustische Geräusche: Angegebene Schallleistung (LwAd): 8,0; Schalldruck (LpAm) (Positionen von Umstehenden): 70,5 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile
* SAS-In-Band-Management über SAS-Verbindungen für externe Regale

