---
permalink: a20-30-50/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Überprüfen Sie beim AFF A20, AFF A30 oder AFF A50 Storage-System, ob die HA-Konfiguration des Controllers aktiv ist und ordnungsgemäß funktioniert, und vergewissern Sie sich, dass alle Pfade zu den Festplatten von den Systemadaptern aufgelistet sind. 
---
= Stellen Sie die Systemkonfiguration wieder her, und überprüfen Sie sie: AFF A20, AFF A30 und AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie beim AFF A20, AFF A30 oder AFF A50 Storage-System, ob die HA-Konfiguration des Controllers aktiv ist und ordnungsgemäß funktioniert, und vergewissern Sie sich, dass alle Pfade zu den Festplatten von den Systemadaptern aufgelistet sind.



== Schritt: Überprüfen Sie HA-Konfigurationseinstellungen

Sie müssen den Status des Controllers überprüfen `HA` und ggf. den Status entsprechend Ihrer Storage-Systemkonfiguration aktualisieren.

. Booten im Wartungsmodus:
+
`boot_ontap maint`

+
.. Geben Sie ein `y`, wenn _Continue with Boot?_ angezeigt wird.
+
Wenn die Warnmeldung _System ID Mismatch_ angezeigt wird, geben Sie ein `y`.



. Geben Sie den Inhalt der Anzeige ein `sysconfig -v` und erfassen Sie diesen.
+

NOTE: Wenn Sie _PERSONALITY MISMATCH_ sehen, wenden Sie sich an den Kundendienst.

. Vergleichen Sie in der `sysconfig -v` Ausgabe die Adapterkarteninformationen mit den Karten und Positionen im Ersatzcontroller.
. Vergewissern Sie sich, dass alle Komponenten denselben `HA` Status aufweisen:
+
`ha-config show`

+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemstatus des Controllers nicht mit der Konfiguration des Storage-Systems übereinstimmt, legen Sie den Status für den Controller fest `HA`:
+
`ha-config modify controller ha-state`

+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
** `ha`
** `mcc` (Nicht unterstützt)
** `mccip` (In ASA Systemen nicht unterstützt)
** `non-ha` (Nicht unterstützt)


. Bestätigen Sie, dass sich die Einstellung geändert hat:
+
`ha-config show`





== Schritt 2: Überprüfen Sie die Datenträgerliste

. Überprüfen Sie, ob der Adapter die Pfade zu allen Festplatten auflistet:
+
`storage show disk -p`

+
Wenn Sie Probleme sehen, überprüfen Sie die Verkabelung, und setzen Sie die Kabel wieder ein.

. Beenden des Wartungsmodus:
+
`halt`



.Was kommt als Nächstes?
Nachdem Sie die Systemkonfiguration für Ihr AFF A20, AFF A30 oder AFF A50 System wiederhergestellt und verifiziert haben, müssen Sie link:controller-replace-recable-reassign-disks.html["Geben Sie den Controller zurück"].
