---
permalink: a20-30-50/install-complete.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, prepare installation 
summary: Führen Sie die Plattformeinrichtung und -Konfiguration mithilfe der Cluster-Erkennung durch, wobei nur eine Verbindung zum Switch und Laptop besteht, oder stellen Sie eine direkte Verbindung zu einem Controller im Storage-System her und stellen Sie dann eine Verbindung zum Management Switch her. 
---
= Komplette Einrichtung und Konfiguration des Storage-Systems – AFF A20, AFF A30 und AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie das Storage-System eingeschaltet haben, können Sie das Cluster-Netzwerk erkennen und ein ONTAP Cluster einrichten.



== Schritt 1: Sammeln von Cluster-Informationen

Falls Sie dies noch nicht getan haben, sammeln Sie die Informationen, die Sie zum Konfigurieren des Clusters benötigen, z. B. den Port der Cluster-Managementoberfläche und die IP-Adresse.

Verwenden Sie das https://docs.netapp.com/us-en/ontap/software_setup/index.html["Arbeitsblatt für die Cluster-Einrichtung"^] , um die Werte aufzuzeichnen, die Sie während der Cluster-Einrichtung benötigen. Wenn ein Standardwert angegeben ist, können Sie diesen Wert verwenden oder Ihren eigenen Wert eingeben.



== Schritt 2: Ermitteln Sie Ihr Cluster-Netzwerk

Durch die Erkennung können Sie die Storage-System-Controller im Netzwerk ermitteln.

[role="tabbed-block"]
====
.Option 1: Netzwerkerkennung ist aktiviert
--
Wenn die Netzwerkerkennung auf Ihrem Laptop aktiviert ist, können Sie die Einrichtung und Konfiguration mithilfe der automatischen Cluster-Erkennung abschließen.

.Schritte
. Verbinden Sie Ihren Laptop mit dem Management-Switch, und greifen Sie auf die Netzwerkcomputer und -Geräte zu.
. Wählen Sie ein ONTAP-Symbol aus, um es zu ermitteln:
+
image::../media/drw_autodiscovery_controler_select_ieops-1849.svg[So ermitteln Sie Ihre Controller mit dem Windows File Explorer]

+
.. Öffnen Sie Den Datei-Explorer.
.. Klicken Sie im linken Fensterbereich auf *Netzwerk*, klicken Sie mit der rechten Maustaste und wählen Sie *Aktualisieren*.
.. Doppelklicken Sie auf das ONTAP-Symbol, und akzeptieren Sie alle auf dem Bildschirm angezeigten Zertifikate.
+

NOTE: XXXXX ist die Seriennummer des Storage-Systems für den Ziel-Node.



+
System Manager wird geöffnet.



--
.Option 2: Netzwerkermittlung ist nicht aktiviert
--
Wenn die Netzwerkerkennung auf Ihrem Laptop nicht aktiviert ist, schließen Sie die Konfiguration mit dem Cluster-Setup-Assistenten für die ONTAP Befehlszeilenschnittstelle (CLI) ab.

.Bevor Sie beginnen
Stellen Sie sicher, dass Ihr Laptop mit dem seriellen Konsolenport verbunden ist und die Controller eingeschaltet sind. Anweisungen finden Sie unter link:install-power-hardware.html#step-2-power-on-the-controllers["Schalten Sie das Speichersystem ein"] .

.Schritte
Weisen Sie einem der Nodes eine erste Node-Management-IP-Adresse zu.

[cols="1,2"]
|===
| Wenn das Managementnetzwerk DHCP enthält... | Dann... 


 a| 
Konfiguriert
 a| 
Notieren Sie die IP-Adresse, die den neuen Controllern zugewiesen ist.



 a| 
Nicht konfiguriert
 a| 
. Öffnen Sie eine Konsolensitzung mit PuTTY, einem Terminalserver oder dem entsprechenden Betrag für Ihre Umgebung.
+

NOTE: Überprüfen Sie die Online-Hilfe Ihres Laptops oder Ihrer Konsole, wenn Sie nicht wissen, wie PuTTY konfiguriert werden soll.

. Stellt eine Verbindung mit der Konsole des ersten Node her.
+
Der Node bootet, und dann startet der Cluster-Setup-Assistent auf der Konsole.

. Geben Sie die Management-IP-Adresse des Node ein, wenn Sie durch den Cluster-Setup-Assistenten dazu aufgefordert werden.


|===
--
====


== Schritt 3: Konfigurieren Sie Ihren Cluster

NetApp empfiehlt, zum Einrichten neuer Cluster System Manager zu verwenden. Anweisungen zur Einrichtung finden Sie unter https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Konfigurieren Sie ONTAP mit System Manager in einem neuen Cluster"^] .

System Manager bietet einen einfachen und einfachen Workflow für die Cluster-Einrichtung und -Konfiguration einschließlich der Zuweisung einer Node-Management-IP-Adresse, Initialisierung des Clusters, Erstellung eines lokalen Tiers, Konfiguration von Protokollen und Erstbereitstellung des angeschlossenen Storage.

.Was kommt als Nächstes?
Nachdem der Cluster initialisiert wurde, laden Sie ihn herunter und führen Sie aus  https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^] , um das Setup zu bestätigen.
