---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: Die Speichersysteme AFF A20, AFF A30 und AFF A50 bieten Flexibilität bei der Erweiterung oder dem Austausch von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn die Netzwerkkapazität erweitert oder ein ausgefallenes Modul repariert werden soll. 
---
= Informationen zum Hinzufügen und Ersetzen von E/A-Modulen in einem AFF A20, AFF A30 oder AFF A50 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Speichersysteme AFF A20, AFF A30 und AFF A50 bieten Flexibilität bei der Erweiterung oder dem Austausch von E/A-Modulen zur Verbesserung der Netzwerkkonnektivität und -leistung. Das Hinzufügen, Hot-Swapping oder der Austausch eines E/A-Moduls ist unerlässlich, wenn die Netzwerkkapazität erweitert oder ein ausgefallenes Modul repariert werden soll.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Sie können E/A-Module hinzufügen, um die Redundanz zu erhöhen und so sicherzustellen, dass das Speichersystem auch dann betriebsbereit bleibt, wenn ein E/A-Modul ausfällt. Sie können E/A-Module hinzufügen, wenn Steckplätze verfügbar sind oder wenn alle Steckplätze vollständig belegt sind.

* link:io-module-hotswap.html["Hot-Swap eines I/O-Moduls"]
+
Bestimmte I/O-Module können im Hot-Swap-Verfahren gegen gleichwertige I/O-Module ausgetauscht werden, um das Speichersystem wieder in seinen optimalen Betriebszustand zu versetzen. Für den Hot-Swap des Moduls ist keine manuelle Übernahme erforderlich.

+
Um dieses Verfahren anwenden zu können, muss auf Ihrem Speichersystem ONTAP 9.17.1 oder höher ausgeführt werden und es müssen bestimmte Anforderungen für die Version von ONTAP, die auf Ihrem System ausgeführt wird, erfüllt sein.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Sie können ein defektes E/A-Modul austauschen, um das Speichersystem wieder in seinen optimalen Betriebszustand zu versetzen. Dieses Verfahren erfordert eine manuelle Übernahme des Controllers mit dem defekten E/A-Modul.


