---
permalink: c250/overview.html 
sidebar: sidebar 
keywords: AFF C250 specifications, AFF C250 specs, NetApp AFF C250, AFF C250 hardware 
summary: Wichtige Spezifikationen des AFF C250 -Speichersystems 
---
= Wichtige Spezifikationen für AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind ausgewählte Spezifikationen für den AFF C250 aufgeführt.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der AFF C250 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für AFF C250

Plattformkonfiguration: AFF C250 Single Chassis HA Pair

Max. Rohkapazität: 1,4736 PB

Arbeitsspeicher: 128.0000 GB

Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 4

Mindestens erforderliche ONTAP -Version: ONTAP 9.10.1P15



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS | 12 | 17,7 PB / 15,7 PiB | 1536 GB 


| SAN | 6 | 8,8 PB / 7,9 PiB | 768 GB 


| HA-Paar |  | 1,5 PB / 1,3 PiB | 128,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 25 Gbit/s | 4 


| Ethernet 10 Gbit/s | 4 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 4 


| Ethernet 25 Gbit/s | 20 


| Ethernet 10 Gbit/s | 4 


| FC 32 Gbit/s | 16 


| NVMe/FC 32 Gbit/s | 16 


|  | 0 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 4 
|===


=== Unterstützte Speichernetzwerke

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 mit NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 2906 BTU/h
* Leistung im schlimmsten Fall: 3750 BTU/h
* Gewicht: 54,3 lbbr/24,6 kg
* Höhe: 2U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe:
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (br/50 °F bis br/95 °F) bei br/= 3048 mbr/= 10000 ft) Höhe; 8 % bis 80 % (br/relative Luftfeuchtigkeit, nicht kondensierend)
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß)<br/>10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 7,2;br/Schalldruck (LpAm) (in der Nähe): 69,1 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle; redundante Hot-Swap-fähige Controller; redundante Hot-Swap-fähige Netzteile;
