---
permalink: c250/install-setup.html 
sidebar: sidebar 
keywords: aff c250, install, setup, initial configuration 
summary: Wählen Sie zwischen Kurzanleitungen, detaillierten Anleitungen oder Videoanleitungen, um ein AFF C250 Storage System zu installieren und einzurichten. 
---
= Installationsoptionen für ein AFF C250 Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Je nach gewünschtem Format und Erfahrungsstand stehen Kurzanleitungen, detaillierte Anleitungen oder Videoanleitungen zur Installation und Einrichtung eines AFF C250 Storage Systems zur Auswahl.

* link:../c250/install-quick-guide.html["Schnelle Schritte"]
+
Eine druckbare PDF-Datei mit Schritt-für-Schritt-Anweisungen mit Live-Links zu zusätzlichen Inhalten.

* link:../c250/install-videos.html["Videoschritte"]
+
Video Schritt-für-Schritt-Anleitungen.

* link:../c250/install-detailed-guide.html["Detaillierte Schritte"]
+
Schritt-für-Schritt-Anleitungen mit Live-Links zu weiteren Inhalten



Wenn sich das System in einer MetroCluster-IP-Konfiguration befindet, lesen Sie den https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster-IP-Konfiguration installieren"^] Anweisungen.
