---
permalink: c250/install-videos.html 
sidebar: sidebar 
keywords: aff a250, hardware installation and cabling video, performing end-to-end software configuration video 
summary: 'Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.' 
---
= Videos – AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.

Wenn Sie über eine MetroCluster-Konfiguration verfügen, verwenden Sie den MetroCluster-Installationsinhalt.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"^]



== Video eines von zwei: Hardware-Installation und -Verkabelung

Das folgende Video zeigt, wie Sie Ihr neues System installieren und verkabeln.

.Animation - Installation und Einrichtung eines AFF C250
video::c6906786-b302-4c14-b39b-afc50062aac5[panopto]


== Video zwei von zwei: Durchführung der End-to-End-Softwarekonfiguration

Das folgende Video zeigt die End-to-End-Softwarekonfiguration für Systeme mit ONTAP 9.2 und höher.

video::WAE0afWhj1c?[youtube]