---
permalink: asa-r2-a1k/bootmedia-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k, overview, the boot media 
summary: Erfahren Sie mehr über die automatisierte Methode und die manuelle Methode zum Austauschen der Boot-Medien. 
---
= Überblick über den Austausch der Startmedien - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können fehlerhafte Startmedien manuell durch Verwendung eines USB-Moduls für das Startabbild oder durch die Option zum automatischen Ersetzen des Startmediums (BMR) ersetzen.

* link:bootmedia-replace-requirements-bmr.html["Automatisierter Austausch von Boot-Medien"]
+
Beim automatischen Austausch von Startmedien wird das Startabbild vom Partnerknoten verwendet und automatisch die entsprechende Startmenüoption ausgeführt, um das Startabbild auf den Ersatz-Startmedien zu installieren.

* link:bootmedia-replace-requirements.html["Manueller Start-Datenträger ersetzen"]
+
Beim manuellen Ersetzen von Startmedien wird das ONTAP-Image von der NetApp-Support-Website heruntergeladen, das Image auf ein USB-Laufwerk übertragen, auf das Startmedium heruntergeladen und manuell durch die Optionen des Startmenüs geleitet, um das ONTAP-Image auf dem Ersatz-Startmedium zu installieren.


