---
permalink: asa-r2-a1k/bootmedia-recovery-image-boot-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, boot the recovery image 
summary: Sie müssen das ONTAP-Image vom USB-Laufwerk starten, das Dateisystem wiederherstellen und die Umgebungsvariablen überprüfen. 
---
= Automatische Startwiederherstellung - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie das ONTAP-Image vom Partnerknoten wieder her, wenn das Boot-Medium beschädigt ist.

.Über diese Aufgabe
Wenn das Boot-Medium eines Node beschädigt ist, wird der Boot-Prozess an der Loader-Eingabeaufforderung angehalten und Boot-Fehlermeldungen angezeigt.

Wenn diese Boot-Fehlermeldungen angezeigt werden, müssen Sie das ONTAP-Image vom Partner-Node wiederherstellen.

.Zeigt ein Beispiel für Boot-Fehlermeldungen an
[%collapsible]
====
....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....
====
.Schritte
. Geben Sie an der Loader-Eingabeaufforderung den Befehl ein:
+
`boot_recovery -partner`

+
Auf dem Bildschirm wird die folgende Meldung angezeigt:

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Überwachen Sie den Recovery-Prozess für Startmedien, während Loader die lokalen Cluster-Ports konfiguriert und vom Partner-Node aus ausgeführt `netboot` wird.
+
Wenn Netzboot ausgeführt wird, wird die `Starting BMR` Meldung angezeigt.

. Wählen Sie je nach Verschlüsselungsmethode die Option aus, die zu Ihrer Single-Node-Konfiguration passt:
+
[role="tabbed-block"]
====
.Keine Verschlüsselung
--
Wenn keine Verschlüsselung erkannt wird, wird der Wiederherstellungsvorgang des Startmediums ohne Schlüsselmanagement fortgesetzt.

Überwachen Sie den Wiederherstellungsprozess weiter, während die Backup-Konfiguration, die env-Datei, mdb und rdb vom Partner-Node wiederhergestellt werden.

Nach Abschluss der Wiederherstellung wird der Node neu gebootet. Die folgenden Meldungen weisen auf eine erfolgreiche Wiederherstellung hin:

....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....
--
.Onboard Key Manager (OKM)
--
Wenn Onboard Key Manager (OKM) erkannt wird, zeigt das System die folgende Eingabeaufforderung an.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Geben Sie in der Eingabeaufforderung Bootmenu die Option Bootmedia Recovery ein `Y`, um zu bestätigen, dass Sie die Bootmedia Recovery-Option verwenden möchten.
.. Geben Sie die Passphrase für Onboard Key Manager ein, wenn Sie dazu aufgefordert werden, und geben Sie die Passphrase erneut ein, um sie zu bestätigen.
+
.Beispiel für Passphrase-Eingabeaufforderungen anzeigen
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====
.. Überwachen Sie den Wiederherstellungsprozess weiter, während die Backup-Konfiguration, die env-Datei, mdb und rdb vom Partner-Node wiederhergestellt werden.
+
Nach Abschluss der Wiederherstellung wird der Node neu gebootet. Die folgenden Meldungen weisen auf eine erfolgreiche Wiederherstellung hin:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.
....


--
.Externer Schlüsselmanager (EKM)
--
Wenn EKM konfiguriert ist, zeigt das System die folgende Eingabeaufforderung an.

....
Error when fetching key manager config from partner <IP>: 28

Has key manager been configured on this system? {y|n}
....
.. Geben Sie ein `Y`, wenn EKM konfiguriert wurde.
+
....
key manager is configured.
Entering Bootmenu Option 11...
....
+
Sie werden aufgefordert, die EKM-Einstellungen einzugeben, die beim Einrichten verwendet wurden.

.. Geben Sie jede EKM-Konfigurationseinstellung ein, wenn Sie dazu aufgefordert werden.
.. Überprüfen Sie, ob die Attribute für die Cluster-UUID und die Keystore-UUID korrekt sind.
+
*** Rufen Sie auf dem Partner-Node die Cluster-UUID mit dem folgenden Befehl ab.
+
`cluster identity show`

*** Rufen Sie auf dem Partner-Node die Keystore-UUID mit den folgenden Befehlen ab.
+
`vserver show -type admin`

+
`key-manager keystore show -vserver <nodename>`

*** Wenn der Partner-Node nicht verfügbar ist, verwenden Sie den Mroot-AK-Schlüssel, um die UUID abzurufen:
+
**** Geben Sie für die Cluster-UUID den folgenden Befehl ein:
+
`x-NETAPP-ClusterName: <cluster name>`

**** Geben Sie für die Keystore-UUID den folgenden Befehl ein:
+
`x-NETAPP-KeyUsage: MROOT-AK`





.. Geben Sie bei der entsprechenden Aufforderung die Werte für Keystore-UUID und Cluster-UUID ein.
.. Je nachdem, ob der Schlüssel erfolgreich wiederhergestellt wurde, führen Sie eine der folgenden Aktionen durch:
+
*** Wenn der Schlüssel erfolgreich wiederhergestellt wurde, wird der Wiederherstellungsprozess fortgesetzt und der Knoten neu gestartet. Fahren Sie mit Schritt 4 fort.
*** Wenn der Schlüssel nicht erfolgreich wiederhergestellt wurde, hält das System an und zeigt Fehler- und Warnmeldungen an. Führen Sie den Wiederherstellungsprozess erneut aus.
+
.Zeigt ein Beispiel für Fehler und Warnmeldungen bei der Schlüsselwiederherstellung an
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...

WARNING: kmip_init: authentication keys might not be available.

System cannot connect to key managers.

ERROR: kmip_init: halting this system with encrypted mroot...

Terminated

Uptime: 11m32s

System halting...

LOADER-B>
....
=====




--
====


. Wenn der Node neu gebootet wird, überprüfen Sie, ob die Boot-Medien erfolgreich wiederhergestellt wurden, indem Sie bestätigen, dass das System wieder online und funktionsfähig ist.
. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`.

. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local -auto-giveback true`.

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`.


