---
permalink: asa-r2-a1k/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a1k, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Überprüfen Sie, ob die logischen Schnittstellen (LIFs) an ihren Home Port berichten, führen Sie eine Cluster-Zustandsprüfung durch und senden Sie das fehlerhafte Teil anschließend an NetApp zurück, um den letzten Schritt beim ASA A1K-Controller-Austausch abzuschließen.' 
---
= Kompletter Controller-Austausch - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Controlleraustausch für Ihr ASA A1K-System abzuschließen, stellen Sie zunächst die NetApp Storage Encryption-Konfiguration wieder her (falls erforderlich). Vergewissern Sie sich als nächstes, dass die logischen Schnittstellen (LIFs) ihren Home Ports berichten und eine Cluster-Zustandsprüfung durchführen. Senden Sie anschließend das ausgefallene Teil an NetApp zurück.



== Schritt 1: Verifizieren von LIFs und Überprüfen des Clusterzustands

Bevor Sie den Ersatz-Node an einen Service zurücksenden, überprüfen Sie, ob sich die logischen Schnittstellen auf ihren Home Ports befinden, überprüfen Sie den Cluster-Zustand und setzen Sie das automatische Giveback zurück.

.Schritte
. Überprüfen Sie, ob die logischen Schnittstellen an ihren Home-Server und ihre Ports berichten:
+
`network interface show -is-home false`

+
Falls logische Schnittstellen als „false“ aufgeführt sind, werden sie wieder auf ihre ursprünglichen Ports zurückgesetzt:

+
`network interface revert -vserver * -lif *`

. Überprüfen Sie den Zustand Ihres Clusters.  Siehe die https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["So führen Sie eine Cluster-Integritätsprüfung mit einem Skript in ONTAP durch"^] KB-Artikel.
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local -auto-giveback true`





== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
