= Schritt 1: Schalten Sie den beeinträchtigten Regler aus
:allow-uri-read: 


Das NVRAM-Modul besteht aus der NVRAM12-Hardware und vor Ort austauschbaren DIMMs. Ein ausgefallenes NVRAM-Modul oder die DIMMs im NVRAM-Modul können Sie ersetzen. Um ein fehlerhaftes NVRAM-Modul zu ersetzen, müssen Sie das Modul aus dem Gehäuse entfernen, die DIMMs in das Ersatzmodul verschieben und das Ersatz-NVRAM-Modul in das Gehäuse einsetzen.

Alle anderen Komponenten im System müssen ordnungsgemäß funktionieren; andernfalls müssen Sie sich an https://support.netapp.com["NetApp Support"].

Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.



== Schritt 1: Schalten Sie den beeinträchtigten Regler aus

Fahren Sie den Regler herunter oder übernehmen Sie ihn mit einer der folgenden Optionen.

[role="tabbed-block"]
====
.Option 1: Die meisten Systeme
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Über diese Aufgabe
* Wenn Sie über ein SAN-System verfügen, müssen Sie Event-Meldungen ) für den beeinträchtigten Controller SCSI Blade überprüft haben  `cluster kernel-service show`. Mit dem `cluster kernel-service show` Befehl (im erweiterten Modus von priv) werden der Knotenname, der Quorum-Status dieses Node, der Verfügbarkeitsstatus dieses Node und der Betriebsstatus dieses Node angezeigt.
+
Jeder Prozess des SCSI-Blades sollte sich im Quorum mit den anderen Nodes im Cluster befinden. Probleme müssen behoben werden, bevor Sie mit dem Austausch fortfahren.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].


.Schritte
. Wenn AutoSupport aktiviert ist, können Sie die automatische Case-Erstellung durch Aufrufen einer AutoSupport Meldung unterdrücken: `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
+

NOTE: Wenn Sie sehen _Möchten Sie Auto-Giveback deaktivieren?_, geben Sie ein `y`.

. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung für das System oder Passwort
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
.Option 2: Controller befindet sich in einem MetroCluster
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].
* Wenn Sie über eine MetroCluster-Konfiguration verfügen, müssen Sie bestätigt haben, dass der MetroCluster-Konfigurationsstatus konfiguriert ist und dass die Nodes in einem aktivierten und normalen Zustand vorliegen (`metrocluster node show`).


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
====


== Schritt 2: Ersetzen Sie das NVRAM-Modul

Um das NVRAM-Modul auszutauschen, suchen Sie es in Steckplatz 4/5 im Gehäuse, und befolgen Sie die entsprechenden Schritte.

. Drücken Sie auf der Vorderseite des Gehäuses die Daumen, um jedes Laufwerk fest einzuschieben, bis Sie einen positiven Stopp spüren. Dadurch wird sichergestellt, dass die Laufwerke fest an der Mittelplatine des Gehäuses sitzen.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[drw a800-Laufwerk mit IEOPS 960]

. Gehen Sie zur Rückseite des Gehäuses. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Trennen Sie das Controller-Modul von der Stromversorgung, indem Sie das Controller-Modul ungefähr drei Zoll herausziehen:
+
.. Drücken Sie beide Verriegelungen des Controller-Moduls nach unten, und drehen Sie beide Verriegelungen gleichzeitig nach unten.
.. Ziehen Sie das Controller-Modul ungefähr 3 Zoll aus dem Chassis, um die Stromversorgung zu trennen.


. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Tasten an der Innenseite des Kabelführungs-Fachs herausziehen und nach unten drehen.
. Entfernen des Ziel-NVRAM-Moduls aus dem Chassis:
+
.. Drücken Sie die Taste für die Nockenverriegelung.
+
Die Nockentaste bewegt sich vom Gehäuse weg.

.. Drehen Sie die Nockenverriegelung so weit wie möglich.
.. Entfernen Sie das außer Betrieb genommene NVRAM-Modul aus dem Gehäuse, indem Sie den Finger in die Öffnung des Nockenhebels einhaken und das Modul aus dem Gehäuse ziehen.
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[Entfernen Sie das NVRAM12-Modul und die DIMMs]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Legende Nummer 1,Breite=30px"]
 a| 
Nockenverriegelungstaste



 a| 
image:../media/legend_icon_02.svg["Callout-Nummer 2,Breite=30 px"]
 a| 
DIMM-Verriegelungslaschen

|===


. Stellen Sie das NVRAM-Modul auf eine stabile Oberfläche.
. Entfernen Sie nacheinander die DIMMs aus dem außer Betrieb genommenen NVRAM-Modul, und setzen Sie sie in das Ersatz-NVRAM-Modul ein.
. Installieren Sie das Ersatz-NVRAM-Modul in das Chassis:
+
.. Richten Sie das Modul an den Kanten der Gehäuseöffnung in Steckplatz 4/5 aus.
.. Schieben Sie das Modul vorsichtig bis zum Anschlag in den Steckplatz, und drücken Sie dann die Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Schließen Sie das Controller-Modul wieder an die Stromversorgung an:
+
.. Drücken Sie das Controller-Modul fest in das Gehäuse, bis es auf die Mittelebene trifft und vollständig sitzt.
+
Die Verriegelungen steigen, wenn das Controller-Modul voll eingesetzt ist.

.. Drehen Sie die Verriegelungen nach oben in die verriegelte Position.


+

NOTE: Der Controller wird neu gebootet, sobald er vollständig im Chassis eingesetzt ist.

. Drehen Sie das Kabelführungs-Fach bis in die geschlossene Position.




== Schritt 3: Ersetzen Sie ein NVRAM-DIMM

Um NVRAM-DIMMs im NVRAM-Modul auszutauschen, müssen Sie das NVRAM-Modul entfernen und dann das Ziel-DIMM ersetzen.

. Drücken Sie auf der Vorderseite des Gehäuses die Daumen, um jedes Laufwerk fest einzuschieben, bis Sie einen positiven Stopp spüren. Dadurch wird sichergestellt, dass die Laufwerke fest an der Mittelplatine des Gehäuses sitzen.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[drw a800-Laufwerk mit IEOPS 960]

. Gehen Sie zur Rückseite des Gehäuses. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Trennen Sie das Controller-Modul von der Stromversorgung, indem Sie das Controller-Modul ungefähr drei Zoll herausziehen:
+
.. Drücken Sie beide Verriegelungen des Controller-Moduls nach unten, und drehen Sie beide Verriegelungen gleichzeitig nach unten.
.. Ziehen Sie das Controller-Modul ungefähr 3 Zoll aus dem Chassis, um die Stromversorgung zu trennen.


. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Stifte an den Enden des Fachs vorsichtig herausziehen und das Fach nach unten drehen.
. Entfernen des Ziel-NVRAM-Moduls aus dem Chassis:
+
.. Drücken Sie die Nockentaste.
+
Die Nockentaste bewegt sich vom Gehäuse weg.

.. Drehen Sie die Nockenverriegelung so weit wie möglich.
.. Entfernen Sie das NVRAM-Modul aus dem Gehäuse, indem Sie den Finger in die Öffnung des Nockenhebels einhaken und das Modul aus dem Gehäuse ziehen.
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[Entfernen Sie das NVRAM12-Modul und die DIMMs]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Legende Nummer 1,Breite=30px"]
| Nockenverriegelungstaste 


 a| 
image:../media/legend_icon_02.svg["Callout-Nummer 2,Breite=30 px"]
 a| 
DIMM-Verriegelungslaschen

|===


. Stellen Sie das NVRAM-Modul auf eine stabile Oberfläche.
. Machen Sie das DIMM-Modul ausfindig, das im NVRAM-Modul ersetzt werden soll.
+

NOTE: Verwenden Sie das FRU-Kartenetikett auf der Seite des NVRAM-Moduls, um die Position der DIMM-Steckplätze 1 und 2 zu bestimmen.

. Entfernen Sie das DIMM-Modul, indem Sie die DIMM-Sperrklinken nach unten drücken und das DIMM aus dem Sockel heben.
. Installieren Sie das ErsatzDIMM, indem Sie das DIMM-Modul am Sockel ausrichten und das DIMM vorsichtig in den Sockel schieben, bis die Verriegelungslaschen einrasten.
. Installieren Sie das NVRAM-Modul in das Chassis:
+
.. Schieben Sie das Modul vorsichtig in den Steckplatz, bis die Nockenverriegelung mit dem E/A-Nockenbolzen einrastet, und drehen Sie dann die Nockenverriegelung bis zum Anschlag nach oben, um das Modul zu verriegeln.


. Schließen Sie das Controller-Modul wieder an die Stromversorgung an:
+
.. Drücken Sie das Controller-Modul fest in das Gehäuse, bis es auf die Mittelebene trifft und vollständig sitzt.
+
Die Verriegelungen steigen, wenn das Controller-Modul voll eingesetzt ist.

.. Drehen Sie die Verriegelungen nach oben in die verriegelte Position.


+

NOTE: Der Controller wird neu gebootet, sobald er vollständig im Chassis eingesetzt ist.

. Drehen Sie das Kabelführungs-Fach bis in die geschlossene Position.




== Schritt 4: Festplatten neu zuweisen

Sie müssen die Änderung der System-ID bestätigen, wenn Sie den Controller booten, und dann überprüfen, ob die Änderung implementiert wurde.


CAUTION: Eine Neuzuweisung der Festplatte ist nur erforderlich, wenn das NVRAM-Modul ersetzt wird. Dies gilt nicht für den Austausch des NVRAM-DIMM.

.Schritte
. Wenn sich der Controller im Wartungsmodus befindet (es wird die Eingabeaufforderung angezeigt `*>` ), beenden Sie den Wartungsmodus und fahren Sie mit der LOADER-Eingabeaufforderung _stop_ fort
. Starten Sie an der LOADER-Eingabeaufforderung auf dem Controller den Controller, und geben Sie bei der Eingabeaufforderung „_y_“ ein, um die System-ID aufgrund einer nicht übereinstimmenden System-ID zu überschreiben.
. Warten Sie, bis Sie auf die Rückgabe warten... Die Meldung wird auf der Konsole des Controllers mit dem Ersatzmodul angezeigt und dann vom fehlerfreien Controller aus überprüft, ob die neue Partnersystem-ID automatisch zugewiesen wurde: _Storage Failover show_
+
In der Befehlsausgabe sollte eine Meldung angezeigt werden, dass sich die System-ID auf dem beeinträchtigten Controller geändert hat und die korrekten alten und neuen IDs angezeigt werden. Im folgenden Beispiel wurde node2 ersetzt und hat eine neue System-ID von 151759706.

+
[listing]
----
node1:> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Geben Sie den Controller zurück:
+
.. Geben Sie auf dem funktionstüchtigen Controller den Storage des ausgetauschten Controllers zurück: _Storage Failover Giveback -ofnode Replacement_Node_Name_
+
Der Controller nimmt seinen Storage wieder auf und schließt den Bootvorgang ab.

+
Wenn Sie aufgefordert werden, die System-ID aufgrund einer nicht übereinstimmenden System-ID zu überschreiben, geben Sie _y_ ein.

+

NOTE: Wenn das Rückübertragung ein Vetorecht ist, können Sie erwägen, das Vetos außer Kraft zu setzen.

+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted["Manuelle Giveback-Befehle"^] Thema, um das Veto zu überschreiben.

.. Nach Abschluss der Rückgabe muss sichergestellt werden, dass das HA-Paar in einem ordnungsgemäßen Zustand ist und dass ein Takeover möglich ist: _Storage Failover show_
+
Die Ausgabe von der `storage failover show` Befehl sollte nicht die in der Partnernachricht geänderte System-ID enthalten.



. Überprüfen Sie, ob die Festplatten ordnungsgemäß zugewiesen wurden: `storage disk show -ownership`
+
Die Laufwerke, die zum Controller gehören, sollten die neue System-ID anzeigen. Im folgenden Beispiel zeigen die Festplatten von node1 jetzt die neue System-ID, 151759706:

+
[listing]
----
node1:> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        151759706  151759706  -       151759706 Pool0
1.0.1  aggr0_1  node1 node1           151759706  151759706  -       151759706 Pool0
.
.
.
----
. Wenn sich das System in einer MetroCluster-Konfiguration befindet, überwachen Sie den Status des Controllers: _MetroCluster Node show_
+
Die MetroCluster-Konfiguration dauert einige Minuten nach dem Austausch und kehrt in den normalen Zustand zurück. Zu diesem Zeitpunkt zeigt jeder Controller einen konfigurierten Status mit aktivierter DR-Spiegelung und einem normalen Modus an. Der `metrocluster node show -fields node-systemid` In der Befehlsausgabe wird die alte System-ID angezeigt, bis die MetroCluster-Konfiguration den normalen Status aufweist.

. Wenn der Controller in einer MetroCluster-Konfiguration befindet, überprüfen Sie abhängig vom Status des MetroCluster, ob im Feld für die DR-Home-ID der ursprüngliche Eigentümer der Festplatte angezeigt wird, wenn der ursprüngliche Eigentümer ein Controller am Disaster-Standort ist.
+
Dies ist erforderlich, wenn beide der folgenden Werte erfüllt sind:

+
** Die MetroCluster Konfiguration befindet sich in einem Switchover-Zustand.
** Der Controller ist der aktuelle Besitzer der Festplatten am Notfallstandort.
+
Siehe https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Änderungen am Festplattenbesitz während HA Takeover und MetroCluster Switchover in einer MetroCluster Konfiguration mit vier Nodes"] Finden Sie weitere Informationen.



. Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, vergewissern Sie sich, dass für jeden Controller Folgendes konfiguriert ist: _MetroCluster Node show - Fields Configuration-State_
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Vergewissern Sie sich, dass die erwarteten Volumes für jeden Controller vorhanden sind: `vol show -node node-name`
. Wenn die Speicherverschlüsselung aktiviert ist, müssen Sie die Funktion wiederherstellen.
. Wenn Sie die automatische Übernahme beim Neustart deaktiviert haben, aktivieren Sie sie über den funktionstüchtigen Controller: _Storage Failover modify -Node Replacement-Node-Name -onreboot true_
. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung mit dem Befehl wiederherstellen/zurücknehmen. `system node autosupport invoke -node * -type all -message MAINT=END`




== Schritt 5: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://mysupport.netapp.com/site/info/rma["Teilerückgabe  Austausch"] Seite für weitere Informationen.
