= Schritt: Überprüfen Sie HA-Konfigurationseinstellungen
:allow-uri-read: 




== Schritt: Überprüfen Sie HA-Konfigurationseinstellungen

Sie müssen die überprüfen `HA` Status des Controller-Moduls und, falls erforderlich, aktualisieren Sie den Status entsprechend Ihrer Systemkonfiguration.

. Booten im Wartungsmodus: `boot_ontap maint`
+
.. Geben Sie ein `y`, wenn _Continue with Boot?_ angezeigt wird.
+
Wenn die Warnmeldung _System ID Mismatch_ angezeigt wird, geben Sie ein `y`.



. Geben Sie den Inhalt der Anzeige ein `sysconfig -v` und erfassen Sie diesen.
+

NOTE: Wenn Sie _PERSONALITY MISMATCH_ sehen, wenden Sie sich an den Kundendienst.

. Vergleichen Sie in der `sysconfig -v` Ausgabe die Adapterkarteninformationen mit den Karten und Positionen im Ersatzcontroller.
. Vergewissern Sie sich, dass alle Komponenten denselben `HA` Status aufweisen: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemstatus des Controller-Moduls nicht mit Ihrer Systemkonfiguration übereinstimmt, legen Sie den Status für das Controller-Modul fest `HA`: `ha-config modify controller ha`
+
Für den HA-Status kann einer der folgenden Werte verwendet werden:

+
** `ha`
** `mcc` (Nicht unterstützt)
** `mccip` (In ASA Systemen nicht unterstützt)
** `non-ha` (Nicht unterstützt)


. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`




== Schritt 2: Überprüfen Sie die Datenträgerliste

. Überprüfen Sie, ob der Adapter die Pfade zu allen Festplatten mit auflistet `storage show disk -p`.
+
Wenn Sie Probleme sehen, überprüfen Sie die Verkabelung, und setzen Sie die Kabel wieder ein.

. Beenden Sie den Wartungsmodus: `halt`.

