= Schritt 1: Schalten Sie den beeinträchtigten Regler aus
:allow-uri-read: 


Gehen Sie wie folgt vor, um ein fehlerhaftes I/O-Modul zu ersetzen.

* Sie können dieses Verfahren mit allen Versionen von ONTAP verwenden, die von Ihrem Speichersystem unterstützt werden.
* Alle anderen Komponenten des Storage-Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.




== Schritt 1: Schalten Sie den beeinträchtigten Regler aus

Fahren Sie den Regler herunter oder übernehmen Sie ihn mit einer der folgenden Optionen.

[role="tabbed-block"]
====
.Option 1: Die meisten Systeme
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

.Über diese Aufgabe
* Wenn Sie über ein SAN-System verfügen, müssen Sie Event-Meldungen ) für den beeinträchtigten Controller SCSI Blade überprüft haben  `cluster kernel-service show`. Mit dem `cluster kernel-service show` Befehl (im erweiterten Modus von priv) werden der Knotenname, der Quorum-Status dieses Node, der Verfügbarkeitsstatus dieses Node und der Betriebsstatus dieses Node angezeigt.
+
Jeder Prozess des SCSI-Blades sollte sich im Quorum mit den anderen Nodes im Cluster befinden. Probleme müssen behoben werden, bevor Sie mit dem Austausch fortfahren.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].


.Schritte
. Wenn AutoSupport aktiviert ist, können Sie die automatische Case-Erstellung durch Aufrufen einer AutoSupport Meldung unterdrücken: `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
+

NOTE: Wenn Sie sehen _Möchten Sie Auto-Giveback deaktivieren?_, geben Sie ein `y`.

. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung für das System oder Passwort
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
.Option 2: Controller befindet sich in einem MetroCluster
--
Um den beeinträchtigten Controller herunterzufahren, müssen Sie den Status des Controllers bestimmen und gegebenenfalls den Controller übernehmen, damit der gesunde Controller weiterhin Daten aus dem beeinträchtigten Reglerspeicher bereitstellen kann.

* Wenn Sie über ein Cluster mit mehr als zwei Nodes verfügen, muss es sich im Quorum befinden. Wenn sich das Cluster nicht im Quorum befindet oder ein gesunder Controller FALSE anzeigt, um die Berechtigung und den Zustand zu erhalten, müssen Sie das Problem korrigieren, bevor Sie den beeinträchtigten Controller herunterfahren; siehe link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Synchronisieren eines Node mit dem Cluster"^].
* Wenn Sie über eine MetroCluster-Konfiguration verfügen, müssen Sie bestätigt haben, dass der MetroCluster-Konfigurationsstatus konfiguriert ist und dass die Nodes in einem aktivierten und normalen Zustand vorliegen (`metrocluster node show`).


.Schritte
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die automatische Erstellung eines Cases durch Aufrufen einer AutoSupport Meldung: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Die folgende AutoSupport Meldung unterdrückt die automatische Erstellung von Cases für zwei Stunden: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deaktivieren Sie das automatische Giveback von der Konsole des gesunden Controllers: `storage failover modify –node local -auto-giveback false`
. Nehmen Sie den beeinträchtigten Controller zur LOADER-Eingabeaufforderung:
+
[cols="1,2"]
|===
| Wenn der eingeschränkte Controller angezeigt wird... | Dann... 


 a| 
Die LOADER-Eingabeaufforderung
 a| 
Fahren Sie mit dem nächsten Schritt fort.



 a| 
Warten auf Giveback...
 a| 
Drücken Sie Strg-C, und antworten Sie dann `y` Wenn Sie dazu aufgefordert werden.



 a| 
Eingabeaufforderung des Systems oder Passwort (Systempasswort eingeben)
 a| 
Übernehmen oder stoppen Sie den beeinträchtigten Regler von der gesunden Steuerung: `storage failover takeover -ofnode _impaired_node_name_`

Wenn der Regler „beeinträchtigt“ auf Zurückgeben wartet... anzeigt, drücken Sie Strg-C, und antworten Sie dann `y`.

|===


--
====


== Schritt 2: Ersetzen Sie ein fehlerhaftes I/O-Modul

Um ein E/A-Modul zu ersetzen, suchen Sie es innerhalb des Controller-Moduls und befolgen Sie die Schritte.

. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Trennen Sie alle Kabel vom Ziel-E/A-Modul.
+
Achten Sie darauf, dass Sie die Kabel so beschriften, dass Sie wissen, woher sie stammen.

. Drehen Sie das Kabelführungs-Fach nach unten, indem Sie die Tasten an der Innenseite des Kabelführungs-Fachs herausziehen und nach unten drehen.
. Entfernen Sie das E/A-Modul aus dem Controller-Modul:
+

NOTE: Diese Abbildung zeigt das Entfernen eines horizontalen und vertikalen E/A-Moduls. In der Regel entfernen Sie nur ein I/O-Modul.

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Entfernen Sie das E/A-Modul]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Legende Nummer 1,Breite=30px"]
 a| 
Nockenverriegelungstaste

|===
+
.. Drücken Sie die Taste für die Nockenverriegelung.
+
Die Nockenverriegelung bewegt sich vom Controller-Modul weg.

.. Drehen Sie die Nockenverriegelung so weit wie möglich nach unten. Drehen Sie bei horizontalen Modulen den Nocken so weit wie möglich vom Modul weg.
.. Entfernen Sie das Modul vom Controller-Modul, indem Sie den Finger in die Öffnung des Nockenhebels einhaken und das Modul aus dem Controller-Modul herausziehen.
+
Stellen Sie sicher, dass Sie den Steckplatz verfolgen, in dem sich das I/O-Modul befand.



. Legen Sie das E/A-Modul beiseite.
. Setzen Sie das Ersatz-E/A-Modul in den Zielsteckplatz ein:
+
.. Richten Sie das E/A-Modul an den Kanten des Schlitzes aus.
.. Schieben Sie das Modul vorsichtig in den Steckplatz bis zum Controller-Modul, und drehen Sie dann die Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Verkabeln Sie das E/A-Modul.
. Wiederholen Sie die Schritte zum Entfernen und Installieren, um zusätzliche Module für den Controller zu ersetzen.
. Drehen Sie das Kabelführungs-Fach in die verriegelte Position.




== Schritt 3: Starten Sie den Controller neu

Nachdem Sie ein I/O-Modul ersetzt haben, müssen Sie das Controller-Modul neu starten.


NOTE: Wenn das neue I/O-Modul nicht das gleiche Modell wie das ausgefallene Modul ist, müssen Sie zuerst den BMC neu booten.

.Schritte
. Starten Sie den BMC neu, wenn das Ersatzmodul nicht dasselbe Modell wie das alte Modul ist:
+
.. Wechseln Sie an der Eingabeaufforderung des LOADERS in den erweiterten Berechtigungsmodus: _Set Privilege Advanced_
.. Starten Sie BMC: _Sp reboot_ neu


. Starten Sie an der LOADER-Eingabeaufforderung den Node: _Bye_ neu
+

NOTE: Dadurch werden die I/O-Karten und andere Komponenten neu initialisiert und der Node neu gestartet.

+

NOTE: Achten Sie darauf, den Wartungsmodus nach Abschluss der Konvertierung zu beenden.

. Kehren Sie den Knoten wieder in den normalen Betrieb zurück: _Storage Failover Giveback -ofnode Impaired_Node_Name_
. Wenn das automatische Giveback deaktiviert wurde, aktivieren Sie es erneut: _Storage Failover modify -Node local -Auto-Giveback true_




== Schritt 4: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://mysupport.netapp.com/site/info/rma["Teilerückgabe  Austausch"] Seite für weitere Informationen.
