= Schritt 1: Starten Sie die Controller und geben Sie die Controller zurück
:allow-uri-read: 




== Schritt 1: Starten Sie die Controller und geben Sie die Controller zurück

Nachdem die Controller neu gebootet wurden, booten Sie ONTAP und geben Sie die Controller zurück.

.Schritte
. Überprüfen Sie die Konsolenausgabe:
+
.. Wenn der Controller bei der LOADER-Eingabeaufforderung stoppt, booten Sie den Controller mit dem `boot_ontap` Befehl.
.. Sobald der Knoten hochfährt und die Anmeldeaufforderung anzeigt, melden Sie sich beim Partner-Controller an und überprüfen Sie, ob der ersetzte Controller zur Rückgabe bereit ist mit `storage failover show` Befehl.


. Giveback durchführen:
+
.. Schließen Sie das Konsolenkabel an den Partner Controller an.
.. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
*** Wenn die _Anmeldeaufforderung_ angezeigt wird, fahren Sie mit dem nächsten Schritt fort.
*** Wenn keine Anmeldeaufforderung angezeigt wird, melden Sie sich beim Partnerknoten an.


.. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.  Weitere Informationen zu Berechtigungsstufen finden Sie unterlink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Verstehen Sie die Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

.. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und prüfen Sie den Failover-Status und den Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

.. Wenn die HA-Interconnect-Links deaktiviert wurden, stellen Sie sie wieder her:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

.. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. Wenn die automatische Rückgabe deaktiviert war, aktivieren Sie sie erneut: `storage failover modify -node _impaired_node_name_ -auto-giveback-of _true_`
.. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen: `system node autosupport invoke -node * -type all -message MAINT=END`






== Schritt 2: Überprüfen Sie den Zustand des Storage-Systems

Nachdem der Controller den Speicher zurückgegeben hat, überprüfen Sie den Zustand mit https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .

.Schritte
. Nachdem die Rückgabe abgeschlossen ist, führen Sie Active IQ Config Advisor aus, um den Zustand des Storage-Systems zu überprüfen.
. Beheben Sie alle Probleme, die auftreten.




== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
