= 
:allow-uri-read: 


.Bevor Sie beginnen
* Für OKM benötigen Sie die clusterweite Passphrase und die Sicherungsdaten.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** Datei /cfcard/kmip/servers.cfg.
** Datei /cfcard/kmip/certs/Client.crt.
** Datei /cfcard/kmip/certs/client.key.
** Datei /cfcard/kmip/certs/CA.pem.




.Schritte
. Geben Sie an der Loader-Eingabeaufforderung den Befehl ein:
+
`boot_recovery -partner`

+
Auf dem Bildschirm wird die folgende Meldung angezeigt:

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Überwachen Sie den Wiederherstellungsprozess für die Installation der Startmedien.
+
Der Vorgang ist abgeschlossen und zeigt die `Installation complete` Meldung an.

. Das System prüft nach Verschlüsselung und Verschlüsselungstyp und zeigt eine von zwei Meldungen an. Je nachdem, welche Meldung angezeigt wird, führen Sie eine der folgenden Aktionen durch:
+

IMPORTANT: Gelegentlich kann der Prozess möglicherweise nicht erkennen, ob der Schlüsselmanager auf dem System konfiguriert ist. Es wird eine Fehlermeldung angezeigt, gefragt, ob Key Manager für das System konfiguriert ist, und dann gefragt, welcher Schlüsselmanager konfiguriert ist. Der Vorgang wird fortgesetzt, nachdem Sie das Problem behoben haben.

+
.Beispiel für Eingabeaufforderungen zum Suchen von Konfigurationsfehlern anzeigen
[%collapsible]
====
....
Error when fetching key manager config from partner ${partner_ip}: ${status}

Has key manager been configured on this system

Is the key manager onboard

....
====
+
[cols="1,2"]
|===
| Wenn diese Meldung angezeigt wird... | Tun Sie das... 


 a| 
`key manager is not configured. Exiting.`
 a| 
Auf dem System ist keine Verschlüsselung konfiguriert. Führen Sie die folgenden Schritte aus:

.. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
*** Wenn die Anmeldeaufforderung angezeigt wird, fahren Sie mit Schritt 4 fort.
*** Wenn keine Anmeldeaufforderung angezeigt wird, melden Sie sich beim Partnerknoten an und fahren Sie mit Schritt 4 fort.


.. Fahren Sie mit Schritt 6 fort, um die automatische Rückgabe zu aktivieren, falls sie deaktiviert war.




 a| 
`key manager is configured.`
 a| 
Fahren Sie mit Schritt 5 fort, um den entsprechenden Schlüsselmanager wiederherzustellen.

Der Knoten greift auf das Startmenü zu und führt Folgendes aus:

** Option 10 für Systeme mit Onboard Key Manager (OKM).
** Option 11 für Systeme mit externem Key Manager (EKM).


|===
. Wenn auf dem System keine Verschlüsselung installiert ist und die Anmeldeaufforderung nicht angezeigt wird. Führen Sie die folgenden Schritte aus:
+
.. Geben Sie nur die Wurzel mit der Option „override-destination-checks“ zurück:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Dieser Befehl ist nur im Diagnosemodus verfügbar. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Berechtigungsstufen für ONTAP CLI-Befehle"^] .

+
Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].

.. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und prüfen Sie den Failover-Status und den Giveback-Status:
+
`storage failover show`Und `storage failover show-giveback`

+

NOTE: Der folgende Befehl ist nur auf der Berechtigungsebene „Diagnosemodus“ verfügbar.

.. Wenn Sie ONTAP 9.17.1 ausführen und die HA-Internconnect-Links deaktiviert wurden, aktivieren Sie sie erneut:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

+

NOTE: Wenn Sie 9.18.1 oder höher ausführen, überspringen Sie den obigen Schritt und fahren Sie mit dem nächsten Schritt fort.

.. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`



. Wählen Sie für Systeme mit konfiguriertem Schlüsselmanager den entsprechenden Schlüsselmanager-Wiederherstellungsprozess aus.
+
[role="tabbed-block"]
====
.Onboard Key Manager (OKM)
--
Wenn OKM erkannt wird, zeigt das System die folgende Meldung an und beginnt mit der Ausführung der Startmenüoption 10.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Geben Sie an der Eingabeaufforderung ein `Y`, um zu bestätigen, dass Sie den OKM-Wiederherstellungsprozess starten möchten.
.. Geben Sie bei der entsprechenden Aufforderung Folgendes ein:
+
... Die Passphrase
... Die Passphrase erneut, wenn Sie zur Bestätigung aufgefordert werden
... Sicherungsdaten für den integrierten Schlüsselmanager
+
.Beispiel für Eingabeaufforderungen für Passphrasen und Sicherungsdaten anzeigen
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END ACKUP-----
....
=====


.. Überwachen Sie den Recovery-Prozess weiterhin, wenn die entsprechenden Dateien vom Partner-Node wiederhergestellt werden.
+
Nach Abschluss der Wiederherstellung wird der Node neu gebootet. Die folgenden Meldungen weisen auf eine erfolgreiche Wiederherstellung hin:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. Wenn der Node neu gebootet wird, überprüfen Sie, ob die Boot-Medien erfolgreich wiederhergestellt wurden, indem Sie bestätigen, dass das System wieder online und funktionsfähig ist.
.. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Wenn die HA-Verbindungslinks getrennt wurden, aktivieren Sie sie erneut, um die automatische Rückgabe fortzusetzen:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



.. Nachdem der Partner-Node vollständig eingerichtet ist und Daten bereitstellt, synchronisieren Sie die OKM-Schlüssel über das Cluster hinweg.
+
`security key-manager onboard sync`



--
.Externer Schlüsselmanager (EKM)
--
Wenn EKM erkannt wird, zeigt das System die folgende Meldung an und beginnt mit der Ausführung der Startmenüoption 11.

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. Je nachdem, ob der Schlüssel erfolgreich wiederhergestellt wurde, führen Sie eine der folgenden Aktionen durch:
+
*** Wenn Sie sehen `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` In der Ausgabe wurde die EKM-Konfiguration erfolgreich wiederhergestellt.
+
Der Prozess versucht, die entsprechenden Dateien vom Partnerknoten wiederherzustellen und startet den Knoten neu.  Fahren Sie mit Schritt d fort.

*** Wenn der Schlüssel nicht erfolgreich wiederhergestellt werden kann, wird das System angehalten und zeigt an, dass der Schlüssel nicht wiederhergestellt werden konnte.  Die Fehler- und Warnmeldungen werden angezeigt.  Sie müssen den Wiederherstellungsprozess erneut ausführen:
+
`boot_recovery -partner`

+
.Zeigt ein Beispiel für Fehler und Warnmeldungen bei der Schlüsselwiederherstellung an
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. Wenn der Node neu gebootet wird, überprüfen Sie, ob die Boot-Medien erfolgreich wiederhergestellt wurden, indem Sie bestätigen, dass das System wieder online und funktionsfähig ist.
.. Wiederherstellung des normalen Betriebs des Controllers durch Zurückgeben des Speichers:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Wenn die HA-Verbindungslinks getrennt wurden, aktivieren Sie sie erneut, um die automatische Rückgabe fortzusetzen:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`





--
====


. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local auto-giveback-of true`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


