= 
:allow-uri-read: 


Sie können das ONTAP-Image (Boot-Medien-Recovery) vom Partner-Node mithilfe des `boot_recovery -partner` Befehls für ASA r2-Plattformen mit ONTAP 9.16.0 und höher wiederherstellen.

.Bevor Sie beginnen
Wenn Sie einen Node booten und die Boot-Medien auf diesem Node beschädigt sind, werden an der Loader-Eingabeaufforderung die folgenden Meldungen und der Boot-Prozess mit stop angezeigt:

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
Wenn diese Meldung angezeigt wird, müssen Sie das ONTAP-Image wiederherstellen

.Schritte
. Geben Sie an der Loader-Eingabeaufforderung den Befehl _Boot_Recovery -Partner_ ein.
+
Auf dem Bildschirm wird die Meldung angezeigt `Starting boot media recovery (BMR) process press Ctrl-C to abort...` und die ersten Überprüfungen werden gestartet.

. Überwachen Sie den Prozess, während Loader die lokalen Cluster-Ports konfiguriert und Netzboot über ausführt `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`.
+
Sobald Netzboot ausgeführt wird, `Starting BMR ...` wird auf dem Bildschirm angezeigt, und der Vorgang schließt den Installationsvorgang ab.

+
.. Wenn Key Manager nicht konfiguriert ist, wird die folgende Meldung angezeigt:
+
....
key manager is not configured. Exiting.
....
.. Wenn die folgende Meldung angezeigt wird, ist Onboard Key Manager (OKM) konfiguriert:
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
Gehen Sie zu, um den Wiederherstellungsprozess abzuschließen.

.. Wenn die folgende Meldung angezeigt wird, wird External Key Manager (EKM) konfiguriert. Gehen Sie zum EKM-Thema und schließen Sie den Wiederherstellungsprozess ab:
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. Überwachen Sie den BMR-Prozess bei der Ausführung von Wiederherstellungskonfiguration, Env-Datei, mdb und rdb vom Partner.
. Der Knoten wird neu gestartet und BMR ist abgeschlossen, wenn Folgendes angezeigt wird:


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....