= 
:allow-uri-read: 


[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Sie müssen die ausgefallene Komponente durch eine FRU-Ersatz-Komponente ersetzen, die dieselbe Kapazität hat wie Sie von NetApp erhalten.
* Prüfen Sie, ob die e0S-Schnittstelle (e0M wrench port) am betroffenen Controller nicht defekt ist.
+
Der e0M-Port wird während des automatisierten Boot-Wiederherstellungsprozesses zur Kommunikation zwischen den beiden Controllern verwendet.

* Für OKM benötigen Sie die clusterweite Passphrase und auch die Sicherungsdaten.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** Datei /cfcard/kmip/servers.cfg.
** Datei /cfcard/kmip/certs/Client.crt.
** Datei /cfcard/kmip/certs/client.key.
** Datei /cfcard/kmip/certs/CA.pem.


* Es ist wichtig, die Befehle auf den richtigen Controller anzuwenden, wenn Sie das beschädigte Startmedium ersetzen:
+
** Der _beschädigte Controller_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _gesunde Controller_ ist der HA-Partner des beeinträchtigten Controllers.



