= Überprüfen der NVE-Konfiguration
:allow-uri-read: 


Vor dem Herunterfahren des beeinträchtigten Controllers müssen Sie prüfen, ob im System NetApp Volume Encryption (NVE) oder NetApp Storage Encryption (NSE) aktiviert ist. In diesem Fall müssen Sie die Konfiguration überprüfen.

.Schritte
. Schließen Sie das Konsolenkabel an den beeinträchtigten Controller an.
. Überprüfen Sie, ob NVE für alle Volumes im Cluster konfiguriert ist: `volume show -is-encrypted true`
+
Wenn im Output irgendwelche Volumes aufgelistet werden, wird NVE konfiguriert, und Sie müssen die NVE-Konfiguration überprüfen. Wenn keine Volumes aufgeführt sind, prüfen Sie, ob NSE konfiguriert ist.

. Überprüfen Sie, ob NSE konfiguriert ist: `storage encryption disk show`
+
** Wenn in der Befehlsausgabe die Laufwerkdetails mit Informationen zu Modus und Schlüssel-ID aufgeführt werden, wird NSE konfiguriert und Sie müssen die NSE-Konfiguration überprüfen.
** Wenn NVE und NSE nicht konfiguriert sind, kann der beeinträchtigte Controller sicher heruntergefahren werden.






== Überprüfen der NVE-Konfiguration

.Schritte
. Anzeigen der Schlüssel-IDs der Authentifizierungsschlüssel, die auf den Schlüsselverwaltungsservern gespeichert sind: `security key-manager query`
+
** Wenn der `Restored` Spalte wird angezeigt `yes` Außerdem werden alle Schlüsselmanager angezeigt `available`, Es ist sicher, den beeinträchtigten Regler herunterzufahren.
** Wenn der `Restored` Spalte zeigt alle anderen als an `yes`, Oder wenn ein Schlüsselmanager angezeigt wird `unavailable`, Sie müssen einige zusätzliche Schritte.
** Wenn die Meldung angezeigt wird dieser Befehl wird nicht unterstützt, wenn die integrierte Schlüsselverwaltung aktiviert ist, müssen Sie einige weitere Schritte durchführen.


. Wenn der `Restored` Spalte hat andere als angezeigt `yes`, Oder wenn ein Schlüsselmanager angezeigt `unavailable`:
+
.. Abrufen und Wiederherstellen aller Authentifizierungsschlüssel und der zugehörigen Schlüssel-IDs: `security key-manager restore -address *`
+
Wenn der Befehl fehlschlägt, wenden Sie sich an den NetApp Support.

+
http://mysupport.netapp.com/["mysupport.netapp.com"]

.. Überprüfen Sie das `Restored` Spalte wird angezeigt `yes` Für alle Authentifizierungsschlüssel und dass alle Schlüsselmanager angezeigt werden `available`: `security key-manager query`
.. Schalten Sie den beeinträchtigten Regler aus.


. Wenn Sie die Meldung gesehen haben dieser Befehl wird nicht unterstützt, wenn die integrierte Schlüsselverwaltung aktiviert ist, zeigen Sie die im Onboard-Schlüsselmanager gespeicherten Schlüssel an: `security key-manager key show -detail`
+
.. Wenn der `Restored` Spalte wird angezeigt `yes` Manuelle Sicherung der Informationen zum Onboard-Verschlüsselungsmanagement:
+
*** Wechseln Sie zum erweiterten Berechtigungsebene-Modus, und geben Sie ein `y` Wenn Sie dazu aufgefordert werden, fortzufahren: `set -priv advanced`
*** Geben Sie den Befehl ein, um die OKM Backup-Informationen anzuzeigen: `security key-manager backup show`
*** Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei. Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.
*** Zurück zum Admin-Modus: `set -priv admin`
*** Schalten Sie den beeinträchtigten Regler aus.


.. Wenn der `Restored` Spalte zeigt alle anderen als an `yes`:
+
*** Führen Sie den Setup-Assistenten für den Schlüsselmanager aus: `security key-manager setup -node target/impaired node name`
+

NOTE: Geben Sie an der Eingabeaufforderung die integrierte Passphrase für das Verschlüsselungsmanagement des Kunden ein. Wenn die Passphrase nicht angegeben werden kann, wenden Sie sich an http://mysupport.netapp.com/["mysupport.netapp.com"]

*** Überprüfen Sie das `Restored` Spalte wird angezeigt `yes` Für alle Authentifizierungsschlüssel: `security key-manager key show -detail`
*** Wechseln Sie zum erweiterten Berechtigungsebene-Modus, und geben Sie ein `y` Wenn Sie dazu aufgefordert werden, fortzufahren: `set -priv advanced`
*** Geben Sie den Befehl ein, um die OKM Backup-Informationen anzuzeigen: `security key-manager backup show`
*** Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei. Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.
*** Zurück zum Admin-Modus: `set -priv admin`
*** Sie können den Controller sicher herunterfahren.








== Überprüfen der NSE-Konfiguration

.Schritte
. Anzeigen der Schlüssel-IDs der Authentifizierungsschlüssel, die auf den Schlüsselverwaltungsservern gespeichert sind: `security key-manager query`
+
** Wenn der `Restored` Spalte wird angezeigt `yes` Außerdem werden alle Schlüsselmanager angezeigt `available`, Es ist sicher, den beeinträchtigten Regler herunterzufahren.
** Wenn der `Restored` Spalte zeigt alle anderen als an `yes`, Oder wenn ein Schlüsselmanager angezeigt wird `unavailable`, Sie müssen einige zusätzliche Schritte.
** Wenn die Meldung angezeigt wird dieser Befehl wird nicht unterstützt, wenn die integrierte Schlüsselverwaltung aktiviert ist, müssen Sie einige weitere Schritte durchführen


. Wenn der `Restored` Spalte hat andere als angezeigt `yes`, Oder wenn ein Schlüsselmanager angezeigt `unavailable`:
+
.. Abrufen und Wiederherstellen aller Authentifizierungsschlüssel und der zugehörigen Schlüssel-IDs: `security key-manager restore -address *`
+
Wenn der Befehl fehlschlägt, wenden Sie sich an den NetApp Support.

+
http://mysupport.netapp.com/["mysupport.netapp.com"]

.. Überprüfen Sie das `Restored` Spalte wird angezeigt `yes` Für alle Authentifizierungsschlüssel und dass alle Schlüsselmanager angezeigt werden `available`: `security key-manager query`
.. Schalten Sie den beeinträchtigten Regler aus.


. Wenn Sie die Meldung gesehen haben dieser Befehl wird nicht unterstützt, wenn die integrierte Schlüsselverwaltung aktiviert ist, zeigen Sie die im Onboard-Schlüsselmanager gespeicherten Schlüssel an: `security key-manager key show -detail`
+
.. Wenn der `Restored` Spalte wird angezeigt `yes`, Manuelle Sicherung der Informationen zum Onboard-Verschlüsselungsmanagement:
+
*** Wechseln Sie zum erweiterten Berechtigungsebene-Modus, und geben Sie ein `y` Wenn Sie dazu aufgefordert werden, fortzufahren: `set -priv advanced`
*** Geben Sie den Befehl ein, um die OKM Backup-Informationen anzuzeigen:  `security key-manager backup show`
*** Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei. Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.
*** Zurück zum Admin-Modus: `set -priv admin`
*** Schalten Sie den beeinträchtigten Regler aus.


.. Wenn der `Restored` Spalte zeigt alle anderen als an `yes`:
+
*** Führen Sie den Setup-Assistenten für den Schlüsselmanager aus: `security key-manager setup -node target/impaired node name`
+

NOTE: Geben Sie die OKM-Passphrase des Kunden an der Eingabeaufforderung ein. Wenn die Passphrase nicht angegeben werden kann, wenden Sie sich an http://mysupport.netapp.com/["mysupport.netapp.com"]

*** Überprüfen Sie das `Restored` In der Spalte wird angezeigt `yes` Für alle Authentifizierungsschlüssel: `security key-manager key show -detail`
*** Wechseln Sie zum erweiterten Berechtigungsebene-Modus, und geben Sie ein `y` Wenn Sie dazu aufgefordert werden, fortzufahren: `set -priv advanced`
*** Geben Sie den Befehl ein, um die OKM-Informationen zu sichern: ``security key-manager backup show``
+

NOTE: Stellen Sie sicher, dass OKM-Informationen in Ihrer Protokolldatei gespeichert werden. Diese Informationen werden in Disaster-Szenarien benötigt, in denen OKM möglicherweise manuell wiederhergestellt werden muss.

*** Kopieren Sie den Inhalt der Sicherungsinformationen in eine separate Datei oder Ihr Protokoll. Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.
*** Zurück zum Admin-Modus: `set -priv admin`
*** Sie können den Controller sicher herunterfahren.





