= Schritt 1: Wiederherstellen des Schlüsselmanagers
:allow-uri-read: 




== Schritt 1: Wiederherstellen des Schlüsselmanagers

Die Schritte für Systeme mit aktiviertem Onboard Key Manager (OKM), NetApp Storage Encryption (NSE) oder NetApp Volume Encryption (NVE) müssen über die zu Beginn dieses Verfahrens erfassten Einstellungen ausgeführt werden.


NOTE: Wenn NSE oder NVE zusammen mit Onboard oder externem Key Manager aktiviert sind, müssen Sie die Einstellungen wiederherstellen, die Sie zu Beginn dieses Verfahrens erfasst haben.

.Schritte
. Schließen Sie das Konsolenkabel an den Ziel-Controller an.
. Wählen Sie eine der folgenden Optionen aus, um die Onboard-Schlüsselmanager-Konfiguration aus dem ONATP-Startmenü wiederherzustellen.


[role="tabbed-block"]
====
.Option 1: Systeme mit integrierter Key Manager Server-Konfiguration
--
Stellen Sie die OKM-Konfiguration (Onboard Key Manager) über das ONTAP-Startmenü wieder her.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie beim Wiederherstellen der OKM-Konfiguration folgende Informationen haben:
+
** Cluster-weite Passphrase eingegeben https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["Und ermöglicht integriertes Verschlüsselungsmanagement"].
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Backup-Informationen für den Onboard Key Manager"].


* Führen Sie das https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Verifizierung von Onboard-Verschlüsselungsmanagement-Backup und Cluster-weiter Passphrase"] Verfahren durch, bevor Sie fortfahren.


.Schritte
. Schließen Sie das Konsolenkabel an den Ziel-Controller an.
. Wählen Sie im ONTAP-Startmenü die entsprechende Option aus:
+
[cols="1a,2a"]
|===
| ONTAP-Version | Wählen Sie diese Option aus 


 a| 
ONTAP 9.8 oder höher
 a| 
Wählen Sie Option 10.

|===


--
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
[]
====
A ONTAP 9.7 und früher A Wählen Sie die versteckte Option aus `recover_onboard_keymanager`

====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
[]
====
|===


| + . Bestätigen Sie, dass Sie den Wiederherstellungsprozess fortsetzen möchten. + .Beispielaufforderung anzeigen [%kollabierbar] 
|===
====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

[]
====
. Geben Sie die Cluster-weite Passphrase zweimal ein.
+
Während der Eingabe der Passphrase zeigt die Konsole keine Eingaben an.



====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

[]
====
+

. Geben Sie die Sicherungsinformationen ein.
+
.. Fügen Sie den gesamten Inhalt aus der Zeile „START BACKUP“ durch die Zeile „END BACKUP“ ein.




====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
[]
====
. Drücken Sie am Ende des Eingangs zweimal die Eingabetaste.
+
Die Wiederherstellung ist abgeschlossen.



====
....

Enter the backup data:

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
[]
====
+ WARNUNG: Fahren Sie nicht fort, wenn die angezeigte Ausgabe etwas anderes als ist `Successfully recovered keymanager secrets` . Führen Sie die Fehlerbehebung durch, um den Fehler zu beheben.

. Wählen Sie Option 1 aus dem Startmenü, um mit dem Booten in ONTAP fortzufahren.


====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
[]
====
. Vergewissern Sie sich, dass die Konsole des Controllers Folgendes anzeigt:
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

. Geben Sie vom Partner-Knoten aus das Partner-Controller ein:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`.

. Führen Sie nach dem Booten nur mit CFO-Aggregat den folgenden Befehl aus:
+
`security key-manager onboard sync` Befehl.

. Geben Sie die Cluster-weite Passphrase für das Onboard Key Manager ein.


====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
[]
====
+ HINWEIS: Wenn die Synchronisierung erfolgreich war, wird die Cluster-Eingabeaufforderung ohne zusätzliche Meldungen zurückgegeben. Wenn die Synchronisierung fehlschlägt, wird eine Fehlermeldung angezeigt, bevor Sie zur Cluster-Eingabeaufforderung zurückkehren. Fahren Sie nicht fort, bis der Fehler behoben ist und die Synchronisierung erfolgreich ausgeführt wird.

. Stellen Sie sicher, dass alle Schlüssel synchronisiert sind:
+
`security key-manager key query -restored false`.

+
`There are no entries matching your query.`

+

NOTE: Beim Filtern nach FALSE im wiederhergestellten Parameter sollten keine Ergebnisse angezeigt werden.

. GiveBack der Node aus dem Partner:
+
`storage failover giveback -fromnode local`

. Stellen Sie das automatische Giveback wieder her, falls Sie es deaktiviert haben, indem Sie den folgenden Befehl eingeben:
+
`storage failover modify -node local -auto-giveback true`

. Wenn AutoSupport aktiviert ist, stellen Sie die automatische Fallerstellung wieder her, indem Sie den folgenden Befehl eingeben:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--

--
Stellen Sie die Konfiguration des External Key Manager über das ONATP-Startmenü wieder her.

.Bevor Sie beginnen
Sie benötigen die folgenden Informationen für die Wiederherstellung der Konfiguration des externen Schlüsselmanagers (EKM):

* Eine Kopie der Datei /cfcard/kmip/servers.cfg von einem anderen Clusterknoten oder die folgenden Informationen:
+
** Die Adresse des KMIP-Servers.
** Der KMIP-Port.
** Eine Kopie der Datei /cfcard/kmip/certs/Client.crt von einem anderen Clusterknoten oder dem Clientzertifikat.
** Eine Kopie der Datei /cfcard/kmip/certs/client.key von einem anderen Clusterknoten oder dem Client-Schlüssel.
** Eine Kopie der Datei /cfcard/kmip/certs/CA.pem von einem anderen Clusterknoten oder der KMIP-Server-CA(s).




.Schritte
. Schließen Sie das Konsolenkabel an den Ziel-Controller an.
. Wählen Sie Option 11 aus dem ONTAP-Startmenü.


====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
[]
====
+

. Bestätigen Sie, dass Sie die erforderlichen Informationen gesammelt haben, wenn Sie dazu aufgefordert werden.


====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
[]
====
+

====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
[]
====
+

. Geben Sie bei der entsprechenden Aufforderung die Client- und Serverinformationen ein.


====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
[]
====
+ .Beispiel anzeigen

====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
MIIDvjCCAqagAwIBAgICN3gwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAlVT
MRMwEQYDVQQIEwpDYWxpZm9ybmlhMQwwCgYDVQQHEwNTVkwxDzANBgNVBAoTBk5l
MSUbQusvzAFs8G3P54GG32iIRvaCFnj2gQpCxciLJ0qB2foiBGx5XVQ/Mtk+rlap
Pk4ECW/wqSOUXDYtJs1+RB+w0+SHx8mzxpbz3mXF/X/1PC3YOzVNCq5eieek62si
Fp8=
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAoU1eajEG6QC2h2Zih0jEaGVtQUexNeoCFwKPoMSePmjDNtrU
MSB1SlX3VgCuElHk57XPdq6xSbYlbkIb4bAgLztHEmUDOkGmXYAkblQ=
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
MIIEizCCA3OgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCVVMx
7yaumMQETNrpMfP+nQMd34y4AmseWYGM6qG0z37BRnYU0Wf2qDL61cQ3/jkm7Y94
EQBKG1NY8dVyjphmYZv+
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
​​​​....


====

. The recovery process completes.


+
.Show example prompt
[%collapsible]
====
....
Das System ist bereit, externe Schlüsselmanager zu verwenden. Es wird versucht, Schlüssel von Schlüsselservern wiederherzustellen [Aug 29 21:06:28]: 0x808806100: 0: DEBUG: Kmip2::main: [InitOpensl]:460: Initialisierung von OpenSSL erfolgreich durchgeführt keymanager Geheimnisse wiederhergestellt.

....



. Select option 1 from the boot menu to continue booting into ONTAP.

+
....
****
* Wählen Sie die Option „(1) Normal Boot.“, um den Wiederherstellungsvorgang abzuschließen. *


****
(1) Normaler Start. (2) Start ohne /etc/rc. (3) Passwort ändern. (4) Reinigen Sie die Konfiguration und initialisieren Sie alle Festplatten. (5) Boot im Wartungsmodus. (6) Aktualisieren Sie Flash von der Backup-Konfiguration. (7) Installieren Sie zuerst neue Software. (8) Node neu booten. (9) Konfigurieren Sie Die Erweiterte Laufwerkpartitionierung. (10) Festlegen von Recovery-Geheimnissen für Onboard Key Manager. (11) Konfigurieren des Node für externes Verschlüsselungsmanagement Auswahl (1-11)? 1

....
====
+


. Restore automatic giveback, if you disabled it, by entering the following command:
+
`storage failover modify -node local -auto-giveback true` command.

. If AutoSupport is enabled, restore automatic case creation by entering  the following command:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


--

====

== Step 2: Complete the boot media replacement

Complete the boot media replacement process after the normal boot by completing final checks and giving back storage.

. Check the console output:
+
[%header,cols="1,3"]
|===
| If the console displays...| Then...
a|
The login prompt
a|
Go to Step 6.
a|
Waiting for giveback...
a|

 .. Log into the partner controller.
 .. Confirm the target controller is ready for giveback with the _storage failover show_ command.

|===

. Move the console cable to the partner controller and give back the target controller storage using the _storage failover giveback -fromnode local -only-cfo-aggregates true_ command.

 ** If the command fails because of a failed disk, physically disengage the failed disk, but leave the disk in the slot until a replacement is received.

 ** If the command fails because the partner is "not ready", wait 5 minutes for the HA subsystem to synchronize between the partners.
 ** If the command fails because of an NDMP, SnapMirror, or SnapVault process, disable the process. See the appropriate Documentation Center for more information.
. Wait 3 minutes and check the failover status with the _storage failover show_ command.
. At the clustershell prompt, enter the _network interface show -is-home false_ command to list the logical interfaces that are not on their home controller and port.
+
If any interfaces are listed as `false`, revert those interfaces back to their home port using the _net int revert -vserver Cluster -lif _nodename_ command.

. Move the console cable to the target controller and run the _version -v_ command to check the ONTAP versions.

. Use the `storage encryption disk show` to review the output.
. Use the _security key-manager key query_ command to display the key IDs of the authentication keys that are stored on the key management servers.
 ** If the `Restored` column = `yes/true`, you are done and can proceed to complete the replacement process.
 ** If the `Key Manager type` = `external` and the `Restored` column = anything other than `yes/true`, use the _security key-manager external restore_ command to restore the key IDs of the authentication keys.
+
NOTE: If the command fails, contact Customer Support.

 ** If the `Key Manager type` = `onboard` and the `Restored` column = anything other than `yes/true`, use the _security key-manager onboard sync_ command to synchronize the missing onboard keys on the repaired node.
+
Use the _security key-manager key query_ command to verify that the `Restored` column = `yes/true` for all authentication keys.

. Connect the console cable to the partner controller.
. Give back the controller using the `storage failover giveback -fromnode local` command.
. Restore automatic giveback if you disabled it by using the _storage failover modify -node local -auto-giveback true_ command.
. If AutoSupport is enabled, restore/unsuppress automatic case creation by using the _system node autosupport invoke -node * -type all -message MAINT=END_ command.
....