= Anforderungen
:allow-uri-read: 


Sie müssen die Anforderungen und Überlegungen für den Controller-Austausch überprüfen.



== Anforderungen

* Alle Regale müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Sie müssen einen Controller durch einen Controller desselben Modelltyps ersetzen. Sie können Ihr System nicht aktualisieren, indem Sie einfach den Controller austauschen.
* Im Rahmen dieses Verfahrens können keine Laufwerke oder Shelfs geändert werden.
* Sie müssen immer die Konsolenausgabe des Controllers in einer Textprotokolldatei erfassen.
+
Die Konsolenausgabe enthält eine Aufzeichnung des Verfahrens, mit dem Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.





== Überlegungen

* Es ist wichtig, dass Sie die Befehle in diesem Verfahren auf den richtigen Controller anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.



