= 
:allow-uri-read: 


Schalten Sie das Ersatz-I/O-Modul online, überprüfen Sie, ob die I/O-Modul-Ports erfolgreich initialisiert wurden, überprüfen Sie, ob der Steckplatz mit Strom versorgt ist, und überprüfen Sie dann, ob das I/O-Modul online und erkannt ist.

.Über diese Aufgabe
Nachdem das E/A-Modul ausgetauscht wurde und die Ports wieder in einen fehlerfreien Zustand versetzt wurden, werden die LIFs auf das ausgetauschte E/A-Modul zurückgesetzt.

.Schritte
. Schalten Sie das Ersatz-E/A-Modul online:
+
.. Geben Sie den folgenden Befehl ein:
+
`system controller slot module insert -node _impaired_node_name_ -slot _slot_number_`

.. Eingeben `y` wenn die Eingabeaufforderung „Möchten Sie fortfahren?“ angezeigt wird
+
Die Ausgabe sollte bestätigen, dass das I/O-Modul erfolgreich online geschaltet wurde (eingeschaltet, initialisiert und in Betrieb genommen).

+
Beispielsweise bringt der folgende Befehl Steckplatz 4 auf Knoten 2 (den beeinträchtigten Controller) online und zeigt eine Meldung an, dass der Vorgang erfolgreich war:

+
[listing]
----
node2::> system controller slot module insert -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----


. Überprüfen Sie, ob jeder Port des E/A-Moduls erfolgreich initialisiert wurde:
+
.. Geben Sie den folgenden Befehl von der Konsole des beeinträchtigten Controllers ein:
+
`event log show -event \*hotplug.init*`

+

NOTE: Es kann mehrere Minuten dauern, bis erforderliche Firmware-Updates durchgeführt und Ports initialisiert sind.

+
Die Ausgabe sollte ein oder mehrere hotplug.init.success EMS-Ereignisse anzeigen, die darauf hinweisen, dass jeder Port auf dem E/A-Modul erfolgreich initialisiert wurde.

+
Beispielsweise zeigt die folgende Ausgabe, dass die Initialisierung für die I/O-Ports e4b und e4a erfolgreich war:

+
[listing]
----
node2::> event log show -event *hotplug.init*

Time                Node             Severity      Event

------------------- ---------------- ------------- ---------------------------

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4b" in slot 4 succeeded

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4a" in slot 4 succeeded

2 entries were displayed.
----
.. Falls die Portinitialisierung fehlschlägt, überprüfen Sie das EMS-Log, um die nächsten Schritte zu ermitteln.


. Überprüfen Sie, ob der I/O-Modul-Steckplatz eingeschaltet und betriebsbereit ist:
+
`system controller slot module show`

+
Die Ausgabe sollte den Steckplatzstatus als  `_powered-on_` anzeigen und somit die Betriebsbereitschaft des E/A-Moduls signalisieren.

. Prüfen Sie, ob das I/O-Modul online und erkannt ist.
+
Geben Sie den Befehl von der Konsole des beeinträchtigten Controllers ein:

+
`system controller config show -node local -slot _slot_number_`

+
Wenn das I/O-Modul erfolgreich online geschaltet wurde und erkannt wird, zeigt die Ausgabe Informationen zum I/O-Modul an, einschließlich Portinformationen für den Slot.

+
Beispielsweise sollten Sie eine Ausgabe ähnlich der folgenden für ein E/A-Modul in Steckplatz 4 sehen:

+
[listing]
----
node2::> system controller config show -node local -slot 4

Node: node2
Sub- Device/
Slot slot Information
---- ---- -----------------------------
   4    - Dual 40G/100G Ethernet Controller CX6-DX
                  e4a MAC Address: d0:39:ea:59:69:74 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2807GJFM-B
                  e4b MAC Address: d0:39:ea:59:69:75 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2809G26F-A
                  Device Type:        CX6-DX PSID(NAP0000000027)
                  Firmware Version:   22.44.1700
                  Part Number:        111-05341
                  Hardware Revision:  20
                  Serial Number:      032403001370
----

