= Für die Installation erforderliche Ausrüstung
:allow-uri-read: 




== Für die Installation erforderliche Ausrüstung

Zur Installation des Storage-Systems benötigen Sie die folgenden Geräte und Tools:

* Zugriff auf einen Webbrowser zur Konfiguration des Speichersystems
* Band für elektrostatische Entladung (ESD)
* Taschenlampe
* Laptop oder Konsole mit USB-/serieller Verbindung
* Büroklammer oder Kugelschreiber mit schmaler Spitze zum Einstellen der NS224-Einschubnummern
* Kreuzschlitzschraubendreher #2




== Vorsichtsmaßnahmen beim Anheben

Storage-Systeme und Storage Shelves sind schwer. Gehen Sie beim Anheben und Bewegen dieser Gegenstände vorsichtig vor.



=== Gewichte des Storage-Systems

Treffen Sie die erforderlichen Vorsichtsmaßnahmen, wenn Sie das Speichersystem bewegen oder anheben.

[role="tabbed-block"]
====
.A1K
--
Ein A1K-Speichersystem kann bis zu 28.5 kg (62.83 lbs) wiegen. Zum Anheben des Systems zwei Personen oder einen Hydraulikhub verwenden.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K Warnsymbol beim Anheben]

--
.A70 und A90
--
Ein A70 Storage-System oder ein A90 Storage-System kann bis zu 68.8 kg (151.68 lbs) wiegen. Zum Anheben des Systems vier Personen oder einen Hydraulikhub verwenden.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]

--
====


=== Gewicht des Lagerregals

Ein NS224-Einlegeboden kann bis zu 30.29 kg (66.78 lbs) wiegen. Zum Anheben des Lagerregals zwei Personen oder einen Hydraulikhub verwenden. Halten Sie alle Komponenten im Lagerregal (vorne und hinten), um ein Ausbalancieren des Regalgewichts zu vermeiden.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Vorsicht beim Anheben]

.Verwandte Informationen
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Sicherheitsinformationen und gesetzliche Hinweise"^]

