= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF Systeme
--
Die Modelle der AFF A-Series und C-Series sind eine robuste, horizontal skalierbare Plattform für virtualisierte Umgebungen und können als unabhängiges System oder als High-Performance-Tier in einer NetApp ONTAP Konfiguration implementiert werden. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Erfahren Sie mehr über die AFF Systeme"].

.AFF A20, AFF A30, AFF A50
Verfügbar ab ONTAP 9.16.1

.AFF C30, AFF C60
Verfügbar ab ONTAP 9.16.1

.AFF A1K, AFF A70 und AFF A90
Verfügbar ab ONTAP 9.15.1

.AFF A150
Verfügbar ab ONTAP 9.13.1, ONTAP 9.12.1P1, ONTAP 9.11.1P8, ONTAP 9.10.1P12

.AFF A900
Verfügbar ab ONTAP 9.10.1

.AFF A250 und AFF A800
Verfügbar ab ONTAP 9.8

.AFF A400
Verfügbar ab ONTAP 9.7

.AFF C250, AFF C400, AFF C800
Verfügbar ab ONTAP 9.12.1P1, ONTAP 9.13.1 GA

--
.ASA r2-Systeme
--
ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung, die eine vereinfachte Erfahrung speziell für die Anforderungen reiner SAN-Kunden bietet. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].

.ASA A1K, ASA A70, ASA A90
Verfügbar ab ONTAP 9.16.0

--
.ASA Systeme
--
Die ASA Modelle der A-Series und C-Series bieten ein vereinfachtes, dediziertes SAN-Arbeitsumfeld mit kontinuierlicher Datenverfügbarkeit für geschäftskritische Enterprise-Datenbanken und sonstige SAN-Workloads unter Verwendung von FCP oder iSCSI. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Erfahren Sie mehr über die ASA Systeme"].

.ASA A150, ASA A250, ASA A400, ASA A900
Verfügbar ab ONTAP 9.13.1

.ASA C250, C400, C800
Verfügbar ab ONTAP 9.13.1P1

--
.FAS Systeme
--
FAS Systeme bieten effizienten und sicheren Sekundärspeicher – die ultimative Lösung für Tiering, Backup und Disaster Recovery. link:https:://www.netapp.com/data-storage/fas/["Erfahren Sie mehr über FAS Systeme"].

.FAS70 und FAS90
Verfügbar ab ONTAP 9.15.1

.FAS9500
Verfügbar ab ONTAP 9.11.1, ONTAP 9.10.1P3

.FAS8300 und FAS700
Verfügbar ab ONTAP 9.7

.FAS2820
Verfügbar ab ONTAP 9.13.1

.FAS2700
Verfügbar ab ONTAP 9.13.1

--
====