= 
:allow-uri-read: 


[cols="2*"]
|===
| Plattformen | Verfügbar ab 


 a| 
https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2-Systeme"]

* ASA A1K
* ASA A70
* ASA A90

 a| 
ONTAP 9.16.0



 a| 
https://www.netapp.com/data-storage/fas/["FAS70 und FAS90"]
 a| 
ONTAP 9.15.1



 a| 
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A1K"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A70"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A90"]

 a| 
ONTAP 9.15.1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9.13.1P1



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA und neuere ONTAP Versionen

[NOTE]
====
Diese Plattformen werden mit ONTAP 9.13.1 RC1 nicht unterstützt.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
Versuchen Sie nicht, Ihr AFF A150-Speichersystem mit einer nicht unterstützten ONTAP-Version zu installieren oder zu booten. Wenn Sie versuchen, Ihr System mit einer nicht unterstützten Version von ONTAP zu installieren oder zu starten, lässt ONTAP dies zu (ONTAP blockiert den Versuch nicht). Die Folge ist, dass Ihr AFF A150 Storage-System als FAS2750 Storage-System eingesetzt wird.

==== a| 
ONTAP 9.13.1 und höhere ONTAP-Versionen

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7623-ds-3989.pdf["AFF C 190"^]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===