= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF Systeme
--
Die Systeme der AFF A-Series und AFF C-Series bieten eine robuste, horizontal skalierbare Plattform, die speziell auf virtualisierte Umgebungen zugeschnitten ist. Sie können als Standalone-Systeme oder als High-Performance-Tier in NetApp ONTAP Konfigurationen eingesetzt werden. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Erfahren Sie mehr über AFF Systeme"].

Die Systeme der AFF A-Serie und der AFF C-Serie werden ab den folgenden ONTAP Versionen unterstützt.

ONTAP 9.16.1::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* AFF A800


--


--
.ASA r2-Systeme
--
ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung, die eine vereinfachte Erfahrung speziell für die Anforderungen reiner SAN-Kunden bietet. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über die ASA r2-Systeme"].

ASA r2 Systeme werden ab den folgenden ONTAP Versionen unterstützt.

ONTAP 9.16.0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.ASA Systeme
--
Die Systeme der ASA A-Series und ASA C-Series bieten ein vereinfachtes, dediziertes SAN-Arbeitsumfeld mit kontinuierlicher Datenverfügbarkeit für geschäftskritische Enterprise-Datenbanken und sonstige SAN-Workloads unter Verwendung von FCP oder iSCSI. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Erfahren Sie mehr über die ASA Systeme"].

ASA Systeme werden ab den folgenden ONTAP Versionen unterstützt.

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9.7::
+
--
* ASA AFF A400


--


--
.FAS Systeme
--
FAS Systeme bieten effizienten und sicheren Sekundärspeicher – die ultimative Lösung für Tiering, Backup und Disaster Recovery. link:https://www.netapp.com/data-storage/fas/["Erfahren Sie mehr über FAS Systeme"].

FAS Systeme werden ab den folgenden ONTAP Versionen unterstützt.

ONTAP 9.15.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.Festplatten-Shelfs
--
Festplatten-Shelfs wurden speziell für NetApp AFF, ASA und FAS Systeme entwickelt und bieten die Performance, Ausfallsicherheit und Flexibilität, die Sie für die digitale Transformation benötigen.

Festplatten-Shelfs sind ab den folgenden ONTAP Versionen verfügbar.

ONTAP 9.16.1:: NS224 mit NSM100B-Modulen
ONTAP 9.6:: NS224-Shelf mit NSM100-Modulen


--
====