---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: Lernen Sie den Austausch des Bootmediums auf einem AFF C190 -System kennen und verstehen Sie die verschiedenen Austauschmethoden. Das AFF C190 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt. 
---
= Informationen zum Austausch des Bootmediums in Ihrem AFF C190 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lernen Sie den Austausch des Bootmediums auf einem AFF C190 -System kennen und verstehen Sie die verschiedenen Austauschmethoden. Das Bootmedium speichert primäre und sekundäre Boot-Image-Dateien, die das System beim Start verwendet. Je nach Netzwerkkonfiguration können Sie entweder einen unterbrechungsfreien Austausch (HA-Paar mit Netzwerk verbunden) oder einen unterbrechenden Austausch (erfordert zwei Neustarts) durchführen.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
Das AFF C190 -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt.

Sie müssen über ein USB-Flash-Laufwerk verfügen, das auf FAT32 formatiert ist, und über die entsprechende Speichermenge, um die zu speichern `image_xxx.tgz` Datei:

* Bei den unterbrechungsfreien und mit Unterbrechungen verbundenen Methoden zum Austausch von Boot-Medien müssen Sie das var Dateisystem wiederherstellen:
+
** Um den unterbrechungsfreien Austausch zu gewährleisten, muss das HA-Paar mit einem Netzwerk verbunden sein, um das var Filesystem wiederherzustellen.
** Um den Austausch zu unterbrechen, benötigen Sie keine Netzwerkverbindung zur Wiederherstellung des var-Dateisystems. Der Vorgang muss jedoch zwei Neustarts erfordern.


* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Controller anwenden:
+
** Der Controller _Impared_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _Healthy_ Controller ist der HA-Partner des beeinträchtigten Controllers.



