---
permalink: c190/chassis-replace-complete-rma.html 
sidebar: sidebar 
keywords: aff c190, verify and set HA state 
summary: Sie müssen den HA-Status des Chassis überprüfen. 
---
= Wiederherstellen und Überprüfen der Konfiguration – AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen den HA-Status des Chassis überprüfen.



== Schritt 1: Überprüfen und Einstellen des HA-Status des Chassis

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an:
+
`*ha-config show*`

+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest:
+
`*ha-config modify chassis _HA-state_*`

+
Der Wert für `_HA-state_` Kann einer der folgenden sein:

+
*** `ha`
*** `non-ha`


.. Bestätigen Sie, dass sich die Einstellung geändert hat:
+
`*ha-config show*`



. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.
. Starten Sie das System neu.




== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://mysupport.netapp.com/site/info/rma["Teilerückgabe  Austausch"] Seite für weitere Informationen.
