---
permalink: c190/maintain-overview.html 
sidebar: sidebar 
keywords: c190 maintenance, maintenance, repairing c190, repairing c190, replace c190 components, replace c190 components 
summary: Wartung der AFF C190 Hardware 
---
= Instandhaltung der AFF C190 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für das AFF C190 Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



== Ventilator

Der Lüfter kühlt den Controller.



== NVMEM-Akku

Im Lieferumfang des Controllers ist ein Akku enthalten, der die Notstromversorgung bereitstellt, wenn der Netzstrom ausfällt.



== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



== Akku in Echtzeit

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
