---
permalink: c190/maintain-overview.html 
sidebar: sidebar 
keywords: c190 maintenance, maintenance, repairing c190, repairing c190, replace c190 components, replace c190 components 
summary: Wartung der AFF C190 Hardware 
---
= Informationen zur Wartung eines AFF C190 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Hardware des AFF C190 Storage-Systems wird gewartet, um langfristige Zuverlässigkeit und optimale Leistung sicherzustellen. Regelmäßige Wartungsaufgaben wie der Austausch fehlerhafter Komponenten verhindern Ausfallzeiten und Datenverlust.



[[boot-media]]
== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[drive]]
== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



[[fan]]
== Ventilator

Der Lüfter kühlt den Controller.



[[nvmem-battery]]
== NVMEM-Akku

Im Lieferumfang des Controllers ist ein Akku enthalten, der die Notstromversorgung bereitstellt, wenn der Netzstrom ausfällt.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Akku in Echtzeit

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
