---
permalink: a700/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Anforderungen sollten vor dem Austausch eines AFF A700 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Gehäuses in Ihrem AFF A700 System sollten die Anforderungen für einen erfolgreichen Austausch geprüft werden. Das Verfahren zum Austausch des Gehäuses umfasst das Überführen aller Komponenten vom defekten Gehäuse in das Ersatzgehäuse und ist mit einer Unterbrechung verbunden.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

