---
permalink: a700/maintain-overview.html 
sidebar: sidebar 
keywords: aff A700 maintenance, maintenance, repairing A700, repairing aff A700, replace aff A700 components, replace aff A700 components 
summary: Warten Sie die AFF A700 Hardware 
---
= Informationen zur Wartung eines AFF A700 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für das AFF A700 Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



[[boot-media]]
== Boot-Medien

Das Bootmedium speichert einen primären und einen sekundären Satz von Boot-Image-Dateien, die das System beim Start verwendet. Das AFF A700 und FAS9000 System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien.



[[caching-module]]
== Caching-Modul

Sie müssen das Caching-Modul des Controllers ersetzen, wenn Ihr System eine einzelne AutoSupport-Meldung (ASUP) registriert, dass das Modul offline gegangen ist.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dcpm]]
== DFPM

Die DCPM (Controller-Stromversorgungsmodul der Auslagerung) enthält die NVRAM11-Batterie.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[fan]]
== Ventilator

Der Lüfter kühlt den Controller.



[[io-module]]
== I/O-Modul

Das E/A-Modul (Eingangs-/Ausgangsmodul) ist eine Hardwarekomponente, die als Vermittler zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.



[[led-usb]]
== LED USB

Das USB-LED-Modul stellt Verbindungen zu Konsolenports und Systemstatus bereit.



[[nvram]]
== NVRAM

Das NVRAM-Modul (Non-Volatile Random Access Memory) ermöglicht es dem Controller, Daten während des aus- und Einschaltzyklus oder beim Neustart des Systems aufzubewahren.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Akku in Echtzeit

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.



[[x91148a-module]]
== X91148A-Modul

Das X91148A-Modul ist ein E/A-Modul, das als Zwischenstation zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.
