---
permalink: a700/x91148a-module-install-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, add, x91148a, storage, module, NIC, no open, slots, open slots, system 
summary: Sie können Ihrem System ein I/O-Modul hinzufügen, indem Sie entweder einen NIC oder einen Speicheradapter durch einen neuen in einem vollständig bestückten System ersetzen oder einen neuen NIC- oder Speicheradapter in einen leeren Gehäusesteckplatz Ihres Systems hinzufügen. 
---
= Informationen zum Hinzufügen eines X91148A Moduls zu einem AFF A700 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zum Hinzufügen eines X91148A Moduls zu Ihrem AFF A700 System, entweder durch Ersetzen einer NIC oder eines Storage-Adapters oder durch Hinzufügen des Moduls zu einem leeren Chassis-Steckplatz.

Sie können Ihrem System ein I/O-Modul hinzufügen, indem Sie entweder einen NIC oder einen Speicheradapter durch einen neuen in einem vollständig bestückten System ersetzen oder einen neuen NIC- oder Speicheradapter in einen leeren Gehäusesteckplatz Ihres Systems hinzufügen.

.Bevor Sie beginnen
* Überprüfung des  https://hwu.netapp.com["NetApp Hardware Universe"] zur Sicherstellung, dass das neue E/A-Modul mit Ihrem System und der von Ihnen verwendeten ONTAP-Version kompatibel ist.
* Wenn mehrere Steckplätze verfügbar sind, sollten die Steckplatzprioritäten in  https://hwu.netapp.com["NetApp Hardware Universe"] überprüft und der beste verfügbare für Ihr E/A-Modul verwendet werden.
* Damit ein I/O-Modul unterbrechungsfrei hinzugefügt werden kann, müssen Sie den Ziel-Controller übernehmen, die Abdeckung des Steckplatzes im Zielsteckplatz entfernen oder ein vorhandenes I/O-Modul entfernen, das neue oder das neue I/O-Modul ersetzen und dann den Ziel-Controller zurückgeben.
* Stellen Sie sicher, dass alle anderen Komponenten ordnungsgemäß funktionieren.

