---
permalink: fas-70-90/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the boot media 
summary: Erfahren Sie mehr über die Anforderungen für den Austausch der Boot-Medien. 
---
= Boot-Medien ersetzen Anforderungen – FAS70 und FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie vor dem Austauschen des Startmediums die folgenden Anforderungen.

* Sie müssen über ein USB-Flash-Laufwerk verfügen, das auf FAT32 formatiert ist, und über die entsprechende Speichermenge, um die zu speichern `image_xxx.tgz` Datei:
* Sie müssen die Datei zur späteren Verwendung in diesem Verfahren auf das USB-Flash-Laufwerk kopieren `image_xxx.tgz` .
* Sie müssen die fehlerhafte Komponente durch eine FRU-Austauschkomponente ersetzen, die Sie NetApp erhalten haben.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Controller anwenden:
+
** Der Controller _Impared_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _Healthy_ Controller ist der HA-Partner des beeinträchtigten Controllers.



