---
permalink: fas-70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the chassis 
summary: Stellen Sie vor dem Austausch des Gehäuses in Ihrem FAS70- oder FAS90-System sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, und dass Sie über lokale Administratoranmeldeinformationen für ONTAP, das richtige Ersatzgehäuse und die erforderlichen Tools verfügen. 
---
= Voraussetzungen für den Chassistausch - FAS70 und FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Gehäuses in Ihrem FAS70- oder FAS90-System sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, und dass Sie über lokale Administratoranmeldeinformationen für ONTAP, das richtige Ersatzgehäuse und die erforderlichen Tools verfügen.

Das Gehäuse ist das physische Gehäuse, in dem alle Systemkomponenten wie Lüfter, Controller-/CPU-Einheit, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile untergebracht sind.

Überprüfen Sie die folgenden Anforderungen.

* Stellen Sie sicher, dass alle anderen Komponenten des Systems ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an, http://mysupport.netapp.com/["NetApp Support"^] um Unterstützung zu erhalten.
* Holen Sie sich lokale Administratoranmeldeinformationen für ONTAP ein, wenn diese nicht vorhanden sind.
* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.
* Sie können das Verfahren zum Austausch des Gehäuses für alle Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Bei der Beschreibung des Verfahrens zum Austausch des Gehäuses wird davon ausgegangen, dass Sie Blende, Lüfter, Controllermodul, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile in das neue Gehäuse einbauen und dass es sich bei dem Austauschgehäuse um eine neue Komponente von NetApp handelt.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie link:chassis-replace-prepare.html["Bereiten Sie den Austausch des Gehäuses vor"].
