---
permalink: fas-70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the chassis 
summary: Bevor das Chassis im FAS70 oder FAS90 System ersetzt wird, sollte überprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Bestätigung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass lokale Administratoranmeldedaten für ONTAP vorliegen, das richtige Ersatzchassis vorhanden ist und die erforderlichen Werkzeuge bereitstehen. 
---
= Die Anforderungen für den Austausch eines Chassis in einem FAS70 oder FAS90 System werden dargestellt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Chassis im FAS70 oder FAS90 System ersetzt wird, sollte überprüft werden, ob alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu zählt die Bestätigung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass lokale Administratoranmeldedaten für ONTAP vorliegen, das richtige Ersatzchassis vorhanden ist und die erforderlichen Werkzeuge bereitstehen.

Das Gehäuse ist das physische Gehäuse, in dem alle Systemkomponenten wie Lüfter, Controller-/CPU-Einheit, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile untergebracht sind.

Überprüfen Sie die folgenden Anforderungen.

* Stellen Sie sicher, dass alle anderen Komponenten des Systems ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an, http://mysupport.netapp.com/["NetApp Support"^] um Unterstützung zu erhalten.
* Holen Sie sich lokale Administratoranmeldeinformationen für ONTAP ein, wenn diese nicht vorhanden sind.
* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.
* Sie können das Verfahren zum Austausch des Gehäuses für alle Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Bei der Beschreibung des Verfahrens zum Austausch des Gehäuses wird davon ausgegangen, dass Sie Blende, Lüfter, Controllermodul, NVRAM12, Systemverwaltungsmodul, E/A-Karten und Blindmodule sowie Netzteile in das neue Gehäuse einbauen und dass es sich bei dem Austauschgehäuse um eine neue Komponente von NetApp handelt.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie link:chassis-replace-prepare.html["Bereiten Sie den Austausch des Gehäuses vor"].
