---
permalink: fas-70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, prerequisite, replace the controller module 
summary: Bevor Sie den Controller in Ihrem FAS70 oder FAS90 System austauschen, sollte bestätigt werden, dass alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu gehört die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass der richtige Ersatzcontroller vorhanden ist und dass die Konsolenausgabe des Controllers in einer Textprotokolldatei gespeichert wird. 
---
= Die Anforderungen für den Austausch eines Controllers in einem FAS70 oder FAS90 System werden hier aufgeführt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie den Controller in Ihrem FAS70 oder FAS90 System austauschen, sollte bestätigt werden, dass alle notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sind. Dazu gehört die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, dass der richtige Ersatzcontroller vorhanden ist und dass die Konsolenausgabe des Controllers in einer Textprotokolldatei gespeichert wird.

Überprüfen Sie die Anforderungen für den Austausch des Controllers.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Verwenden Sie dieses Verfahren nicht für Controller-Upgrades. Eine Anleitung finden Sie im https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Wählen Sie das Upgrade Ihrer Controller-Hardware aus"].
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie im Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"] , ob Sie diesen Vorgang zum Austausch des Controllers durchführen sollten.
* Sie müssen die ausgefallene Komponente durch die Field-Replaceable Unit (FRU) ersetzen, die Sie von NetApp erhalten haben.
* Ein Controller-Modul muss durch ein Controller-Modul desselben Modelltyps ersetzt werden. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* Da sich das Startgerät auf dem Systemverwaltungsmodul befindet, das auf der Rückseite des Systems installiert ist, müssen Sie das Startgerät beim Austausch eines Controller-Moduls nicht verschieben.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.




.Was kommt als Nächstes?
Nachdem Sie die Anforderungen überprüft haben, um Ihren FAS70 oder FAS90 Controller zu ersetzen, müssen Sie link:controller-replace-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].
