---
permalink: fas-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Überprüfen Sie, ob die logischen Schnittstellen (LIFs) an ihren Heimatport melden, führen Sie eine Cluster-Integritätsprüfung durch und senden Sie dann das defekte Teil zurück an NetApp, um den letzten Schritt im FAS70- oder FAS90-Controller-Austauschverfahren abzuschließen.' 
---
= Der Controller-Austausch für Ihr FAS70 oder FAS90 System wird abgeschlossen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Controller-Austausch für Ihr FAS70- oder FAS90-System abzuschließen, wird zunächst die NetApp Storage Encryption-Konfiguration (falls erforderlich) wiederhergestellt. Anschließend wird bestätigt, dass die logischen Schnittstellen (LIFs) an ihren Home-Ports melden, und eine Cluster-Integritätsprüfung durchgeführt. Abschließend wird das defekte Bauteil an NetApp zurückgesendet.



[[step-1-verify-lifs-and-check-cluster-health]]
== Schritt 1: Verifizieren von LIFs und Überprüfen des Clusterzustands

Bevor Sie den Ersatz-Node an einen Service zurücksenden, überprüfen Sie, ob sich die logischen Schnittstellen auf ihren Home Ports befinden, überprüfen Sie den Cluster-Zustand und setzen Sie das automatische Giveback zurück.

.Schritte
. Überprüfen Sie, ob die logischen Schnittstellen an ihren Home-Server und ihre Ports berichten:
+
`network interface show -is-home false`

+
Falls logische Schnittstellen als „false“ aufgeführt sind, werden sie wieder auf ihre ursprünglichen Ports zurückgesetzt:

+
`network interface revert -vserver * -lif *`

. Überprüfen Sie den Zustand Ihres Clusters.  Siehe die https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["So führen Sie eine Cluster-Integritätsprüfung mit einem Skript in ONTAP durch"^] KB-Artikel.
. Wenn die automatische Rückübertragung deaktiviert wurde, aktivieren Sie sie erneut:
+
`storage failover modify -node local -auto-giveback true`





[[step-2-return-the-failed-part-to-netapp]]
== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
