---
permalink: fas-70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, prerequisite, replace the controller module 
summary: Bevor Sie den Controller in Ihrem FAS70- oder FAS90-System austauschen, stellen Sie sicher, dass Sie die erforderlichen Anforderungen für einen erfolgreichen Austausch erfüllen. Dazu gehört der richtige Ersatz-Controller, ein Backup Ihrer Systemkonfiguration sowie der Zugriff auf alle erforderlichen Tools und Firmware. 
---
= Voraussetzung für den Austausch des Controllers – FAS70 und FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie den Controller in Ihrem FAS70- oder FAS90-System austauschen, stellen Sie sicher, dass Sie die erforderlichen Anforderungen für einen erfolgreichen Austausch erfüllen. Dazu gehört der richtige Ersatz-Controller, ein Backup Ihrer Systemkonfiguration sowie der Zugriff auf alle erforderlichen Tools und Firmware.

Überprüfen Sie die Anforderungen für den Austausch des Controllers.

* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Verwenden Sie dieses Verfahren nicht für Controller-Upgrades. Eine Anleitung finden Sie im https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Wählen Sie das Upgrade Ihrer Controller-Hardware aus"].
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie im Abschnitt überprüfen https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Auswahl des richtigen Wiederherstellungsverfahrens"] , ob Sie diesen Vorgang zum Austausch des Controllers durchführen sollten.
* Sie müssen die ausgefallene Komponente durch die Field-Replaceable Unit (FRU) ersetzen, die Sie von NetApp erhalten haben.
* Ein Controller-Modul muss durch ein Controller-Modul desselben Modelltyps ersetzt werden. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* Da sich das Startgerät auf dem Systemverwaltungsmodul befindet, das auf der Rückseite des Systems installiert ist, müssen Sie das Startgerät beim Austausch eines Controller-Moduls nicht verschieben.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.


* Sie müssen immer die Konsolenausgabe des Controllers in einer Textprotokolldatei erfassen.
+
Auf diese Weise erhalten Sie eine Aufzeichnung des Verfahrens, damit Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.



.Was kommt als Nächstes?
Nachdem Sie die Anforderungen überprüft haben, um Ihren FAS70 oder FAS90 Controller zu ersetzen, müssen Sie link:controller-replace-shutdown.html["Fahren Sie die Controller herunter"].
