---
permalink: fas-70-90/install-hardware.html 
sidebar: sidebar 
keywords: fas70, fas90, install hardware, telco rack 
summary: Installieren Sie Ihr Speichersystem im Schrank oder im Telco-Rack. 
---
= Installieren Sie die Hardware FAS70 und FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Installieren Sie nach der Vorbereitung auf die Installation Ihres FAS70- oder FAS90-Speichersystems die Hardware für das System. Installieren Sie zunächst die Schienensätze. Installieren und sichern Sie dann Ihre Plattform in einem Schrank oder einem Telco-Rack.

Überspringen Sie diesen Schritt, wenn Ihr Schrank bereits bestückt ist.

.Bevor Sie beginnen
* Stellen Sie sicher, dass die Anweisungen im Schienensatz enthalten sind.
* Beachten Sie die Sicherheitsbedenken im Zusammenhang mit dem Gewicht des Lagersystems und des Lagerregals.
* Stellen Sie fest, dass der Luftstrom durch das Speichersystem von der Vorderseite, an der die Blende oder die Endkappen installiert sind, einströmt und an der Rückseite, an der sich die Anschlüsse befinden, absaugt.


.Schritte
. Installieren Sie die Schienen-Kits für Ihr Speichersystem und die Lagerregale nach Bedarf gemäß den Anweisungen, die den Kits beiliegen.
. Installieren und sichern Sie Ihr Speichersystem im Schrank oder im Telco-Rack:
+
.. Positionieren Sie das Speichersystem auf den Schienen in der Mitte des Schranks oder des Telco-Racks, und stützen Sie das Speichersystem von unten ab, und schieben Sie es hinein.
.. Befestigen Sie das Speichersystem mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.


. Montieren Sie das Lagerregal:
+
.. Positionieren Sie die Rückseite des Lagerregals auf den Schienen, und stützen Sie das Regal von unten ab, und schieben Sie es in den Schrank oder das Telco-Rack.
+
Wenn Sie mehrere Storage-Shelfs installieren, platzieren Sie das erste Storage-Shelf direkt über den Controllern. Platzieren Sie das zweite Storage-Shelf direkt unter den Controllern. Wiederholen Sie dieses Muster für zusätzliche Storage-Shelfs.

.. Befestigen Sie den Aufbewahrungs-Shelf mit den mitgelieferten Befestigungsschrauben am Schrank oder Telco-Rack.


. Schließen Sie die Kabelverwaltungsgeräte an der Rückseite des Speichersystems an.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installieren Sie das Kabelverwaltungsgerät]

. Befestigen Sie die Blende an der Vorderseite des Speichersystems.


.Was kommt als Nächstes?
Nachdem Sie die Hardware für Ihr FAS70 oder FAS90 Storage-System installiert haben, können Sie link:install-cable.html["Verkabeln Sie die Hardware für Ihr FAS70 oder FAS90 Storage-System."].
