---
permalink: asa900/chassis_replace_overview.html 
sidebar: sidebar 
keywords: asa a900, replace the chassis, overview 
summary: Alle anderen Systemkomponenten müssen einwandfrei funktionieren. Andernfalls müssen Sie sich an den technischen Support wenden. 
---
= Anforderungen sollten vor dem Austausch eines ASA A900 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Austauschen des Gehäuses müssen Sie die Netzteile, Lüfter, Controller-Module, I/O-Module, DCPM-Module entfernen. Und USB-LED-Modul aus dem beeinträchtigten Gehäuse, entfernen Sie das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank, installieren Sie das Ersatzgehäuse an seiner Stelle und installieren Sie dann die Komponenten im Ersatzgehäuse.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

