---
permalink: asa900/controller_replace_system_config_restore_and_verify.html 
sidebar: sidebar 
keywords:  
summary: Nach dem Austausch und dem Booten der Hardware im Wartungsmodus überprüfen Sie die Low-Level-Systemkonfiguration des Ersatz-Controllers und konfigurieren nach Bedarf die Systemeinstellungen neu. 
---
= Stellen Sie die Systemkonfiguration wieder her und überprüfen Sie sie – ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Austausch der Hardware überprüfen Sie die Low-Level-Systemkonfiguration des Ersatz-Controllers und konfigurieren das System nach Bedarf neu.



== Schritt 1: Stellen Sie die Systemzeit ein und überprüfen Sie sie

Sie sollten die Uhrzeit und das Datum auf dem Ersatzcontroller-Modul gegen das gesunde Controller-Modul in einem HA-Paar oder gegen einen zuverlässigen Zeitserver in einer eigenständigen Konfiguration überprüfen. Wenn Zeit und Datum nicht übereinstimmen, müssen Sie sie auf dem Ersatzcontroller-Modul zurücksetzen, um mögliche Ausfälle auf Clients aufgrund von Zeitunterschieden zu verhindern.

.Über diese Aufgabe
Es ist wichtig, dass Sie die Befehle in den Schritten auf den richtigen Systemen anwenden:

* Der Node _Replacement_ ist der neue Node, der den beeinträchtigten Knoten im Rahmen dieses Verfahrens ersetzt.
* Der Node _Healthy_ ist der HA-Partner des Node _Replacement_.


.Schritte
. Wenn sich der Node _Replacement_ nicht an der LOADER-Eingabeaufforderung befindet, halten Sie das System an der LOADER-Eingabeaufforderung an.
. Überprüfen Sie auf dem Node _Healthy_ die Systemzeit: `cluster date show`
+
Datum und Uhrzeit basieren auf der konfigurierten Zeitzone.

. Prüfen Sie an der LOADER-Eingabeaufforderung Datum und Uhrzeit auf dem Node _Replacement_: `show date`
+
Datum und Uhrzeit werden in GMT angegeben.

. Legen Sie bei Bedarf das Datum in GMT auf dem Ersatzknoten fest: `set date _mm/dd/yyyy_`
. Stellen Sie bei Bedarf die Zeit in GMT auf dem Ersatzknoten ein: `set time _hh:mm:ss_`
. Bestätigen Sie an der LOADER-Eingabeaufforderung Datum und Uhrzeit am Node _Replacement_: `show date`
+
Datum und Uhrzeit werden in GMT angegeben.





== Schritt 2: Überprüfen und Einstellen des HA-Status des Controllers

Sie müssen die überprüfen `HA` Status des Controller-Moduls und, falls erforderlich, aktualisieren Sie den Status entsprechend Ihrer Systemkonfiguration.

. Überprüfen Sie im Wartungsmodus des Ersatz-Controller-Moduls, ob alle Komponenten gleich angezeigt werden `HA` Bundesland: `ha-config show`
+
[cols="1,2"]
|===
| Ihr System befindet sich in... | Der HA-Status für alle Komponenten sollte... 


 a| 
Ein HA-Paar
 a| 
Hochverfügbarkeit



 a| 
MetroCluster FC-Konfiguration mit vier oder mehr Nodes
 a| 
mcc



 a| 
Eine MetroCluster IP-Konfiguration
 a| 
Mccip

|===
. Wenn der angezeigte Systemzustand des Controller-Moduls nicht mit der Systemkonfiguration übereinstimmt, setzen Sie das ein `HA` Status für das Controller-Modul: `ha-config modify controller _ha-state_`
. Wenn der angezeigte Systemzustand des Gehäuses nicht mit der Systemkonfiguration übereinstimmt, legen Sie den fest `HA` Status für das Chassis: `ha-config modify chassis _ha-state_`

