---
permalink: asa900/overview.html 
sidebar: sidebar 
keywords: ASA A900 specifications, ASA A900 specs, NetApp ASA A900, ASA A900 hardware 
summary: Wichtige Spezifikationen für das ASA A900 -Speichersystem 
---
= Wichtige Spezifikationen für ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für den ASA A900.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der ASA A900 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für ASA A900

Plattformkonfiguration: ASA A900 Single Chassis HA-Paar

Max. Rohkapazität: 14,6880 PB

Arbeitsspeicher: 2048.0000 GB

Formfaktor: 8U-Gehäuse mit 2 HA-Controllern

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 20

Mindestens erforderliche ONTAP -Version: ONTAP 9.13.1



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS |  |  |  


| SAN | 6 | 88,1 PB / 78,3 PiB | 12288 GB 


| HA-Paar |  | 14,7 PB / 13,0 PiB | 2048,0000 
|===


=== IO



==== Integrierte E/A

Keine Onboard-E/A-Daten.



==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 32 


| Ethernet 25 Gbit/s | 64 


| Ethernet 10 Gbit/s | 64 


| FC 32 Gbit/s | 64 


| NVMe/FC 32 Gbit/s | 64 


|  | 0 


| SAS 12 Gbit/s | 64 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 2 


| RS-232 115 Kbps | 6 


| USB 12 Mbit/s | 2 
|===


=== Unterstützte Speichernetzwerke

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 8004 BTU/h
* Leistung im schlimmsten Fall: 9937 BTU/h
* Gewicht: 220,5 lbbr/100,0 kg
* Höhe: 8U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,7 Zoll, 45,0 cm)
* Tiefe: 28,8 Zoll (36,8 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (br/50 °F bis br/95 °F) bei br/= 3048 mbr/= 10000 ft) Höhe; 8 % bis 80 % (br/relative Luftfeuchtigkeit, nicht kondensierend)
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß)<br/>10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 7,4;br/Schalldruck (LpAm) (in der Nähe): 65,0 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP -Management-Schnittstelle; Redundante Hot-Swap-fähige Controller; Redundante Hot-Swap-fähige Netzteile; SAS-In-Band-Management über SAS-Verbindungen; [//] 2025-10-15 ontap-systems-internal/issues/1357
