---
permalink: a150/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, shutdown, checks, onboard, encryption, keys, impaired controller, disable, automatic, feedback 
summary: Bevor Sie den beeinträchtigten Controller herunterfahren und den Status der integrierten Verschlüsselungsschlüssel prüfen, müssen Sie den Status des beeinträchtigten Controllers überprüfen, die automatische Rückgabe deaktivieren und überprüfen, welche Version von ONTAP das System ausführt. 
---
= Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Datensicherheit auf Ihrem Speichersystem zu gewährleisten, müssen Sie die Unterstützung und den Status des Verschlüsselungsschlüssels auf Ihrem Boot-Medium überprüfen. Überprüfen Sie, ob Ihre ONTAP Version NetApp Volume Encryption (NVE) unterstützt und bevor Sie den Controller herunterfahren, ob der Schlüsselmanager aktiv ist.



== Schritt: Prüfen Sie, ob Ihre Version von ONTAP NetApp-Volume-Verschlüsselung unterstützt

Prüfen Sie, ob Ihre ONTAP Version NetApp Volume Encryption (NVE) unterstützt. Diese Informationen sind entscheidend, um das richtige ONTAP-Image herunterzuladen.

.Schritte
. Stellen Sie fest, ob Ihre ONTAP-Version Verschlüsselung unterstützt, indem Sie den folgenden Befehl ausführen:
+
`version -v`

+
Wenn die Ausgabe enthält `1Ono-DARE`, wird NVE auf Ihrer Cluster-Version nicht unterstützt.

. Je nachdem, ob NVE auf Ihrem System unterstützt wird, führen Sie eine der folgenden Aktionen durch:
+
** Falls NVE unterstützt wird, laden Sie das ONTAP Image mit NetApp Volume Encryption herunter.
** Falls NVE nicht unterstützt wird, laden Sie das ONTAP Image *ohne* NetApp-Volume-Verschlüsselung herunter.






== Schritt 2: Stellen Sie fest, ob es sicher ist, den Controller herunterzufahren

Um einen Controller sicher herunterzufahren, müssen Sie zuerst ermitteln, ob der External Key Manager (EKM) oder der Onboard Key Manager (OKM) aktiv ist. Überprüfen Sie anschließend den verwendeten Schlüsselmanager, zeigen Sie die entsprechenden Schlüsselinformationen an und ergreifen Sie Maßnahmen, die auf dem Status der Authentifizierungsschlüssel basieren.

.Schritte
. Bestimmen Sie, welcher Schlüsselmanager auf Ihrem System aktiviert ist:
+
[cols="1a,2a"]
|===
| ONTAP-Version | Führen Sie diesen Befehl aus 


 a| 
ONTAP 9.14.1 oder höher
 a| 
`security key-manager keystore show`

** Wenn EKM aktiviert ist, `EKM` wird in der Befehlsausgabe aufgelistet.
** Wenn OKM aktiviert ist, `OKM` wird in der Befehlsausgabe aufgelistet.
** Wenn kein Schlüsselmanager aktiviert ist, `No key manager keystores configured` wird in der Befehlsausgabe aufgeführt.




 a| 
ONTAP 9.13.1 oder früher
 a| 
`security key-manager show-key-store`

** Wenn EKM aktiviert ist, `external` wird in der Befehlsausgabe aufgelistet.
** Wenn OKM aktiviert ist, `onboard` wird in der Befehlsausgabe aufgelistet.
** Wenn kein Schlüsselmanager aktiviert ist, `No key managers configured` wird in der Befehlsausgabe aufgeführt.


|===
. Wählen Sie eine der folgenden Optionen, je nachdem, ob ein Key Manager auf Ihrem System konfiguriert ist.
+
[role="tabbed-block"]
====
.Kein Schlüsselmanager konfiguriert
--
Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].

--
.Externer oder integrierter Schlüsselmanager konfiguriert
--
.. Geben Sie den folgenden Abfragebefehl ein, um den Status der Authentifizierungsschlüssel in Ihrem Schlüsselmanager anzuzeigen.
+
`security key-manager key query`

.. Überprüfen Sie die Ausgabe für den Wert in der `Restored` Spalte für Ihren Schlüsselmanager.
+
Diese Spalte gibt an, ob die Authentifizierungsschlüssel für Ihren Schlüsselmanager (entweder EKM oder OKM) erfolgreich wiederhergestellt wurden.



--
====


. Wählen Sie je nachdem, ob Ihr System den External Key Manager oder den Onboard Key Manager verwendet, eine der folgenden Optionen aus.
+
[role="tabbed-block"]
====
.Externer Schlüsselmanager
--
Befolgen Sie je nach dem in der Spalte angezeigten Ausgangswert `Restored` die entsprechenden Schritte.

[cols="1a,2a"]
|===
| Ausgabewert in `Restored` Spalte | Führen Sie die folgenden Schritte aus... 


 a| 
`true`
 a| 
Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].



 a| 
Alles andere als `true`
 a| 
.. Stellen Sie die externen Authentifizierungsschlüssel für das Verschlüsselungsmanagement auf allen Nodes im Cluster mit dem folgenden Befehl wieder her:
+
`security key-manager external restore`

+
Wenn der Befehl fehlschlägt, wenden Sie sich an http://mysupport.netapp.com/["NetApp Support"^].

.. Überprüfen Sie, ob in der `Restored` Spalte für alle Authentifizierungsschlüssel die angezeigt werden `true`, indem Sie den  Befehl eingeben `security key-manager key query`.
+
Wenn alle Authentifizierungsschlüssel vorhanden sind `true`, können Sie den beeinträchtigten Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].



|===
--
.Onboard Key Manager
--
Befolgen Sie je nach dem in der Spalte angezeigten Ausgangswert `Restored` die entsprechenden Schritte.

[cols="1a,2a"]
|===
| Ausgabewert in `Restored` Spalte | Führen Sie die folgenden Schritte aus... 


 a| 
`true`
 a| 
Sichern Sie die OKM-Informationen manuell.

.. Wechseln Sie in den erweiterten Modus, indem `set -priv advanced` Sie aufrufen und dann bei Aufforderung eingeben `Y`.
.. Geben Sie den folgenden Befehl ein, um die Informationen zum Verschlüsselungsmanagement anzuzeigen:
+
`security key-manager onboard show-backup`

.. Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei.
+
Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.

.. Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].




 a| 
Alles andere als `true`
 a| 
.. Geben Sie den integrierten Sicherheitsschlüssel-Manager Sync-Befehl ein:
+
`security key-manager onboard sync`

.. Geben Sie bei Aufforderung die 32-stellige alphanumerische Passphrase für das Onboard-Verschlüsselungsmanagement ein.
+
Wenn die Passphrase nicht angegeben werden kann, wenden Sie sich an http://mysupport.netapp.com/["NetApp Support"^].

.. Überprüfen Sie, ob die `Restored` Spalte für alle Authentifizierungsschlüssel angezeigt wird `true`:
+
`security key-manager key query`

.. Überprüfen Sie, ob der `Key Manager` Typ , anzeigt `onboard`und sichern Sie die OKM-Informationen manuell.
.. Geben Sie den Befehl ein, um die Backup-Informationen für das Verschlüsselungsmanagement anzuzeigen:
+
`security key-manager onboard show-backup`

.. Kopieren Sie den Inhalt der Backup-Informationen in eine separate Datei oder eine Protokolldatei.
+
Sie werden es in Disaster-Szenarien benötigen, in denen Sie OKM manuell wiederherstellen müssen.

.. Sie können den außer Betrieb genommenen Controller sicher herunterfahren. Gehen Sie zu link:bootmedia-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].


|===
--
====

