---
permalink: a150/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Sie ersetzen ein beschädigtes Chassis durch ein neues Chassis desselben Modells wie das beschädigte Chassis. 
---
= Die Anforderungen für den Austausch des Chassis in Ihrem AFF A150 System werden hier aufgeführt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Chassis im AFF A150 System ersetzt wird, müssen die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllt sein. Dazu zählt die Überprüfung, dass alle anderen Komponenten im System ordnungsgemäß funktionieren, sowie das Verständnis, dass das Verfahren unterbrechend ist und das Herunterfahren beider Controller erfordert.

Um das Gehäuse zu ersetzen, müssen Sie die Netzteile, Festplatten und Controller-Module oder Module vom beeinträchtigten Gehäuse in das neue Gehäuse verlegen und das beeinträchtigte Gehäuse aus dem Geräterrack oder dem Systemschrank durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse auswechseln.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie alle Laufwerke und Controller-Module bzw. -Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Controllern kommt es zu einem vollständigen Service-Ausfall und zu einem teilweisen Ausfall in einem Cluster mit mehreren Nodes.

