---
permalink: a150/install-videos.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, aff a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.' 
---
= Videos - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt zwei Videos: Eine, die zeigt, wie ein Rack und Verkabelung Ihres Systems erfolgen, und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.

Wenn Sie über eine MetroCluster-Konfiguration verfügen, verwenden Sie den MetroCluster-Installationsinhalt.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster-Dokumentation"^]



== Video eines von zwei: Hardware-Installation und -Verkabelung

Das folgende Video zeigt, wie Sie Ihr neues System installieren und verkabeln.

.Animation - Installation und Einrichtung eines AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]


== Video zwei von zwei: Durchführung der End-to-End-Softwarekonfiguration

Das folgende Video zeigt die End-to-End-Softwarekonfiguration für Systeme mit ONTAP 9.2 und höher.

video::WAE0afWhj1c?[youtube]