---
permalink: a150/install-setup.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, install, setup, initial configuration 
summary: Installieren und richten Sie Ihr System ein. 
---
= Starten Sie hier: Wählen Sie Ihre Installation und Setup-Erfahrung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die meisten Konfigurationen stehen Ihnen verschiedene Content-Formate zur Verfügung.

* link:../a150/install-quick-guide.html["Schnelle Schritte"]
+
Eine druckbare PDF-Datei mit Schritt-für-Schritt-Anweisungen mit Live-Links zu zusätzlichen Inhalten.

* link:../a150/install-videos.html["Videoschritte"]
+
Video Schritt-für-Schritt-Anleitungen.

* link:../a150/install-detailed-guide.html["Detaillierte Schritte"]
+
Schritt-für-Schritt-Anleitungen mit Live-Links zu weiteren Inhalten



Wenn sich das System in einer MetroCluster-IP-Konfiguration befindet, lesen Sie den https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster-IP-Konfiguration installieren"] Anweisungen.

*Warnung:* Wenn Ihr System mit ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 oder ONTAP 9.15.1 - 9.15.1P2 installiert wird und Ihr System 10 oder mehr interne Solid-State-Laufwerke enthält, müssen Sie zusätzliche Schritte zur Vorbereitung des Systems auf die Installation durchführen. Siehe Ausgabe  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173 - ADP hinterlässt keine freie Root-Partition auf einer AFF A150 mit 10 oder mehr internen Laufwerken"^].
