---
permalink: a150/overview.html 
sidebar: sidebar 
summary: Wichtige Spezifikationen für die A150-Plattformgruppe 
---
= Wichtige Spezifikationen für AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das AFF A150 -Speichersystem in einem einzelnen Hochverfügbarkeitspaar.  Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== Wichtige Spezifikationen für AFF A150

* Plattformkonfiguration: AFF A150 UTA2 Einzelgehäuse HA-Paar
* Max. Rohkapazität: 0,5472 PB
* Arbeitsspeicher: 64.0000 GB
* Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen
* ONTAP -Version: ONTAP: 9.16.1P2
* Mindest ONTAP -Version: ONTAP 9.10.1P12 == Scaleout-Maxima
* Typ: NAS; HA-Paare: 12; Rohkapazität: 6,6 PB / 5,8 PiB; Max. Speicher: 768 GB
* Typ: SAN; HA-Paare: 6; Rohkapazität: 3,3 PB / 2,9 PiB; Max. Speicher: 384 GB
* Typ: HA-Paar; Rohkapazität: 0,5 PB / 0,5 PiB; Max. Speicher: 64.0000




== E/A



=== Integrierte E/A

* Protokoll: Ethernet 10 Gbit/s; Ports: 12
* Protokoll: FC 16 Gbit/s; Ports: 8
* Protokoll: SAS 12 Gbit/s; Ports: 4




=== Gesamt-E/A

* Protokoll: Ethernet 10 Gbit/s; Ports: 12
* Protokoll: FC 16 Gbit/s; Ports: 8
* Protokoll: SAS 12 Gbit/s; Ports: 4




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 2
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 12 Mbit/s; Anschlüsse: 2




== Speichernetzwerke werden unterstützt

* CIFS
* FC
* FCoE
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/TCP
* S3
* S3 mit NAS
* KMU 2.0
* SMB 2.1
* SMB 2.x
* KMU 3.0
* KMU 3.1
* SMB 3.1.1 == Systemumgebungsspezifikationen
* Typische Leistung: 1209 BTU/h
* Leistung im schlimmsten Fall: 1676 BTU/h
* Gewicht: 60.8 lb 27.6 kg
* Höhe: 2U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 19,0 Zoll (24,1 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 5 °C bis 45 °C (41 °F bis 113 °F) bei <= 3048 m (<= 10000 ft) Höhe; 8 % bis 90 % relative Luftfeuchtigkeit, nicht kondensierend
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß) 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 6,9 Schalldruck (LpAm) (in der Nähe): 51,0 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile
* SAS-In-Band-Verwaltung über SAS-Verbindungen

