---
permalink: asa-c400/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: asa-c400, replace the boot media 
summary: Stellen Sie vor dem Austausch des Bootmediums in Ihrem ASA C400 System sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Stellen Sie dazu sicher, dass Sie über einen USB-Stick mit ausreichend Speicherplatz verfügen und dass Sie das richtige Ersatz-Bootmedium verwenden. 
---
= Voraussetzungen für die manuelle Wiederherstellung von Bootmedien – ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Bootmediums in Ihrem ASA C400 System sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Stellen Sie dazu sicher, dass Sie über einen USB-Stick mit ausreichend Speicherplatz verfügen und dass Sie das richtige Ersatz-Bootmedium verwenden.

Wenn Ihr Speichersystem ONTAP 9.17.1 oder höher ausführt, verwenden Sie dielink:bootmedia-replace-workflow-bmr.html["automatisiertes Boot-Wiederherstellungsverfahren"] .  Wenn auf Ihrem System eine frühere Version von ONTAP ausgeführt wird, müssen Sie den manuellen Boot-Wiederherstellungsprozess verwenden.

.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Boot-Mediums überprüft haben, müssen Sie link:bootmedia-encryption-preshutdown-checks.html["Prüfen Sie die Unterstützung und den Status der Verschlüsselungsschlüssel auf dem Startmedium"].
