---
permalink: asa-r2-70-90/bootmedia-overview.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, overview, the boot media 
summary: Erfahren Sie mehr über die automatisierte Methode und die manuelle Methode zum Austauschen der Boot-Medien. 
---
= Übersicht über den Austausch der Boot-Medien - ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können fehlerhafte Startmedien manuell durch Verwendung eines USB-Moduls für das Startabbild oder durch die Option zur automatischen Wiederherstellung des Startmediums (BMR) ersetzen.

* link:bootmedia-replace-requirements-bmr.html["Automatisierte Recovery von Boot-Medien"]
+
Die automatische Boot-Medien-Recovery verwendet das Boot-Image vom Partned-Knoten und führt automatisch die entsprechende Boot-Menüoption aus, um das Boot-Image auf dem Ersatz-Boot-Medium zu installieren.

* link:bootmedia-replace-requirements.html["Manueller Start-Datenträger ersetzen"]
+
Beim manuellen Ersetzen von Startmedien wird das ONTAP-Image von der NetApp-Support-Website heruntergeladen, das Image auf ein USB-Laufwerk übertragen, auf das Startmedium heruntergeladen und manuell durch die Optionen des Startmenüs geleitet, um das ONTAP-Image auf dem Ersatz-Startmedium zu installieren.


