---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: Erfahren Sie mehr über die Anforderungen für den Austausch der Boot-Medien. 
---
= Voraussetzungen für den Austausch von Boot-Medien – ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie vor dem Austauschen des Startmediums die folgenden Anforderungen.

* Sie müssen das ausgefallene Boot-Medium durch ein Ersatz-Boot-Medium ersetzen, das Sie von NetApp erhalten haben.
* Es dürfen keine fehlerhaften Cluster-Ports auf dem gestörten Controller vorhanden sein.
* Stellen Sie fest, ob Onboard Key Manager (OKM) oder Eternal Key Manager (EKM) mithilfe einer der folgenden Methoden konfiguriert ist:
+
** Sie können den Systemadministrator fragen, ob OKM oder EKM aktiviert sind.
** Um zu überprüfen, ob OKM aktiviert ist, können Sie die verwenden `security key-manager onboard show`.
** Um zu überprüfen, ob EKM aktiviert ist, können Sie die verwenden `security key-manager external show`.


* Für OKM benötigen Sie den Inhalt der OKM-Passphrase-Datei.
* Für EKM benötigen Sie Kopien der folgenden Dateien vom Partnerknoten:
+
** Datei /cfcard/kmip/servers.cfg.
** Datei /cfcard/kmip/certs/Client.crt.
** Datei /cfcard/kmip/certs/client.key.
** Datei /cfcard/kmip/certs/CA.pem.




.Wie es weiter geht
Nachdem Sie die Anforderungen für die Startmedien überprüft haben, können Sie link:bootmedia-shutdown-bmr.html["Schalten Sie den außer Betrieb genommenen Controller aus"].
