---
permalink: asa-r2-70-90/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, overview, the boot media 
summary: Die Wiederherstellung der Startmedien für Ihr ASA A70- oder ASA A90-Speichersystem verwendet das Boot-Image des Partner-Knotens und führt automatisch die entsprechende Startmenüoption aus, um das Startabbild auf dem Ersatz-Startmedium zu installieren. 
---
= Übersicht über Boot-Medien Wiederherstellung - ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Wiederherstellung der Startmedien für Ihr ASA A70- oder ASA A90-Speichersystem verwendet das Boot-Image des Partner-Knotens und führt automatisch die entsprechende Startmenüoption aus, um das Startabbild auf dem Ersatz-Startmedium zu installieren.

Wenn beim Booten Fehlermeldungen wie der unten gezeigten auftreten, müssen Sie die Boot-Medien ersetzen und das ONTAP Image vom Partner-Node wiederherstellen.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....