---
permalink: asa-r2-70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, verify and set HA state, complete the replacement process 
summary: Sie müssen den HA-Status des Gehäuses überprüfen und das fehlerhafte Teil an NetApp zurücksenden, wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben. 
---
= Schließen Sie den Austausch des Gehäuses ab – ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Gehäuseersatzprozess abzuschließen, müssen Sie ONTAP starten, den Storage zurücksenden, den Zustand des Speichersystems überprüfen und das fehlerhafte Gehäuse an NetApp zurücksenden.



== Schritt 1: Starten Sie die Controller und geben Sie die Controller zurück

Nachdem die Controller neu gebootet wurden, booten Sie ONTAP und geben Sie die Controller zurück.

. Überprüfen Sie die Konsolenausgabe:
+
.. Wenn der Controller bis zur Loader-Eingabeaufforderung gebootet wird, booten Sie den Controller mit dem Befehl neu `boot_ontap`.
.. Wenn die Konsole nach dem Neubooten angezeigt wird `waiting for giveback`, loggen Sie sich beim Partner-Controller ein und überprüfen Sie, ob der ausgetauschte Controller mit dem Befehl bereit ist, die Rückgabe durchzuführen `storage failover show`.


. Giveback durchführen:
+
.. Schließen Sie das Konsolenkabel an den Partner Controller an.
.. Geben Sie mit dem Befehl den Controller zurück `storage failover giveback -fromnode local`.






== Schritt 2: Überprüfen Sie den Zustand des Storage-Systems

Nachdem der Controller den Speicher zurückgegeben hat, sollten Sie den Gesamtzustand mit überprüfen https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].

. Nachdem die Rückgabe abgeschlossen ist, führen Sie Active IQ Config Advisor aus, um den Zustand des Storage-Systems zu überprüfen.
. Beheben Sie alle Probleme, die auftreten.




== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
