---
permalink: asa-r2-70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, prepare to replace the chassis 
summary: Bereiten Sie den Austausch des Gehäuses für beeinträchtigte Personen in Ihrem ASA A70 oder ASA A90-System vor, indem Sie das Gehäuse für beeinträchtigte Personen identifizieren, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module beschriften. 
---
= Bereiten Sie den Austausch des Gehäuses vor – ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bereiten Sie den Austausch des Gehäuses für beeinträchtigte Personen in Ihrem AFF A70- oder AFF A90-System vor, indem Sie das Gehäuse für beeinträchtigte Personen ermitteln, die Ersatzkomponenten überprüfen und die Kabel und Controller-Module beschriften.



== Schritt 1: Suchen und überwachen Sie Ihr System

Sie sollten eine Konsolensitzung öffnen und Sitzungsprotokolle zur späteren Referenz speichern und die LED für die Systemposition einschalten, um das Gehäuse für beeinträchtigte Personen zu finden.

. Stellen Sie eine Verbindung zum seriellen Konsolenport mit der Schnittstelle mit her und überwachen Sie das System.
. Suchen und Einschalten der Standort-LED des Controllers:
+
.. Verwenden Sie den `system controller location-led show` Befehl, um den aktuellen Status der Standort-LED anzuzeigen.
.. Ändern Sie den Status der Standort-LED auf „ein“:
+
`system controller location-led modify -node _node1_ -state on`.

+
Die Standort-LED leuchtet 30 Minuten lang.







== Schritt 2: Prüfen Sie die Austauschkomponenten

Überprüfen Sie, ob Sie die erforderlichen Komponenten erhalten haben, entfernen Sie sie aus der Verpackung, und bewahren Sie die Verpackung auf.

. Bevor Sie die Verpackung öffnen, sollten Sie auf dem Verpackungsetikett nachsehen und Folgendes überprüfen:
+
** Teilenummer der Komponente.
** Teilebeschreibung.
** Menge im Karton.


. Entfernen Sie den Inhalt aus der Verpackung, und verwenden Sie die Verpackung, um die fehlerhafte Komponente an NetApp zurückzugeben.




== Schritt 3: Beschriften Sie die Kabel und Controller-Module und Erden Sie sich selbst.

Bevor Sie die Kabel und Controller aus den Controller-Modulen oder dem Chassis entfernen, sollten Sie die Kabel und Controller beschriften.

. Beschriften Sie alle Kabel, die dem Speichersystem zugeordnet sind. Dies erleichtert die spätere Neueinbringung in diesem Verfahren.
. Beschriften Sie die Controller-Module.
. Wenn Sie nicht bereits ordnungsgemäß geerdet sind, Erden Sie sich.


.Was kommt als Nächstes?
Nachdem Sie bereit sind, Ihre ASA A70 oder ASA A90 Chassis Hardware zu ersetzen, müssen Sie link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"].
