---
permalink: asa-r2-70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to recable the system, boot the system 
summary: Steuerung der Speicherressourcen wieder an den Ersatz-Controller zurückgeben, damit Ihr ASA A70 oder ASA A90 System den normalen Betrieb wieder aufnehmen kann. 
---
= Geben Sie die Steuerung zurück - ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Steuerung der Speicherressourcen wieder an den Ersatz-Controller zurückgeben, damit Ihr ASA A70 oder ASA A90 System den normalen Betrieb wieder aufnehmen kann. Das Rückgabeverfahren variiert je nach dem von Ihrem System verwendeten Verschlüsselungstyp: keine Verschlüsselung oder Onboard Key Manager (OKM)-Verschlüsselung.

[role="tabbed-block"]
====
.Keine Verschlüsselung
--
Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie seinen Speicher zurückgeben.

.Schritte
. Geben Sie in der Loader-Eingabeaufforderung `boot_ontap` .
. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die Eingabeaufforderung _Login_ angezeigt wird, fahren Sie mit dem nächsten Schritt am Ende dieses Abschnitts fort.
** Wenn „_waiting for Giveback_“ angezeigt wird, drücken Sie die Taste <enter>, melden Sie sich beim Partner-Node an und fahren Sie dann mit dem nächsten Schritt am Ende dieses Abschnitts fort.


. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`
. Wenn das automatische Giveback deaktiviert wurde, aktivieren Sie es erneut: `storage failover modify -node local -auto-giveback _true_`
. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Onboard-Verschlüsselung (OKM)
--
Setzt die integrierte Verschlüsselung zurück und setzt den Controller in den normalen Betrieb zurück.

.Schritte
. Geben Sie in der Loader-Eingabeaufforderung `boot_ontap maint` .
. Starten Sie das ONTAP-Menü über die Loader-Eingabeaufforderung `boot_ontap menu`, und wählen Sie Option 10.
. Geben Sie die OKM-Passphrase ein.
+

NOTE: Sie werden zweimal zur Eingabe der Passphrase aufgefordert.

. Geben Sie die Daten des Sicherungsschlüssels ein, wenn Sie dazu aufgefordert werden.
. Geben Sie im Startmenü die Option für den normalen Start ein `1`.
. Drücken Sie <enter>, wenn _Waiting for Giveback_ angezeigt wird.
. Schieben Sie das Konsolenkabel zum Partner-Node und melden Sie sich als an `admin`.
. Nur die CFO-Aggregate zurückgeben (das Root-Aggregat): `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].


. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und überprüfen Sie den Failover-Status und den Giveback-Status: `storage failover show` Und `storage failover show-giveback`.
. Synchronisieren und überprüfen Sie den Status der Tasten:
+
.. Bringen Sie das Konsolenkabel wieder zum Ersatzcontroller.
.. Fehlende Schlüssel synchronisieren: `security key-manager onboard sync`
+

NOTE: Sie werden aufgefordert, die Cluster-weite Passphrase von OKM für das Cluster einzugeben.

.. Überprüfen Sie den Status der Schlüssel: `security key-manager key query -restored _false_`
+
Die Ausgabe sollte bei ordnungsgemäßer Synchronisierung keine Ergebnisse zeigen.

+
Wenn in der Ausgabe Ergebnisse angezeigt werden (die Schlüssel-IDs von Schlüsseln, die nicht in der internen Schlüsseltabelle des Systems vorhanden sind), wenden Sie sich an https://support.netapp.com["NetApp Support"].



. Stellen Sie den funktionsbeeinträchtigten Controller wieder in den Normalbetrieb ein, indem Sie den Speicher zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`
. Wenn das automatische Giveback deaktiviert wurde, aktivieren Sie es erneut: `storage failover modify -node local -auto-giveback _true_`
. Wenn AutoSupport aktiviert ist, können Sie die automatische Fallerstellung wiederherstellen/zurücknehmen: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====