---
permalink: asa-r2-70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to recable the system, boot the system 
summary: Sie müssen den Storage neu booten. 
---
= Geben Sie die Steuerung zurück - ASA A70 und ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie die Storage- und Netzwerkverbindungen, und geben Sie dann den Controller zurück.



== Geben Sie den Controller zurück

Setzen Sie die Verschlüsselung zurück, wenn diese aktiviert ist, und setzen Sie den Controller wieder in den normalen Betrieb ein.

[role="tabbed-block"]
====
.Keine Verschlüsselung
--
. Geben Sie in der Loader-Eingabeaufforderung `boot_ontap` .
. Drücken Sie <enter>, wenn die Konsolenmeldungen angehalten werden.
+
** Wenn die Eingabeaufforderung _Login_ angezeigt wird, fahren Sie mit dem nächsten Schritt am Ende dieses Abschnitts fort.
** Wenn „_waiting for Giveback_“ angezeigt wird, drücken Sie die Taste <enter>, melden Sie sich beim Partner-Node an und fahren Sie dann mit dem nächsten Schritt am Ende dieses Abschnitts fort.


. Stellen Sie den außer Betrieb genommenen Controller wieder ein, indem Sie seine Speicherung zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`.
. Wenn die automatische Rückgabe deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`.
. Wenn AutoSupport aktiviert ist, kann die automatische Fallerstellung wiederhergestellt/aufgehoben werden: `system node autosupport invoke -node * -type all -message MAINT=END`.


--
.Onboard-Verschlüsselung (OKM)
--
. Geben Sie in der Loader-Eingabeaufforderung `boot_ontap maint` .
. Starten Sie das ONTAP-Menü über die Loader-Eingabeaufforderung `boot_ontap menu`, und wählen Sie Option 10.
. Geben Sie die OKM-Passphrase ein. Sie können diese Passphrase vom Kunden erhalten, oder wenden Sie sich an https://support.netapp.com["NetApp Support"].
+

NOTE: Sie werden zweimal zur Eingabe der Passphrase aufgefordert.

. Geben Sie die Daten des Sicherungsschlüssels ein, wenn Sie dazu aufgefordert werden.
. Geben Sie im Startmenü die Option für den normalen Start ein `1`.
. Drücken Sie <enter>, wenn _Waiting for Giveback_ angezeigt wird.
. Schieben Sie das Konsolenkabel zum Partner-Node und melden Sie sich als an `admin`.
. Stellen Sie sicher, dass alle Core Dumps auf dem reparierten Node gespeichert werden, indem Sie in den erweiterten Modus“ und dann `run local partner savecore` wechseln `set -privilege advanced`.
. Zurück zum Admin-Hebel: `set privilege admin`.
. Nur die CFO-Aggregate zurückgeben (das Root-Aggregat): `storage failover giveback -fromnode local -only-cfo-aggregates true`
+
** Wenn Sie auf Fehler stoßen, wenden Sie sich an https://support.netapp.com["NetApp Support"].


. Warten Sie 5 Minuten, nachdem der Giveback-Bericht abgeschlossen ist, und überprüfen Sie den Failover-Status und den Giveback-Status: `storage failover show` Und `storage failover show-giveback`.
. Schieben Sie das Konsolenkabel zum Ersatzknoten, und geben Sie ein `security key-manager onboard sync`
+

NOTE: Sie werden aufgefordert, die Cluster-weite Passphrase von OKM für den Cluster einzugeben.

. Überprüfen Sie den Status der Tasten mit folgendem Befehl: `security key-manager key query -key-type svm-KEK`.
+
Wenn in der Spalte _restored_ alles außer _true_ angezeigt wird, kontaktieren Sie https://support.netapp.com["NetApp Support"].

. Stellen Sie den außer Betrieb genommenen Controller wieder ein, indem Sie seine Speicherung zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`.
. Wenn die automatische Rückgabe deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`.
. Wenn AutoSupport aktiviert ist, kann die automatische Fallerstellung wiederhergestellt/aufgehoben werden: `system node autosupport invoke -node * -type all -message MAINT=END`.


--
.Externer Schlüsselmanager (EKM))
--
. Wenn das Stammvolume mit External Key Manager verschlüsselt ist und das Konsolenkabel mit dem Ersatzknoten verbunden ist, geben Sie die Option ein `boot_ontap menu` und wählen Sie diese aus `11`.
. Beantworten Sie `y` oder `n` die folgenden Fragen:
+
Haben Sie eine Kopie der Datei /cfcard/kmip/certs/Client.crt? {J/n}

+
Haben Sie eine Kopie der Datei /cfcard/kmip/certs/client.key? {J/n}

+
Haben Sie eine Kopie der Datei /cfcard/kmip/certs/CA.pem? {J/n}

+
ODER

+
Haben Sie eine Kopie der Datei /cfcard/kmip/servers.cfg? {J/n}

+
Kennen Sie die KMIP-Serveradresse? {J/n}

+
Kennen Sie den KMIP-Port? {J/n}

+

NOTE: Wenden Sie sich https://support.netapp.com["NetApp Support"] bei Problemen an.

. Geben Sie die Informationen an für:
+
** Der Dateiinhalt des Clientzertifikats (Client.crt).
** Der Dateiinhalt des Client-Schlüssels (Client.key).
** Dateiinhalte der KMIP-Server-CA(s) (CA.pem)
** Die IP-Adresse für den KMIP-Server.
** Der Port für den KMIP-Server.


. Sobald das System verarbeitet wird, wird das Startmenü angezeigt. Wählen Sie „1“ für den normalen Start.
. Überprüfen Sie den Übernahmestatus: `storage failover show`.
. Stellen Sie sicher, dass alle Core Dumps auf dem reparierten Node gespeichert werden, indem Sie in den erweiterten Modus“ und dann `run local partner savecore` wechseln `set -privilege advanced`.
. Stellen Sie den außer Betrieb genommenen Controller wieder ein, indem Sie seine Speicherung zurückgeben: `storage failover giveback -ofnode _impaired_node_name_`.
. Wenn die automatische Rückgabe deaktiviert wurde, aktivieren Sie sie erneut: `storage failover modify -node local -auto-giveback true`.
. Wenn AutoSupport aktiviert ist, kann die automatische Fallerstellung wiederhergestellt/aufgehoben werden: `system node autosupport invoke -node * -type all -message MAINT=END`.


--
====