---
permalink: asa-r2-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a70 asa r2 a90 maintenance, maintenance, repairing asa r2 a70 asa r2 a90, repairing a70 asa r2 a90, replace a70 asa r2 a90 components 
summary: Wartung der ASA r2 A70, ASA r2 A90 Hardware 
---
= Wartung der ASA A70 und ASA A90 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Wartungsverfahren für Ihre Hardware durchführen. In diesem Abschnitt finden Sie Verfahren zur Wartung Ihrer Systemkomponenten ASA A70 und ASA A90.

Bei den Verfahren in diesem Abschnitt wird davon ausgegangen, dass die Systeme ASA A70 und ASA A90 bereits als Storage Node in der ONTAP-Umgebung implementiert wurden.



== Systemkomponenten

Für die Speichersysteme ASA A70 und ASA A90 können Sie Wartungsverfahren für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
link:bootmedia-overview.html["Boot-Medien – manuelle Wiederherstellung"]

link:bootmedia-overview-bmr.html["Boot-Medien – automatisierte Wiederherstellung"]
 a| 
Sie können fehlerhafte Startmedien manuell durch Verwendung eines USB-Moduls für das Startabbild ersetzen.

Beim automatischen Bootmedienaustausch wird das Boot-Image vom Partner-Node verwendet und automatisch die entsprechende Startmenüoption ausgeführt, um das Boot-Image auf den Ersatz-Boot-Medien zu installieren.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert den Storage, die I/O-Karten und führt die ONTAP Betriebssystemsoftware aus.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Ein duales Inline-Speichermodul (DIMM) ist eine Art von Computerspeicher. Sie sind installiert, um einem Controller-Motherboard Systemspeicher hinzuzufügen.



 a| 
link:drive-replace.html["Laufwerk"]
 a| 
Ein Laufwerk ist ein Gerät, das den für Daten erforderlichen physischen Storage bereitstellt.



 a| 
link:fan-swap-out.html["Ventilator"]
 a| 
Ein Lüfter kühlt den Controller.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
Der NVRAM (Non-Volatile Random Access Memory) ist ein Modul, mit dem der Controller Daten während der Übertragung schützen und speichern kann, wenn das System Strom verliert. Die System-ID befindet sich im NVRAM-Modul. Bei Austausch nimmt der Controller die neue System-ID vom Ersatz-NVRAM-Modul an.



 a| 
link:nvdimm-battery-replace.html["NV-Batterie"]
 a| 
Die NV-Batterie ist dafür verantwortlich, das NVRAM-Modul mit Strom zu versorgen, während die aktiven Daten nach einem Stromausfall in den Flash-Speicher ausgelagert werden.



 a| 
link:io-module-overview.html["I/O-Modul"]
 a| 
Das E/A-Modul (Eingangs-/Ausgangsmodul) ist eine Hardwarekomponente, die als Vermittler zwischen dem Controller und verschiedenen Geräten oder Systemen dient, die Daten mit dem Controller austauschen müssen.



 a| 
link:power-supply-replace.html["Stromversorgung"]
 a| 
Ein Netzteil stellt eine redundante Stromquelle in einem Controller bereit.



 a| 
link:rtc-battery-replace.html["Akku in Echtzeit"]
 a| 
Bei ausgeschaltetem Gerät bleiben Datum und Uhrzeit über eine Echtzeitbatterie erhalten.



 a| 
link:system-management-replace.html["System Management-Modul"]
 a| 
Das System Management-Modul stellt die Schnittstelle zwischen dem Controller und einer Konsole oder einem Laptop für Controller- oder Systemwartungszwecke bereit. Das Systemmanagementmodul enthält das Startmedium und speichert die Seriennummer des Systems (SSN).

|===