---
permalink: c800/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff c800, shutdown the controllers 
summary: Zum Austausch des Chassis müssen Sie die Controller herunterfahren. 
---
= Die AFF C800 Controller werden heruntergefahren, um das Chassis auszutauschen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Schalten Sie die Controller Ihres AFF C800 -Speichersystems ab, um Datenverlust zu vermeiden und die Systemstabilität beim Austausch des Gehäuses zu gewährleisten.

Dieses Verfahren gilt für Systeme mit zwei-Knoten-Konfigurationen. Weitere Informationen über das ordnungsgemäßes Herunterfahren beim Warten eines Clusters finden Sie unter https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Anleitung zur Problemlösung für das Speichersystem – NetApp Knowledge Base"].

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie über die erforderlichen Berechtigungen und Anmeldeinformationen verfügen:
+
** Lokale Administratoranmeldeinformationen für ONTAP.
** BMC accessibility für jeden Controller.


* Stellen Sie sicher, dass Sie über die erforderlichen Werkzeuge und Geräte für den Austausch verfügen.


.Schritte
. Melden Sie sich über SSH beim Cluster an oder von einem beliebigen Node im Cluster mit einem lokalen Konsolenkabel und einem Laptop/einer Konsole an.
. Stoppen Sie den Zugriff aller Clients/Hosts auf Daten auf dem NetApp System.
. Externe Sicherungsaufträge werden angehalten.
. Wenn AutoSupport aktiviert ist, unterdrücken Sie die Case-Erstellung und geben Sie an, wie lange Sie das System voraussichtlich offline sein werden:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Ermitteln Sie die SP/BMC-Adresse aller Cluster-Nodes:
+
`system service-processor show -node * -fields address`

. Beenden Sie die Cluster-Shell:
+
`exit`

. Melden Sie sich beim SP/BMC jedes Controllers mit der im vorherigen Schritt ermittelten IP-Adresse an:
+
** Wenn Sie sich vom BMC über SSH anmelden, stellen Sie die Verbindung über die SP/BMC-Adresse her (zum Beispiel  `ssh admin@<SP/BMC_address>`), geben Sie dann den Befehl  `system console` ein und authentifizieren Sie sich.
** Wenn Sie eine lokale Konsole oder einen Laptop verwenden, der direkt mit dem Controller verbunden ist, melden Sie sich mit denselben Cluster Administrator-Anmeldeinformationen an.


. Halten Sie die beiden Nodes im beeinträchtigten Chassis an:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Bei Clustern mit SnapMirror Synchronous-Betrieb im StructSync-Modus: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Geben Sie *y* für jeden Controller im Cluster ein, wenn Folgendes angezeigt wird:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Warten Sie, bis die einzelnen Controller angehalten sind, und zeigen Sie die LOADER-Eingabeaufforderung an.


.Was kommt als Nächstes?
Nach dem Abschalten der Controller,link:chassis-replace-move-hardware.html["Setzen Sie das Gehäuse wieder ein"] Die
