---
permalink: c800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c800, verify and set HA state, run diagnostics, complete the replacement process 
summary: Sie müssen den HA-Status des Chassis überprüfen, Diagnosen ausführen und das ausgefallene Teil an NetApp zurücksenden, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben. 
---
= Schließen Sie den Wiederherstellungs- und Austauschprozess ab – AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen den HA-Status des Chassis überprüfen, Diagnosen ausführen und das ausgefallene Teil an NetApp zurücksenden, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben.



== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest: `ha-config modify chassis _HA-state_`
+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`


. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.
. Bringen Sie die Blende wieder an der Vorderseite des Systems an.




== Schritt 2: Diagnose ausführen

Nachdem Sie eine Komponente im System ausgetauscht haben, sollten Sie Diagnosetests auf dieser Komponente durchführen.

Ihr System muss die LOADER-Eingabeaufforderung aufweisen, um die Diagnose zu starten.

Alle Befehle im Diagnoseverfahren werden vom Controller ausgegeben, der die Komponente ersetzt wird.

.Schritte
. Wenn der zu wartenden Controller nicht an der LOADER-Eingabeaufforderung angezeigt wird, booten Sie den Controller neu: `system node halt -node node_name`
+
Nachdem Sie den Befehl ausgegeben haben, sollten Sie warten, bis das System an der LOADER-Eingabeaufforderung angehalten wird.

. Rufen Sie an der LOADER-Eingabeaufforderung die speziellen Treiber auf, die speziell für die Diagnose auf Systemebene entwickelt wurden, um ordnungsgemäß zu funktionieren: `boot_diags`
. Wählen Sie im angezeigten Menü *Scansystem* aus, um die Ausführung der Diagnosetests zu aktivieren.
. Wählen Sie im angezeigten Menü die Option *Speicher testen* aus.
. Fahren Sie auf der Grundlage des Ergebnisses des vorhergehenden Schritts fort:
+
** Wenn der Test fehlgeschlagen ist, korrigieren Sie den Fehler, und führen Sie den Test erneut aus.
** Wenn der Test keine Fehler gemeldet hat, wählen Sie im Menü Neu starten aus, um das System neu zu starten.






== Schritt 3: Senden Sie das fehlgeschlagene Teil an NetApp zurück

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück. Siehe https://["Teilerückgabe  Austausch"] Seite für weitere Informationen.
