---
permalink: c800/drive-replace.html 
sidebar: sidebar 
keywords: aff c800, replace the drives 
summary: Sie müssen ein Laufwerk ersetzen, wenn die Plattform eine Warnmeldung an die Systemkonsole protokolliert, die darauf hinweist, dass ein Laufwerk ausgefallen ist. Darüber hinaus leuchten die Fehler-LED auf der Bedieneranzeige und die Fehler-LED am ausgefallenen Laufwerk. 
---
= Ersetzen Sie das SSD-Laufwerk – AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
Sie können ein ausgefallenes SSD-Laufwerk unterbrechungsfrei ersetzen, während I/O ausgeführt wird.

Wenn ein Laufwerk ausfällt, meldet die Plattform eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Fehler-LED auf der Bedieneranzeige und die Fehler-LED am ausgefallenen Laufwerk.

.Bevor Sie beginnen
* Befolgen Sie die Best Practice, und installieren Sie die aktuelle Version des DQP (Disk Qualification Package), bevor Sie ein Laufwerk ersetzen.
* Identifizieren Sie das ausgefallene Laufwerk, indem Sie den ausführen `storage disk show -broken` Befehl über die Systemkonsole.
+
Das ausgefallene Laufwerk wird in der Liste der ausgefallenen Laufwerke angezeigt. Falls nicht, sollten Sie warten und dann den Befehl erneut ausführen.

+

NOTE: Es kann mehrere Stunden dauern, bis das Laufwerk in der Liste der ausgefallenen Laufwerke angezeigt wird.

* Legen Sie fest, ob die SED-Authentifizierung aktiviert ist.
+
Wie Sie die Festplatte austauschen, hängt davon ab, wie das Festplattenlaufwerk verwendet wird. Wenn die SED-Authentifizierung aktiviert ist, müssen Sie die SED-Ersatzanweisungen im verwenden https://["ONTAP 9 – NetApp Verschlüsselungsleitfadens"]. In diesen Anweisungen werden zusätzliche Schritte beschrieben, die vor und nach dem Austausch einer SED ausgeführt werden müssen.

* Stellen Sie sicher, dass das Ersatzlaufwerk von Ihrer Plattform unterstützt wird. Siehe https://["NetApp Hardware Universe"].
* Stellen Sie sicher, dass alle anderen Komponenten im System ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.


.Über diese Aufgabe
Die Festplatten-Firmware wird bei neuen Laufwerken, die nicht über aktuelle Firmware-Versionen verfügen, automatisch (unterbrechungsfrei) aktualisiert.

Beim Austausch mehrerer Festplattenlaufwerke müssen Sie eine Minute zwischen dem Entfernen jedes ausgefallenen Laufwerks und dem Einsetzen des Ersatzlaufwerks warten, damit das Storage-System die Existenz jeder neuen Festplatte erkennen kann.

.Schritte
. Wenn Sie dem Ersatzlaufwerk den Besitz eines Laufwerks manuell zuweisen möchten, müssen Sie das Ersatzlaufwerk für die automatische Laufwerkszuweisung deaktivieren, sofern dieses aktiviert ist
+

NOTE: Sie weisen den Antriebseigentum manuell zu und aktivieren dann die automatische Laufwerkszuweisung später in diesem Verfahren.

+
.. Überprüfen Sie, ob die automatische Laufwerkszuweisung aktiviert ist: `storage disk option show`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Wenn die automatische Laufwerkszuweisung aktiviert ist, wird die Ausgabe angezeigt `on` In der Spalte „`Auto Assign`“ (für jedes Controller-Modul).

.. Wenn die automatische Laufwerkszuweisung aktiviert ist, deaktivieren Sie sie: `storage disk option modify -node node_name -autoassign off`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen deaktivieren.



. Richtig gemahlen.
. Identifizieren Sie das ausgefallene Laufwerk physisch.
+
Wenn ein Laufwerk ausfällt, protokolliert das System eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Warnungs-LED (gelb) auf der Anzeige des Festplatten-Shelf-Bedieners und des ausgefallenen Laufwerks.

+

NOTE: Die Aktivitäts-LED (grün) auf einem ausgefallenen Laufwerk kann leuchten (leuchtet dauerhaft), was darauf hinweist, dass das Laufwerk zwar mit Strom versorgt wird, aber nicht blinken sollte, was auf I/O-Aktivität hinweist. Ein ausgefallenes Laufwerk hat keine I/O-Aktivität.

. Entfernen Sie das ausgefallene Laufwerk:
+
.. Drücken Sie die Entriegelungstaste an der Antriebsfläche, um den Nockengriff zu öffnen.
.. Schieben Sie den Antrieb mithilfe des Nockengriffs aus dem Regal und halten Sie den Antrieb mit der anderen Hand.


. Warten Sie mindestens 70 Sekunden, bevor Sie das Ersatzlaufwerk einsetzen.
+
Dadurch erkennt das System, dass ein Laufwerk entfernt wurde.

. Setzen Sie das Ersatzlaufwerk ein:
+
.. Wenn sich der Nockengriff in der geöffneten Position befindet, setzen Sie den Ersatzantrieb mit beiden Händen ein.
.. Drücken Sie, bis das Laufwerk stoppt.
.. Schließen Sie den Nockengriff, so dass der Antrieb fest in der Mittelebene sitzt und der Griff einrastet.
+
Schließen Sie den Nockengriff langsam, damit er korrekt an der Antriebsfläche ausgerichtet ist.



. Vergewissern Sie sich, dass die Aktivitäts-LED (grün) des Laufwerks leuchtet.
+
Wenn die Aktivitäts-LED des Laufwerks leuchtet, bedeutet dies, dass das Laufwerk mit Strom versorgt wird. Wenn die Aktivitäts-LED des Laufwerks blinkt, bedeutet dies, dass das Laufwerk gerade mit Strom versorgt wird und der I/O-Vorgang ausgeführt wird. Wenn die Laufwerk-Firmware automatisch aktualisiert wird, blinkt die LED.

. Wenn Sie ein anderes Laufwerk ersetzen, wiederholen Sie die Schritte 3 bis 7.
. Wenn Sie die automatisierte Laufwerkszuweisung in Schritt 1 deaktiviert haben, weisen Sie die Laufwerkseigentümer manuell zu und aktivieren Sie bei Bedarf die automatische Laufwerkszuweisung erneut.
+
.. Alle Laufwerke ohne Besitzer anzeigen: `storage disk show -container-type unassigned`
+
Sie können den Befehl an einem der Controller-Module eingeben.

.. Weisen Sie jedes Laufwerk zu: `storage disk assign -disk disk_name -owner owner_name`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Mit dem Platzhalterzeichen können Sie mehr als ein Laufwerk gleichzeitig zuweisen.

.. Bei Bedarf die automatische Laufwerkszuweisung erneut aktivieren: `storage disk option modify -node node_name -autoassign on`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen erneut aktivieren.



. Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.
+
Wenden Sie sich an den technischen Support unter https://["NetApp Support"], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik) wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen.


