---
permalink: c800/install-videos.html 
sidebar: sidebar 
keywords: aff c800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.' 
---
= Videos – AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt zwei Videos: Ein Video zum Rack und Verkabelung Ihres Systems und ein Beispiel für die Verwendung des System Manager Guided Setup zur Durchführung der Erstkonfiguration des Systems.

Wenn Sie über eine MetroCluster-Konfiguration verfügen, verwenden Sie den MetroCluster-Installationsinhalt.

https://["MetroCluster-Dokumentation"^]



== Video eines von zwei: Hardware-Installation und -Verkabelung

Das folgende Video zeigt, wie Sie Ihr neues System installieren und verkabeln.

.Animation - Installation und Einrichtung eines AFF C800
video::db9f506c-b08e-4b66-b781-afc40187b639[panopto]


== Video zwei von zwei: Führen Sie End-to-End-Software-Konfiguration

Das folgende Video zeigt die End-to-End-Softwarekonfiguration für Systeme mit ONTAP 9.2 und höher.

video::WAE0afWhj1c?[youtube]