---
permalink: c800/overview.html 
sidebar: sidebar 
keywords: AFF C800 specifications, AFF C800 specs, NetApp AFF C800, AFF C800 hardware 
summary: Wichtige Spezifikationen für das AFF C800 Speichersystem 
---
= Wichtige Spezifikationen für AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind ausgewählte Spezifikationen für den AFF C800 aufgeführt.  Besuchen https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) für eine vollständige Liste der AFF C800 Spezifikationen.  Diese Seite spiegelt ein einzelnes Paar mit hoher Verfügbarkeit wider.



=== Wichtige Spezifikationen für AFF C800

Plattformkonfiguration: AFF C800 Single Chassis HA Pair

Max. Rohkapazität: 7,3680 PB

Arbeitsspeicher: 1280.0000 GB

Formfaktor: 4U-Gehäuse mit 2 HA-Controllern und 48 Laufwerkssteckplätzen

ONTAP -Version: b_startONTAP: 9.16.1P2b_end

PCIe-Erweiterungssteckplätze: 10

Mindestens erforderliche ONTAP -Version: ONTAP 9.10.1P15



=== Scaleout-Maximalwerte

|===


| Typ | HA-Paare | Rohkapazität | Max. Speicher 


| NAS | 12 | 88,4 PB / 78,5 PiB | 15360 GB 


| SAN | 6 | 44,2 PB / 39,3 PiB | 7680 GB 


| HA-Paar |  | 7,4 PB / 6,5 PiB | 1280,0000 
|===


=== IO



==== Integrierte E/A

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 4 
|===


==== Gesamt-IO

|===


| Protokoll | Häfen 


| Ethernet 100 Gbit/s | 20 


| Ethernet 25 Gbit/s | 16 


| Ethernet 10 Gbit/s | 32 


| FC 32 Gbit/s | 32 


| NVMe/FC 32 Gbit/s | 32 


|  | 0 


|  | 0 
|===


==== Verwaltungsports

|===


| Protokoll | Häfen 


| Ethernet 1 Gbit/s | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbit/s | 4 
|===


=== Unterstützte Speichernetzwerke

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 mit NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Spezifikationen der Systemumgebung

* Typische Leistung: 6626 BTU/h
* Leistung im schlimmsten Fall: 8417 BTU/h
* Gewicht: 132,5 lbbr/60,1 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 34,5 Zoll (36,6 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 5 °C bis 40 °C (br/41 °F bis br/104 °F) bei br/= 3048 mbr/= 10000 ft) Höhe; 8 % bis 90 % (br/relative Luftfeuchtigkeit, nicht kondensierend)
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß)<br/>10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 8,0;br/Schalldruck (LpAm) (in der Nähe): 62,8 dB




=== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




=== Hohe Verfügbarkeit

Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle; redundante Hot-Swap-fähige Controller; redundante Hot-Swap-fähige Netzteile;

 [//] 2025-10-15 ontap-systems-internal/issues/1357