---
permalink: fas2600/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas2600, verify and set HA state, complete the replacement process 
summary: Den Chassis-Austausch für Ihr FAS2600-System abschließen, indem der HA-Status des Chassis überprüft und die defekte Komponente an NetApp zurückgesendet wird. 
---
= Der Chassis-Austausch für Ihr FAS2600 System ist abgeschlossen.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Chassis-Austausch für Ihr FAS2600-System wird abgeschlossen, indem der HA-Status des Chassis überprüft und das defekte Teil an NetApp zurückgesendet wird, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben.



[[step-1-verify-and-set-the-ha-state-of-the-chassis]]
== Schritt: Überprüfen Sie den HA-Status des Chassis und legen Sie diesen fest

Sie müssen den HA-Status des Chassis überprüfen und gegebenenfalls den Status entsprechend Ihrer Systemkonfiguration aktualisieren.

. Zeigen Sie im Wartungsmodus von einem der Controller-Module aus den HA-Status des lokalen Controller-Moduls und des Chassis an: `ha-config show`
+
Der HA-Status sollte für alle Komponenten identisch sein.

. Wenn der angezeigte Systemzustand für das Chassis nicht mit der Systemkonfiguration übereinstimmt:
+
.. Legen Sie für das Chassis den HA-Status fest: `ha-config modify chassis _HA-state_`
+
Für den HA-Status kann einer der folgenden Werte vorliegen:

+
*** `ha`
*** `non-ha`


.. Bestätigen Sie, dass sich die Einstellung geändert hat: `ha-config show`


. Falls Sie dies noch nicht getan haben, können Sie den Rest Ihres Systems erneut verwenden.
. Der nächste Schritt hängt von Ihrer Systemkonfiguration ab.
+
[cols="1,2"]
|===
| Ihr System befindet sich in... | Dann... 


 a| 
Eine eigenständige Konfiguration
 a| 
.. Beenden des Wartungsmodus: `halt`
.. Gehen Sie zu link:chassis-replace-move-hardware.html["Abschluss des Austauschvorgangs"].




 a| 
Ein HA-Paar mit einem zweiten Controller-Modul
 a| 
Beenden des Wartungsmodus: `halt`

Die LOADER-Eingabeaufforderung wird angezeigt.

|===




[[step-2-return-the-failed-part-to-netapp]]
== Schritt 2: Rückgabe des fehlerhaften Teils an NetApp

Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.  https://mysupport.netapp.com/site/info/rma["Rückgabe und Austausch von Teilen"]Weitere Informationen finden Sie auf der Seite.
