---
permalink: fas2600/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas2600, replace the chassis 
summary: Vor dem Austausch des Chassis in Ihrem FAS2600-System sollten die Anforderungen für das Verschieben von Komponenten in das Ersatzchassis sowie für das Einsetzen in das Gerätegestell oder den Systemschrank geprüft werden. 
---
= Anforderungen sollten vor dem Austausch des FAS2600 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Chassis in Ihrem FAS2600-System sollten die Anforderungen für das Verschieben der Netzteile, Festplatten und des/der Controller-Module vom defekten Chassis in das neue Chassis sowie den Austausch des defekten Chassis im Geräteschrank oder Systemschrank gegen das neue Chassis desselben Modells geprüft werden.

Alle anderen Systemkomponenten müssen einwandfrei funktionieren. Falls dies nicht der Fall ist, sollte der technische Support kontaktiert werden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie alle Laufwerke und Controller-Module bzw. -Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieses Verfahren ist mit Störungen verbunden. Bei einem Zwei-Node-Cluster kommt es zu einem vollständigen Dienstausfall, bei einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall.


video::FcitUi3YEyI[youtube]