---
permalink: fas2600/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas2600, prerequisite, replace the controller module 
summary: Vor dem Austausch des Controllers in Ihrem FAS2600 System sollten die Voraussetzungen für das Austauschverfahren geprüft und das passende Verfahren für Ihre Version des ONTAP Betriebssystems ausgewählt werden. 
---
= Anforderungen sollten vor dem Austausch des Controllers in Ihrem FAS2600 System geprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Controllers in Ihrem FAS2600 System sollten die Voraussetzungen für das Austauschverfahren geprüft und das passende Verfahren für Ihre Version des ONTAP Betriebssystems ausgewählt werden.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====
* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Wenn sich Ihr System in einem HA-Paar befindet, muss der gesunde Controller in der Lage sein, den zu ersetzenden Controller zu übernehmen (in diesem Verfahren als „`eingeschränkter Controller`“ bezeichnet).
* Dieses Verfahren umfasst je nach Konfiguration Ihres Systems Schritte zur automatischen oder manuellen Neuzuteilung von Laufwerken an den _Replacement_-Controller.
+
Sie sollten die Umverteilung des Laufwerks wie in der Prozedur beschrieben durchführen.

* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Sie müssen ein Controller-Modul durch ein Controller-Modul desselben Modelltyps ersetzen. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* In diesem Verfahren wird das Boot-Gerät vom beeinträchtigten Controller auf den _Replacement_-Controller verschoben, sodass der _Replacement_-Controller in derselben ONTAP-Version wie das alte Controller-Modul gestartet wird.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.



