---
permalink: fas9000/bootmedia-2n-mcc-switchback.html 
sidebar: sidebar 
keywords: fas9000, aff a700, metrocluster, switchback, manual, manual boot recovery 
summary: 'Nach Abschluss des FRU-Austauschs in einer Zwei-Knoten-MetroCluster-Konfiguration können Sie die MetroCluster-Rückschaltung durchführen. Dadurch wird die Konfiguration in ihren normalen Betriebszustand zurückversetzt, wobei die Sync-Source Storage Virtual Machines (SVMs) am zuvor beeinträchtigten Standort nun aktiv sind und Daten aus den lokalen Festplattenpools bereitstellen. Das FAS9000 System unterstützt ausschließlich manuelle Boot-Medien-Wiederherstellungsverfahren.' 
---
= Switch-Back-Aggregate in einer Zwei-Node-Cluster MetroCluster Konfiguration für ein FAS9000 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Austausch des Startmediums ist die MetroCluster Switchback-Operation auf Ihrem FAS9000 System durchzuführen. Mit diesem Verfahren wird die Konfiguration in den normalen Betriebszustand zurückversetzt, wobei die Sync-Source Storage Virtual Machines (SVMs) am zuvor beeinträchtigten Standort nun aktiv sind und Daten aus den lokalen Festplattenpools bereitstellen. Das FAS9000 System unterstützt ausschließlich manuelle Verfahren zur Wiederherstellung des Startmediums.

Dieser Task gilt nur für MetroCluster-Konfigurationen mit zwei Nodes.

.Schritte
. Vergewissern Sie sich, dass sich alle Nodes im befinden `enabled` Bundesland: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Überprüfen Sie, ob die Neusynchronisierung auf allen SVMs abgeschlossen ist: `metrocluster vserver show`
. Überprüfen Sie, ob die automatischen LIF-Migrationen durch die heilenden Vorgänge erfolgreich abgeschlossen wurden: `metrocluster check lif show`
. Führen Sie den Wechsel zurück mit dem aus `metrocluster switchback` Befehl von einem beliebigen Node im verbleibenden Cluster
. Stellen Sie sicher, dass der Umkehrvorgang abgeschlossen ist: `metrocluster show`
+
Der Vorgang zum zurückwechseln wird weiterhin ausgeführt, wenn sich ein Cluster im befindet `waiting-for-switchback` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
Der Vorgang zum zurückwechseln ist abgeschlossen, wenn sich die Cluster im befinden `normal` Bundesland:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Wenn ein Wechsel eine lange Zeit in Anspruch nimmt, können Sie den Status der in-progress-Basispläne über die überprüfen `metrocluster config-replication resync-status show` Befehl.

. Wiederherstellung beliebiger SnapMirror oder SnapVault Konfigurationen

