---
permalink: fas9000/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Vor dem Austausch des Chassis in einem FAS9000-System sollte überprüft werden, ob alle anderen Komponenten ordnungsgemäß funktionieren und ob das Ersatzchassis das gleiche Modell wie das defekte Chassis ist. 
---
= Die Anforderungen für den Austausch eines Chassis in einem FAS9000 System werden hier aufgeführt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Chassis in einem FAS9000-System sollte geprüft werden, ob alle anderen Komponenten ordnungsgemäß funktionieren und ob das Ersatzchassis das gleiche Modell wie das defekte Chassis ist. Das Verfahren ist unterbrechungsfrei und verursacht einen vollständigen Dienstausfall in einem Zwei-Node-Cluster oder einen teilweisen Ausfall in einem Cluster mit mehreren Knoten.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

