---
permalink: fas9000/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, replace, controller, module, prerequisites, procedure 
summary: Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen. 
---
= Überblick über den Austausch von Controller-Modulen – AFF A700 und FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Voraussetzungen für den Austausch prüfen und die richtige für Ihre Version des ONTAP Betriebssystems auswählen.

* Alle Festplatten-Shelfs müssen ordnungsgemäß funktionieren.
* Wenn Ihr System ein FlexArray-System ist oder über eine V_StorageAttach-Lizenz verfügt, müssen Sie vor der Durchführung dieses Verfahrens die zusätzlichen erforderlichen Schritte beachten.
* Wenn sich Ihr System in einem HA-Paar befindet, muss der gesunde Knoten den Knoten übernehmen können, der ersetzt wird (in diesem Verfahren wird „`beeinträchtigter Knoten`“ genannt).
* Wenn sich Ihr System in einer MetroCluster-Konfiguration befindet, müssen Sie den Abschnitt überprüfen https://["Auswahl des richtigen Wiederherstellungsverfahrens"] Um zu bestimmen, ob Sie dieses Verfahren verwenden sollten.
+
Beachten Sie, dass das Verfahren zum Austausch des Controllers bei einem Node in einer MetroCluster Konfiguration mit vier oder acht Nodes mit dem bei einem HA-Paar identisch ist. Es sind keine MetroCluster-spezifischen Schritte erforderlich, da der Ausfall auf ein HA-Paar beschränkt ist und Storage Failover-Befehle zur unterbrechungsfreien Ausführung während des Austauschs genutzt werden können.

* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Sie müssen ein Controller-Modul durch ein Controller-Modul desselben Modelltyps ersetzen. Sie können kein System-Upgrade durch einen Austausch des Controller-Moduls durchführen.
* Im Rahmen dieses Verfahrens können Laufwerke oder Laufwerk-Shelfs nicht geändert werden.
* In diesem Verfahren wird das Boot-Gerät vom Knoten mit beeinträchtigten Knoten auf den Node _Replacement_ verschoben, sodass der Node _Replacement_ in derselben ONTAP-Version wie das alte Controller-Modul gestartet wird.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf die richtigen Systeme anwenden:
+
** Der Node _gestredenen_ ist der Knoten, der ersetzt wird.
** Der Node _Replacement_ ist der neue Node, der den beeinträchtigten Knoten ersetzt.
** Der Node _Healthy_ ist der noch lebende Knoten.


* Sie müssen die Konsolenausgabe des Knotens immer in einer Textdatei erfassen.
+
Auf diese Weise erhalten Sie eine Aufzeichnung des Verfahrens, damit Sie Probleme beheben können, die während des Austauschvorgangs auftreten können.


