---
permalink: fas9000/x91148a-module-install-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, add, x91148a, storage, module, NIC, no open, slots, open slots, system 
summary: Ein X91148A Modul kann zu einem FAS9000 System hinzugefügt werden, indem entweder in einem vollständig bestückten System eine NIC oder ein Storage Adapter durch einen neuen ersetzt wird oder indem eine neue NIC oder ein neuer Storage Adapter in einen leeren Chassis-Slot eingesetzt wird. 
---
= Informationen zum Hinzufügen von X91148A Modulen zu einem FAS9000 System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein X91148A Modul kann zu einem FAS9000 System hinzugefügt werden, indem entweder in einem vollständig bestückten System eine NIC oder ein Storage Adapter durch einen neuen ersetzt wird oder indem eine neue NIC oder ein neuer Storage Adapter in einen leeren Chassis-Slot eingesetzt wird.

Sie können Ihrem System ein I/O-Modul hinzufügen, indem Sie entweder einen NIC oder einen Speicheradapter durch einen neuen in einem vollständig bestückten System ersetzen oder einen neuen NIC- oder Speicheradapter in einen leeren Gehäusesteckplatz Ihres Systems hinzufügen.

.Bevor Sie beginnen
* Überprüfung des  https://hwu.netapp.com["NetApp Hardware Universe"] zur Sicherstellung, dass das neue E/A-Modul mit Ihrem System und der von Ihnen verwendeten ONTAP-Version kompatibel ist.
* Wenn mehrere Steckplätze verfügbar sind, sollten die Steckplatzprioritäten in  https://hwu.netapp.com["NetApp Hardware Universe"] überprüft und der beste verfügbare für Ihr E/A-Modul verwendet werden.
* Damit ein I/O-Modul unterbrechungsfrei hinzugefügt werden kann, müssen Sie den Ziel-Controller übernehmen, die Abdeckung des Steckplatzes im Zielsteckplatz entfernen oder ein vorhandenes I/O-Modul entfernen, das neue oder das neue I/O-Modul ersetzen und dann den Ziel-Controller zurückgeben.
* Stellen Sie sicher, dass alle anderen Komponenten ordnungsgemäß funktionieren.

