---
permalink: fas9000/x91148a-modules-with-open-slots-add.html 
sidebar: sidebar 
keywords: aff a700, fas9000, ass, x91148a, module, open, slots, nic, storage 
summary: Sie können ein X91148A-Modul in einem leeren Modulsteckplatz in Ihrem System entweder als 100-GbE-NIC oder als Speichermodul für die NS224-Speicher-Shelfs hinzufügen. 
---
= Fügen Sie ein X91148A-Modul in einem System mit offenen Steckplätzen hinzu - FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein X91148A-Modul in einem leeren Modulsteckplatz in Ihrem System entweder als 100-GbE-NIC oder als Speichermodul für die NS224-Speicher-Shelfs hinzufügen.

* Ihr System muss ONTAP 9.8 und höher ausführen.
* Um das X91148A-Modul unterbrechungsfrei hinzuzufügen, müssen Sie den Zielcontroller übernehmen, die Abdeckung für die Steckplatzabdeckung im Zielsteckplatz entfernen, das Modul hinzufügen und dann den Zielcontroller zurückgeben.
* Auf Ihrem System müssen mindestens ein freier Steckplatz verfügbar sein.
* Wenn mehrere Steckplätze verfügbar sind, installieren Sie das Modul gemäß der Slot Priority Matrix für das X91148A-Modul im Hardware Universe.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Wenn Sie das Modul X91148A als Speichermodul hinzufügen, müssen Sie die Modulsteckplätze 3 und/oder 7 installieren.
* Wenn Sie das X91148A-Modul als 100-GbE-NIC hinzufügen, können Sie jeden offenen Steckplatz verwenden. Standardmäßig werden die Steckplätze 3 und 7 als Speichersteckplätze festgelegt. Wenn Sie diese Steckplätze als Netzwerksteckplätze verwenden möchten und keine NS224-Shelfs hinzufügen, müssen Sie die Steckplätze für die Netzwerknutzung mit dem ändern `storage port modify -node _node name_ -port _port name_ -mode network` Befehl. Im Hardware Universe finden Sie weitere Steckplätze, die vom X91148A-Modul für die Netzwerkanbindung verwendet werden können.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.




== Option 1: Fügen Sie ein X91148A-Modul als NIC-Modul in ein System mit offenen Steckplätzen hinzu

Um ein X91148A-Modul als NIC-Modul in einem System mit offenen Steckplätzen hinzuzufügen, müssen Sie die genaue Reihenfolge der Schritte befolgen.

.Schritte
. Herunterfahren-Controller A:
+
.. Automatisches Giveback deaktivieren: `storage failover modify -node local -auto-giveback false`
.. Übernehmen des Ziel-Node: `storage failover takeover -ofnode _target_node_name_`
+
Die Konsolenverbindung zeigt an, dass der Node nach Abschluss der Übernahme auf die LOADER-Eingabeaufforderung abschaltet.



. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Entfernen Sie die Abdeckung des Zielsteckplatzes:
+
.. Drücken Sie die Taste mit der Nummerierung und dem Buchstaben.
.. Drehen Sie die Nockenverriegelung nach unten, bis sie sich in horizontaler Position befindet.
.. Entfernen Sie die Abdeckung.


. Installieren Sie das X91148A-Modul:
+
.. Richten Sie das X91148A-Modul an den Kanten des Schlitzes aus.
.. Schieben Sie das X91148A-Modul in den Steckplatz, bis der letzte und nummerierte E/A-Nockenverschluss mit dem E/A-Nockenstift in Kontakt kommt.
.. Drücken Sie die E/A-Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.


. Verbinden Sie das Modul mit den Datenschaltern.
. Neustart von Controller A: `boot_ontap`
. GiveBack der Knoten vom Partner-Knoten: `storage failover giveback -ofnode _target_node_name_`
. Automatisches Giveback aktivieren, falls deaktiviert: `storage failover modify -node local -auto-giveback true`
. Wiederholen Sie diese Schritte für Controller B.




== Option 2: Fügen Sie ein X91148A-Modul als Speichermodul in ein System mit offenen Steckplätzen hinzu

Um ein X91148A-Modul als Speichermodul in einem System mit offenen Steckplätzen hinzuzufügen, müssen Sie die genaue Reihenfolge der Schritte befolgen.

* Bei diesem Verfahren wird vorausgesetzt, dass die Schlitze 3 und/oder 7 offen sind.


.Schritte
. Herunterfahren von Controller A:
+
.. Automatisches Giveback deaktivieren: `storage failover modify -node local -auto-giveback false`
.. Übernehmen des Ziel-Node: `storage failover takeover -ofnode target_node_name`
+
Die Konsolenverbindung zeigt an, dass der Node nach Abschluss der Übernahme auf die LOADER-Eingabeaufforderung abschaltet.



. Wenn Sie nicht bereits geerdet sind, sollten Sie sich richtig Erden.
. Entfernen Sie die Abdeckung des Zielsteckplatzes:
+
.. Drücken Sie die Taste mit der Nummerierung und dem Buchstaben.
.. Drehen Sie die Nockenverriegelung nach unten, bis sie sich in horizontaler Position befindet.
.. Entfernen Sie die Abdeckung.


. Installieren Sie das X91148A-Modul in Steckplatz 3:
+
.. Richten Sie das X91148A-Modul an den Kanten des Schlitzes aus.
.. Schieben Sie das X91148A-Modul in den Steckplatz, bis der letzte und nummerierte E/A-Nockenverschluss mit dem E/A-Nockenstift in Kontakt kommt.
.. Drücken Sie die E/A-Nockenverriegelung ganz nach oben, um das Modul zu verriegeln.
.. Wenn Sie ein zweites X91148A-Modul zur Speicherung installieren, wiederholen Sie diesen Schritt für das Modul in Steckplatz 7.


. Neustart von Controller A: `boot_ontap`
. GiveBack der Knoten vom Partner-Knoten: `storage failover giveback -ofnode target_node_name`
. Automatisches Giveback aktivieren, falls deaktiviert: `storage failover modify -node local -auto-giveback true`
. Wiederholen Sie diese Schritte für Controller B.
. Installieren und verkabeln Sie die NS224-Regale, wie in beschrieben https://docs.netapp.com/us-en/ontap-systems/ns224/hot-add-shelf.html["Hot-Add - NS224-Shelfs"].

