---
permalink: asa-r2-a20-30-50/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, overview, automatic recovery, boot media 
summary: Erfahren Sie mehr über die automatisierte Methode zum Austauschen der Boot-Medien. 
---
= Übersicht über die Wiederherstellung von Startmedien – AFF A20, AFF A30 und AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Wiederherstellung der Startmedien verwendet das Startabbild vom Partner-Node und führt automatisch die entsprechende Startmenüoption aus, um das Startabbild auf den Ersatz-Startmedien zu installieren.

Wenn beim Booten Fehlermeldungen wie der unten gezeigten auftreten, müssen Sie die Boot-Medien ersetzen und das ONTAP Image vom Partner-Node wiederherstellen.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....