---
permalink: asa-r2-a20-30-50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the chassis 
summary: Bevor Sie das Gehäuse des ASA A20, ASA A30 oder ASA A50-Systems austauschen, stellen Sie sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, ob das richtige Ersatzgehäuse vorhanden ist und welche Tools erforderlich sind. 
---
= Voraussetzungen für den Austausch des Gehäuses – ASA A20, ASA A30 und ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das Gehäuse des ASA A20, ASA A30 oder ASA A50-Systems austauschen, stellen Sie sicher, dass Sie die erforderlichen Voraussetzungen für einen erfolgreichen Austausch erfüllen. Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, ob das richtige Ersatzgehäuse vorhanden ist und welche Tools erforderlich sind.

Lesen Sie die folgenden Anforderungen und Überlegungen durch.



== Anforderungen

* Das Ersatzgehäuse muss das gleiche Modell aufweisen wie das Gehäuse für beeinträchtigte Störungen. Dieses Verfahren gilt für einen ähnlichen Austausch, nicht für ein Upgrade.
* Alle anderen Komponenten des Speichersystems müssen ordnungsgemäß funktionieren. Falls nicht, wenden Sie sich an https://mysupport.netapp.com/site/global/dashboard["NetApp Support"], bevor Sie mit diesem Verfahren fortfahren.




== Überlegungen

* Das Verfahren zum Austausch des Gehäuses führt zu Unterbrechungen. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.
* Sie können das Verfahren zum Gehäuseaustausch bei allen Versionen von ONTAP verwenden, die von Ihrem Speichersystem unterstützt werden.
* Beim Austausch des Gehäuses wird angenommen, dass Sie den Blende, die Laufwerke, etwaige Laufwerkplatzhalter und die Controller auf das neue Gehäuse verschieben.


.Was kommt als Nächstes?
Nachdem Sie die Anforderungen für den Austausch des Gehäuses überprüft haben, müssen Sie link:chassis-replace-shutdown.html["Fahren Sie die Controller herunter"].
