---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: Stellen Sie vor dem Austausch des Controllers in Ihrem ASA A20-, ASA A30- oder ASA A50-Speichersystem sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, die Überprüfung, ob Sie den richtigen Ersatzcontroller haben, und das Speichern der Konsolenausgabe des Controllers in einer Textprotokolldatei. 
---
= Die Anforderungen für den Austausch eines Controllers in einem ASA A20, ASA A30 oder ASA A50 System werden dargestellt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor dem Austausch des Controllers in Ihrem ASA A20-, ASA A30- oder ASA A50-Speichersystem sicher, dass Sie die notwendigen Voraussetzungen für einen erfolgreichen Austausch erfüllen.  Dazu gehört die Überprüfung, ob alle anderen Komponenten im System ordnungsgemäß funktionieren, die Überprüfung, ob Sie den richtigen Ersatzcontroller haben, und das Speichern der Konsolenausgabe des Controllers in einer Textprotokolldatei.

Sie müssen die Anforderungen und Überlegungen für den Controller-Austausch überprüfen.

[NOTE]
====
NetApp empfiehlt dringend, die Protokollierung auf den Geräten, mit denen Sie arbeiten, zu aktivieren und bei der Durchführung dieses Verfahrens die folgenden Maßnahmen zu ergreifen:

* Lassen Sie AutoSupport während Ihrer Wartung aktiviert. So kann der NetApp Support bei Problemen Diagnoseinformationen erhalten.
* Aktivieren Sie die Protokollierung für alle CLI-Sitzungen. Dadurch wird ein vollständiges Protokoll aller Befehle und Systemausgaben während der Wartungsaktivität erstellt. Hinweise zur Aktivierung der Sitzungsprotokollierung finden Sie unter  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Wie konfiguriert man PuTTY für eine optimale Verbindung zu ONTAP-Systemen"^].


====


[[requirements]]
== Anforderungen

* Alle Regale müssen ordnungsgemäß funktionieren.
* Der gesunde Regler muss in der Lage sein, den zu ersetzenden Regler zu übernehmen (bezeichnet in diesem Verfahren als „`eingeschränkte Steuerung`“).
* Sie müssen einen Controller durch einen Controller desselben Modelltyps ersetzen. Sie können Ihr System nicht aktualisieren, indem Sie einfach den Controller austauschen.
* Im Rahmen dieses Verfahrens können keine Laufwerke oder Shelfs geändert werden.




[[considerations]]
== Überlegungen

* Es ist wichtig, dass Sie die Befehle in diesem Verfahren auf den richtigen Controller anwenden:
+
** Die Steuerung _imired_ ist die Steuerung, die ersetzt wird.
** Die Steuerung _Replacement_ ist die neue Steuerung, die die beeinträchtigte Steuerung ersetzt.
** Der _Healthy_ Controller ist der überlebende Controller.




.Was kommt als Nächstes?
Nachdem Sie die Anforderungen überprüft haben, um den beeinträchtigten Controller zu ersetzen, müssen Sie link:controller-replace-shutdown.html["Schalten Sie den außer Betrieb genommenen Controller aus"].
