---
permalink: asa-r2-a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90, ASA A70, replace io module 
summary: 'Sie müssen die ausgefallene Komponente durch eine FRU-Komponente (Field Replaceable Unit) ersetzen, die Sie von Ihrem Anbieter erhalten haben.' 
---
= Überblick über Hinzufügen und Ersetzen eines E/A-Moduls – ASA A20, ASA A30 und ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Systeme ASA A20, ASA A30 und ASA A50 bieten Flexibilität beim erweitern oder Ersetzen von I/O-Modulen, um die Netzwerkkonnektivität und -Leistung zu verbessern. Das Hinzufügen oder Austauschen eines E/A-Moduls ist wichtig, wenn die Netzwerkfunktionen aktualisiert oder ein fehlerhaftes Modul behandelt werden soll.

Sie können ein ausgefallenes I/O-Modul in Ihrem Speichersystem durch denselben I/O-Modultyp oder durch einen anderen E/A-Modultyp ersetzen. Sie können auch ein I/O-Modul zu einem Speichersystem mit verfügbaren Steckplätzen hinzufügen.

* link:io-module-add.html["Fügen Sie ein I/O-Modul hinzu"]
+
Durch das Hinzufügen zusätzlicher I/O-Module kann die Redundanz verbessert werden, wodurch sichergestellt wird, dass das Speichersystem auch bei Ausfall eines I/O-Moduls betriebsbereit bleibt.

* link:io-module-replace.html["Ersetzen Sie ein E/A-Modul"]
+
Durch das Ersetzen eines fehlerhaften I/O-Moduls kann das Speichersystem wieder in den optimalen Betriebszustand versetzt werden.


