---
permalink: afx/afx-install-setup.html 
sidebar: sidebar 
keywords: afx, afx 1k, install, setup, initial configuration 
summary: Installieren und richten Sie Ihr System ein. 
---
= Installieren und Einrichten Ihres AFX-Speichersystems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie zum https://docs.netapp.com/us-en/ontap-afx/index.html["AFX-Dokumentation"^] um zu erfahren, wie Sie Ihr AFX-System installieren, verwenden und verwalten.

Der https://docs.netapp.com/us-en/ontap-afx/index.html["AFX-Dokumentation"^] enthält Informationen wie:

* Installations- und Setup-Anweisungen
* Administrationsanweisungen zum Konfigurieren Ihres Systems, z. B. Bereitstellen von NAS-Speicher, Klonen von Daten und Ändern der Größe des lokalen Speichers.
* Anweisungen zum Managen Ihres Systems, einschließlich Managen des Client-Zugriffs, Sichern Ihrer Daten und Schützen Ihrer Daten.
* Anleitungen für das Monitoring und die Fehlerbehebung, einschließlich Informationen zu Warnmeldungen, Cluster-Ereignissen und Systemprotokollen.


Spezifische Wartungsverfahren für jeden AFX-Systemtyp finden Sie in derlink:../afx-landing-maintain/index.html["Abschnitt zur AFX-Systemwartung"] .
