---
permalink: asa-c250/install-quick-guide.html 
sidebar: sidebar 
keywords: asa c250,  quick steps 
summary: Ein ASA C250 Speichersystem kann mithilfe von ausdruckbaren, grafischen Schnellinstallationsanweisungen installiert werden, die die Rackmontage, Verkabelung und erste Inbetriebnahme des Systems abdecken. 
---
= Ein ASA C250 Speichersystem mit schnellen Schritten installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein ASA C250 Speichersystem kann mithilfe von ausdruckbaren, grafischen Schnellinstallationsanweisungen installiert werden, die die Rackmontage, Verkabelung und erste Inbetriebnahme des Systems abdecken.

Die Installations- und Setup-Anweisungen enthalten grafische Anweisungen für eine typische Installation Ihres Systems, von Rack und Verkabelung bis zur ersten Inbetriebnahme des Systems. Wenn Sie mit der Installation von NetApp Systemen vertraut sind, lesen Sie diesen Leitfaden.


NOTE: Die ASA A250 und ASA C250 verwenden das gleiche Installationsverfahren wie das AFF A250-System.

link:../media/PDF/Mar_2024_Rev4_AFFA250_ISI_IEOPS-1611.pdf["Installations- und Setup-Anleitung für AFF A250"^]
