---
permalink: asa-c250/overview.html 
sidebar: sidebar 
keywords: ASA C250 specifications, ASA C250 specs, NetApp ASA C250, ASA C250 hardware 
summary: Wichtige Spezifikationen für die ASA-C250-Plattformgruppe 
---
= Wichtige Spezifikationen für ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das ASA C250 -Speichersystem in einem einzelnen Hochverfügbarkeitspaar.  Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== Wichtige Spezifikationen für ASA C250

* Plattformkonfiguration: ASA C250 Single Chassis HA-Paar
* Max. Rohkapazität: 1,4736 PB
* Arbeitsspeicher: 128.0000 GB
* Formfaktor: 2U-Gehäuse mit 2 HA-Controllern und 24 Laufwerkssteckplätzen
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 4
* Mindest ONTAP -Version: ONTAP 9.13.1P1 == Scaleout-Maxima
* Typ: NAS
* Typ: SAN; HA-Paare: 6; Rohkapazität: 8,8 PB / 7,9 PiB; Max. Speicher: 768 GB
* Typ: HA-Paar; Rohkapazität: 1,5 PB / 1,3 PiB; Max. Speicher: 128.0000




== E/A



=== Integrierte E/A

* Protokoll: Ethernet 25 Gbit/s; Ports: 4
* Protokoll: Ethernet 10 Gbit/s; Ports: 4




=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 4
* Protokoll: Ethernet 25 Gbit/s; Ports: 20
* Protokoll: Ethernet 10 Gbit/s; Ports: 4
* Protokoll: FC 32 Gbit/s; Ports: 16
* Protokoll: NVMe/FC 32 Gbit/s; Ports: 16
* Anschlüsse: 0




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 2
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 12 Mbit/s; Anschlüsse: 4




== Speichernetzwerke werden unterstützt

* FC
* iSCSI
* NVMe/FC == Systemumgebungsspezifikationen
* Typische Leistung: 2906 BTU/h
* Leistung im schlimmsten Fall: 3750 BTU/h
* Gewicht: 54.3 lb 24.6 kg
* Höhe: 2U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe:
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bei 3048 m (10000 Fuß) Höhe; 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß) 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 7,2 Schalldruck (LpAm) (in der Nähe): 69,1 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile [//] 2025-10-15 ontap-systems-internal/issues/1357

