---
permalink: a300/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a300, replace the chassis 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Anforderungen sollten vor dem Austausch eines AFF A300 Chassis überprüft werden.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor dem Austausch des Gehäuses in Ihrem AFF A300 System sollten die Anforderungen für einen erfolgreichen Austausch geprüft werden. Bei diesem Verfahren werden alle Netzteile, Lüfter und Controller-Module vom defekten Gehäuse in das Ersatzgehäuse übertragen, und der Vorgang ist mit einer Unterbrechung verbunden.

Alle anderen Komponenten des Systems müssen ordnungsgemäß funktionieren. Falls nicht, müssen Sie sich an den technischen Support wenden.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Hierbei wird angenommen, dass Sie das Controller-Modul oder die Module in das neue Chassis verschieben und dass es sich um eine neue Komponente von NetApp handelt.
* Dieser Vorgang ist störend. Für ein Cluster mit zwei Nodes tritt ein vollständiger Service-Ausfall und ein teilweiser Ausfall in einem Cluster mit mehreren Nodes auf.

