---
permalink: a300/maintain-overview.html 
sidebar: sidebar 
keywords: aff A4300 maintenance, maintenance, repairing A300, repairing asa A300, replace  A300 components, replace A300 components 
summary: Wartung der ASA A400 Hardware 
---
= Wartung der AFF A300 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim AFF A300 Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



== Ventilator

Der Lüfter kühlt den Controller.



== NVDIMM-Batterie

Eine NVDIMM-Batterie ist für die Aufrechterhaltung der Stromversorgung des NVDIMM-Moduls verantwortlich.



== PCIe

Eine PCIe-Karte (Peripheral Component Interconnect Express) ist eine Erweiterungskarte, die in den PCIe-Steckplatz auf der Hauptplatine eingesteckt wird.



== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



== Echtzeituhr-Akku

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
