---
permalink: a300/maintain-overview.html 
sidebar: sidebar 
keywords: aff A4300 maintenance, maintenance, repairing A300, repairing asa A300, replace  A300 components, replace A300 components 
summary: Warten Sie die AFF A300 Hardware 
---
= Informationen zur Wartung eines AFF A300 Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim AFF A300 Storage-System können Sie Wartungsverfahren für die folgenden Komponenten durchführen.



[[boot-media]]
== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[fan]]
== Ventilator

Der Lüfter kühlt den Controller.



[[nvdimm-battery]]
== NVDIMM-Batterie

Eine NVDIMM-Batterie ist für die Aufrechterhaltung der Stromversorgung des NVDIMM-Moduls verantwortlich.



[[pcie]]
== PCIe

Eine PCIe-Karte (Peripheral Component Interconnect Express) ist eine Erweiterungskarte, die in den PCIe-Steckplatz auf der Hauptplatine eingesteckt wird.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Echtzeituhr-Akku

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
