---
permalink: ns224/cable-as-switch-attached.html 
sidebar: sidebar 
keywords: ns224 nvme drive shelf cabling guide, ns224 drive shelf cabling guide, ns224 shelf cabling guide, ns224 cabling guide, switch-attach, switch-attached, switch-attached storage, cable ns224 drive shelves as switch-attached storage 
summary: 'Wenn Sie über ein System verfügen, in dem die NS224 Laufwerk-Shelfs als Switch-Attached Storage \ (nicht Direct-Attached Storage\) verkabelt werden müssen, verwenden Sie die bereitgestellten Informationen.' 
---
= Kabeleinschübe als Switch-Attached Storage – NS224-Einschübe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über ein System verfügen, bei dem die NS224-Laufwerk-Shelfs als Switch-Attached Storage verkabelt werden müssen (kein Direct-Attached Storage), verwenden Sie die bereitgestellten Informationen.

* Wenn Sie NS224-Laufwerk-Shelfs über Storage-Switches verkabeln, finden Sie im https://hwu.netapp.com["NetApp Hardware Universe"^] weitere Informationen. Bei älteren Hardware-Modellen finden Sie Informationen zur Switch-Verkabelung auch im https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Shelf-Verkabelung bei NS224 NVMe-Laufwerken"^].
* Informationen zum Installieren der Speicherschalter finden Sie im https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Dokumentation zu den Switches von AFF und FAS"^].
* Informationen zur Überprüfung der unterstützten Hardware für Ihr Plattformmodell, z. B. Speicherschalter und Kabel, finden Sie im https://hwu.netapp.com["NetApp Hardware Universe"^].

