---
permalink: ns224/complete-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, complete, drive, hot-add an ns224 drive shelf 
summary: Wenn Sie die automatische Laufwerkszuweisung im Rahmen der Vorbereitung auf das NS224-Festplatten-Shelf-Hot-Add deaktiviert haben, müssen Sie die Laufwerkseigentümer manuell zuweisen und bei Bedarf die automatische Laufwerkszuweisung erneut aktivieren. 
---
= Schließen Sie die NS224-Shelfs für den Hot-Add-Betrieb ab
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die automatische Laufwerkszuweisung im Rahmen der Vorbereitung auf das NS224-Shelf-Hot-Add deaktiviert haben, müssen Sie die Laufwerkseigentümerschaft manuell zuweisen und gegebenenfalls die automatische Laufwerkszuweisung erneut aktivieren.

.Bevor Sie beginnen
Sie müssen das Shelf bereits wie angewiesen über Ihr HA-Paar angeschlossen haben. Siehe link:cable-overview-hot-add-shelf.html["Übersicht über die Verkabelung für Hot-Add"].

.Schritte
. Alle Laufwerke ohne Besitzer anzeigen: `storage disk show -container-type unassigned`
+
Sie können bei beiden Controllern den Befehl eingeben.

. Weisen Sie jedes Laufwerk zu: `storage disk assign -disk _disk_name_ -owner _owner_name_`
+
Sie können bei beiden Controllern den Befehl eingeben.

+
Sie können den Platzhalter verwenden, um mehr als ein Laufwerk gleichzeitig zuzuweisen.

. Bei Bedarf die automatische Laufwerkszuweisung erneut aktivieren: `storage disk option modify -node _node_name_ -autoassign on`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controllern erneut aktivieren.


