---
permalink: ns224/hot-add-asa-cable-a250.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa a250, cable 
summary: Verbinden Sie Ihr NS224-Shelf per Kabel mit Ihrem ASA A250-System, sodass jedes Shelf über zwei Verbindungen zu jedem Controller im HA-Paar verfügt. 
---
= Verbinden Sie ein NS224-Regal per Kabel mit Ihrem ASA A250-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verbinden Sie Ihr NS224-Shelf per Kabel mit Ihrem ASA A250-System, sodass jedes Shelf über zwei Verbindungen zu jedem Controller im HA-Paar verfügt.

.Über diese Aufgabe
Wenn Sie von der Rückseite des Plattform-Chassis aus betrachtet werden, ist der RoCE-fähige Karten-Port auf der linken Seite Port „A“ (e1a) und der Port auf der rechten Seite der Port „b“ (e1b).

.Schritte
. Shelf-Verbindungen verkabeln:
+
.. Kabel-Shelf NSM A Port e0a zu Controller A-Steckplatz 1, Port A (e1a)
.. Kabel-Shelf NSM A-Port e0b zum Controller B-Steckplatz 1 Port b (e1b).
.. Kabel-Shelf NSM B-Port e0a zu Controller B, Steckplatz 1, Port A (e1a)
.. Kabel-Shelf NSM B-Port e0b zum Controller A-Steckplatz 1 Port b (e1b). + die folgende Abbildung zeigt die Shelf-Verkabelung, wenn der Vorgang abgeschlossen ist.
+
image::../media/drw_ns224_a250_c250_f500f_1shelf_ieops-1824.svg[Verkabelung für ein AFF/ASA A250 C250 oder FAS500f mit einem NS224-Shelf und einem Satz PCIe-Karten-Ports]



. Überprüfen Sie mit https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Wenn Verkabelungsfehler auftreten, befolgen Sie die entsprechenden Korrekturmaßnahmen.



.Wie es weiter geht
Wenn Sie die automatische Laufwerkszuordnung im Rahmen der Vorbereitung dieses Vorgangs deaktiviert haben, müssen Sie die Laufwerkszuordnung manuell vornehmen und die automatische Laufwerkszuordnung gegebenenfalls wieder aktivieren. Gehen Sie zu link:hot-add-asa-complete.html["Füllen Sie das Hot Add aus"].

Andernfalls müssen Sie das Hot-Add-Regal verwenden.
