---
permalink: ns224/hot-add-asa-cable-a20.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa a20, cable 
summary: Verbinden Sie Ihr NS224-Shelf per Kabel mit Ihrem ASA A20-System, sodass jedes Shelf über zwei Verbindungen zu jedem Controller im HA-Paar verfügt. 
---
= Ein NS224 Shelf mit einem ASA A20 System verkabeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verbinden Sie Ihr NS224-Shelf per Kabel mit Ihrem ASA A20-System, sodass jedes Shelf über zwei Verbindungen zu jedem Controller im HA-Paar verfügt.

Sie können einem ASA A20 HA-Paar im laufenden Betrieb maximal ein NS224-Shelf hinzufügen, wenn zusätzlicher Storage (zum internen Shelf) erforderlich ist.

.Über diese Aufgabe
* Bei diesem Verfahren wird vorausgesetzt, dass das HA-Paar nur über internen Storage verfügt (keine externen Shelves) und dass Sie bei laufendem Betrieb zu einem zusätzlichen Shelf hinzufügen.
* Dieses Verfahren behandelt die folgenden Hot-Add-Szenarien:
+
** Hinzufügen des ersten Shelfs zu einem HA-Paar mit einem RoCE-fähigen I/O-Modul pro Controller während des laufenden Betriebs
** Hinzufügen des ersten Shelfs zu einem HA-Paar mit zwei RoCE-fähigen I/O-Modulen pro Controller und während des laufenden Betriebs


* Diese Systeme sind mit NS224-Shelfs mit NSM100-Modulen und NS224-Shelfs mit NSM100B-Modulen kompatibel. Um sicherzustellen, dass Sie die Controller mit den richtigen Ports verkabeln, ersetzen Sie das „X“ in jedem Diagramm durch die richtige Portnummer für Ihr Modul:
+
[cols="1,4"]
|===
| Modultyp | Anschlusskennzeichnung 


 a| 
NSM100
 a| 
„0“

Beispiel e0a



 a| 
NSM100B
 a| 
„1“

Z. B. e1a

|===


.Schritte
. Wenn Sie während des laufenden Betriebs ein Shelf mit einem Satz RoCE-fähiger Ports (ein RoCE-fähiges I/O-Modul) in jedem Controller-Modul hinzufügen, und dies das einzige NS224-Shelf in Ihrem HA-Paar ist, führen Sie die folgenden Teilschritte durch.
+
Andernfalls fahren Sie mit dem nächsten Schritt fort.

+

NOTE: Bei diesem Schritt wird davon ausgegangen, dass Sie das RoCE-fähige I/O-Modul in Steckplatz 3 installiert haben.

+
.. Kabel-Shelf-Port NSM A Exa zu Controller A-Steckplatz 3, Port A (e3a).
.. Kabel-Shelf-Port NSM A EXB mit Controller B-Steckplatz 3, Port b (e3b).
.. Kabel-Shelf-Port NSM B Exa zu Controller B-Steckplatz 3, Port A (e3a).
.. Kabel-Shelf-Port NSM B EXB mit Controller A-Steckplatz 3, Port b (e3b).
+
Die folgende Abbildung zeigt die Verkabelung für ein Hot-Added Shelf mit einem RoCE-fähigen I/O-Modul pro Controller-Modul:

+
image::../media/drw_ns224_g_1shelf_1card_ieops-2002.svg[Verkabelung für AFF/ASA A20 mit einem Shelf und einem I/O-Modul]



. Wenn Sie jedem Controller-Modul ein Shelf mit zwei RoCE-fähigen Ports (zwei RoCE-fähige I/O-Module) während des laufenden Betriebs hinzufügen, führen Sie die folgenden Teilschritte durch.
+
.. Kabel NSM A Port Exa zu Controller A Steckplatz 3 Port A (e3a).
.. Kabel NSM A Port EXB zu Controller B Steckplatz 1 Port b (e1b).
.. Kabel NSM B Port Exa zu Controller B Steckplatz 3 Port A (e3a).
.. Kabel NSM B Port EXB zu Controller A Steckplatz 1 Port b (e1b).




Die folgende Abbildung zeigt die Verkabelung für ein Hot-Added Shelf mit zwei RoCE-fähigen I/O-Modulen pro Controller-Modul:

image::../media/drw_ns224_g_1shelf_2card_ieops-2005.svg[Verkabelung für AFF/ASA A20 mit einem Shelf und zwei I/O-Modulen]

. Überprüfen Sie mit https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Wenn Verkabelungsfehler auftreten, befolgen Sie die entsprechenden Korrekturmaßnahmen.



.Wie es weiter geht
Wenn Sie die automatische Laufwerkszuordnung im Rahmen der Vorbereitung dieses Vorgangs deaktiviert haben, müssen Sie die Laufwerkszuordnung manuell vornehmen und die automatische Laufwerkszuordnung gegebenenfalls wieder aktivieren. Gehen Sie zu link:hot-add-asa-complete.html["Füllen Sie das Hot Add aus"].

Andernfalls müssen Sie das Hot-Add-Regal verwenden.
