---
permalink: ns224/install-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, install, hot-add an ns224 drive shelf 
summary: Sie können ein NS224-Festplatten-Shelf im laufenden Betrieb hinzufügen, nachdem Ihr HA-Paar bestimmte Anforderungen erfüllt und nachdem die Vorbereitungsaufgaben für Ihr HA-Paar abgeschlossen wurden. 
---
= Installieren Sie ein Shelf für NS224-Hot-Add-Shelves
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen ein NS224 Shelf in einem Schrank oder Telco-Rack installieren, die Netzkabel anschließen (das das Shelf automatisch einschaltet) und die Shelf-ID festlegen.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie eine Büroklammer mit einer begradigten Seite oder einen Kugelschreiber mit schmaler Spitze haben.
+
Um die Shelf-ID zu ändern, verwenden Sie die Büroklammer oder den Kugelschreiber, um auf die Shelf-ID-Taste hinter dem Bedienfeld (ODP) für den Schritt Shelf-ID ändern zuzugreifen.

* Ein voll beladenes NS224-Regal kann mit NSM100-Modulen bis zu 66.78 kg (30.29 lbs) oder mit NSM100B-Modulen im Durchschnitt 56.8 lbs (25.8 kg) wiegen und erfordert zwei Personen zum Anheben oder Verwenden eines hydraulischen Hubs. Entfernen Sie keine Regalkomponenten (von der Vorder- oder Rückseite des Regals), um das Gewicht des Regals zu verringern, da das Regalgewicht unausgeglichen wird.


.Schritte
. Montieren Sie den Schienensatz für das Regal nach Bedarf gemäß den Anweisungen im Kit.
+

NOTE: Verwenden Sie immer das entsprechende Schienensatz für Ihr Regal, um das Regal in einem Rack oder Schrank zu installieren.

. Setzen Sie das Shelf ein:
+
.. Positionieren Sie die Rückseite des Regals auf den Schienen, und stützen Sie das Regal von unten ab, und schieben Sie es in den Schrank oder das Telco-Rack.
+
Wenn Sie mehrere Shelfs installieren, platzieren Sie das erste Shelf direkt über den Controllern. Platzieren Sie das zweite Shelf direkt unter den Controllern. Wiederholen Sie dieses Muster für alle zusätzlichen Regale.

.. Befestigen Sie das Regal mit den im Kit enthaltenen Befestigungsschrauben am Schrank oder Telco-Rack.


. Anschließen der Stromversorgung:
+
.. Schließen Sie die Netzkabel an das Shelf an und befestigen Sie sie.
+
Wenn es sich um Netzgeräte handelt, befestigen Sie diese mit der Netzkabelhalterung.

+
Wenn es sich um Gleichstromnetzteile handelt, befestigen Sie diese mit den beiden Flügelschrauben.

.. Schließen Sie die Netzkabel an verschiedene Stromquellen an, um die Ausfallsicherheit zu erhöhen.
+
Ein Shelf schaltet sich ein, wenn es mit einer Stromquelle verbunden ist. Es verfügt nicht über Netzschalter. Bei ordnungsgemäßer Funktion leuchtet die zweifarbige LED des Netzteils grün.



. Legen Sie die Shelf-ID auf eine Nummer fest, die innerhalb des HA-Paars eindeutig ist:
+
Weitere Anweisungen finden Sie unter link:change-shelf-id.html["Shelf-ID ändern – NS224-Einschübe"^].

+
.. Entfernen Sie die linke Endkappe, und suchen Sie die kleine Öffnung rechts neben den LEDs.
.. Setzen Sie das Ende einer Büroklammer oder eines ähnlichen Werkzeugs in die kleine Öffnung ein, um die Shelf-ID-Taste zu erreichen.
.. Halten Sie die Taste (bis zu 15 Sekunden lang) gedrückt, bis die erste Ziffer auf der digitalen Anzeige blinkt. Lassen Sie dann die Taste los.
+
Wenn die ID länger als 15 Sekunden dauert, halten Sie die Taste erneut gedrückt, und drücken Sie sie vollständig.

.. Drücken Sie die Taste und lassen Sie sie los, um die Nummer so lange zu drücken, bis Sie die gewünschte Zahl von 0 auf 9 erreicht haben.
.. Wiederholen Sie die Unterschritte 4c und 4d, um die zweite Nummer der Shelf-ID festzulegen.
+
Es kann bis zu drei Sekunden (statt 15 Sekunden) dauern, bis die Ziffer blinkt.

.. Halten Sie die Taste gedrückt, bis die zweite Ziffer nicht mehr blinkt.
+
Nach etwa fünf Sekunden beginnen beide Ziffern zu blinken, und die gelbe LED am ODP leuchtet auf.

.. Schalten Sie das Shelf aus und wieder ein, damit die Shelf-ID übernommen wird.
+
Sie müssen beide Netzkabel aus dem Regal ziehen, 10 Sekunden warten und dann wieder anschließen.

+
Wenn die Stromversorgung wiederhergestellt ist, leuchten die LEDs mit zweifarbigen LEDs grün.





.Was kommt als Nächstes?
Verkabeln Sie das Hot-Add-Shelf. Gehen Sie zu link:cable-overview-hot-add-shelf.html["Übersicht über die Verkabelung für Hot-Add"].
