---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: Sie können ein NS224-Festplatten-Shelf im laufenden Betrieb hinzufügen, nachdem Ihr HA-Paar bestimmte Anforderungen erfüllt und nachdem die Vorbereitungsaufgaben für Ihr HA-Paar abgeschlossen wurden. 
---
= Vorbereitung auf den Hot-Add-Betrieb – NS224-Shelfs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie die auf Ihr HA-Paar zutreffenden Vorbereitungsaufgaben aus, bevor Sie ein NS224-Shelf im laufenden Betrieb hinzufügen.

Wenn Sie mit den entsprechenden Vorbereitungsaufgaben fertig sind, gehen Sie zu link:prepare-hot-add-shelf.html["Installieren Sie ein Shelf für ein Hot-Add-System"].



== Installieren Sie RoCE-fähige PCIe-Karten oder I/O-Module

Wenn Ihr Plattformmodell die Verwendung von RoCE-fähigen PCIe-Karten oder I/O-Modulen unterstützt, muss Ihr HA-Paar über genügend RoCE-fähige Ethernet-Ports verfügen, um die Anzahl der hinzuzufüenden Shelfs zu unterstützen.

.Schritte
. Vergewissern Sie sich für jedes hinzuzufügendes Shelf, dass auf jedem Controller zwei RoCE-fähige Ports vorhanden sind.
+
Diese Ports können je nach Plattformmodell auf den Controllern, auf RoCE-fähigen PCIe-Karten oder auf RoCE-fähigen I/O-Modulen integriert werden.

. Wenn das HA-Paar nicht über genügend RoCE-fähige Ports verfügt, installieren Sie die zusätzlichen PCIe-Karten oder I/O-Module in den richtigen Controller-Steckplätzen, die vom Plattformmodell unterstützt werden.
+
.. Identifizieren Sie die richtigen Controller-Steckplätze für Ihr Plattformmodell. Siehe https://hwu.netapp.com["NetApp Hardware Universe"^].
.. Anweisungen zur Installation der PCIe-Karte oder des E/A-Moduls finden Sie in der Dokumentation Ihres Plattformmodells.






== RoCE-fähige Ports für die Storage-Verwendung konfigurieren

Wenn das HA-Paar über nicht dedizierte RoCE-fähige Ethernet-Ports verfügt, die Sie verwenden, um ein NS224-Shelf im laufenden Betrieb hinzuzufügen, müssen Sie die Ports für Storage-Verwendung konfigurieren (nicht für die Verwendung durch das Netzwerk).

.Bevor Sie beginnen
* Vergewissern Sie sich, dass Sie zusätzliche RoCE-fähige PCIe-Karten oder I/O-Module in jedem Controller installiert haben.


.Über diese Aufgabe
* Wenn bei einigen Plattformmodellen eine RoCE-fähige PCIe-Karte oder ein I/O-Modul in einem unterstützten Steckplatz auf einem Controller installiert ist, werden die Ports automatisch standardmäßig Storage-verwendet (anstelle von Netzwerken). es wird jedoch empfohlen, das folgende Verfahren durchzuführen, um zu überprüfen, ob die RoCE-fähigen Ports für die Speichernutzung konfiguriert sind.
* Wenn Sie feststellen, dass die nicht-dedizierten RoCE-fähigen Ports in Ihrem HA-Paar nicht für die Storage-Nutzung konfiguriert sind, ist es ein unterbrechungsfreies Konfigurieren der Ports. Sie müssen die Controller nur neu booten, wenn sich ein oder beide Controller im Wartungsmodus befinden. Für diese Vorgehensweise wird vorausgesetzt, dass sich keiner der Controller im Wartungsmodus befindet.
* Wenn Sie in Zukunft die Ports von der Speichernutzung auf die Netzwerkverwendung ändern müssen, geben Sie den Befehl ein, `storage port modify -node _node_name_ -port _port_name_ -mode network`.


.Schritte
. Melden Sie sich beim Cluster mit SSH oder dem seriellen Konsolen-Port an.
. Geben Sie den folgenden Befehl ein, um zu überprüfen, ob die nicht dedizierten Ports im HA-Paar für den Storage konfiguriert sind:
+
`storage port show`

+
** Wenn auf Ihrem HA-Paar ONTAP 9.8 oder höher ausgeführt wird, werden die nicht dedizierten Ports angezeigt `storage` Im `Mode` Spalte.
** Wenn auf Ihrem HA-Paar ONTAP 9.7 ausgeführt wird, werden auch die nicht dedizierten Ports, die in der `Is Dedicated?` Spalte angezeigt werden, in der `State` Spalte `enabled` angezeigt `false`.
+
[NOTE]
====
Wenn keine dedizierten Ports für den Storage konfiguriert sind, wird in der Befehlsausgabe Folgendes angezeigt:

*** Wenn auf Ihrem HA-Paar ONTAP 9.8 oder höher ausgeführt wird, werden die nicht dedizierten Ports angezeigt `network` Im `Mode` Spalte.
*** Wenn auf Ihrem HA-Paar ONTAP 9.7 ausgeführt wird, werden auch die nicht dedizierten Ports, die in der `Is Dedicated?`` Spalte angezeigt werden, in der `State` Spalte `disabled` angezeigt `false`.


====


. Wenn die nicht dedizierten Ports für die Speichernutzung konfiguriert sind, gehen Sie wie folgt vor.
+
Andernfalls müssen Sie die Ports konfigurieren, indem Sie die Schritte 4 bis 7 ausführen.

. Konfigurieren Sie die nicht dedizierten Ports für die Speichernutzung auf einem der Controller:
+
Sie müssen den entsprechenden Befehl für jeden zu konfigurierende Port wiederholen.

+
[cols="1,3"]
|===
| Wenn Ihr HA-Paar läuft... | Befehl 


 a| 
ONTAP 9.8 oder höher
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. Wiederholen Sie Schritt 4 für den zweiten Controller.
. Überprüfen Sie, ob die nicht dedizierten Ports auf beiden Controllern für die Speichernutzung konfiguriert sind: `storage port show`
+
** Wenn auf Ihrem HA-Paar ONTAP 9.8 oder höher ausgeführt wird, werden die nicht dedizierten Ports angezeigt `storage` Im `Mode` Spalte.
** Wenn auf Ihrem HA-Paar ONTAP 9.7 ausgeführt wird, werden auch die nicht dedizierten Ports, die in der `Is Dedicated?` Spalte angezeigt werden, in der `State` Spalte `enabled` angezeigt `false`.






== Wiederverskaufbarkeit vorhandener Shelves

Bevor Sie zusätzliche Shelfs während des laufenden Betriebs hinzufügen können, müssen Sie je nach Plattformmodell möglicherweise ein vorhandenes Shelf (nachdem die zusätzlichen RoCE-fähigen PCIe-Karten oder I/O-Module installiert wurden) über zwei Portsätze in unterschiedlichen Steckplätzen hinweg neu ausstatten, um eine Ausfallsicherheit bei Steckplatzausfällen zu gewährleisten.

.Bevor Sie beginnen
* Vergewissern Sie sich, dass Sie zusätzliche RoCE-fähige PCIe-Karten oder I/O-Module in jedem Controller installiert haben.
* Stellen Sie sicher, dass die nicht dedizierten Ports auf den RoCE-fähigen PCIe-Karten oder den installierten I/O-Modulen für die Storage-Verwendung konfiguriert sind.


.Über diese Aufgabe
* Die Neuverkabeln von Port-Verbindungen ist ein unterbrechungsfreies Verfahren, wenn Ihr Shelf über Multipath-HA-Konnektivität verfügt.
* Sie verschieben jeweils ein Kabel, um während dieses Vorgangs immer die Konnektivität zum Shelf aufrechtzuerhalten.
+

NOTE: Beim Anschließen eines Kabels muss zwischen dem Abziehen des Kabels von einem Anschluss und dem Anschließen an einen anderen Anschluss keine Wartezeit mehr Zeit in Anspruch genommen werden.

* Falls erforderlich, lesen Sie die Abbildungen der Shelf-Verkabelung für Ihr Plattformmodell in link:cable-overview-hot-add-shelf.html["Übersicht über die Verkabelung für Hot-Add"].


.Schritte
. Vorhandene Shelf-Verbindungen können gegebenenfalls über zwei Sätze RoCE-fähiger Ports in verschiedenen Steckplätzen zurückgeführt werden.


* Für AFF Systeme:
+
[role="tabbed-block"]
====
.AFF A1K
--
Führen Sie einen der folgenden Schritte aus, wenn Sie ein zweites oder ein viertes Shelf im laufenden Betrieb hinzufügen.


NOTE: Wenn Sie über ein AFF A1K HA-Paar verfügen und während des laufenden Betriebs ein drittes Shelf hinzufügen und ein drittes oder viertes RoCE-fähiges I/O-Modul in jeden Controller installieren, ist das dritte Shelf nur mit den dritten, dritten und vierten I/O-Modulen verbunden. Sie müssen keine vorhandenen Shelfs erneut vertragen.

** Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 11 und Steckplatz 10 auf jedem Controller neu anschaffen.
+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 11 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 11 Port b (e11b) in Steckplatz 10 Port b (e10b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Wenn Sie ein viertes Shelf während des laufenden Betriebs hinzufügen, können Sie das dritte Shelf über die RoCE-fähigen I/O-Module in Steckplatz 9 und Steckplatz 8 auf jedem Controller umverteilen.
+
Bei den Teilschritten wird davon ausgegangen, dass das dritte Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 9 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 9 Port b (e9b) in Steckplatz 8 Port b (e8b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.AFF A70, AFF A90 oder AFF C80
--
Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 11 und Steckplatz 8 auf jedem Controller neu anschaffen.

Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 11 verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 11 Port b (e11b) in Steckplatz 8 Port b (e8b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
.AFF A800 oder AFF C800
--
Wenn Sie ein zweites Shelf während des laufenden Betrieb hinzufügen, können Sie das erste Shelf über die beiden RoCE-fähigen Ports in Steckplatz 5 und Steckplatz 3 an jedem Controller neu anschaffen.

Die Unterschritte gehen davon aus, dass das vorhandene Shelf in jedem Controller-Steckplatz 5 mit RoCE-fähigen PCIe-Karten verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 5 Port b (e5b) in Steckplatz 3 Port b (e3b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
.AFF A700
--
Wenn Sie ein zweites Shelf während des laufenden Betrieb hinzufügen, können Sie das erste Shelf über die beiden RoCE-fähigen Ports in Steckplatz 3 und Steckplatz 7 an jedem Controller neu anschaffen.

Die Unterschritte setzen voraus, dass das vorhandene Shelf in Steckplatz 3 an jedem Controller mit RoCE-fähigen I/O-Modulen verbunden ist.

.. Stellen Sie am Controller A das Kabel von Steckplatz 3 Port b (e3b) in Steckplatz 7 Port b (e7b) um.
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
.AFF A400 oder AFF C400
--
Wenn Sie je nach Plattformmodell im laufenden Betrieb ein zweites Shelf hinzufügen, führen Sie einen der folgenden Schritte aus:

** Auf der AFF A400:
+
Das erste Shelf kann auf jedem Controller über die beiden Sätze von RoCE-fähigen Ports hinweg, Onboard e0c/e0d und in Steckplatz 5, wieder verwendet werden.

+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit RoCE-fähigen Onboard-Ports e0c/e0d verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Port e0d nach Steckplatz 5 Port b (e5b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Auf dem AFF C400:
+
Wiederbesorgen des ersten Shelf über die beiden RoCE-fähigen Ports in Steckplatz 4 und Steckplatz 5 auf jedem Controller

+
Bei den Teilschritten wird davon ausgegangen, dass das vorhandene Shelf an jedem Controller an RoCE-fähige Ports in Steckplatz 4 angeschlossen ist.

+
... Bringen Sie das Kabel an Controller A von Steckplatz 4 Port A (e4a) in Steckplatz 5 Port b (e5b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.AFF A900
--
Führen Sie einen der folgenden Schritte aus, wenn Sie ein zweites oder ein viertes Shelf im laufenden Betrieb hinzufügen.

** Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 2 und Steckplatz 10 auf jedem Controller neu anschaffen.
+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 2 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 2 Port b (e2b) in Steckplatz 10 Port b (e10b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Wenn Sie ein viertes Shelf während des laufenden Betriebs hinzufügen, können Sie das dritte Shelf über die RoCE-fähigen I/O-Module in Steckplatz 1 und Steckplatz 11 auf jedem Controller umverteilen.
+
Bei den Teilschritten wird davon ausgegangen, dass das dritte Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 1 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 1 Port b (e1b) in Steckplatz 11 Port b (e11b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.AFF A30, AFF C30, AFF A50 oder AFF C60
--
Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 3 und Steckplatz 1 auf jedem Controller neu anschaffen.

Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 3 verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 3 Port b (e3b) in Steckplatz 1 Port b (e1b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
====


* Für ASA Systeme:
+
[role="tabbed-block"]
====
.ASA A1K
--
Führen Sie einen der folgenden Schritte aus, wenn Sie ein zweites oder ein viertes Shelf im laufenden Betrieb hinzufügen.


NOTE: Wenn Sie über ein ASA A1K HA-Paar verfügen und während des laufenden Betriebs ein drittes Shelf hinzufügen und ein drittes oder viertes RoCE-fähiges I/O-Modul in jeden Controller installieren, ist das dritte Shelf nur mit den dritten, dritten und vierten I/O-Modulen verbunden. Sie müssen keine vorhandenen Shelfs erneut vertragen.

** Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 11 und Steckplatz 10 auf jedem Controller neu anschaffen.
+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 11 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 11 Port b (e11b) in Steckplatz 10 Port b (e10b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Wenn Sie ein viertes Shelf während des laufenden Betriebs hinzufügen, können Sie das dritte Shelf über die RoCE-fähigen I/O-Module in Steckplatz 9 und Steckplatz 8 auf jedem Controller umverteilen.
+
Bei den Teilschritten wird davon ausgegangen, dass das dritte Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 9 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 9 Port b (e9b) in Steckplatz 8 Port b (e8b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.ASA A70 oder ASA A90
--
Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 11 und Steckplatz 8 auf jedem Controller neu anschaffen.

Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 11 verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 11 Port b (e11b) in Steckplatz 8 Port b (e8b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
.ASA A800 oder ASA C800
--
Wenn Sie ein zweites Shelf während des laufenden Betrieb hinzufügen, können Sie das erste Shelf über die beiden RoCE-fähigen Ports in Steckplatz 5 und Steckplatz 3 an jedem Controller neu anschaffen.

Die Unterschritte gehen davon aus, dass das vorhandene Shelf in jedem Controller-Steckplatz 5 mit RoCE-fähigen PCIe-Karten verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 5 Port b (e5b) in Steckplatz 3 Port b (e3b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
.ASA A400 oder ASA C400
--
Wenn Sie je nach Plattformmodell im laufenden Betrieb ein zweites Shelf hinzufügen, führen Sie einen der folgenden Schritte aus:

** Auf der ASA A400:
+
Das erste Shelf kann auf jedem Controller über die beiden Sätze von RoCE-fähigen Ports hinweg, Onboard e0c/e0d und in Steckplatz 5, wieder verwendet werden.

+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit RoCE-fähigen Onboard-Ports e0c/e0d verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Port e0d nach Steckplatz 5 Port b (e5b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Auf dem ASA C400:
+
Wiederbesorgen des ersten Shelf über die beiden RoCE-fähigen Ports in Steckplatz 4 und Steckplatz 5 auf jedem Controller

+
Bei den Teilschritten wird davon ausgegangen, dass das vorhandene Shelf an jedem Controller an RoCE-fähige Ports in Steckplatz 4 angeschlossen ist.

+
... Bringen Sie das Kabel an Controller A von Steckplatz 4 Port A (e4a) in Steckplatz 5 Port b (e5b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.ASA A900
--
Führen Sie einen der folgenden Schritte aus, wenn Sie ein zweites oder ein viertes Shelf im laufenden Betrieb hinzufügen.

** Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 2 und Steckplatz 10 auf jedem Controller neu anschaffen.
+
Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 2 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 2 Port b (e2b) in Steckplatz 10 Port b (e10b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


** Wenn Sie ein viertes Shelf während des laufenden Betriebs hinzufügen, können Sie das dritte Shelf über die RoCE-fähigen I/O-Module in Steckplatz 1 und Steckplatz 11 auf jedem Controller umverteilen.
+
Bei den Teilschritten wird davon ausgegangen, dass das dritte Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 1 verbunden ist.

+
... Bewegen Sie das Kabel an Controller A von Steckplatz 1 Port b (e1b) in Steckplatz 11 Port b (e11b).
... Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen




--
.ASA A30 oder ASA A50
--
Wenn Sie während des laufenden Betriebs ein zweites Shelf hinzufügen, können Sie das erste Shelf über die RoCE-fähigen I/O-Module in Steckplatz 3 und Steckplatz 1 auf jedem Controller neu anschaffen.

Die Teilschritte gehen davon aus, dass das vorhandene Shelf an jedem Controller mit einem RoCE-fähigen I/O-Modul in Steckplatz 3 verbunden ist.

.. Bewegen Sie das Kabel an Controller A von Steckplatz 3 Port b (e3b) in Steckplatz 1 Port b (e1b).
.. Wiederholen Sie das gleiche Kabel, um es bei Controller B zu bewegen


--
====


. Überprüfen Sie mit https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Wenn Verkabelungsfehler auftreten, befolgen Sie die entsprechenden Korrekturmaßnahmen.





== Automatische Laufwerkszuordnung deaktivieren

Wenn Sie dem NS224-Shelf, das Sie im laufenden Betrieb hinzufügen, manuell Laufwerkseigentum zuweisen, müssen Sie die automatische Laufwerkszuweisung deaktivieren, wenn sie aktiviert ist.

Wenn Sie sich nicht sicher sind, ob Sie die Laufwerkseigentümer manuell zuweisen oder die automatische Zuweisung der Laufwerkseigentumsrichtlinien für Ihr Speichersystem verstehen möchten, gehen Sie zu https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["Allgemeines zur automatischen Zuweisung der Festplatteneigentümer"^].

.Schritte
. Überprüfen Sie, ob die automatische Laufwerkszuweisung aktiviert ist: `storage disk option show`
+
Sie können für beide Nodes den Befehl eingeben.

+
Wenn die automatische Laufwerkszuordnung aktiviert ist, wird die Ausgabe in der Spalte (für jeden Node) angezeigt `on` `Auto Assign` .

. Wenn die automatische Laufwerkszuweisung aktiviert ist, deaktivieren Sie sie: `storage disk option modify -node _node_name_ -autoassign off`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Nodes deaktivieren.


