---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 'Wenn das Boot-Medium in einem NS224-Laufwerk-Shelf in einem HA-Paar, das ONTAP 9.7 oder höher ausführt, oder auf dem Shelf wird die NVMe-Shelf-Modul \(NSM\)-Firmware-Version 1.1x oder höher ausgeführt, können Sie die Boot-Medien ersetzen. Der Austausch der Boot-Medien kann unterbrechungsfrei durchgeführt werden, während das Festplatten-Shelf eingeschaltet ist und I/O gerade läuft.' 
---
= Ersetzen Sie die Boot-Medien – NS224-Shelfs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das Boot-Medium in einem NS224-Laufwerk-Shelf in einem HA-Paar, auf dem ONTAP 9.7 oder höher ausgeführt wird, ausfällt oder auf dem Shelf die NVMe-Shelf-Modul-Firmware (NSM) Version 0111 oder höher ausgeführt wird, können Sie die Boot-Medien ersetzen. Der Austausch der Boot-Medien kann unterbrechungsfrei durchgeführt werden, während das Festplatten-Shelf eingeschaltet ist und I/O gerade läuft.

.Bevor Sie beginnen
* Ihr HA-Paar muss bereits ONTAP 9.7 oder höher ausführen, was die unterstützte Mindestversion der NSM-Firmware hat, oder Ihr HA-Paar muss bereits eine Version von ONTAP 9.6 mit NSM-Firmware-Version 0111 oder höher ausführen.
+
Sie können den eingeben `storage shelf show -module` Befehl an der Konsole eines der beiden Controller, um die Version der NSM-Firmware auf Ihrem Shelf zu überprüfen.

+
[NOTE]
====
Wenn im Shelf keine NSM-Firmware-Version 0111 oder höher ausgeführt wird, können Sie das Boot-Medium nicht ersetzen, müssen Sie das NSM-Modul ersetzen.

link:service-replace-nsm100.html["Ersetzen Sie ein NSM-Modul - NS224-Einlegeböden"^]

====
* Sie benötigen einen Kreuzschlitzschraubendreher #1.
+
Die Schraube, mit der das Boot-Medium an der Platine befestigt wird, erfordert einen Kreuzschlitz #1 Schraubendreher; bei Verwendung eines anderen Schraubendrehers kann die Schraube entfernt werden.

* Das Partner-NSM-Modul des Shelfs muss in Betrieb sein und ordnungsgemäß verkabelt werden, damit das Shelf beim Entfernen des NSM-Moduls mit der fehlerhaften FRU (Ziel-NSM-Modul) die Verbindung aufrecht erhält.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]

* Alle anderen Komponenten im System müssen ordnungsgemäß funktionieren.


.Über diese Aufgabe
* Nach dem Austausch des Boot-Mediums wird das Boot-Image aus dem Partner-NSM-Modul des Shelfs automatisch auf das Ersatz-Boot-Medium kopiert.
+
Dies kann bis zu fünf Minuten dauern.

* Mindestens 70 Sekunden zwischen dem aus- und Einbau des NVMe-Shelf-Moduls (NSM) zulassen.
+
So bleibt ONTAP genügend Zeit, um das NSM-Entfernungsereignis zu bearbeiten.

* *Best Practice:* die Best Practice besteht darin, aktuelle Versionen der NSM-Firmware (NVMe Shelf Module) und der Laufwerk-Firmware auf dem System zu haben, bevor FRU-Komponenten ersetzt werden.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp Downloads: Festplatten-Shelf Firmware"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp Downloads: Festplatten-Firmware"^]

+
[NOTE]
====
Stellen Sie die Firmware nicht auf eine Version zurück, die Ihr Shelf und seine Komponenten nicht unterstützt.

====
* Bei Bedarf können Sie die blauen LEDs am Shelf einschalten, um die physische Suche nach dem betroffenen Shelf zu erleichtern: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Wenn Sie den nicht kennen `_shelf_name_` Führen Sie den aus `storage shelf show` Befehl.

+
Ein Regal hat drei Positionen-LEDs: Eine auf dem Bedienfeld und eine auf jedem NSM-Modul. Die Standort-LEDs leuchten 30 Minuten lang. Sie können sie ausschalten, indem Sie den gleichen Befehl eingeben, jedoch mit dem `off` Option.

* Nach dem Ersetzen der Boot-Medien können Sie das fehlerhafte Teil wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben an NetApp zurücksenden.
+
Wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen, wenden Sie sich an den technischen Support unter https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik).

* Sie können das Bootmedium mit dem folgenden Video oder den schriftlichen Schritten ersetzen.
+
.Animation - Ersetzen Sie die Startmedien in einem NS224-Laufwerk-Shelf
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[panopto]


.Schritte
. Stellen Sie sicher, dass beide NSM-Module im Shelf dieselbe Version von Firmware ausführen: Version 0200 oder höher.
. Richtig gemahlen.
. Trennen Sie die Verkabelung vom NSM-Modul, das die FRU enthält, die Sie ersetzen:
+
.. Ziehen Sie das Netzkabel vom Netzteil ab, indem Sie den Netzkabelhalter öffnen und dann das Netzkabel vom Netzteil trennen.
+
Die Netzteile haben keinen Netzschalter.

.. Trennen Sie die Speicherkabel von den NSM-Modulports.
+
Notieren Sie sich die NSM-Modulanschlüsse, an die jedes Kabel angeschlossen ist. Wenn Sie das NSM-Modul später wieder einsetzen, schließen Sie die Kabel wieder an die gleichen Anschlüsse an.



. Entfernen Sie das NSM-Modul aus dem Shelf:
+
.. Führen Sie die Zeigefinger durch die Fingerlöcher der Verriegelungsmechanismen auf beiden Seiten des NSM-Moduls.
+

NOTE: Wenn Sie das untere NSM-Modul entfernen und die untere Schiene den Zugriff auf die Verriegelungen behindert, setzen Sie Ihre Zeigefinger durch die Fingerlöcher von innen (durch Überqueren der Arme).

.. Drücken Sie bei den Daumen nach unten, und halten Sie die orangefarbenen Laschen über den Verriegelungsmechanismus.
+
Die Verriegelungsmechanismen heben sich an und löschen die Verriegelungsstifte am Regal.

.. Ziehen Sie vorsichtig, bis sich das NSM-Modul etwa ein Drittel des Ausschuppens aus dem Regal befindet. Fassen Sie die NSM-Modulseiten mit beiden Händen an, um das Gewicht zu stützen, und legen Sie es dann auf eine flache, stabile Oberfläche.
+
Wenn Sie mit dem Ziehen beginnen, ziehen sich die Arms des Verriegelungsmechanismus aus dem NSM-Modul und sichern sich in ihrer vollständig ausgestreckten Position.



. Lösen Sie die Flügelschraube der NSM-Modulabdeckung, und öffnen Sie die Abdeckung.
. Suchen Sie das ausgefallene Startmedium physisch.
+
Die Boot-Medien befinden sich an der Wand des Shelf-Chassis gegenüber dem Netzteil.

. Ersetzen Sie die Startmedien:
+
.. Entfernen Sie mit dem Kreuzschlitzschraubendreher #1 vorsichtig die Schraube, mit der das untere (eingekerbte) Ende des Bootmediums an der Platine befestigt ist.
.. Entfernen Sie das Bootmedium, indem Sie das eingekernte Ende leicht nach oben drehen und dann vorsichtig zu Ihnen ziehen, bis es aus dem Sockel löst.
+
Sie können die Startmedien festhalten, indem Sie Daumen und Zeigefinger an den seitlichen Kanten am gekerbten Ende platzieren

.. Entpacken Sie das Bootmedium aus dem antistatischen Beutel.
.. Setzen Sie das Ersatzstartmedium ein, indem Sie es vorsichtig in die Buchse drücken, bis es sich ganz und ganz in der Steckdose befindet.
+
Sie können die Startmedien festhalten, indem Sie Daumen und Zeigefinger an den seitlichen Kanten am gekerbten Ende platzieren Stellen Sie sicher, dass die Seite mit dem Kühlkörper nach oben zeigt.

+
Wenn Sie das Boot-Medium richtig einsetzen und loslassen, wird das eingekerbte Ende des Bootmediums von der Platine abgewinkelt, da es noch nicht mit der Schraube gesichert ist.

.. Halten Sie beim Einlegen vorsichtig das eingekerbte Ende des Bootmediums fest und ziehen Sie die Schraube mit dem Schraubendreher fest, um die Boot-Medien zu befestigen.
+

NOTE: Ziehen Sie die Schraube so fest, dass sie die Bootsmedien sicher hält, aber nicht zu fest anziehen.



. Schließen Sie die NSM-Modulabdeckung, und ziehen Sie dann die Flügelschraube fest.
. Setzen Sie das NSM-Modul wieder in das Regal ein:
+
.. Vergewissern Sie sich, dass die Arms des Verriegelungsmechanismus vollständig ausgefahren sind.
.. Schieben Sie das NSM-Modul vorsichtig mit beiden Händen in das Regal, bis das Gewicht des NSM-Moduls vollständig vom Regal unterstützt wird.
.. Schieben Sie das NSM-Modul in das Regal, bis es anhält (etwa einen halben Zoll von der Rückseite des Regals).
+
Sie können Ihre Daumen auf die orangefarbenen Laschen an der Vorderseite jeder Fingerschleife (der Arms des Verriegelungsmechanismus) legen, um das NSM-Modul einzudrücken.

.. Führen Sie die Zeigefinger durch die Fingerlöcher der Verriegelungsmechanismen auf beiden Seiten des NSM-Moduls.
+

NOTE: Wenn Sie das untere NSM-Modul einsetzen und die untere Schiene den Zugriff auf die Verriegelungen behindert, setzen Sie die Zeigefinger durch die Fingerlöcher von innen (durch Überqueren der Arme).

.. Drücken Sie bei den Daumen nach unten, und halten Sie die orangefarbenen Laschen über den Verriegelungsmechanismus.
.. Drücken Sie vorsichtig nach vorne, um die Verriegelungen über den Anschlag zu bringen.
.. Lösen Sie Ihre Daumen von den Spitzen der Verriegelungen, und drücken Sie dann weiter, bis die Verriegelungen einrasten.
+
Das NSM-Modul sollte vollständig in das Regal eingeführt und mit den Rändern des Regals bündig eingespült werden.



. Schließen Sie die Verkabelung wieder an das NSM-Modul an:
+
.. Schließen Sie die Speicherkabel wieder an die beiden NSM-Modulports an.
+
Die Kabel werden mit der Zuglasche des Steckers nach oben eingesetzt. Wenn ein Kabel richtig eingesetzt wird, klickt es an seine Stelle.

.. Schließen Sie das Netzkabel wieder an das Netzteil an, und befestigen Sie dann das Netzkabel mit der Netzkabelhalterung.
+
Bei ordnungsgemäßer Funktion leuchtet die zweifarbige LED des Netzteils grün.

+
Außerdem leuchten die beiden NSM-Modulports LNK (grün) LEDs auf. Wenn eine LNK-LED nicht leuchtet, setzen Sie das Kabel wieder ein.



. Stellen Sie sicher, dass die Warn-LEDs am NSM-Modul, die das ausgefallene Boot-Medium und die Anzeige des Shelf-Bedieners enthalten, nicht mehr leuchten.
+
Es kann zwischen 5 und 10 Minuten dauern, bis die Warn-LEDs ausgeschaltet werden. Dies ist die Zeit, die das NSM-Modul zum Neustart und die Kopie des Boot-Media-Images benötigt.

+
Wenn die Fehler-LEDs weiterhin leuchten, werden die Boot-Medien möglicherweise nicht richtig eingesetzt oder es kann ein weiteres Problem auftreten. Wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

. Überprüfen Sie, ob das NSM-Modul ordnungsgemäß verkabelt ist, indem Sie Active IQ Config Advisor ausführen.
+
Wenn Verkabelungsfehler auftreten, befolgen Sie die entsprechenden Korrekturmaßnahmen.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]


