---
permalink: ns224/service-replace-fan.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, fan, nondisruptive, power, i/o, progress, replace, replace a fan 
summary: Ein ausgefallener Lüfter kann unterbrechungsfrei in einem NS224-Laufwerk-Shelf ersetzt werden, das eingeschaltet ist und I/O-Vorgänge ausgeführt werden. 
---
= Ersetzen Sie einen Lüfter – NS224-Einschübe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein ausgefallener Lüfter kann unterbrechungsfrei in einem NS224-Laufwerk-Shelf ersetzt werden, das eingeschaltet ist und I/O-Vorgänge ausgeführt werden.

.Bevor Sie beginnen
* Das Partner-NSM-Modul des Shelfs muss in Betrieb sein und ordnungsgemäß verkabelt werden, damit das Shelf beim Entfernen des NSM-Moduls mit der fehlerhaften FRU (Ziel-NSM-Modul) die Verbindung aufrecht erhält.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]

* Alle anderen Komponenten des Systems, einschließlich der anderen vier Lüfter, müssen ordnungsgemäß funktionieren.


.Über diese Aufgabe
* Mindestens 70 Sekunden zwischen dem aus- und Einbau des NVMe-Shelf-Moduls (NSM) zulassen.
+
So bleibt ONTAP genügend Zeit, um das NSM-Entfernungsereignis zu bearbeiten.

* *Best Practice:* die Best Practice besteht darin, aktuelle Versionen der NSM-Firmware (NVMe Shelf Module) und der Laufwerk-Firmware auf dem System zu haben, bevor FRU-Komponenten ersetzt werden.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp Downloads: Festplatten-Shelf Firmware"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp Downloads: Festplatten-Firmware"^]

+
[NOTE]
====
Stellen Sie die Firmware nicht auf eine Version zurück, die Ihr Shelf und seine Komponenten nicht unterstützt.

====
* Bei Bedarf können Sie die blauen LEDs am Shelf einschalten, um die physische Suche nach dem betroffenen Shelf zu erleichtern: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Wenn Sie den nicht kennen `_shelf_name_` Führen Sie den aus `storage shelf show` Befehl.

+
Ein Regal hat drei Positionen-LEDs: Eine auf dem Bedienfeld und eine auf jedem NSM-Modul. Die Standort-LEDs leuchten 30 Minuten lang. Sie können sie ausschalten, indem Sie den gleichen Befehl eingeben, jedoch mit dem `off` Option.

* Wenn Sie den Ersatzlüfter auspacken, bewahren Sie alle Verpackungsmaterialien auf, wenn Sie den defekten Lüfter zurücksenden.
+
Wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen, wenden Sie sich an den technischen Support unter https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik).

* Sie können die folgende Animation oder die geschriebenen Schritte verwenden, um einen Lüfter zu ersetzen.
+
.Ersetzen Sie einen Lüfter in einem NS224-Shelf
video::29635ff8-ae86-4a48-ab2a-aa86002f3b66[panopto]


.Schritte
. Richtig gemahlen.
. Trennen Sie die Verkabelung vom NSM-Modul, das die FRU enthält, die Sie ersetzen:
+
.. Ziehen Sie das Netzkabel vom Netzteil ab, indem Sie den Netzkabelhalter öffnen, wenn es sich um ein Netzteil handelt, oder die beiden Flügelschrauben lösen, wenn es sich um ein Gleichstromnetzteil handelt, und ziehen Sie dann das Netzkabel vom Netzteil ab.
+
Die Netzteile haben keinen Netzschalter.

.. Trennen Sie die Speicherkabel von den NSM-Modulports.
+
Notieren Sie sich die NSM-Modulanschlüsse, an die jedes Kabel angeschlossen ist. Wenn Sie das NSM-Modul später wieder einsetzen, schließen Sie die Kabel wieder an die gleichen Anschlüsse an.



. Entfernen Sie das NSM-Modul aus dem Shelf:
+
.. Führen Sie die Zeigefinger durch die Fingerlöcher der Verriegelungsmechanismen auf beiden Seiten des NSM-Moduls.
+

NOTE: Wenn Sie das untere NSM-Modul entfernen und die untere Schiene den Zugriff auf die Verriegelungen behindert, setzen Sie Ihre Zeigefinger durch die Fingerlöcher von innen (durch Überqueren der Arme).

.. Drücken Sie bei den Daumen nach unten, und halten Sie die orangefarbenen Laschen über den Verriegelungsmechanismus.
+
Die Verriegelungsmechanismen heben sich an und löschen die Verriegelungsstifte am Regal.

.. Ziehen Sie vorsichtig, bis sich das NSM-Modul etwa ein Drittel des Ausschuppens aus dem Regal befindet. Fassen Sie die NSM-Modulseiten mit beiden Händen an, um das Gewicht zu stützen, und legen Sie es dann auf eine flache, stabile Oberfläche.
+
Wenn Sie mit dem Ziehen beginnen, ziehen sich die Arms des Verriegelungsmechanismus aus dem NSM-Modul und sichern sich in ihrer vollständig ausgestreckten Position.



. Lösen Sie die Flügelschraube der NSM-Modulabdeckung, und öffnen Sie die Abdeckung.
+

NOTE: Das FRU-Etikett auf der NSM-Modulabdeckung zeigt die Position der fünf Lüfter an der Rückseite des NSM-Moduls an.

. Identifizieren Sie den ausgefallenen Lüfter physisch.
+
Wenn ein Lüfter ausfällt, protokolliert das System eine Warnmeldung an die Systemkonsole und gibt an, welcher Lüfter ausfällt.

. Ersetzen Sie den ausgefallenen Lüfter:
+
.. Entfernen Sie den defekten Lüfter, indem Sie die Seiten fest greifen, wo sich die blauen Berührungspunkte befinden, und heben Sie ihn dann vertikal an, um ihn von der Buchse zu trennen.
.. Setzen Sie den Ersatzlüfter ein, indem Sie ihn in die Führungen ausrichten, und drücken Sie dann nach unten, bis der Lüftermodulanschluss vollständig in der Buchse sitzt.


. Schließen Sie die NSM-Modulabdeckung, und ziehen Sie dann die Flügelschraube fest.
. Setzen Sie das NSM-Modul wieder in das Regal ein:
+
.. Vergewissern Sie sich, dass die Arms des Verriegelungsmechanismus vollständig ausgefahren sind.
.. Schieben Sie das NSM-Modul vorsichtig mit beiden Händen in das Regal, bis das Gewicht des NSM-Moduls vollständig vom Regal unterstützt wird.
.. Schieben Sie das NSM-Modul in das Regal, bis es anhält (etwa einen halben Zoll von der Rückseite des Regals).
+
Sie können Ihre Daumen auf die orangefarbenen Laschen an der Vorderseite jeder Fingerschleife (der Arms des Verriegelungsmechanismus) legen, um das NSM-Modul einzudrücken.

.. Führen Sie die Zeigefinger durch die Fingerlöcher der Verriegelungsmechanismen auf beiden Seiten des NSM-Moduls.
+

NOTE: Wenn Sie das untere NSM-Modul einsetzen und die untere Schiene den Zugriff auf die Verriegelungen behindert, setzen Sie die Zeigefinger durch die Fingerlöcher von innen (durch Überqueren der Arme).

.. Drücken Sie bei den Daumen nach unten, und halten Sie die orangefarbenen Laschen über den Verriegelungsmechanismus.
.. Drücken Sie vorsichtig nach vorne, um die Verriegelungen über den Anschlag zu bringen.
.. Lösen Sie Ihre Daumen von den Spitzen der Verriegelungen, und drücken Sie dann weiter, bis die Verriegelungen einrasten.
+
Das NSM-Modul sollte vollständig in das Regal eingeführt und mit den Rändern des Regals bündig eingespült werden.



. Schließen Sie die Verkabelung wieder an das NSM-Modul an:
+
.. Schließen Sie die Speicherkabel wieder an die beiden NSM-Modulports an.
+
Die Kabel werden mit der Zuglasche des Steckers nach oben eingesetzt. Wenn ein Kabel richtig eingesetzt wird, klickt es an seine Stelle.

.. Schließen Sie das Netzkabel wieder an das Netzteil an, und befestigen Sie das Netzkabel mit der Netzkabelhalterung, wenn es sich um ein Netzteil handelt. Ziehen Sie die beiden Flügelschrauben fest, wenn es sich um ein Gleichstromnetzteil handelt, und ziehen Sie dann das Netzkabel aus dem Netzteil.
+
Bei ordnungsgemäßer Funktion leuchtet die zweifarbige LED des Netzteils grün.

+
Außerdem leuchten die beiden NSM-Modulports LNK (grün) LEDs auf. Wenn eine LNK-LED nicht leuchtet, setzen Sie das Kabel wieder ein.



. Stellen Sie sicher, dass die Warn-LEDs am NSM-Modul, das den ausgefallenen Lüfter und die Anzeige des Shelf-Bedieners enthält, nicht mehr leuchten.
+
Die Warnungs-LEDs des NSM-Moduls werden nach einem Neustart des NSM-Moduls ausgeschaltet und ein Lüfterproblem wird nicht mehr erkannt. Dies kann drei bis fünf Minuten dauern.

. Überprüfen Sie, ob das NSM-Modul ordnungsgemäß verkabelt ist, indem Sie Active IQ Config Advisor ausführen.
+
Wenn Verkabelungsfehler auftreten, befolgen Sie die entsprechenden Korrekturmaßnahmen.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]


