---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: Ausgefallene Laufwerke können unterbrechungsfrei in einem NS224-Laufwerk-Shelf ausgetauscht werden, das eingeschaltet ist, und während I/O-Vorgänge ausgeführt werden. 
---
= Hot-Swap-fähige Laufwerke – NS224-Einschübe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ausgefallene Laufwerke können unterbrechungsfrei in einem NS224-Laufwerk-Shelf ausgetauscht werden, das eingeschaltet ist, und während I/O-Vorgänge ausgeführt werden.

.Bevor Sie beginnen
* Das Laufwerk, das Sie installieren, muss vom NS224-Shelf unterstützt werden.
+
https://["NetApp Hardware Universe"^]

* Wenn die SED-Authentifizierung aktiviert ist, müssen Sie die SED-Ersatzanweisungen in der ONTAP-Dokumentation verwenden.
+
Anweisungen in der ONTAP-Dokumentation beschreiben zusätzliche Schritte, die vor und nach dem Austausch einer SED ausgeführt werden müssen.

+
https://["Übersicht über die NetApp Verschlüsselung mit CLI"^]

* Alle anderen Komponenten im System müssen ordnungsgemäß funktionieren. Wenden Sie sich andernfalls an den technischen Support.
* Vergewissern Sie sich, dass das Laufwerk, das Sie entfernen, fehlgeschlagen ist.
+
Sie können überprüfen, ob das Laufwerk ausgefallen ist, indem Sie das ausführen `storage disk show -broken` Befehl. Das ausgefallene Laufwerk wird in der Liste der ausgefallenen Laufwerke angezeigt. Falls nicht, sollten Sie warten und dann den Befehl erneut ausführen.

+

NOTE: Abhängig vom Laufwerkstyp und der Kapazität kann es bis zu mehrere Stunden dauern, bis das Laufwerk in der Liste der ausgefallenen Laufwerke angezeigt wird.



.Über diese Aufgabe
* *Best Practice:* die beste Vorgehensweise ist, die aktuelle Version des Disk Qualification Package (DQP) vor dem Hot-Swap eines Laufwerks installiert zu haben.
+
Wenn die aktuelle Version des DQP installiert ist, kann Ihr System neu qualifizierte Laufwerke erkennen und verwenden. Dies verhindert, dass Systemereignimeldungen über nicht aktuelle Laufwerksinformationen verfügen und Laufwerkspartitionierung verhindern, da Laufwerke nicht erkannt werden. Das DQP benachrichtigt Sie auch über nicht aktuelle Laufwerk-Firmware.

+
https://["NetApp Downloads: Disk Qualification Package"^]

* *Best Practice:* die Best Practice besteht darin, aktuelle Versionen der NSM-Firmware (NVMe Shelf Module) und der Laufwerk-Firmware auf dem System zu haben, bevor FRU-Komponenten ersetzt werden.
+
https://["NetApp Downloads: Festplatten-Shelf Firmware"^]

+
https://["NetApp Downloads: Festplatten-Firmware"^]

+
[NOTE]
====
Stellen Sie die Firmware nicht auf eine Version zurück, die Ihr Shelf und seine Komponenten nicht unterstützt.

====
* Die Festplatten-Firmware wird für neue Laufwerke, die nicht über aktuelle Firmware-Versionen verfügen, automatisch (unterbrechungsfrei) aktualisiert.
+

NOTE: Die Laufwerk-Firmware wird alle zwei Minuten überprüft.

* Bei Bedarf können Sie die blauen LEDs am Shelf einschalten, um die physische Suche nach dem betroffenen Shelf zu erleichtern: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Wenn Sie den nicht kennen `_shelf_name_` Führen Sie den aus `storage shelf show` Befehl.

+
Ein Regal hat drei Positionen-LEDs: Eine auf dem Bedienfeld und eine auf jedem NSM-Modul. Die Standort-LEDs leuchten 30 Minuten lang. Sie können sie ausschalten, indem Sie den gleichen Befehl eingeben, jedoch mit dem `off` Option.

* Wenn Sie das Ersatzlaufwerk auspacken, speichern Sie alle Verpackungsmaterialien für die Verwendung, wenn Sie das ausgefallene Laufwerk zurücksenden.
+
Wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen, wenden Sie sich an den technischen Support unter https://["NetApp Support"^], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik).

* Die folgende Animation bietet einen Überblick über die physischen Teile zum Entfernen und Einsetzen des Hot-Swap-Verfahrens für das Laufwerk.
+
.Animation - Hot-Swap eines Laufwerks in einem NS224-Laufwerk-Shelf
video::733011a7-e03a-41b0-8723-aa840133bf25[panopto]
+
.Schritte
.. Wenn Sie dem Ersatzlaufwerk den Besitz eines Laufwerks manuell zuweisen möchten, müssen Sie die automatische Laufwerkszuweisung deaktivieren, wenn diese aktiviert ist.
+

NOTE: Sie müssen die Laufwerkseigentümer manuell zuweisen, wenn Laufwerke im Shelf Eigentum beider Controller-Module des HA-Paars sind.

+

NOTE: Sie weisen den Antriebseigentum manuell zu und aktivieren dann die automatische Laufwerkszuweisung später in diesem Verfahren.

+
... Überprüfen Sie, ob die automatische Laufwerkszuweisung aktiviert ist: `storage disk option show`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Wenn die automatische Laufwerkszuweisung aktiviert ist, wird die Ausgabe angezeigt `on` Im `Auto Assign` Spalte (für jedes Controller-Modul).

... Wenn die automatische Laufwerkszuweisung aktiviert ist, deaktivieren Sie sie: `storage disk option modify -node node_name -autoassign off`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen deaktivieren.



.. Richtig gemahlen.
.. Identifizieren Sie das ausgefallene Laufwerk physisch.
+
Wenn ein Laufwerk ausfällt, protokolliert das System eine Warnmeldung an die Systemkonsole und gibt an, welches Laufwerk ausgefallen ist. Darüber hinaus leuchten die Warnungs-LED (gelb) auf der Anzeige des Festplatten-Shelf-Bedieners und des ausgefallenen Laufwerks.

+

NOTE: Die Aktivitäts-LED (grün) auf einem ausgefallenen Laufwerk kann leuchten (leuchtet dauerhaft), was darauf hinweist, dass das Laufwerk zwar mit Strom versorgt wird, aber nicht blinken sollte, was auf I/O-Aktivität hinweist. Ein ausgefallenes Laufwerk hat keine I/O-Aktivität.

.. Entfernen Sie das ausgefallene Laufwerk:
+
... Drücken Sie die Entriegelungstaste an der Antriebsfläche, um den Nockengriff zu öffnen.
... Schieben Sie den Antrieb mithilfe des Nockengriffs aus dem Regal und halten Sie den Antrieb mit der anderen Hand.


.. Warten Sie mindestens 70 Sekunden, bevor Sie das Ersatzlaufwerk einsetzen.
+
Dadurch erkennt das System, dass ein Laufwerk entfernt wurde.

.. Setzen Sie das Ersatzlaufwerk ein:
+
... Wenn sich der Nockengriff in der geöffneten Position befindet, setzen Sie den Ersatzantrieb mit beiden Händen ein.
... Drücken Sie, bis das Laufwerk stoppt.
... Schließen Sie den Nockengriff, so dass der Antrieb fest in der Mittelebene sitzt und der Griff einrastet.
+
Schließen Sie den Nockengriff langsam, damit er korrekt an der Antriebsfläche ausgerichtet ist.



.. Vergewissern Sie sich, dass die Aktivitäts-LED (grün) des Laufwerks leuchtet.
+
Wenn die Aktivitäts-LED des Laufwerks leuchtet, bedeutet dies, dass das Laufwerk mit Strom versorgt wird. Wenn die Aktivitäts-LED des Laufwerks blinkt, bedeutet dies, dass das Laufwerk gerade mit Strom versorgt wird und der I/O-Vorgang ausgeführt wird. Wenn die Laufwerk-Firmware automatisch aktualisiert wird, blinkt die LED.

.. Wenn Sie ein anderes Laufwerk ersetzen, wiederholen Sie die Schritte 3 bis Schritt 7.
.. Wenn Sie die automatische Laufwerkszuweisung in Schritt 1 deaktiviert haben, weisen Sie die Laufwerkseigentümer manuell zu und aktivieren Sie bei Bedarf die automatische Laufwerkszuweisung neu:
+
... Alle Laufwerke ohne Besitzer anzeigen: `storage disk show -container-type unassigned`
+
Sie können den Befehl an einem der Controller-Module eingeben.

... Weisen Sie jedes Laufwerk zu: `storage disk assign -disk disk_name -owner owner_name`
+
Sie können den Befehl an einem der Controller-Module eingeben.

+
Mit dem Platzhalterzeichen können Sie mehr als ein Laufwerk gleichzeitig zuweisen.

... Bei Bedarf die automatische Laufwerkszuweisung erneut aktivieren: `storage disk option modify -node node_name -autoassign on`
+
Sie müssen die automatische Laufwerkszuweisung auf beiden Controller-Modulen erneut aktivieren.






