---
permalink: ns224/service-replace-power-supply.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, fail, power, supply, nondisruptive, drive, i/o, progress, hot-swap, hot-swap a power supply 
summary: Sie können ein ausgefallenes Netzteil unterbrechungsfrei in einem NS224-Laufwerk-Shelf ersetzen, das eingeschaltet ist, und während I/O gerade läuft. 
---
= Hot-Swap eines Netzteils – NS224-Einschübe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein ausgefallenes Netzteil unterbrechungsfrei in einem NS224-Laufwerk-Shelf ersetzen, das eingeschaltet ist, und während I/O gerade läuft.

.Über diese Aufgabe
* Verwenden Sie keine Netzteile mit unterschiedlichen Wirkungsgrades oder mit unterschiedlichen Eingangstypen.
+
Immer ersetzen wie für „Gefällt mir“.

* Wenn Sie mehrere Netzteile ersetzen, müssen Sie dies nacheinander durchführen, damit das Shelf die Stromversorgung aufrecht erhält.
* *Best Practice:* die beste Praxis ist, das Netzteil innerhalb von zwei Minuten nach dem Entfernen aus dem NSM-Modul zu ersetzen.
+
Wenn Sie die zwei Minuten überschreiten, wird das Shelf weiterhin ausgeführt. ONTAP sendet jedoch Meldungen an die Konsole über das beeinträchtigte Netzteil, bis das Netzteil ersetzt wird.

* Stellen Sie die Firmware nicht auf eine Version zurück, die Ihr Shelf und seine Komponenten nicht unterstützt.
* Bei Bedarf können Sie die blauen LEDs am Shelf einschalten, um die physische Suche nach dem betroffenen Shelf zu erleichtern: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Wenn Sie den nicht kennen `shelf_name` Führen Sie den aus `storage shelf show` Befehl.

+
Ein Regal hat drei Positionen-LEDs: Eine auf dem Bedienfeld und eine auf jedem NSM-Modul. Die Standort-LEDs leuchten 30 Minuten lang. Sie können sie ausschalten, indem Sie denselben Befehl eingeben, jedoch die Option „aus“ verwenden.

* Wenn Sie das Ersatznetzteil auspacken, bewahren Sie alle Verpackungsmaterialien auf, wenn Sie das defekte Netzteil zurücksenden.
+
Wenn Sie die RMA-Nummer oder zusätzliche Hilfe beim Ersatzverfahren benötigen, wenden Sie sich an den technischen Support unter https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^], 888-463-8277 (Nordamerika), 00-800-44-638277 (Europa) oder +800-800-80-800 (Asien/Pazifik).



Verwenden Sie das entsprechende Verfahren für Ihren Netzteiltyp: AC oder DC.

[role="tabbed-block"]
====
.Option 1: Ersetzen Sie ein Wechselstromnetzteil
--
Zum Austauschen eines Netzteils können Sie die Animation ansehen oder die folgenden Schritte ausführen.

video::5794da63-99aa-425a-825f-aa86002f154d[Animation,width=Hot-swap a power supply in an NS224 shelf"]
.Schritte
. Richtig gemahlen.
. Identifizieren Sie das ausgefallene Netzteil physisch.
+
Das System protokolliert eine Warnmeldung an die Systemkonsole und gibt an, welche Stromversorgung fehlgeschlagen ist. Darüber hinaus leuchten die Fehler-LED auf der Anzeige des Shelf-Bedieners und die zweifarbige LED am ausgefallenen Netzteil leuchtet rot.

. Ziehen Sie das Netzkabel vom Netzteil ab, indem Sie den Netzkabelhalter öffnen und dann das Netzkabel vom Netzteil trennen.
+
Die Netzteile haben keinen Netzschalter.

. Entfernen Sie das Netzteil:
+
.. Drehen Sie den Griff nach oben in die horizontale Position, und fassen Sie ihn dann an.
.. Drücken Sie mit dem Daumen auf die blaue Lasche, um den Verriegelungsmechanismus zu lösen.
.. Ziehen Sie das Netzteil aus dem NSM-Modul, während Sie die andere Hand verwenden, um das Gewicht zu unterstützen.


. Setzen Sie das Ersatznetzteil ein:
+
.. Stützen und richten Sie die Kanten des Netzteils mit beiden Händen an der Öffnung im NSM-Modul aus.
.. Schieben Sie das Netzteil vorsichtig in das NSM-Modul, bis der Verriegelungsmechanismus einrastet.
+

NOTE: Verwenden Sie keine übermäßige Kraft, oder Sie können den internen Stecker beschädigen.

.. Drehen Sie den Griff nach unten, so dass er sich nicht im normalen Betrieb befindet.


. Schließen Sie das Netzkabel an das Netzteil an, und befestigen Sie das Netzkabel mit der Netzkabelhalterung.
+
Bei ordnungsgemäßer Funktion leuchtet die zweifarbige LED des Netzteils grün.



--
.Option 2: Ersetzen Sie ein Gleichstromnetzteil
--
Führen Sie zum Austauschen eines Gleichstromnetzteils die folgenden Schritte durch.

. Richtig gemahlen.
. Identifizieren Sie das ausgefallene Netzteil physisch.
+
Das System protokolliert eine Warnmeldung an die Systemkonsole und gibt an, welche Stromversorgung fehlgeschlagen ist. Darüber hinaus leuchten die Fehler-LED auf der Anzeige des Shelf-Bedieners und die zweifarbige LED am ausgefallenen Netzteil leuchtet rot.

. Trennen Sie das Netzteil:
+
.. Lösen Sie die beiden Flügelschrauben am D-SUB-DC-Netzkabelanschluss.
+
In der Abbildung und Tabelle in Schritt 4 sind die beiden Flügelschrauben (Pos. #1) und der D-SUB-DC-Netzkabelanschluss (Pos. #2) dargestellt.

.. Ziehen Sie den D-SUB-Gleichstromkabelanschluss vom Netzteil ab, und legen Sie ihn beiseite.


. Entfernen Sie das Netzteil:
+
.. Drehen Sie den Griff nach oben in die horizontale Position, und fassen Sie ihn dann an.
.. Drücken Sie mit dem Daumen auf die blaue Lasche, um den Verriegelungsmechanismus zu lösen.
.. Ziehen Sie das Netzteil aus dem NSM-Modul, während Sie die andere Hand verwenden, um das Gewicht zu unterstützen.
+

NOTE: Das Netzteil ist kurz. Verwenden Sie immer zwei Hände, um es zu stützen, wenn Sie es aus dem NSM-Modul entfernen, so dass es nicht aus dem NSM-Modul schwingt und Sie verletzt.

+
image::../media/drw_dcpsu_remove-replace-generic_IEOPS-788.svg[drw dcpsu remove Generic IEOPS 788 ersetzen]

+
[cols="1,3"]
|===


 a| 
image:../media/legend_icon_01.svg["Breite=10 px"]
 a| 
Flügelschrauben



 a| 
image:../media/legend_icon_02.svg["Breite=10 px"]
 a| 
D-SUB-DC-Netzkabelanschluss



 a| 
image:../media/legend_icon_03.svg["Breite=10 px"]
 a| 
Netzteilgriff



 a| 
image:../media/legend_icon_04.svg["Breite=10 px"]
 a| 
Blaue Verriegelungslasche für die Stromversorgung

|===


. Setzen Sie das Ersatznetzteil ein:
+
.. Stützen und richten Sie die Kanten des Netzteils mit beiden Händen an der Öffnung im NSM-Modul aus.
.. Schieben Sie das Netzteil vorsichtig in das NSM-Modul, bis der Verriegelungsmechanismus einrastet.
+
Ein Netzteil muss ordnungsgemäß mit dem internen Anschluss und dem Verriegelungsmechanismus verbunden sein. Wiederholen Sie diesen Schritt, wenn Sie das Netzteil nicht richtig eingesetzt haben.

+

NOTE: Verwenden Sie keine übermäßige Kraft, oder Sie können den internen Stecker beschädigen.

.. Drehen Sie den Griff nach unten, so dass er sich nicht im normalen Betrieb befindet.


. Schließen Sie das D-SUB-Gleichstromkabel wieder an:
+
Sobald die Stromversorgung wiederhergestellt ist, sollte die Status-LED grün leuchten.

+
.. Schließen Sie den D-SUB-DC-Netzkabelanschluss an das Netzteil an.
.. Ziehen Sie die beiden Flügelschrauben fest, um den D-SUB-DC-Netzkabelanschluss am Netzteil zu befestigen.




--
====