---
permalink: fas8300/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system 
summary: Sie ersetzen ein beeinträchtigtes Gehäuse durch das neue Gehäuse des gleichen Modells wie das beeinträchtigte Gehäuse. 
---
= Die Anforderungen für den Austausch eines Chassis in einem FAS8300 oder FAS8700 System werden dargestellt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor das Chassis im FAS8300 oder FAS8700 System ersetzt wird, müssen alle anderen Komponenten im System ordnungsgemäß funktionieren; ist dies nicht der Fall, muss der technische Support kontaktiert werden. Dieses Verfahren wird von allen ONTAP Versionen unterstützt, verursacht jedoch einen vollständigen Dienstausfall in einem Cluster mit zwei Controllern und einen teilweisen Ausfall in einem Multi-Node-Cluster.

* Sie können dieses Verfahren bei allen Versionen von ONTAP verwenden, die von Ihrem System unterstützt werden.
* Dieses Verfahren ist störend: Bei einem Cluster mit zwei Controllern kommt es zu einem vollständigen Dienstausfall, bei einem Cluster mit mehreren Knoten zu einem teilweisen Ausfall.

