---
permalink: /fas8300/fas8700-key-specifications.html 
sidebar: sidebar 
summary: Wichtige Spezifikationen für FAS8700 
---
= Wichtige Spezifikationen für FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Folgenden finden Sie ausgewählte Spezifikationen für das FAS8700 Speichersystem in einem einzelnen Hochverfügbarkeitspaar.  Die vollständigen Spezifikationen für dieses Speichersystem finden Sie im NetApp Hardware Universe (HWU).



== FAS8700 Spezifikationen auf einen Blick

* Plattformkonfiguration: FAS8700 Single Chassis HA-Paar, Ethernet-Paket
* Max. Rohkapazität: 15.0000 PB
* Arbeitsspeicher: 512.0000 GB
* Formfaktor: 4U-Gehäuse mit 2 HA-Controllern
* ONTAP -Version: ONTAP: 9.16.1P2
* PCIe-Erweiterungssteckplätze: 14
* Mindest ONTAP -Version: ONTAP 9.7RC1 == Scaleout-Maxima
* Typ: NAS; HA-Paare: 12; Rohkapazität: 180,0 PB / 159,9 PiB; Max. Speicher: 6144 GB
* Typ: SAN; HA-Paare: 6; Rohkapazität: 90,0 PB / 79,9 PiB; Max. Speicher: 3072 GB
* Typ: HA-Paar; Rohkapazität: 15,0 PB / 13,3 PiB; Max. Speicher: 512.0000




== E/A



=== Integrierte E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 4
* Protokoll: Ethernet 25 Gbit/s; Ports: 12
* Protokoll: SAS 12 Gbit/s; Ports: 8




=== Gesamt-E/A

* Protokoll: Ethernet 100 Gbit/s; Ports: 20
* Protokoll: Ethernet 25 Gbit/s; Ports: 28
* Protokoll: Ethernet 10 Gbit/s; Ports: 32
* Protokoll: FC 32 Gbit/s; Ports: 32
* Protokoll: NVMe/FC 32 Gbit/s; Ports: 32
* Anschlüsse: 0
* Protokoll: SAS 12 Gbit/s; Ports: 40




=== Verwaltungsports

* Protokoll: Ethernet 1 Gbit/s; Ports: 2
* Protokoll: RS-232 115 Kbps; Ports: 4
* Protokoll: USB 12 Mbit/s; Anschlüsse: 4




== Speichernetzwerke werden unterstützt

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 mit NAS
* KMU 2.0
* SMB 2.1
* SMB 2.x
* KMU 3.0
* KMU 3.1
* SMB 3.1.1 == Systemumgebungsspezifikationen
* Typische Leistung: 5430 BTU/h
* Leistung im schlimmsten Fall: 5796 BTU/h
* Gewicht: 108.9 lb 49.4 kg
* Höhe: 4U
* Breite: 19 Zoll, IEC-Rack-kompatibel (17,6 Zoll, 44,7 cm)
* Tiefe: 32,6 Zoll (34,7 Zoll mit Kabelführungshalterung)
* Betriebstemperatur/Höhe/Luftfeuchtigkeit: 10 °C bis 35 °C (50 °F bis 95 °F) bei 3048 m (10000 Fuß) Höhe; 8 % bis 80 % relative Luftfeuchtigkeit, nicht kondensierend
* Temperatur/Luftfeuchtigkeit außerhalb des Betriebs: -40 °C bis 70 °C (-40 °F bis 158 °F) bis zu 12.192 m (40.000 Fuß) 10 % bis 95 % relative Luftfeuchtigkeit, nicht kondensierend, im Originalbehälter
* Akustisches Rauschen: Angegebene Schallleistung (LwAd): 8,5 Schalldruck (LpAm) (in der Nähe): 67,2 dB




== Einhaltung

* Zertifizierungen EMC/EMI: AMCA, FCC, ICES, KC, Marokko, VCCI
* Zertifizierungen Sicherheit: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Zertifizierungen Sicherheit/EMV/EMI: EAC, UKRSEPRO
* Zertifizierungen Sicherheit/EMV/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normen EMV/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Teil 15 Klasse A, ICES-003, KS C 9832, KS C 9835
* Sicherheitsstandards: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 Nr. 60950-1, CAN/CSA C22.2 Nr. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (Teil 1)




== Hochverfügbarkeit

* Ethernet-basierter Baseboard Management Controller (BMC) und ONTAP Verwaltungsschnittstelle
* Redundante Hot-Swap-fähige Controller
* Redundante Hot-Swap-fähige Netzteile
* SAS-In-Band-Management über SAS-Verbindungen für externe Regale

