---
permalink: fas8300/install-setup.html 
sidebar: sidebar 
keywords: fas8300, fas8700, install, setup, initial configuration 
summary: Wählen Sie Ihr FAS8300 oder FAS8700 Installations- und Einrichtungserlebnis. 
---
= Wählen Sie Ihr Installations- und Einrichtungserlebnis für FAS8300 oder FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die meisten FAS8300 und FAS8700 Konfigurationen steht das Installations- und Einrichtungsformat zur Auswahl, das den jeweiligen Anforderungen am besten entspricht: Kurzanleitung, Videoanleitung oder detaillierte Anleitung.

* link:../fas8300/install-quick-guide.html["Schnelle Schritte"]
+
Eine druckbare PDF-Datei mit Schritt-für-Schritt-Anweisungen mit Live-Links zu zusätzlichen Inhalten.

* link:../fas8300/install-videos.html["Videoschritte"]
+
Video Schritt-für-Schritt-Anleitungen.

* link:../fas8300/install-detailed-guide.html["Detaillierte Schritte"]
+
Schritt-für-Schritt-Anleitungen mit Live-Links zu weiteren Inhalten



Informationen zu MetroCluster-Konfigurationen finden Sie unter:

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP-Konfiguration installieren"]
* https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["MetroCluster Fabric-Attached-Konfiguration installieren"]

