---
permalink: a700s/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery 
summary: Lernen Sie den Austausch des Bootmediums auf einem AFF A700s -System kennen und verstehen Sie die Wiederherstellungsmethoden. Das AFF A700s -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt. 
---
= Überblick über den Austausch von Boot-Medien - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lernen Sie den Austausch des Bootmediums auf einem AFF A700s -System kennen und verstehen Sie die Wiederherstellungsmethoden. Das primäre Bootmedium speichert das ONTAP Bootabbild, das das System beim Start verwendet. Sie können das primäre Bootmedienabbild mithilfe des ONTAP Abbilds vom sekundären Bootmedium oder, falls erforderlich, von einem mit FAT32 formatierten USB-Stick wiederherstellen.

Das AFF A700s -System unterstützt ausschließlich manuelle Wiederherstellungsverfahren über Bootmedien. Die automatische Wiederherstellung über Bootmedien wird nicht unterstützt.

Wenn das sekundäre Startmedium ausgefallen ist oder die Datei image.tgz fehlt, müssen Sie das primäre Startmedium über ein USB-Flash-Laufwerk wiederherstellen. Das Laufwerk muss in FAT32 formatiert sein und über die entsprechende Menge Speicherplatz verfügen, um die Datei image_xxx.tgz zu speichern.

* Der Ersatzprozess stellt das var-Dateisystem vom sekundären Bootmedium oder USB-Flash-Laufwerk auf den primären Bootmedium wieder her.
* Sie müssen die fehlerhafte Komponente durch eine vom Anbieter empfangene Ersatz-FRU-Komponente ersetzen.
* Es ist wichtig, dass Sie die Befehle in diesen Schritten auf dem richtigen Controller anwenden:
+
** Der Controller _Impared_ ist der Controller, an dem Sie Wartungsarbeiten durchführen.
** Der _Healthy_ Controller ist der HA-Partner des beeinträchtigten Controllers.




Wenn Sie das sekundäre Boot-Medium austauschen müssen, während das primäre Boot-Medium installiert ist und sich in einem ordnungsgemäßen Zustand befindet, wenden Sie sich an den NetApp-Support, und erwähnen Sie den https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["So ersetzen Sie das sekundäre Startgerät einer AFF A700s"^] KB-Artikel.
