---
permalink: a700s/maintain-overview.html 
sidebar: sidebar 
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components 
summary: Wartung der AFF A700s Hardware 
---
= Informationen zur Wartung Ihres AFF A700s Storage-Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für das AFF A700s Storage-System können Sie folgende Komponenten Wartungsverfahren durchführen:



[[boot-media]]
== Boot-Medien

Das Startmedium speichert einen primären und sekundären Satz von Boot-Image-Dateien, die das System beim Booten verwendet.



[[chassis]]
== Chassis

Das Chassis ist das physische Gehäuse, in dem alle Controller-Komponenten wie Controller-/CPU-Einheit, Stromversorgung und I/O-Vorgänge untergebracht sind



[[controller]]
== Controller

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Er steuert die Laufwerke und implementiert die ONTAP-Funktionen.



[[dimm]]
== DIMM

Sie müssen ein DIMM (Dual-Inline-Speichermodul) ersetzen, wenn ein Speicherfehler vorliegt oder ein ausgefallenes DIMM vorliegt.



[[drive]]
== Laufwerk

Ein Laufwerk ist ein Gerät, das den physischen Speicher für Daten bereitstellt.



[[fan]]
== Ventilator

Der Lüfter kühlt den Controller.



[[nvram-battery]]
== NVRAM-Akku

Im Lieferumfang des Controllers ist ein Akku enthalten, der die Notstromversorgung bereitstellt, wenn der Netzstrom ausfällt.



[[nvram-module]]
== NVRAM-Modul

Das NVRAM-Modul (nicht flüchtiger Arbeitsspeicher mit wahlfreiem Zugriff) bewahrt die zwischengespeicherten Daten bei einem Stromausfall auf.



[[pcie-card]]
== PCIe-Karte

Eine PCIe-Karte (Peripheral Component Interconnect Express) ist eine Erweiterungskarte, die in den PCIe-Steckplatz auf der Hauptplatine eingesteckt wird.



[[power-supply]]
== Stromversorgung

Ein Netzteil stellt eine redundante Stromversorgung in einem Controller Shelf bereit.



[[real-time-clock-battery]]
== Akku in Echtzeit

Eine Echtzeituhr-Batterie bewahrt die Systemdaten und -Uhrzeitinformationen, wenn die Stromversorgung ausgeschaltet ist.
