---
permalink: asa-r2/asa-r2-install-setup.html 
sidebar: sidebar 
keywords: asa r2 a1k, a70, a90, install, setup, initial configuration 
summary: Installieren und richten Sie Ihr System ein. 
---
= Installation und Einrichtung Ihrer ASA r2-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unter https://docs.netapp.com/us-en/asa-r2/install-setup/install-setup-workflow.html["Installations- und Setup-Anweisungen für ASA r2"^] erfahren Sie, wie Sie Ihr System installieren und einrichten.

Das https://docs.netapp.com/us-en/asa-r2/index.html["Dokumentation zu ASA r2-Systemen"^] enthält Informationen wie:

* Installations- und Setup-Anweisungen
* Administrationsanweisungen zur Konfiguration Ihres Systems, z. B. Bereitstellung von SAN-Speicher, Klonen von Daten und Neudimensionierung von lokalem Speicher
* Anweisungen zum Managen Ihres Systems, einschließlich Managen des Client-Zugriffs, Sichern Ihrer Daten und Schützen Ihrer Daten.
* Anleitungen für das Monitoring und die Fehlerbehebung, einschließlich Informationen zu Warnmeldungen, Cluster-Ereignissen und Systemprotokollen.


Spezifische Wartungsverfahren für jeden ASA r2-Systemtyp finden Sie im link:../asa-r2-landing-maintain/index.html["ASA r2-Systemwartung"].
